### ISSUE TITLE
Compile using strictFunctionTypes: true

### ISSUE THREAD

**Issue by joschect** [microsoft/fluentui#10226]
#### Describe the feature that you would like added

Office-ui-fabric-react should compile with the typescript option strictFunctionTypes set to true. This would add additional type safety and help prevent potential issues with functions.

Issues requesting fix/examples of friction:

#9581
#10046

#### What component or utility would this be added to

Enable strictFunctionTypes in the ts compiler options

**Comment by kenotron** [comment]
adding some relevant folks to discussion

**Comment by joschect** [comment]
I personally think that this can't hurt to add, if no one has objects I'll explore how much work it would be to enable it.

**Comment by KevinTCoughlin** [comment]
The question is should we fix some typings that lead to incompatibility with `strictFunctionTypes` such as `IRenderFunction`. And if that's the case, would it best be done leading into a major release. At least those were the questions I had when investigating this.

**Comment by JasonGore** [comment]
This came up over the [`List` examples which use `onRenderCell` functions](https://github.com/OfficeDev/office-ui-fabric-react/blob/87b52babf2f9a07f6523ba13d7b06eff27eb8c07/packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.tsx#L108) that are inconsistent with [[`List`'s type]](https://github.com/OfficeDev/office-ui-fabric-react/blob/87b52babf2f9a07f6523ba13d7b06eff27eb8c07/packages/office-ui-fabric-react/src/components/List/List.types.ts#L88) and [generate a type error when using `strictFunctionTypes`](https://www.typescriptlang.org/play/?jsx=2&ts=3.5.1#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdwAdjFlAXlnAJIAywqGAAViYVAB4AKgD44AbzpwlcCE2xMAJmwDCWADZ6A-AC44ACmCsQJuJIA0cZloAeNpgFcQAIzYOBAZVxiA2YAcxsvCAg9HCYASjgAXllsPBgAOlT8ADkILXoAXwYsZ0hYRxY2DlwubgBRZ2RwGO4reUVlGAALTy8mZGA9U0EoMMLi0uh4XD00dH5BKSSUJgBPWRLWTXQsjO0SSCYsFnE+AWFRCRlZBSK6ErLp2dR584BxLohBMIamsBi4JtjhodlQ9gdVMd4AplHAwO4vHpgLg4JRNGwzHFTAApfwADXSdRiICh7VhsMoMHcUCY5nEC3gqnUWigugMiTk3QE6QA+kzgTp9HoCnAAPTSOL0WF3WFgUYAN2QrDgfLUAtZQosVlM9UazSwrSwID86Ocpg83l8jlQgWCSKYoVMkWisSxcFxBKJRtJMPJSkp1NpZnEGmA8rFEqlyiKRSAA).

We're planning on upgrading to TS3.7 soon and could investigate enabling `strictFunctionTypes`. However, to Kevin's point, it may not be possible to enable this without interface breaks. In that case, I think it's important to transition to using `strictFunctionTypes` for our next major release since it helps identify these types of inconsistencies.

**Comment by ecraig12345** [comment]
Agreed, I think the `strictFunctionTypes` transition would be better done in a major release instead of with the TS 3.7 upgrade--both due to the potential for breaks and the extra work involved.
