### ISSUE TITLE
TagPicker onDismiss isn't usable with scroll events

### ISSUE THREAD

**Issue by effectivetom** [microsoft/fluentui#10435]
### Environment Information

- **Package version(s)**: 7.28.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/huckyaus/pen/VwZxqBj

1. Generate some suggestions by typing a few characters into the TagPicker
2. Position the cursor outside the suggestions list and scroll down

#### Actual behavior:

The first suggestion is selected and the suggestions list is closed, despite `event.preventDefault` being called in `onDismiss`.

#### Expected behavior:

I'd like to prevent the TagPicker from selecting the first option when a scroll event is fired.

Overriding the default behaviour by passing a custom `onDismiss` works for other events such as clicks, but scroll events are not cancelable so `preventDefault` has no effect. I believe this functionality is within the scope of what [#3610](https://github.com/OfficeDev/office-ui-fabric-react/pull/3610) intended to accomplish.

### Priorities and help requested:

**Are you willing to submit a PR to fix?** No (I'm not sure how to approach fixing this)

**Requested priority:** High

**Products/sites affected:** We're building a SPFX application which is used heavily on mobile devices with small screens. This issue makes TagPickers unusable when one or more suggestions are rendered off screen. This happens quite often as the on-screen keyboard takes up a lot of space. When the user tries to scroll to see the rest of the suggestions, the first one is selected and the list is closed.

**Comment by natalieethell** [comment]
Hey @effectivetom thanks for opening an issue. I see what you're describing, we're taking a closer look.

**Comment by natalieethell** [comment]
So, as you touched upon, scroll events are not cancelable by `preventDefault`, which is done for good reasons. I do see, however, how there may be scenarios like yours where it's useful to opt out of automatically selecting the first picker suggestion and closing the suggestions container on scroll.

Supporting this behavior would involve a bit of work. 

There would be some extra logic specifically for scrolling events added to [`dismissSuggestions`](https://github.com/OfficeDev/office-ui-fabric-react/blob/9cf5bf6776eafaa5dd80ae965da01fa953a7271e/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L172) in BasePicker.

I see that even when `ev.preventDefault` is called on other events, `suggestionsVisible` is still set to false, closing the suggestions container. For the scenario above, it sounds like they'd want the option to keep the suggestions container open as well. 

Lastly, to ensure that the suggestions container would scroll with the TagPicker text field, you would want to utilize `this.props.pickerCalloutProps.doNotLayer`, since without that the suggestions container would float on its own (it would look something like below): 

![TagPicker suggestions container not closing](https://user-images.githubusercontent.com/14134000/65288398-9ac8ad00-dafb-11e9-9ce4-fd51f430be8c.gif)

This seems like something that might be best to put in the backlog, as it would involve discussion with design and engineering. @joschect What do you think, has the team considered this ask previously?

**Comment by joschect** [comment]
@effectivetom let me make sure I understand correctly, your issue is that being dismissed by a scroll event still selects an item, even though you're preventing default?

If that's correct then I'm a bit confused. You're correct that the pickers do care about defaultPrevented, but for some reason it looks like preventDefault doesn't work on scroll events (see screenshot) We'll need to dig into this more. 

![image](https://user-images.githubusercontent.com/20801176/65290586-bd12f880-db04-11e9-84a6-f697a1efbe31.png)

**Comment by joschect** [comment]
I think that the solution to this is that onDismiss should return something. That might be the only way to get it to do the right thing.

**Comment by effectivetom** [comment]
> @effectivetom let me make sure I understand correctly, your issue is that being dismissed by a scroll event still selects an item, even though you're preventing default?

@joschect you're correct. The reason preventDefault has no effect is that the 'cancelable' property on the scroll event is set to false. I'm not sure what influences the value of this property for any given event.

Just thinking out loud here - what about adding a prop to BasePicker which controls whether the first available suggestion is automatically selected when suggestions are loaded? This could be utilised toonly add an item onDismiss if a suggestion was been selected after the suggestions are loaded (eg. using keyboard focus)?
