### ISSUE TITLE
DatePicker should have required prop over isRequired.

### ISSUE THREAD

**Issue by myokha** [microsoft/fluentui#10456]
#### Describe the feature that you would like added
Use `required` prop on it instead of `isRequired`
#### What component or utility would this be added to
`DatePicker`
#### Have you discussed this feature with our team, and if so, who
No.
#### Additional context/screenshots
It's inconsistent with inputs like `TextField` and `Dropdown` which have `required` on them.

There is an [issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/6636) regarding adding an `isRequired` prop over to Pickers but I suggest that just `required` is a better option.

Also, I believe this is related to the [one](https://github.com/OfficeDev/office-ui-fabric-react/issues/9935) I've created earlier.

**Comment by aneeshack4** [comment]
@OfficeDev/uifabric-calendar @lorejoh12 thoughts on adding 'required' to the DatePicker?

**Comment by lorejoh12** [comment]
Looks like this is a long-standing issue that @micahgodbolt suggested (way back in Dec of last year) that we move to in order to be consistent with the default HTML attributes rather than our custom isRequired. https://github.com/OfficeDev/office-ui-fabric-react/issues/6636. One additional point has been brought up since then about using a wrapping Validating component and removing the prop entirely, although I haven't heard any discussion around it.

Changing it from `isRequired` to `required` would be a breaking change, which is pretty much a non-starter right now. We could consider adding a `required` prop for now and just removing the `isRequired` down the road, but I don't think that's high on our priority list at the moment, since it's more a styling concern than a functional one. I'm happy to discuss this with Micah at our next sync and see if there's a consensus on what the correct approach is here though.

**Comment by mYokha** [comment]
@lorejoh12, there are components with `isRequired`, `onChanged` or `isDisabled` marked as obsolete in documentation.
I'm not pushing for implementing it rn though as a user I _expect_ for consistency of props around the components.
