### ISSUE TITLE
[Accessibility][Keyboard Navigation]: Suggested tags text appears as if it’s a link due to its color (Bug 7)

### ISSUE THREAD

**Issue by jdhuntington** [microsoft/fluentui#10826]
Breakout of issue #8655

**Comment by joschect** [comment]
@betrue-final-final this looks like it's intentional. The issue is the color of the "Suggested Tags" text. As far as I can tell that's intentional. If that's incorrect, which color should I map it to?
![image](https://user-images.githubusercontent.com/20801176/68809783-7d0e5480-0621-11ea-9e99-2d9ecd3e16f6.png)

**Comment by micahgodbolt** [comment]
asked design for some guidance

**Comment by betrue-final-final** [comment]
I've heard this a couple of times. This is derived from the section heads that OWA had in their menus a few years ago. The design could be updated. Since then, I think that OWA has designed out their need for section titles in their menus. Wenvi Hidayet on SharePoint has expressed an interest in using section heads, and maybe she can take a crack at redesigning.
