### ISSUE TITLE
[FocusZone] TextBox does not remove selection on leaving focus in Edge & IE in a focusZone

### ISSUE THREAD

**Issue by tejs-code** [microsoft/fluentui#11308]
### Environment Information

- **Package version(s)**: (7.64.2)
- **Browser and OS versions**: (Edge 44.18362.449.0, Windows 10)

### Describe the issue:
If a textbox is added to a FocusZone, tabbing in or out of the textbox does not update the focus state of the textbox. 
Issue does not repro in Chrome or the new Chromium Edge

#### Actual behavior:

1. Highlight text in a textbox. Tab out of it. Text remains highlighted.
2. Tab into a textbox. Text does not get selected on focus

#### Expected behavior:

1. When tabbing out,  Text should no longer be highlighted since textbox doesn't have focus
2. When tabbing in, text should be highlighted on receiving focus.

### If applicable, please provide a codepen repro:
https://codepen.io/tegill/pen/BaaEqpN

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low): Normal

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
One note: without the focus management, edge automatically selects all of the textfield onfocus

![image](https://user-images.githubusercontent.com/1434956/69665954-403e5680-1040-11ea-82bc-5e208bada1e0.png)

which is consistent with edge behavior on standard HTML input.

Chromium also selects all of the text on focus regardless of focus management. So i think the problem is around what focus management does to the cursor placement in edge. It should always select all text on focus. You shouldn't have to 'select all' to get all of it.

**Comment by micahgodbolt** [comment]
Took 1 more look. Bug is still present. The issue revolves around `handleTabKey={FocusZoneTabbableElements.all}` (both all and inputOnly).
