### ISSUE TITLE
Accessbility Bug: When Tab into PeoplePicker, textbox should be focused

### ISSUE THREAD

**Issue by tianbli** [microsoft/fluentui#11441]
Fabric Version: probably happens on all of them, ex: the one on Fabric site: https://developer.microsoft.com/en-us/fabric#/controls/web/peoplepicker
Tried on Narrator on Edge

### Describe the issue:
For normal PeoplePicker, when there are existing selected items, tab into PeoplePicker will only read first item instead of what's in the textbox's aria-label. This fails to tell user where it is and what this combobox is doing.

### Please provide a reproduction of the issue in a codepen:
1. go to https://codepen.io/tianbli/pen/qBENZOV   you will see Annie Lindqvist and Aaron Reid are existing items in the people picker, don't touch the input box now as it will set focus to input.
2. Focus on any item below, ex: switch the Delay Suggestion Result toggle.
3. Use Shift + Tab to navigate back to PeoplePicker
4. Notice only the first item (which the name Annie Lindqvist) is announced in Narrator, everything in input's aria-label is ignored when user tabbed into PeoplePicker. 

#### Actual behavior:
For a normal picker, the first item in the combobox is focused first due to textbox displayed below all of the existing items in DOM. This causes screen reader only announce the first item and not what is in input's aria-label.

#### Expected behavior:
textbox should be focused.
Also, when itemLimit is set, and items reached its capacity. textbox will disappear (in BasePicker.tsx). This will also hide input's aria-label so screen reader won't read it.

### Documentation describing expected behavior
According to https://www.w3.org/TR/wai-aria-practices/#wai-aria-roles-states-and-properties-6
"When a combobox receives focus, DOM focus is placed on the textbox element."
So we should always focus on textbox when tab into a combobox.

**Comment by micahgodbolt** [comment]
@joschect this is certainly a bit of a functionality change in picker....focus going to the input rather than the first item. Has this been discussed as a possible change?

If that change is too breaking (gotta assume it'll impact users a bit), is there a way we should be announcing all of the existing entries upon focus?

**Comment by joschect** [comment]
@tianbli This is a good callout, you're right, focus should go into the textfield the first time the user interacts with it. If the user leaves the combobox and had been focusing on a user than the focus should go back to that user. This was an oversight and should be fixed. Also a good point on the item limit reached. We'll take a look.

@micahgodbolt I don't believe that this is intentional. All the users should already be announced upon focusing the input. The input has described by which points to the list of users but for some reason narrator isn't reading them all out. It's possible that it's a narrator bug. I'm talking with @jamesedjac about possible ways of solving this. Fixing the focus issue is not a breaking change imo and should be relatively easy.
