### ISSUE TITLE
Missing shape icons 

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#11478]
### Environment Information

- **Package version(s)**: Current version (https://developer.microsoft.com/en-us/fabric#/styles/web/icons#available-icons) How to see which version is used?
- **Browser and OS versions**: any

#### Actual behavior:

There are a few shape icons missing:
![image](https://user-images.githubusercontent.com/2737900/70886868-da107800-1fdc-11ea-8c72-c69980ea44e1.png)

#### Expected behavior:

Following counterparts are missing:
- ShapeSolid
- CubeShapeSolid
- CircleShape
- SquareShape
- DropShape

**Comment by ecraig12345** [comment]
@Jahnp or @maxwellred can you help with this?

**Comment by maxwellred** [comment]
@LukeOwlclaw @ecraig12345 I am currently trying to get a hold of the font owner/designer for more information. In the meantime, I have cross-referenced these icons in the source of truth file and don't see them there. Luke are you assuming they should be there or were they there originally and now they aren't? Thanks!

**Comment by LukeOwlclaw** [comment]
@maxwellred Yes, I am just assuming they should be there. Does not look consistent if some shapes are available in pairs and others are not.

**Comment by maxwellred** [comment]
Just an update: I've talked to a few designers and still have to answer some spec related for the them so I'll keep you all posted

**Comment by Jahnp** [comment]
Further update: @maxwellred and I chatted and managed to get the designs formally queued up. The design work has been done, now we're waiting for handoff to us later this to implement in the [Fabric icons tool](https://aka.ms/uifabric-icons). Once that's updated, we will be able to begin the process of updating @uifabric/icons, which will finally update the UI on the page @LukeOwlclaw linked above. We'll keep you posted as this progresses.

**Comment by Jahnp** [comment]
Update: The icons were handed off late last week, and we just published the update to the Fabric icons tool that includes these icons. You can see them here:
![image](https://user-images.githubusercontent.com/307118/73698912-43387180-4697-11ea-9496-0545038dc0cf.png)

The next step will be to update the default Fabric React icon set. I don't have an ETA for that, but I'd like to get to it this week or early next. But since they're in the icons tool, you can use them right now if you're ok with using custom icon subsets.

**Comment by Jahnp** [comment]
Apologies for the delay. This will be completed in #12088.
