### ISSUE TITLE
Auto-columns for SwatchColorPicker

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoft/fluentui#11481]
#### Describe the feature that you would like added

When no ``columnCount`` for ``SwatchColorPicker`` is defined, use the available width and put as many columns as fit. This is what [ChoiceGroup](https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup) does by default.
(``columnCount`` becomes optional)

#### What component or utility would this be added to

[SwatchColorPicker](https://developer.microsoft.com/en-us/fabric#/controls/web/swatchcolorpicker)

**Comment by ecraig12345** [comment]
I agree this would be convenient, but it's not something we're likely to prioritize due to the amount of work involved and the fact that SwatchColorPicker is one of our less widely used controls. 

Since the control uses a table for layout (which is wrong semantically), we can't use flexbox or other CSS styles to automatically make items wrap. Instead I think we'd have to add manual measurement code, which increases complexity, code size, and potential for bugs. 

It might be more worthwhile to instead do an entire rewrite of the control's layout logic to use flexbox, and add the wrapping feature as part of that. Unfortunately that would have to be done in a major version since the DOM changes could break consumers' styling overrides or tests.

**Comment by ecraig12345** [comment]
Closing this in favor of #13574 since that one is basically requesting the same feature and has more discussion (despite this one being older).
