### ISSUE TITLE
Theme Designer incorrectly states theme is accessible

### ISSUE THREAD

**Issue by betrue-final-final** [microsoft/fluentui#11634]
The Theme Designer has a couple of issues that make it incorrectly identify a theme as accessible:

1. It doesn't check for accessibility of neutralSecondary. This color is used as secondary text across many components, which need to be accessible at 4:1 contrast
 ![image](https://user-images.githubusercontent.com/20363037/71932541-de9bfc80-3154-11ea-94ec-b5b095019cde.png)

2. It does not correctly generate the proper neutralSecondary value, based on the default setting of "Text". This value is #323130, and neutralSecondary should be #605e5c, but it shows as #a3a2a0
![image](https://user-images.githubusercontent.com/20363037/71932618-0723f680-3155-11ea-92d5-580e0a153d20.png)

**Comment by aneeshack4** [comment]
Working on a fix to this - ThemeRulesStandard.ts hasn't been updated in a while and I'm trying to refactor it in such a way that it can stay updated in conjunction with DefaultPalette.ts even as those colors change.

**Comment by aneeshack4** [comment]
Keeping this issue open because although I fixed the fabric palette colors' default values & the theme generation is working properly when the user drags the color pickers, if they reset the primary/text/background colors manually to the defaults (instead of refresh the page), the resulting fabric palette values are not correct/consistent with what they started out with. This is because the algorithm currently overrides the original handpicked colors with generated colors. Will see if I can find a fix in the underlying code for this.
