### ISSUE TITLE
[Accessibility-Keyboard Navigation] - Keyboard focus moves twice on same control for Nav component

### ISSUE THREAD

**Issue by kejatura** [microsoft/fluentui#11705]
### Environment Information

- **Package version(s)**: 7.74.1
- **Browser and OS versions**: Windows 10 + [Edge,Chrome]

### Describe the issue:

This was previously filed here (but not fixed): https://github.com/OfficeDev/office-ui-fabric-react/issues/11321

Team is currently using the Nav component from office-ui-fabric-react as a file dropdown/explorer. We are not using the content as links, but as selectable items.

The team recieved a keyboard navigation accessibility bug due to keyboard moving individually to the "drop down icon" and "dropdown item control".

User experience impact:

- If the focus does not follow proper order, it will be very confusing and disorienting for the user with visual disabilities to perform a task that requires the user to follow certain steps in a particular order or interact with the UI in a uniform order.

- If keyboard focus moves twice on any section and functionality is same in both condition then it will increase one extra step to any user who depends upon keyboard.

### Please provide a reproduction of the issue in a codepen:

(copied from https://developer.microsoft.com/en-us/fabric#/controls/web/nav)

Note: The team is using the same functionality for "onLinkClick" and "onLinkExpandClick" 

codepen: ~~https://codepen.io/kejatura/pen/jOEzQjV?editors=1010~~
https://codepen.io/ecraig12345/pen/JjOoJLB?editors=1010

- start keyboard navigation on icon, then move down.

#### Actual behavior:

Focus is moving individually on "drop-down icon" and "drop-down control" but both controls are having same functionality.

#### Expected behavior:

Focus should not move individually on "drop-down icon" and "drop-down control" having same functionality.

**Comment by xugao** [comment]
@kejatura - I can repro the issue. will look into fixing. 
also, just to point out, #11321 was never fixed. the issue was unclear to us what it was

**Comment by kejatura** [comment]
@xugao thank you for looking into this. And yes, I know it was a bit confusing.

**Comment by xugao** [comment]
@kejatura - I'd like to bring up an option to see if that would work with your app:

In this [example](https://codepen.io/xugao/pen/OJRMKvJ) , instead of only define `links` in each `INavLinkGroup`, you can also define a group header which has the focus behavior you wanted.

Let me know if that would solve your concern or not.

**Comment by ecraig12345** [comment]
Updated codepen: https://codepen.io/ecraig12345/pen/JjOoJLB?editors=1010

**Comment by smhigley** [comment]
It looks like this is because the parent items are defined as links, but don't have URLs. If you edit the `groups` structure so the parent items are not links, as in the "Nav similar to the one in this demo app" example, it works as expected:
https://codepen.io/smhigley/pen/a20627f96ea5eef77b32ea38232e4c6c 

@kejatura does that approach work for you?
