### ISSUE TITLE
Some Fabric CodePens stopped working (fix available)

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#11773]
Due to some recent changes made by CodePen, any pen which declares/destructures a top-level const called `Fabric` will no longer render. For example:
```tsx
const { DefaultButton, Fabric } = window.Fabric;
// this is the problem ^^^^^^ 
```
This will prevent the pen from rendering and display an error in the console: `pen.js:1 Uncaught SyntaxError: Identifier 'Fabric' has already been declared.`

Unfortunately, **any existing pens [like this](https://codepen.io/xugao/pen/gObqWBZ) must be updated manually** (there's no way we can reasonably fix this on the Fabric side).

One way to fix this is to rename the local `Fabric` to something else, and update any references. For example:
```tsx
const { DefaultButton, Fabric: FabricComponent } = window.Fabric;

// later
<FabricComponent>{/*...*/}</FabricComponent>
```

(@xugao has a PR #11771 which will fix this for newly-exported codepens, but I'd like to leave this issue open to highlight the instructions for fixing existing codepens.)

**Comment by shshaw** [comment]
Do you have any example pens where we can see this issue to see if there's anything we can look at on our end?

**Comment by xugao** [comment]
@shshaw - i updated the description to include an example pen: https://codepen.io/xugao/pen/gObqWBZ

**Comment by quezo** [comment]
Thanks @xugao We found the problem. We'll have a fix out soon and update you here.

**Comment by quezo** [comment]
@xugao Sorry about that blip. We fixed the bug and added a test for this specific problem. Your Pens are working again.

**Comment by xugao** [comment]
@quezo - thank you so much for the quick fix. I can confirm this is fixed.
For my own curiosity, could you elaborate on what the root cause was for this bug?

**Comment by ecraig12345** [comment]
This just happened again, meaning some of our codepen templates and a lot of existing codepens in our issues are broken. @shshaw or @quezo if you're still working on codepen.io can you help?

**Comment by ecraig12345** [comment]
I made a PR #16319 to fix "export to codepen" on our website moving forward (same workaround @xugao did last time this came up), but I'm going to leave this issue open since a lot of existing codepens are broken and ideally we need to get in touch with the codepen team to fix it on their side.

**Comment by shshaw** [comment]
Following up from the CodePen side:

Sorry that some Pens are erroring. We updated TypeScript processing to the version 4.1.2 and that seems to have changed how the final output runs on the page. 

Ultimately, Fabric is declared as a global variable in the external script ( `var Fabric = { ...` ), then in the Pens you're trying to redeclare that variable in the global scope through destructuring ( `const { ..., Fabric } =  window.Fabrc;` ) which results in a runtime error in the browser. This happens if you switch from TypeScript to another processor or none at all as it's an issue in the JS.

We may have had some kind of IIFE wrapper on the TypeScript output before which prevented the variables from being in the global scope, but with the latest processing update, the output much more closely matches the input.

Rewriting the Fabric destructuring like already mentioned in the original post ( `var { ..., Fabric: FabricComponent }` or wrapping your code in a function to remove the variable declarations from the global scope are the best long term solutions.

**Comment by ecraig12345** [comment]
@shshaw Thanks for following up! I've made that change for our template, but the unfortunate thing is that there's no way to fix existing codepens all-up on our side (they'd have to be updated by all the authors). So unless there's a way you can add back an IIFE wrapper this means we're stuck with a lot of issues repros that no longer render. (Though I do agree that technically this code which shadows/overwrites the Fabric global was not so great to begin with.)
