### ISSUE TITLE
Controlling Tab re-renders 

### ISSUE THREAD

**Issue by Temkit** [microsoft/fluentui#11965]
#### Describe the feature that you would like added

Controlling pivotItem re-renders

- renderActiveOnly  Only the active pivotItem is rendered. Switching pivotItem unmounts the current pivotItem and mounts the new pivotItem.
- renderActiveOnly={false} All pivotItems are rendered on Pivot mount. Switching pivotItem hides the current pivotItem and shows the new pivotItem, without unmounting pivotItems.

this will prevent filled forms to re-render on pivotitems swith ...

#### What component or utility would this be added to

Pivot

**Comment by khmakoto** [comment]
Hi @Temkit, if I'm understanding correctly you would basically like persistent and non-persistent scenarios for the `Pivot` component right?

@jdhuntington what do you think about this feature request?

**Comment by j-te** [comment]
Having a non-persistent options would be great because react should do the work of deciding when to re-mount the child components which is likely form elements. Currently, it's a complete re-render so we're losing the states. This means the child components in PivotItem require props and a stateful component above Pivot. Also, rendering resource is taken.

For instance: uncontrolled components like Dropdown for currently selected keys.

**Comment by jedmonsanto** [comment]
this would be great feature, no need to mount/unmount when switching PivotItem @khmakoto
