### ISSUE TITLE
Better documentation of inherited props

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#12043]
Right now, we don't have a very obvious way of showing inherited props on the website (we just show a name/link of the extended interface).

![image](https://user-images.githubusercontent.com/5864305/75194137-6b524800-570c-11ea-98af-2092e166b2e7.png)

This is especially bad for components like [Link](https://developer.microsoft.com/en-us/fabric#/controls/web/link#implementation) where core props like `href` are inherited from native and not listed in our prop tables at all.

![image](https://user-images.githubusercontent.com/5864305/75194226-93da4200-570c-11ea-93c4-4da39a7e3dcc.png)

I'm not sure what the best way to handle this is.

**Comment by khmakoto** [comment]
I've noticed this before as well, I wonder if there is a way we could tell the API generator (for example via an annotation) that we want certain specific inherited props surfaced in the API tables.

**Comment by ecraig12345** [comment]
I've looked into getting info about inherited props through API extractor, but as far as I can tell it's not trivial. 
Would be worth the effort though to get it working.

Some other aspects we should consider are:
- the API for marking which inherited props should be surfaced (like you mentioned)
- the visual design for indicating that that a prop is inherited (if this is even needed; it might not matter from a consumer perspective)

**Comment by ecraig12345** [comment]
Related:
https://github.com/OfficeDev/office-ui-fabric-react/issues/7962#issuecomment-462856753
#11729 
#12027
#5936
https://github.com/OfficeDev/office-ui-fabric-react/issues/7439#issuecomment-452551616

I'm pretty sure there was at least one other issue due to someone being confused about the `href` prop being missing from Link documentation, but I can't find it right now.

**Comment by octogonz** [comment]
Other people have requested this feature for API Extractor as well.  It's a good idea and something that DocFX is capable of representing for `docs.microsoft.com`.  I don't see an API Extractor GitHub issue officially requesting this, but we certainly would be onboard.

If someone wants to drive the implementation, I'm happy to help out with the design and strategy.  Please open a GitHub issue for API Extractor.

This Fabric issue seems to be focused on Fabric's proprietary API website, which (if 
 I remember right) consumes the `api-extractor-model` library directly instead of relying on the API Documenter tool.  This scenario may be somewhat easier, since we don't need to update the rendering templates.  We merely need to expose the data via the `api-extractor-model` library.  For example maybe it would be sufficient for [HeritageType](https://github.com/microsoft/rushstack/blob/9f285aec8fbef104092801acbc9e15a68bf3984f/apps/api-extractor-model/src/model/ApiClass.ts#L60) to provide a reference to the base `ApiClass` or `ApiInterface` object, and then Fabric's website renderer can collect the members manually.  We could also implement a helper `ApiClass.getInheritedMembers()` that collects the members for you.

@ecraig12345 @rbuckton @apostolisms FYI
