### ISSUE TITLE
ComboBox: borderColor applied by errorMessage is supplied to an incorrect element 

### ISSUE THREAD

**Issue by adriangut** [microsoft/fluentui#12122]
Error border color is supplied to ComboBox(number)wrapper, but the one that is actually used is within ComboBox(number)wrapper's ::after.

### Environment Information

- **Package version(s)**: 7.98.1

### Please provide a reproduction of the bug in a codepen:

See the border color of ComboBoxes that are given an errorMessage:
https://fabricweb.z5.web.core.windows.net/oufr/7.98.1/#/examples/ComboBox
Compare it to the color of TextFields that are given the same prop:
https://fabricweb.z5.web.core.windows.net/oufr/7.98.1/#/examples/TextField

#### Actual behavior:

The border color stays as if the input had no error.

#### Expected behavior:

The border color changes to inform about the error.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by aneeshack4** [comment]
Hi @adriangut, thanks for reaching out to us! I think I have a fix - I'll send out a PR soon.

**Comment by aneeshack4** [comment]
I thought this was just because the wrote semantic slot was being used but actually ComboBox.styles.ts is correctly setting `semanticColors.errorText`. It seems that the border color of red is being calculated in the styles properly:
![image](https://user-images.githubusercontent.com/4161791/75594991-97890400-5a3f-11ea-8be3-4969ffa0800f.png)
But it's being overriden somehow... @joschect do you know what this could be?

**Comment by joschect** [comment]
@aneeshack4 looks like it's because there isn't an actual border for the combobox. Rather it's using the ::after selector. In the screenshot attached you can see that the border now appears correct. 

I believe that the fix is to change [these lines](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts#L420-L428) and add another selector in the  that reads `:after { bordercolor: root.erroredColor; ...}`
