### ISSUE TITLE
Remove the dependency on React library for @uifabric/icons

### ISSUE THREAD

**Issue by fhljys** [microsoft/fluentui#12178]
#### Describe the feature that you would like added

Long time ago, I created a issue. https://github.com/OfficeDev/office-ui-fabric-react/issues/9660
Now it is closed. But when I try to use it, I still hit this:
![image](https://user-images.githubusercontent.com/18674958/75859019-3c3a8580-5e34-11ea-8d30-0f4b39b862ef.png)

#### What component or utility would this be added to

Though you removed dependency in styling, but styling depends on utilities.
Is it possible to remove react dependency for utilities as well?

**Comment by khmakoto** [comment]
Hi @fhljys, this is much harder than removing the dependency from `styling` itself since many of the things you're pointing out are inherently linked to React. We are, however, in the midst of doing work to break out the utilities package ad can be seen in #11947. Once that is done maybe we can revisit this, until then I'll put this on the backlog.
