### ISSUE TITLE
Clearable search Dropdown doesn't hide the X button when removing a selected item with backspace

### ISSUE THREAD

**Issue by jelenamarjanovic95** [microsoft/fluentui#12225]
When using a clearable search Dropdown component, I am allowed to remove the item by using backspace, but in this case the X button to clear the content doesn't disappear, even if I remove everything from the input field.

Steps to repro:
- Have a clearable search dropdown component with some items
- Select an item from the dropdown --> The field is populated and an X button shows up on the right end of the field
![image](https://user-images.githubusercontent.com/30659878/76092583-e98dd480-5fbf-11ea-9ad5-6c34a5a956a1.png)

- Start removing the text from the field --> **The X button is still present but should disappear and the down arrow should be shown again instead**
![image](https://user-images.githubusercontent.com/30659878/76092636-03c7b280-5fc0-11ea-9c01-be191dd2d3ee.png)

- Remove all the text from the field and click outside of the field --> **The X button is still there**
![image](https://user-images.githubusercontent.com/30659878/76092679-1cd06380-5fc0-11ea-9a42-2b4601bd7a56.png)

**The button will only disappear once clicked on**
### Codepen link:
https://codesandbox.io/s/fluent-ui-example-6nd0u?fontsize=14&hidenavigation=1&theme=dark
It is also easily reproducible on the Fluent website.

**Comment by silviuavram** [comment]
We are keeping the `X` because even though we clear the `searchQuery` the `value` is still there.

If we want to fix this then we should also clear the `value` when there is no `searchQuery` remaining.

That is why we may need a spec written.

**Comment by aneeshack4** [comment]
@jelenamarjanovic95 thanks for reaching out to us. So, you're right that when I clear all the text, the X button is still there but it acts a toggle - if you click the X then it truly clears all and the down arrow appears again. I wonder if this is by design - I can def see the case that it's a bit confusing/should automatically toggle between X and the down arrow when text is manually cleared. Let me check with the owner and see what's up.
