### ISSUE TITLE
Cleared Customer Picker text display again when clicking outside.

### ISSUE THREAD

**Issue by zeedomD** [microsoft/fluentui#12369]
### Environment Information

- **Package version(s)**: 7.105.1
- **Browser and OS versions**: Microsoft Edge 44.18362.449.0

### Please provide a reproduction of the bug in a codepen:

This issue is related with #11865 , but it doesn't fix the problem.

1. Go to UI Fabric React Examples website, https://fabricweb.z5.web.core.windows.net/oufr/7.105.1/#/examples/pickers
2. Go to "Custom Picker".
3. Input the text in the input area.
4. There is a "X" button appeared on the right side.
5. Click on the "X" button, the input text should be cleared.
6. And then clicking on other place to remove the focus on the Picker.

#### Actual behavior:

The cleared text is displayed in the Picker again.

#### Expected behavior:

The text should not be displayed.

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: Normal

**Comment by aneeshack4** [comment]
Hi @zeedomD, thanks for reporting this! I confirm repro of this on Edge on the Custom Picker (document picker). @xugao it looks like that example's snapshot didn't get updated in #11869 which is a bit strange because it seems to use BasePicker mostly the same as TagPicker which did get its snapshot updated... I'll look into this further.

**Comment by zeedomD** [comment]
@aneeshack4 , any updates?

**Comment by zeedomD** [comment]
@aneeshack4 , @xugao , I will try to submit a PR to fix this problem. thx
