### ISSUE TITLE
Dropdown shouldn't show the focus outline after selecting options via mouse click. 

### ISSUE THREAD

**Issue by vida83** [microsoft/fluentui#12375]
The Dropdown shouldn't show the focus outline after selecting options via mouse click. 
In contrast to the Combobox which is related to a Textfield the Dropdown should hide his focus outline in case an option hasn't been selected via the keyboard. 

As you can see in the screenshot, the dropdown shows a focus outline while the body carries the isFocusHidden. 
![Screenshot 2020-03-20 at 16 02 24](https://user-images.githubusercontent.com/7108517/77178356-419bff00-6ac7-11ea-8fe6-5317069b11ac.png)

### Environment Information
- **Package version(s)**: 7.105.1

**Comment by aneeshack4** [comment]
@vida83 Thanks for reaching out to us. I believe this is by design - I just checked on [Combobox](https://developer.microsoft.com/en-us/fabric#/controls/web/combobox) and [Dropdown](https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown) and [TextField](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield) - this focus outline on mouse click gets dismissed when you click out and that's consistent across these 3 components.
