### ISSUE TITLE
Background color removed on ChoiceGroup when disabled

### ISSUE THREAD

**Issue by Puyush6889** [microsoft/fluentui#12386]
https://github.com/microsoft/fluentui/blob/492fff101f5943affeae637bebe761fdd163b0a0/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.styles.ts#L178

![image](https://user-images.githubusercontent.com/14367457/77259388-4e8f2e80-6c3e-11ea-9235-1984339e1a46.png)

Why was the background color removed on raidobutton when it's disabled. Our team is using fabric version 7.7.0.

**Comment by aneeshack4** [comment]
@Puyush6889 If you look at "git blame" you can see that it was removed in this PR: https://github.com/microsoft/fluentui/commit/c83add9cbc62c6530f2a9afd06fad57297473b40 by @Vitalius1 - looks like it was removed among bulk style adjustments a year ago - the PR description doesn't say anything else but maybe Vitalie can provide further context.

**Comment by Vitalius1** [comment]
This was a part of the fluentization process for the Fabric 7 so this was definitely an intentional change. A quick look at the line that was linked the change was to follow the design specs for fluent looks of the control (when a choice is checked but at the same time is disabled). Below are some screenshots to how it was before (Fabric 6 MDL2 styling) and after (Fabric 7 fluent styling)

# Before
![choice_non_fluent](https://user-images.githubusercontent.com/29514833/77354817-ab531d80-6d00-11ea-9353-64262bfb8dec.jpg)
 # After
![choice_fluent](https://user-images.githubusercontent.com/29514833/77354832-b312c200-6d00-11ea-8b28-3a786343fdf7.jpg)

**Comment by Puyush6889** [comment]
In fabric 6 the the disabled and checked state was treated to be same. So when a checkbox was disabled it would be marked out gray.
![image](https://user-images.githubusercontent.com/14367457/77359932-acd51380-6d09-11ea-9beb-4ee364f1d1e8.png)

After syncing with @Vitalius1, fabric 7 they keep track of the state so when it's disabled the circle is changed to disabled state as shown in the picture 
![image](https://user-images.githubusercontent.com/14367457/77360136-0e957d80-6d0a-11ea-8c93-e481cd145c9e.png)
