### ISSUE TITLE
When empty string is passed as iconName in DefaultButton the icon placeholder isn't rendered

### ISSUE THREAD

**Issue by asnikam-7** [microsoft/fluentui#12425]
### Environment Information

- **Package version(s)**: ^7.105.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/byQeBY

#### Actual behavior:

When passing in empty strings as the iconName for iconProps in DefaultButton, the placeholder does not get rendered. Passing in a random string that does not match an icon name or an empty string with a space renders the placeholder however.

#### Expected behavior:

Passing in empty strings as iconNames should render the placeholder icons.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@asnikam-7 Thanks for reporting this. I confirm repro. I believe this line needs an added check in Icon.base.tsx: https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Icon/Icon.base.tsx#L27 The added check should make sure the string is in the list of icon names - not sure why empty string is being accepted though because there is a `length === 0` check. Let me dig further and report back to you.
