### ISSUE TITLE
A11Y - CommandButton Dropdown announces "selection contains 0 items" when an item is selected and dropdown is collapsed

### ISSUE THREAD

**Issue by achang0406** [microsoft/fluentui#12424]
### Environment Information

- **Package version(s)**: Office-ui-fabric-react ^7.0.0
- **Browser and OS versions**: chromium Edge Version 80.0.361.69

### Describe the issue:

Using the CommandButton component to create a dropdown. When a value is selected for the dropdown, the narrator will read "selection contains 0 items" even though an item is selected.

1. turn on narrator
2. focus on dropdown
3. select a value in the dropdown
4. refocus on the dropdown while its collapsed
4. observe

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/NomNoms/pen/PoqywVG

#### Actual behavior:

the narrator reads "selection contains 0 items" even though an item has been selected.

#### Expected behavior:

narrator should acknowledge there are items selected in the dropdown component.

### Documentation describing expected behavior

A11Y MAS guideline
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4%7d&cid=d3faf69f-e509-48bc-9833-b320268ef176

@jgage176

**Comment by aneeshack4** [comment]
@achang0406 Why don't you use the CommandButton [codepen ](https://codepen.io/aneeshack4/pen/zYGMKba?editable=true) that has been provided on our docs site? It looks like it will your purposes exactly and Narrator works well with that and doesn't announce incorrectly.
![image](https://user-images.githubusercontent.com/4161791/77594340-881c9f80-6eb3-11ea-8c59-61a569ca918f.png)

**Comment by achang0406** [comment]
well this simply just doesn't announce whether an item is selected at all.

Is there no way to have the narrator acknowledge how many items are selected in the dropdown?

**Comment by aneeshack4** [comment]
@achalachal2003 As you can see in the screenshot Narrator announces "selection contains 2 items" - that implies an item is selected... no other information is necessary.

**Comment by achang0406** [comment]
Wait this is incorrect. The narrator is only announcing the selection when the dropdown is expanded.

However, the narrator does not announce what has been selected when the dropdown is collapsed.

This is still an issue.

**Comment by aneeshack4** [comment]
@achang0406 I believe this is the correct behavior to only announced selection when expanded... because by definition, when collapsed the items inside the dropdown are not selected. I looked at the MAS guidance you linked and it doesn't anything substantial about this... do you have any other guidance that states this behavior should be otherwise?

**Comment by aneeshack4** [comment]
@achang0406 Also, I don't see anywhere in that NarratorBuddy output nor remember from hearing the narration the AT announcing "selection contains 0 items" - on collapsed it says "New item, menu item, collapsed" and upon expand it says "Email message, menu item 1 of 2, etc..." which is the correct behavior. So I still don't repro the incorrect behavior you're talking about.

**Comment by achang0406** [comment]
First comment:
It seems counter intuitive to me that the narrator does not announce the selected value when the dropdown is collapsed. So every time the user wants to know the selected value, they would have to expand the dropdown? This seems excessive.

2nd comment:
I realize narrator would only announce "selection contains 0 items" when the role is "listbox". I guess this is no longer relevant.

**Comment by aneeshack4** [comment]
@achang0406 Afaik, there's no ARIA role to set the selected value to tell ATs to read out the selected value. Here's aria-selected: https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#aria-selected which is being correctly set right now in Dropdown but as you can see it's a boolean state. Here's a reference example of Dropdown aria roles: https://a11y-guidelines.orange.com/web_EN/exemples/simple-menu/simple-menu.html. I can't find any that have the selected value specifically called out. So like I said before, this is by design.

**Comment by achang0406** [comment]
Ok i have found an alternative solution to announcing the selection by simply adding the text in the aria-label.

Thanks for addressing the issue.
