### ISSUE TITLE
Combobox with autocomplete = 'on' is narrated as read-only by Windows Narrator

### ISSUE THREAD

**Issue by SarveshNamjoshi** [microsoft/fluentui#12497]
**Environment Information**
         Package version(s): current
         Browser and OS versions: Microsoft Edge Version 81.0.416.34 (Official build) beta (64-bit)

**Please provide a reproduction of the bug in a codepen:**
Code pen : https://codepen.io/Namjoshi/pen/oNXVmNp
repro-steps : 1. Run the codepen in Edge (preferably in Edge chromium)
                     2. Start windows narrator (with scan mode off)
		     3. navigate till combobox
		     4. Observe that narrator is narrating the combobox as read-only
			  
**Actual behavior:**
For Combobox with autocomplete = 'on', windows narrator is narrating as read-only.

**Expected behavior:**
Since user is able to type in the combobox, narrator should not narrate the combobox as read-only.

**Priorities and help requested:**
Requested priority: High

**Comment by aneeshack4** [comment]
Hi @SarveshNamjoshi, thanks for reaching out o this. I confirm repro of this behavior:
![Uploading image.png…]()
When autocomplete is on but allowFreeForm is also set to true, it doesn't repro
![image](https://user-images.githubusercontent.com/4161791/78207306-25e51100-7456-11ea-8320-800ff910d9ac.png). This behavior is [explicitly defined](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx#L1975) in ComboBox.tsx. When freeform is not allowed, [readonly](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx#L437) is set to true. I believe this is because it's not allowing the user to input options outside of the pre-set ones. So Narrator is correctly reading this out loud as read only. @joschect - correct me if I'm wrong.

**Comment by SarveshNamjoshi** [comment]
@aneeshack4  Thanks for clarifying the behavior. 
@joschect Could you please confirm on this, and I am fine to close this thread.

**Comment by aneeshack4** [comment]
@SarveshNamjoshi Yes confirming that behavior.

**Comment by betrue-final-final** [comment]
Hey @aneeshack4, @smhigley brought this to my attention. I understand that if you think about how it's built it may make sense for it to be "read-only", but that's a confusing message for someone hearing and using the control. Is there anything we can do?

**Comment by smhigley** [comment]
If it helps, there's work on creating an example of exactly this pattern in the APG: https://github.com/w3c/aria-practices/issues/1026 (code preview: https://raw.githack.com/w3c/aria-practices/select-only-combo/examples/combobox/combobox-select-only.html).

The gist is that rather than use an `<input>`, the combobox role goes on a `<div>`, so a `readonly` attribute is not needed to prevent freeform input
