### ISSUE TITLE
Screen readers in virtual cursor mode can navigate to an invisible element at the end of a List

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluentui#12527]
Environment Information
Package version(s): office-ui-fabric-react@7
Browser and OS versions: Chrome 80, JAWS 2019.1912.1
Describe the issue:
In virtual cursor mode, JAWS can navigate to an invisible "list end" element at the end of a List

Please provide a reproduction of the issue in a codepen:
https://codepen.io/davyrwoo/pen/WNvBbqL?editable=true

Actual behavior:
Using up and down arrows in virtual cursor mode, the screen reader focuses on an invisible element at the end of a list and says "list end"

Expected behavior:
Screen reader should not navigate to this invisible element in virtual cursor mode.

**Comment by aneeshack4** [comment]
@davyrwoo Thanks for reaching out to us. This doesn't repro on Narrator: 
![image](https://user-images.githubusercontent.com/4161791/78416110-4a1e2a80-75db-11ea-974a-969158cc49c5.png)
And I don't have access to JAWS - either way since this doesn't repro on Narrator, it's probably a JAWS issue. Please contact them.

**Comment by davyrwoo** [comment]
Yes this seems to be a JAWS only issue
