### ISSUE TITLE
In ContextualMenu, menu item with text '-' is wrongly rendered as divider

### ISSUE THREAD

**Issue by yyqian** [microsoft/fluentui#12542]
In ContextualMenu, if we define the menu items in below:

```
const menuItems: IContextualMenuItem[] = [
  {
    key: 'newItem',
    text: 'New Item',
    onClick: () => console.log('New clicked'),
  },
  {
    key: 'rename',
    text: '-',
    onClick: () => console.log('Rename clicked'),
  },
  {
    key: 'edit',
    text: 'Edit',
    onClick: () => console.log('Edit clicked'),
  }];
```

The rendered item list is:
- New Item
- [Divider]
- Edit

instead of:
- New Item
- `-`
- Edit

**Comment by joschect** [comment]
@yyqian Thanks for the submission! This is certainly confusing as it is not documented, but this is expected behavior. I believe that before there was a menuItemType we used the - to indicate that an item should be a divider. We will update the docs to make it more clear that this is expected behavior. 

As a workaround I would suggest using an emdash (—), the figuredash (‒) the minus symbol (−), which is distinct from the endash that most keyboards make (-). Here's a [codepen](https://codepen.io/slimemold/pen/dyoxZMJ) that demonstrates the differences.

**Comment by yyqian** [comment]
Thx, I think I can take the workaround to replace - with figuredash (‒)
