### ISSUE TITLE
Dropdown items shifting & moving when max height is set

### ISSUE THREAD

**Issue by canmenekse** [microsoft/fluentui#12635]
### Environment Information
Windows 10
### Please provide a reproduction of the bug in a codepen:

There is `maxHeight ` set on the dropdown item container

https://codepen.io/cm1234/pen/oNjNJBd

1.  Open the dropdown scroll down.
2.  Move the cursor up and down in the dropdown callout.
3.  The items are going to shift places and become hard to select.

#### Actual behavior:
The items are shifting places.

#### Expected behavior:

The items or the scrollbar should not move when the cursor moves.

### Priorities and help requested:
Requested priority: (Blocking, High, **Normal**, Low)

Additionally this does not happen in combo box which is a similar component.

**Comment by joschect** [comment]
@canmenekse Thanks for the submission! This is due to the height needing to be controlled by the callout rather than the dropdown for some eventing. It's poorly documented. I'll make a task to have this more explicit in both dropdown and combobox. You can see the dropdown working  as expected in [this modified version of your codepen](https://codepen.io/slimemold/pen/bGVGOLd?editors=0010)

**Comment by canmenekse** [comment]
That works, thank you! 👍
