### ISSUE TITLE
Choice group with icon hides text

### ISSUE THREAD

**Issue by TonyTroeff** [microsoft/fluentui#12652]
![image](https://user-images.githubusercontent.com/33567383/79037721-4e9aa280-7bdc-11ea-87f7-8e910239b84c.png)

Whenever the icon is too small and the text too long, it looks like it is trimmed by the choice group.

### Environment Information

- **Package version(s)**: 7.106.0
- **Browser and OS versions**: Windows 10, Photo is taken on Brave but tested on other browsers as well.

#### Actual behavior:

I cannot see the text if the icon should be small.

#### Expected behavior:

The text should be visible with small icons. 
Maybe add a max-length restrictions for the text if you worried about the cases when someone would write a whole text in that choice group.

**Comment by joschect** [comment]
@TonyTroeff Thanks for the submission! I can see that choice group does not automatically resize based on the text. @ecraig12345 might be able to chime in on exactly the expected behavior.

Luckily you can already fix this using styling. Here is a [codpen](https://codepen.io/slimemold/pen/vYNOwwY?editors=1010) with a few examples of customizing the text. You can see that the small image doesn't look appropriate, and would likely need something like smaller text size or the entire choiceoption would need to be sized up. At least in the short term you should be able to customize the choice group option to fit your needs as a workaround.

**Comment by ecraig12345** [comment]
I'm not sure what the design is here, but it does seem incorrect that the text is being clipped rather than ellipsized when it's too long. Beyond that, I think it's up to the user to either ensure their text is short enough to work with the image size they want, or restyle it in one of the ways @joschect showed.

**Comment by TonyTroeff** [comment]
@ecraig12345, I agree with you but I think that this issue still can be improved. You can see that the text is not that long an I am sure that it can be freely contained within that area.

**Comment by joschect** [comment]
@TonyTroeff Thanks for suggestion. We'll keep that in mind when put the bugfix in!
