### ISSUE TITLE
Negative tabIndex on ChoiceGroup elements is ignored when other elements don't have a tabIndex

### ISSUE THREAD

**Issue by ehmPlankje** [microsoft/fluentui#12662]
### Describe the issue:
When an element has a negative tabIndex value, it should be ignored when the user tabs through the page. However, when other elements on the page don't have a tabIndex, then the ChoiceGroup on the page will still get focused.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/ehmplankje/pen/wvKaOyP

#### Actual behavior:
When a ChoiceGroup element is created with a tabIndex value of -1, it will get focused when the user navigates by tabbing.

#### Expected behavior:
When a ChoiceGroup element is created with a tabIndex value of -1, it will not get focused when the user navigates by tabbing.

### Documentation describing expected behavior
https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation-and-the-tabindex-attribute

**Comment by joschect** [comment]
@ehmPlankje Thanks for the submission! I suspect that this is working as intended. @ecraig12345 might be able to comment more. I think it's working as intended since placing a tabindex of -1 on a container of focusable elements will result in the focusable elements still being focusable. I modified your [codepen](https://codepen.io/slimemold/pen/ZEbbEKq?editors=0010) and I set the individual options to have a tabindex of -1 and things work the way you've commented. Additionally I have an example in there of a div that's not focusable with a button. You should see that the button still gets focus when you're tabbing through the options.
