### ISSUE TITLE
Using collapseAllVisibility=0 on a DetailsList causes DetailsList header and rows to render with incorrect width

### ISSUE THREAD

**Issue by ehmPlankje** [microsoft/fluentui#12663]
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ehmplankje/pen/qBOdvMO

#### Actual behavior:
When the property groupProps.collapseAllVisibility is set to CollapseAllVisibility.hidden on a DetailsList, then there will be a whitespace on the right of the rows and headers of the DetailsList. This becomes especially apparent when hovering over a row or the header.

#### Expected behavior:
When the property collapseAllVisibility is set to CollapseAllVisibility.hidden on a DetailsList, then the rows and headers of the detailslist should be rendered fully justified to the page, as if the toggle button was never intended in the header, and the forced indentation of the rows is removed.

Similarly, when the collapseAllVisibility property is set, the toggle button on the group headers should also disappear.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by joschect** [comment]
@ehmPlankje Thanks for submitting this issue! That's an interesting whitespace that's been added. I believe its' related to [this line](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L303) since it's the only one that seems to reference the hidden enum and it's related to the spacer length. We'll added this to the backlog.

**Comment by joschect** [comment]
The problem:

Header highlighted:

![image](https://user-images.githubusercontent.com/20801176/79170489-602ea680-7da4-11ea-893e-a892575ea943.png)

Row item selected:

![image](https://user-images.githubusercontent.com/20801176/79170508-6cb2ff00-7da4-11ea-9141-0818ca4e584f.png)
