### ISSUE TITLE
ActivityItems persona first items

### ISSUE THREAD

**Issue by PooLP** [microsoft/fluentui#12672]
### Environment Information

- **Package version(s)**: 7.106.0
- **Browser and OS versions**: Chrome / Win10

### Describe the issue:

Hi,
Activity component don't work correctly.
If pass an array to activityPersona parameters with first element of array do not have imageUrl or imageInitials, the personna zone don't appear.

see codepen : https://codepen.io/PooLP/pen/KKddMpy

Thanks

**Comment by joschect** [comment]
@PooLP Thanks for the submission! I can see the behavior that you're talking about and as far as I can tell it looks to be intentional based on [line 97](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/ActivityItem/ActivityItem.tsx#L97) but I'm not positive. @jdhuntington might be able to chime in more

**Comment by jdhuntington** [comment]
Hi @PooLP - @joschect is correct about the reason this is occurring. I don't believe the existing behavior needs to stay this way however, if you'd like to propose a pull request to modify it. Thanks!

**Comment by PooLP** [comment]
Hi, any news for this bug ? 
I'm sorry, i don't have expérience/level to make a this PR. sorry.
