### ISSUE TITLE
Disabled button doesn't show title

### ISSUE THREAD

**Issue by kamran-afsar** [microsoft/fluentui#12673]
### Environment Information

- **Package version(s)**: 0.47.0
- **Chrome on Windows 10

### Please provide a reproduction of the bug in a codepen:
Just hover on the diabled button and then hover on enabled button
Link to reproduce: https://ru0mq.csb.app/
#### Actual behavior:
Should be allowed to show title while button is disabled

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

**Comment by jurokapsiar** [comment]
By design, html `<button>` does not show `title` if it is disabled. There is a workaround to make Buttons show a Tooltip on hover, but this is not accessible (as disabled buttons do not accept focus): https://fluentsite.z22.web.core.windows.net/components/tooltip/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#usage-disabled-trigger

**Comment by kamran-afsar** [comment]
In previous versions where fluent ui was stardust ui it was possible to show title on hovering a button, I don't need the work arounds I have already wrapped buttons with divs where needed
