### ISSUE TITLE
Unable to use onRenderIcon for CommandBar oveflowItems

### ISSUE THREAD

**Issue by jacklovett** [microsoft/fluentui#12682]
### Environment Information

- **Package version(s)**: We are currently using office-ui-fabric-react: ^7.105.10 But also, see codepen example

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/jacklovett/pen/OJyyppE?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

onRenderIcon() is not working for CommandBar overflow items. Any desired custom content is not being added.

#### Expected behavior:

Expected to be able to add content using onRenderIcon(). Our actual desired scenario is that we are trying to use onRenderIcon() to add a Tooltip around the menuItem. However, as shown in the codepen, onRenderIcon doesn't render at all.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

**Comment by joschect** [comment]
@jacklovett Thanks for the submission! This is confusing because there is a slight difference in the way that command bar and the contextualmenu decide whether or not display an icon. Contextualmenu icons assume if you don't supply iconProps then the icon shouldn't be rendered at all, and that onRenderIcon should only be invoked if there is an icon to render. 

This isn't documented well but you can see it working in this [variation of your codepen](https://codepen.io/slimemold/pen/xxwZzLX?editors=0010) that I forked. 

I don't believe that we'll be able to change this check as doing so could break contextualMenuUsers that expect onRenderIcon to only be called when there is an icon. That said, it's possible that commandBar could automatically take care of this. We'll get it added to the backlog.
