### ISSUE TITLE
FocusTrapZone does not trap focus when narrator is on with scan mode

### ISSUE THREAD

**Issue by SainathBommisetty** [microsoft/fluentui#12737]
### Environment Information

- **Package version(s)**: current
- **Browser and OS versions**:  edge- latest, windows - latest

### Describe the issue:

While navigating in scan mode, the narrator focus moves out of the callout. Tested on the sample callout in the Office UI Fabric. 
(https://developer.microsoft.com/en-us/fluentui#/controls/web/callout)

### Please provide a reproduction of the issue in a codepen:

Turn on a focus trap zone.
Turn on narrator with scan mode on (caps lock + spacebar to toggle scan mode)
From inside a FocusTrapZoneCallout, use the up or down key to navigate

#### Actual behavior:

Focus is moving out of the callout while navigating in scan mode

#### Expected behavior:

Focus should not go out from the callout as we have focusTrapZone.

**Comment by joschect** [comment]
@SainathBommisetty Thanks for the submission! This is interesting behavior but I believe that it's working as intended. Per this other issue #6535, it looks like focus should not be trapped if the dialog is not modal. Most callouts are not modal, since they do not block user action elsewhere on the page.

You can add `role=dialog` and `aria-modal` to the callout as in [this codepen](https://codepen.io/slimemold/pen/qBONEJO) which is all that should be necessary for narrator to maintain focus. However it still does not trap focus, which means that this is likely an edge and narrator issue.
