### ISSUE TITLE
Please improve the quality of your package

### ISSUE THREAD

**Issue by ptallett** [microsoft/fluentui#12740]
Have to say out of the countless packages we've been using, this has to be the worst in terms of quality.

We've probably had a dozen or so build breaks where incomplete packages have been published, blocking all development on our project - waiting a couple of hours and it all starts working again.

Now the docs have gone AWOL.

Styling the components is excruciatingly difficult requiring you to pass some undocumented object to style the unknown components of the control. The only real way to figure it out is to read the source code.

Terrible. I'd have dumped this a while back if I could find something else as nice visually.

**Comment by dzearing** [comment]
Thanks for the feedback.

We do agree that styling needs improvement. While we had hoped `styles` props were the answer, they just aren't. We're working on base components that have no styling, so that you could provide your own. We're also moving to css variables, so that when you do want to override things, we can leverage the browser to provide value overrides rather than expensive css in js.

WRT the dozen or so build breaks due to publishing, this is definitely a major concern. We have a few tracking issues on our tooling to make this far more resilient, for example: https://github.com/microsoft/beachball/issues/321 is one that would have caught the recent fix.
