### ISSUE TITLE
I am unable to register and icon alias after an icon is mounted

### ISSUE THREAD

**Issue by jacksonv1lle** [microsoft/fluentui#12744]
### Environment Information

- **Package version(s)**: current

### Please provide a reproduction of the bug in a codepen:
[https://codepen.io/ijackson/pen/bGVpGow?editors=0010](https://codepen.io/ijackson/pen/bGVpGow?editors=0010)

#### Describe the issue

I am trying to implement a way to dynamically swap between the default Fabric/Fluent icons set and a set of custom SVG icons. For this to work I want to use the `registerIconAlias` function to apply the custom icons upon clicking a button.

In the pen above, I have set up a simple scenario. I want to replace the 'Delete' icon with the custom 'svg-circle'. This works when I place the `registerIconAlias` block before the class definition. But I would like for this to work dynamically.

#### Actual behavior:

Upon clicking the button, the 'Delete' icon remains the same

#### Expected behavior:

Upon clicking the button, the 'Delete' icon is expected to change to the circle shape having used the `registerIconAlias` function inside the click handler function.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by joschect** [comment]
@jacksonv1lle Thanks for the submission! This is an interesting case. The "Delete Icon" won't actually change, even if you render an entirely new icon. I modified your [codpen here](https://codepen.io/slimemold/pen/gOaMbqG?editors=0010) and you can see that behavior.

I'm fairly certain this is happening because of [this line](https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Icon/FontIcon.tsx#L14) in font icon. The function that retrieves the Icon content is memoized to help increase its overall speed. The problem that you're encountering is that the memoization doesn't know about the icons at large, it only knows about the string that's coming in so it will return same the value for the same string even if the global value may have changed.

So there is a workaround, you can call `resetMemoizations` but that should be handled carefully since it can heavily impact perf. Here's another modified version of your [codepen](https://codepen.io/slimemold/pen/XWmKJwr?editors=0010) with things working as you'd expect. You also will need to change something going to the icon, as force update only triggers children to go through their standard react life cycle, which means they won't update if they don't receive new props.

@ecraig12345  might have something else to add about this.

**Comment by jacksonv1lle** [comment]
Hi @joschect. Thanks for your reply. I see now how the icon references are memoized. I didn't know about the `resetMemoizations` function. This is very helpful. 

I have also noticed [this line](https://github.com/microsoft/fluentui/blob/76405da1c979fa0b7a54594b6727acd293a8f605/packages/office-ui-fabric-react/src/components/Icon/FontIcon.tsx#L36) in the `FontIcon` file stating that the FontIcon can't be targeted by customizations. Is there an Icon component which can be targeted by customizations?

**Comment by joschect** [comment]
@jacksonv1lle Sorry for my slow response. I believe that is only for the FastIcons, regular icons can be targeted by customizations. I believe in your codepen you're using the Icon component which is customizable. That's the tradeoff of using the FontIcon in isolation.
