### ISSUE TITLE
ContextualMenu: items are rendered incorrectly in RTL mode

### ISSUE THREAD

**Issue by kamil7x** [microsoft/fluentui#12756]
### Environment Information

- **Package version(s)**: "@fluentui/react": "7.106.2",

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/kamil7x/pen/VwvaXvV

#### Actual behavior:

When using RTL mode, contextual menu items in CommandBar (using `subMenuProps`) are still rendered left-to-right

#### Expected behavior:

Menu items should also be rendered in right-to-left mode

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by joschect** [comment]
@kamil7x Thanks for submitting this issue. This is happening because the contextualmenu is rendered at the end of the dom, after everything else. It's done that way to help ensure that it will always appear on top. The downside is that RTL set on an html element won't apply to it. Additionally, fabric primarily checks the document and body for rtl, it doesn't walk up the tree and check every individual element so there is other functionality that can be lost.

Recently there was a checkin so that theme can support RTL. This is probably the best way to work around this as it scopes theme to the elements contained within the customizer. You can see that working [here](https://codepen.io/slimemold/pen/gOaMpLz?editors=1010) in a codepen fork of your example.

**Comment by joschect** [comment]
Also here is the [pr that](https://github.com/microsoft/fluentui/pull/11560) was put in to enable this

**Comment by kamil7x** [comment]
@joschect Hi, thanks for response. I checked your codepen and it's not working for me:
![image](https://user-images.githubusercontent.com/7629808/79637347-19afc200-817f-11ea-8ab3-6644dcce19fb.png)

**Comment by joschect** [comment]
@kamil7x That was my mistake! I was working with two codepens [this one](https://codepen.io/slimemold/pen/XWmKbJW?editors=001) should work as expected!
