### ISSUE TITLE
Dropdown options render on the side

### ISSUE THREAD

**Issue by lrabinowicz** [microsoft/fluentui#12828]
### Environment Information

- **Package version(s)**: 7.102.2
- **Browser and OS versions**: Chrome, Windows 10

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/LuciaRabinowicz/pen/pojREyb?editors=1010

When there are more options than space below, the dropdown goes to the side instead of down

#### Actual behavior:

Dropdown goes to the side:
![image](https://user-images.githubusercontent.com/12565958/80037314-33ffdd80-84a8-11ea-8c87-d8af12edad31.png)
#### Expected behavior:

Dropdown goes down with a scroll bar on the side (in the image the scroll bar is missing becuse there is enough space):
![image](https://user-images.githubusercontent.com/12565958/80037713-fc456580-84a8-11ea-8d16-c22ad1f53ee4.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@lrabinowicz Thanks for the submission! The callout is doing this because there is no maxHeight provided, so it does it's best to fill the available space given. There are 2 options

You can provide either a maxHeight, which will allow the callout to flip and move to fit still, or you can provide `directionalHintFixed` which will force the callout to only appear below the dropdown. Here's a [codepen](https://codepen.io/slimemold/pen/JjYEEGK?editors=0010) with both examples

**Comment by lrabinowicz** [comment]
Thank you so much. I'll close this bug.
