### ISSUE TITLE
isLightDismiss property do not works when isBlocking is false

### ISSUE THREAD

**Issue by tatelang** [microsoft/fluentui#12842]
### Description
isLightDismiss property is not working when isBlocking is false

### Environment Information
**Package version(s)**: office-ui-fabric-react@7

###  Reproduction in Codepen
 https://codepen.io/ttelang/pen/rNOjomm

**Comment by joschect** [comment]
@tatelang Thanks for the submission! This is pretty interesting, it seems intentional because the onLightClick dismiss is only added when isBlocking is true. That being said this seems like confusing behavior. At the very least it needs to be documented better. @aneeshack4 or @micahgodbolt do you have any ideas?

**Comment by micahgodbolt** [comment]
two things: how can we best support the current panel without breaking partners. Might be that we just need to improve docs about how to enable certain scenarios.

second thing: how do we look at Fluent 8 and how the panel could be less confusing with so many possibly conflicting modes.
