### ISSUE TITLE
DatePicker: Entered invalid date should not be reverted to the previous one

### ISSUE THREAD

**Issue by mygalukr** [microsoft/fluentui#12882]
### Environment Information

- **Package version(s):** 7.28.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
**Actual behavior:**
I have datepicker with allowTextInput and formatDate specified.
Every time incorrect date is entered, the actual date in the picker is reverted to the previous one.
So it is not clear what is entered(whether format is wrong, or anything else).
Error message is displayed, but that is not enough.
![image](https://user-images.githubusercontent.com/2537065/80367729-e27e9680-888b-11ea-8db7-d04ced9abd47.png)

**Expected behavior:**
Entered invalid text should remain unchanged.
Or it would be nice to have an option in props for that.

Are you willing to submit a PR to fix? (Yes, No) **No**
Requested priority: (Blocking, High, Normal, Low) **High**

**Comment by aneeshack4** [comment]
@mygalukr Hi, I believe it's intentional for this component to enforce the proper format by not accepting the incorrect date and reverting previous. As it says on the documentation site, "The control renders date in a specific format. If allowing for manual entry of date, provide helper text in the appropriate format." You can provide this helper text in the label.

**Comment by mygalukr** [comment]
Hi @aneeshack4 
Thanks for reply.
I think the entire feature of allowing manual input does not make sense if inputted text is gone all the time.
