### ISSUE TITLE
Keyboard Focus order is incorrect while doing reverse navigation under due date in Calender Component.

### ISSUE THREAD

**Issue by Deena-the-coder** [microsoft/fluentui#12893]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Edge Chromium & Windows

### Describe the issue:
We are using Calender Component from 'office-ui-fabric-react/lib/Calendar'. When we navigate in a reverse order using shift+tab key from save button to calender component, keyboard focus is going to next month button instead of selected date button. Here is the bug https://alexanderplatz.visualstudio.com/To-Do/_workitems/edit/35388 for your reference.This also contains the video explaining the issue. We are also using the calender component in other place.It behaves properly there as we are having timepicker there. But here , we don't have timepicker and i guess that is disturbing the reverse focus order. Please let me know if you need further details.

### Please provide a reproduction of the issue in a codepen:

**Pre-requisite Steps: -**
Go to the link https://beta.to-do.microsoft.com/

**Repro Steps:** 
1.Navigate to any list which has task added already and activate it from the left pane.
2.Activate any task and select "Pick a date" under Due date
3.Navigate from the "Next month button" to "Save button"
4.Observe the focus order in reverse navigation from "Save button" to "Next month button"

**Expected Result:**
Focus order should remain the same in reverse navigation also.

**Actual Result:**
Focus order is incorrect in reverse navigation.

**While navigating from "Save button" it directly goes to "Next month button" and skips the selected date.**

**Comment by Deena-the-coder** [comment]
Any update on this? @aneeshack4

**Comment by joschect** [comment]
@Deena-the-coder Thanks for the submission! I can see the issue you're talking about. I was a little confused as to what you were talking about because I couldn't get an isolated repro. I made this [codepen here](https://codepen.io/slimemold/pen/yLYXxYw?editors=1010) and originally just loaded the calendar and everything worked as expected. That changed once I put the calendar into a contextualmenu. 

ContextualMenu, like detailsList, has a focusZone which helps to manage the focus internally. Int this case, the ContextualMenu's focusZone and the Calendar's FocusZone were interfering with one another. I was able to work around this by rendering a custom submenu which uses a Callout and since Callout doesn't use a FocusZone you can see this problem is resolved.

ContextualMenu is a little complicated and in this case I would recommend subbing out the default submenu for a simpler callout. You'll need to do a bunch of work to manage focus yourself but you'll have access to all the props that go to a submenu and callout should be able to handle most of them.

**Comment by Deena-the-coder** [comment]
@joschect Thank you for the confirmation.

### ContextualMenu, like detailsList, has a focusZone which helps to manage the focus internally. Int this case, the ContextualMenu's focusZone and the Calendar's FocusZone were interfering with one another. 
I see.So this is disturbing the focus order.We do use ContextualMenu and we push Calender as one of the items as u did in codepen.

### I was able to work around this by rendering a custom submenu which uses a Callout and since Callout doesn't use a FocusZone you can see this problem is resolved.
Yeah.I just saw tgat resolved the issue and the focus is going to date from previous button.

### ContextualMenu is a little complicated and in this case I would recommend subbing out the default submenu for a simpler callout. You'll need to do a bunch of work to manage focus yourself but you'll have access to all the props that go to a submenu and callout should be able to handle most of them.
We have a component called ContextMenu which is a wrapper component over FABRIC UI's ContextualMenu. https://outlookweb.visualstudio.com/Outlook%20Web/_git/to-do-web?path=%2Fpackages%2Ftodo-client%2Fsrc%2Fcommon-components%2FContextMenu%2FContextMenu.js . we have methods to handle the rendering of menu items there. This component is already used in multiple places and we cant sub out sub menu items as it may impact other. Can you please let me know if something else to fix this.

**Comment by joschect** [comment]
@Deena-the-coder This a tough case. I played around with the codepen to attempt to find a way to get around this but there isn't an easy solution. As I mentioned above this is happening because both the ContextualMenu and the Calendar have a focusZone. FocusZone has explicit logic to prevent navigation into an internal FocusZone unless explicitly told to do so. This has the unfortunate result that you're seeing now where the external FocusZone (the ContextualMenu's) is preventing focus from going into the Calendar. It's likely working with your time component because the time component

Fixing this isn't really obvious either, we could add a property to selectively disable the focus zone for either component. It's possible that the focus zone should have another way of dealing with this. 

Which time picker component are you using? I don't believe that Fabric currently has a time picker component.

**Comment by Deena-the-coder** [comment]
@joschect : Thank you so much for taking your time to analyze and explain the root cause of bug for us. We have also spent quite lot of time on this to locate where exactly its causing issue.

**Which time picker component are you using? I don't believe that Fabric currently has a time picker component.**
Yes. You are right. We have developed our own TimePicker component as Fabric doesn't have one. 
Please take a look at our time picker component. https://outlookweb.visualstudio.com/Outlook%20Web/_git/to-do-web?path=%2Fpackages%2Ftodo-client%2Fsrc%2Fviews%2Fdetails%2FTimePicker%2FTimePicker.js . We wrap this up with Fabric's Calender component here https://outlookweb.visualstudio.com/Outlook%20Web/_git/to-do-web?path=%2Fpackages%2Ftodo-client%2Fsrc%2Fcommon-components%2FCalendar%2FCalendar.tsx .

**Comment by joschect** [comment]
@Deena-the-coder It makes sense that the custom time picker you've built is working as expected since it doesn't contain a focusZone. The issue is the nested focus zones, one contained in the contextualMenu and one contained in the Calendar.

Currently your best option is my example with putting the submenu in a Calendar. We have this in our backlog and we'll see if we can't get a fix in. @lorejoh12 might have another way way to use calendar to enable this behavior, but based on a quick look at the code I don't believe that's the case.
