### ISSUE TITLE
TextField - Displaying error outline without a text message

### ISSUE THREAD

**Issue by boomgetchopped** [microsoft/fluentui#12961]
For required fields, we were wondering if we could just show the nice error outline that shows when error message is set.  But we don't necessarily have a text error message for these, and would want to prevent the height of the control from changing that comes with displaying error messsages underneath.  So basically, we want to display the error outline without showing an error message.

I know we can do this via css, but was wondering if there was something built in to get this behavior?

Thanks!

**Comment by aneeshack4** [comment]
@boomgetchopped I do see that if the errorMessage passed in an empty string or not passed in at all, the red outline doesn't show. It doesn't seem like there's anything built in and we currently don't have plans to add that ability, especially because we have over 10 different error message variations of TextField already (Show text fields toggle under the variations section) - I'd suggest just doing this with CSS.
