### ISSUE TITLE
CommandBar focus method not working

### ISSUE THREAD

**Issue by JosephThomas** [microsoft/fluentui#12964]
### Environment Information

- **Package version(s)**: 7.107.6
- **Browser and OS versions**: All

### Describe the issue:

CommandBar focus method not working

If I change the method to:
```
CommandBarBase.prototype.focus = function () {
        // var overflowSet = this._overflowSet.current;
        // overflowSet && overflowset.focus();
        this._overflowSet && this._overflowSet.focus();
};
```

in CommandBarBase.js, it works properly. It looks like its trying to be accessed like a RefObject<OverFlowSet> but componentRef just returns a OverFlowSet.

#### Actual behavior:

Does not focus on first item in CommandBar

#### Expected behavior:

focus on first item in CommandBar

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes
If my fix looks like the right way to go

Requested priority: (Normal)
Blocking accessibility features

Products/sites affected: MSX Portal

**Comment by ecraig12345** [comment]
I noticed that in your codepen's HTML section, it was loading `office-ui-fabric-react` version 6.189.2. When I change it to version 7, the problem goes away.
https://codepen.io/ecraig12345/pen/ZEbvzRY

I see your issue description mentions version 7.107.6--is that the version you're using locally, or are you using version 6 locally?

**Comment by JosephThomas** [comment]
I've update the example to use a class instead of a functional component.
If I step through the code it seems that commandBar loses the reference after a rerender.

I also noticed that I can't properly access the command bar ref unless I do componentRef={(ref) => ref && (this.commandBarReference = ref)} for commandBar, as it seems to be resetting the ref to null.

**Comment by ecraig12345** [comment]
Talked to @dzearing and he thinks this is because the way ResizeGroup works (it's used internally by CommandBar). 

When re-rendering, ResizeGroup first renders things off-screen so it can measure the size, then renders at the appropriate size on-screen. This means CommandBar's _onRenderData is called to render its OverflowSet (and passes along the component ref) multiple times. But the off-screen rendered copy may not be fully disposed before the real one is created, meaning **the component ref could be shared by multiple copies** and get corrupted when the off-screen copy is disposed.

The ideal (but probably not immediately feasible) way to fix this is to not render two copies of things: maybe use simpler measurement logic (without the off-screen measurement step) by default and have the complex logic be opt-in for the few things that need it. There's apparently been some discussion of making this change, but it's not something we could do outside a major version.

In the short term, we need to figure out if we can either:
- Somehow get rid of the extra measurement rendering: like just render on-screen and resize as needed (probably won't work since it seems likely to cause flashing)
- Prevent passing and/or resolving component refs through while measuring
- Ensure the disposal order is correct

@micahgodbolt Does this sound correct to you and do you know which approach would be the most feasible?

**Comment by micahgodbolt** [comment]
yeah, this is the case we found in the past. refs get messed up when measured. We have considered having 2 sets of props, one without refs (for measurement) then one with refs for rendering. Not sure if that was still feasible or not. Certainly a bit messier. We considered automatically stripping the refs for the measuring render, but anything more than a shallow check would get expensive.
