### ISSUE TITLE
Native props in TooltipHost are misleading

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#12971]
When assigning native props to TooltipHost I would expect that they would be placed on the root of the TooltipHost. This is not the case though. They are instead passed into the Tooltip itself. This seems redundant since ITooltipProps are already exposed within ITooltipHostProps. More intuitive behavior seems like it would be to spread the native props into the root of the component the props are applied to. If a consumer wants to apply native props to the Tooltip itself this is already possible.

### Environment Information

- **Package version(s)**: current

#### Actual behavior:

Native props passed into TooltipHost are applied to Tooltip

#### Expected behavior:
Native props passed into TooltipHost are applied to the root element within TooltipHost itself.

### Priorities and help requested:

Are you willing to submit a PR to fix? Sure!

Requested priority: Normal

Products/sites affected: M365 Admin Controls

**Comment by brandonthomas** [comment]
https://github.com/microsoft/fluentui/blob/34f1d9d40f8cdcecee7e7dca0e0284453f43ad7e/packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.base.tsx#L118

**Comment by ecraig12345** [comment]
Thanks for pointing this out! This is unfortunately something we can't change outside of a major version since it would be a major behavior change. The change would basically be:
- Switch native props to be passed to the TooltipHost itself
- In the migration tool (assuming we have one), detect cases where native props are being passed into a TooltipHost and warn that they should be moved to `tooltipProps` (this prop already exists) or move them automatically if feasible

@dzearing Do you think this is something we can/should change as part of version 8? Or wait until the converged Tooltip?

**Comment by JustSlone** [comment]
This is going to have to wait until we refresh/converge Tooltip (currently starting soon, but not for version 8).
