### ISSUE TITLE
Drag&Drop on DetailsList is stopped working on last versions of fluentui

### ISSUE THREAD

**Issue by gencer** [microsoft/fluentui#12988]
# Environment Information

- **Package version(s)**: 7.110.1
- **Browser and OS versions**: Chrome 81 & Edge 84 Canary

#### Actual behavior:

No drag and drop behavior. Just select and re-select. No DnD.

![5](https://user-images.githubusercontent.com/1711576/80988084-a626d980-8e3b-11ea-818c-9a73c2421828.gif)

#### Expected behavior:

When selected, i should be able to drag & drop selected items. Even fluentui demo has this issue. Older version has no this issue which is in our production server at the moment. Due to this bug i cannot push latest changes to prod server.

### Priorities and help requested:

Are you willing to submit a PR to fix? No (Not because I don't want. No because I'm not familiar with the environment at the moment)

Requested priority: Blocking
Products/sites affected: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/draganddrop#feedback

Even your demo has this issue.

**Comment by ecraig12345** [comment]
Thanks for noticing this! Looking through https://aka.ms/fabricdemo this last worked in [7.107.6](https://fabricweb.z5.web.core.windows.net/oufr/7.107.6/#/examples/detailslist/draganddrop) and stopped working in the next version [7.110.0](https://fabricweb.z5.web.core.windows.net/oufr/7.110.0/#/examples/detailslist/draganddrop) (108 and 109 were skipped due to publishing issues).

In that range, the most suspicious change is @khmakoto's PR #12484, so he's looking into it.

**Comment by ecraig12345** [comment]
Actually now we think the issue was from #12722
