### ISSUE TITLE
Disable Default Tooltip for Dropdown values

### ISSUE THREAD

**Issue by malvica** [microsoft/fluentui#13007]
Hello
When using Dropdown I see a default tooltip appearing for all the values along with my custom tooltip.
So, in order to get rid of that I have to use an empty string for the title for each dropdown element:
const options: IDropdownOption[] = [
{ key: 'apple', text: 'Apple', title:'' },

Is there a way to disable this built-in tooltip? I am using office-fabric-ui-react version ^7.98.3

Thanks

**Comment by ecraig12345** [comment]
By default we use the item text as the `title` in case the item is too wide and the text overflows, and passing an empty string (like you're already doing) is currently the recommended way to disable that behavior. 

It would be possible to add a prop to Dropdown to disable the text-as-title behavior, but we'd probably prefer not to do that to avoid unnecessarily increasing our API surface, since having custom tooltip logic isn't an especially common case and there's an existing way to handle disabling the tooltip.

**Comment by malvica** [comment]
@ecraig12345  Understood! Thanks a lot for your quick responses, really appreciate it!
