### ISSUE TITLE
Using UNSAFE_componentWillReceiveProp warning because of ImageBase component

### ISSUE THREAD

**Issue by Silidrone** [microsoft/fluentui#13021]
### Environment Information

- **Package version(s)**: (7.110.1)

### Describe the issue:

I am getting a warning about usage of a deprecated react function componentWillRecieveProp which is used in ImageBase component of FluentUI

#### Actual behavior:

Getting a warning "Using UNSAFE_componentWillReceiveProp, please update the following components: ImageBase"

#### Expected behavior:

Expected behavior is to not get the warning

**Comment by ecraig12345** [comment]
Thanks for filing this, but I'm not seeing this warning in the console with the current version of React and default options. Which version of React are you using, and are you rendering in strict mode or with other special options? (If you can make a CodePen repro which displays the warning, that would be ideal--start from https://aka.ms/fluentpen.)

Getting rid of the deprecated lifecycles has definitely been on our radar, but it hasn't been the highest priority because at least last we were aware, warnings about the lifecycles were only shown in strict mode. So far we've been prioritizing conversions to function components (to be released as part of version 8) rather than getting rid of deprecated lifecycles in-place in the current version. See https://github.com/microsoft/fluentui/issues/4613#issuecomment-622468304 for more info.

**Comment by Silidrone** [comment]
My react version is 16.13.1 
Indeed the error only occurs in StrictMode (https://codepen.io/silidrone/pen/ZEbrmrQ). I understand you are focusing on conversion to function components although I think it would nice to also get rid of deprecated lifecycle methods in the near future. In the meantime, I can ignore the warning, I just wanted to let you know about the warning, thanks for the help.

**Comment by ecraig12345** [comment]
Thanks for clarifying! In that case I'm going to close this since we already have an issue (#4613) to track these type of fixes all-up. And while I agree that it would be nice to get rid of the deprecated lifecycle methods sooner, in many cases that's non-trivial, so we've chosen to focus our resources on the bigger goal of function component conversions (since that will address the deprecated lifecycle issue and multiple other concerns).
