### ISSUE TITLE
Negative dates in Calendar cause rendering issues/crash

### ISSUE THREAD

**Issue by HarryGifford** [microsoft/fluentui#13027]
### Environment Information

- **Package version(s)**: `@fluentui/react@7.110.4`
- **Browser and OS versions**: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36`

#### Steps
1. Open codepen: <https://codepen.io/hegi/pen/xxwYdvO>.
2. A calendar should now appear. Click the up arrow, to go to the previous year.
3. You should now be in the year -1. Now click one of the months, e.g. Jan.

#### Actual behavior:

The calendar now shows a bunch of NaNs. Additionally, if you click one of them then the client will hang. Below is a screenshot demonstrating the issue.

![image](https://user-images.githubusercontent.com/21968002/81209874-ee521300-8f85-11ea-8d1b-b58f02eeadda.png)

#### Expected behavior:

There should be a default `minDate` set. I've not tested going to a large date in the future, but perhaps there should be a default `maxDate` too.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No.

Requested priority: (Blocking, High, Normal, Low) Low.

Products/sites affected: (if applicable) Dynamics 365.

**Comment by aneeshack4** [comment]
@HarryGifford Thanks for reaching out to us. Calendar docs page has the following guidance which extends to `minDate` and `maxDate` as well - negative dates aren't recommended for the date props. And `minDate` and `maxDate` are furthermore optional

> Set the default date to the current date unless a specific date is required for context (e.g. the date of the conference).

Having limits on them would be a nice to have but it's not high priority for us right now.  @lorejoh12 if you think this is high pri, please feel free to suggest a fix/raise a PR - I'm going to reassign this to you so that the Calendar team can assess and track this.
