### ISSUE TITLE
Random publish failure in ADO pipeline due to office-ui-fabric-react.

### ISSUE THREAD

**Issue by huiren-jiang** [microsoft/fluentui#13038]
### Environment Information

- **Package version(s)**: 7.88.1
- **Browser and OS versions**: N/A

#### Actual behavior:
In ADO pipeline, the publish step will fail randomly (about 20%) due to below errors:
```
  ./node_modules/office-ui-fabric-react/lib/components/Modal/Modal.base.js
EXEC : Attempted import error : 'allowOverscrollOnElement' is not exported from '../../Utilities'.
```
#### Expected behavior:

The publish step should pass successfully.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: CICD pipelines of ADO

**Comment by ecraig12345** [comment]
This type of error shouldn't be intermittent--something is either exported from a particular package version, or it's not. In this case `allowOverscrollOnElement` is definitely exported from `@uifabric/utilities` (and therefore also `office-ui-fabric-react/lib/Utilities`) in the latest version.

So this appears to be a problem with your setup somehow, not with OUFR. My best guess would be that you're getting this error due to having multiple versions of `@uifabric/utilities` referenced in your repo, and maybe your package manager is somehow inconsistent about which version it's referencing when.

**Comment by aneeshack4** [comment]
Going to close this as this isn't an issue in Fluent.
