### ISSUE TITLE
StackedBarChart NumberDisplay display is inconsistent if optional chartTitle is not provided

### ISSUE THREAD

**Issue by beeisabelm** [microsoft/fluentui#13052]
When using StackedBarChart without providing the chartTitle, the number display on top of the bars will show up aligned left instead of staying on the right causing the UX view inconsistency when displayed with multiple charts used on the page.

# Environment Information

- **Package version(s)**: charting v. 2.0.0
- **Browser and OS versions**: Chrome, Windows 10

#### Actual behavior:

StackedBarChart numberDisplay aligns left on top of the chart bar where the chart title was

#### Expected behavior:

StackedBarChart numberDisplay remains right-aligned on top of the chart bar regardless of the use of the optional chart title

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: admin center

**Comment by aneeshack4** [comment]
@beeisabelm Please provide detailed repro steps on a codepen so that this is actionable for us. Also assigning charting package owner @Raghurk as his team made this component. Raghu, if think this is a high pri issue, please suggest a fix/raise a PR. If it is not high pri or behaving as intended or not aligned with your plans for this component, please feel free to close.

**Comment by beeisabelm** [comment]
@Raghurk , let's chat offline as Brandon and I found this minor bug.
