### ISSUE TITLE
Please fix "multiple modules with names that only differ in casing" warnings.

### ISSUE THREAD

**Issue by sarahkang58** [microsoft/fluentui#13056]
#### Describe the feature that you would like added

My project is using the FluentUI package, but these warnings (refer to screenshot below) show up when I run my project locally, and there are a lot of them.

How to fix: please double check that you are using the exact casing in your imports.
For reference: https://stackoverflow.com/questions/47534267/webpack-there-are-multiple-modules-with-names-that-only-differ-in-casing-but

This also may help.  Add in this compile option flag:
`forceConsistentCasingInFileNames`

So that it helps you fix the current warnings and prevent these warnings from occurring in the future.
For reference: https://github.com/Microsoft/TypeScript/issues/14460

#### What component or utility would this be added to

Your tsc compile script.

#### Have you discussed this feature with our team, and if so, who

Nope.

#### Additional context/screenshots

Here's an example of one of the warnings:
![Casing Error](https://user-images.githubusercontent.com/64438850/81342272-d0f57580-9067-11ea-9a2b-59d3cbeb6f46.PNG)

**Comment by ecraig12345** [comment]
Thanks for filing an issue, but we already use `forceConsistentCasingInFileNames` when compiling our packages, so the problem here is probably an import somewhere within your code. Based on the error message you might try doing a case-sensitive search in your project for `office-ui-fabric-react/lib/Components` to find the incorrect import.
