### ISSUE TITLE
How to show the overflowing element menu with the custom overflow button(created with overflowButtonAs)

### ISSUE THREAD

**Issue by fdevGit** [microsoft/fluentui#13062]
<CommandBar
                className={"XRibbonBar"}
                items={this.modifyItems()}
                children={children}
                farItems={farItems}
               overflowButtonAs={() => { return <Button >x</Button> }}
                overflowButtonProps={overflowButtonProps}
                overflowItems={overflowItems}
            />

The button is added as an overflow button as expected. The menu does not open when clicked. How can I open this menu

**Comment by fdevGit** [comment]
sample code is [here](https://codepen.io/founderdev/pen/mdexmQW?editors=0010)

**Comment by aneeshack4** [comment]
@fdevGit Thanks for filing this but please do not blank our issue template - you must fill it out so that it is actionable to us. For tech help questions such as this that are not issues, please use Stack Overflow not Github as this is to report issues. I'm going to close this as it sounds like a question, not an issue.
