### ISSUE TITLE
DetailsList - cells white-space style

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#13091]
The cells of the details list component are applying a `white-space: nowrap` style rule.
This is affecting the content actually displayed: if the string contains a series of whitespace characters they will be stripped out, causing the displayed value to be different from the original value.

### Environment Information

- **Package version(s)**: ^7.x.x

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/jlrv7y4py

if you look at the codesandbox you will see the first row with the standard style (where whitespace characters are removed) and the last one with the ` white-space`  that doesn't strip out the spaces (the cell value is the same for both rows)

#### Actual behavior:

The applied style removes all the characters chars in a string

#### Expected behavior:

String content shouldn't be modified by the style

### Priorities and help requested:

Are you willing to submit a PR to fix? no

Requested priority: High

**Comment by ecraig12345** [comment]
Thanks for reporting this, but I don't think we can change the default white-space setting due to risk of causing regressions or unexpected behavior changes in other apps which use DetailsList (where this may be the desired behavior, or at least is the expected behavior because it's been this way for so long). 

However, there are a couple workarounds you could use in addition to the one in your codesandbox:
- If only certain columns will have content with extra spaces, you can set `IColumn.className` to a class with `white-space: pre` applied.
- If you want this style on all columns, you can use `IDetailsListProps.onRenderRow` to set custom cell styles. (There's unfortunately not a more direct way to pass in cell styles.)

This codesandbox demonstrates both approaches: https://codesandbox.io/s/detailslist-white-space-rrxfr

**Comment by fildahui** [comment]
hi @ecraig12345 thanks for your reply.
yeah I already knew I could style the cells using a number of options, the thing that concerned me was that anyway it felt a bit wrong to have a displayed value that's different compared to the original one. I understand the potential regression failures and yes it's not a big deal to solve this by myself.
thanks anyway
