### ISSUE TITLE
Grid Layout Styles are Breaking since last 24 hours

### ISSUE THREAD

**Issue by srujalsk** [microsoft/fluentui#13112]
### Environment Information

- **Package version(s)**: 7.111.1
- **Browser and OS versions**: Chrome, Windows 10

### Priorities and help requested: 

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable) Yes

**Comment by amanRAT** [comment]
![Icon not rendering](https://user-images.githubusercontent.com/46020577/81686815-57e68b80-9476-11ea-879b-bdc3009528cc.png)

There is an issue in rendering icons as well.

**Comment by chelobone** [comment]
We have the same problem in our project. Grid Layoyt stopped working yesterday.

The grid looks like this

![Sin título](https://user-images.githubusercontent.com/46089516/81702004-bc82f580-9438-11ea-81ad-9bcac04c73bb.png)

And since yesterday, it looks like this

![Anotación 2020-05-12 100556](https://user-images.githubusercontent.com/46089516/81701620-48e0e880-9438-11ea-847c-4e106a2290ec.png)

**Comment by aneeshack4** [comment]
@srujalsk The Grid utility hasn't had any changes in [two months](https://github.com/microsoft/fluentui/commits/master/packages/office-ui-fabric-react/src/utilities/grid) and even those were mass prettier/basecomponent/tslint deprecation changes. The most relevant change was made in January but that was about [onBlur](https://github.com/microsoft/fluentui/commit/8e8e50ed2f3f4cfc3d5a113dc9fc8b258d38951a#diff-5787a4a658d86fed4f452407fbc67203), not styles so I don't think this is a regression - there's most likely something on your end that you've updated.

I suggest using Stack in place of Grid. You can achieve what you're trying to do in your Codepen more easily if you just wrap in a Stack and set the direction to vertical. https://developer.microsoft.com/en-us/fluentui#/controls/web/stack

We're currently focused on larger work items in performance improvements and coherence so we'll likely not get to address this Grid issue in the near future, especially since there's a workaround and it's not a regression so I'm going to mark this as won't fix.

**Comment by srujalsk** [comment]
@aneeshack4 The codepen example was provided just for demo of non-working grid layout.

Stack control cannot be used for all use-cases, it cannot provide mobile responsive layout to my web application.

Please find below link showing the use case of Grid Layout in Office Fabric UI

https://developer.microsoft.com/en-us/fluentui#/styles/web/layout

We have been working with office fabric UI since really long time and we haven't faced any issue.

It was just since yesterday we have started facing broken grid layout issue in both version of office fabric UI i.e. 6.189.2 & 7.111.1

I doubt there is some serious issue with CDN's response, post yesterday's deployment. (which has caused this issue)

Requesting you to please help in fixing this issue.

**Comment by ecraig12345** [comment]
The `ms-Grid` classes come from Fabric Core, not the Grid utility component (that was built basically for a single specific purpose which is different from the ms-Grid responsive classes).  The Fabric Core styles may have implicitly been included in Fabric React in the past, but that must have changed recently. @dzearing is it possible that your changes to scss processing caused this?

In the meantime, you can work around this by manually adding a reference to the Fabric Core stylesheet in your app.
```html
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"/>
```

**Comment by ecraig12345** [comment]
Actually I talked with @dzearing and he says we've never bundled Fabric Core with OUFR. (If you change to an older OUFR version in the codepen, it still doesn't work.) So it probably means something in your environment has changed.

I see from @chelobone's screenshot that you're working within SharePoint. @srujalsk and @amanRAT is that the case for you as well? If so, it's likely that SharePoint changed something such that the classes are no longer loaded on the page by default.

**Comment by dzearing** [comment]
I'm not sure how that codepen ever worked. fabric core classnames like `ms-Grid` are only defined when you import the fabric core css stylesheet.

See documentation here:
https://developer.microsoft.com/en-us/fluentui#/get-started#fabric-core

When you add the link, it works as expected:
https://codepen.io/dzearing/pen/BaoPjoV

Can you see if you're importing the stylesheet correctly? And if so, check if the url is resolving? Perhaps a CDN outage happened.

**Comment by dzearing** [comment]
@chelobone Same thing as mentioned above; how is the fabric core stylesheet loading in your app? Is there a url that's no longer resolving, or, are you importing it through sass?

**Comment by ecraig12345** [comment]
Talked with @KevinTCoughlin who works on SPFx, and apparently the *availability* of the Fabric Core classes globally was actually a regression which was recently fixed by removing them again. Here's an excerpt from an email explaining the change, as well as links explaining how to load the styles yourself:

> Starting with SPFx 1.8.0, we deprecated the default loading of legacy Fabric CSS styles. Customers could still opt into the load by changing their solution manifest to specify they still want the CSS loaded.
> 
> However, around November we rolled out a regression to this behavior and started always loading the legacy Fabric CSS styles again. We are checking in a fix which [apparently rolled out yesterday]. 
> 
> If a developer has an SPFx component developed with 1.8.0 or greater during this time frame, they may have unintentionally been dependent on the legacy Fabric CSS styles being loaded. Either the [1.8.0 release notes](https://github.com/SharePoint/sp-dev-docs/wiki/SharePoint-Framework-v1.8-release-notes#deprecating-legacy-fabric-css-consumption) or the [follow up documentation](https://github.com/SharePoint/sp-dev-docs/wiki/Safely-using-legacy-Fabric-Styles) should enable customers to fix themselves.

**Comment by chelobone** [comment]
@dzearing  @ecraig12345 Thanks to the both of you for your help! That was the problem. After importing de Stylesheet (it was not necessary before) it works perfectly!

**Comment by nsksaisaravana** [comment]
I have imported the stylesheet and it is working fine in the development environment but failing in the production environment. Please check the screenshot below. ms-hiddenXxlUp and ms-hiddenXlDown are not working in the production environment.

Mobile view and large screen css are not working.

```
<div class="ms-Grid-col ms-sm12 ms-hiddenXxlUp">Visible on smaller screens</div>
<div class="ms-Grid-col ms-sm12 ms-hiddenXlDown">Visible on larger screens</div>
```


![image](https://user-images.githubusercontent.com/17681573/82019942-74c7cc80-96cb-11ea-8f99-ea1bcc96c582.png)

**Comment by ecraig12345** [comment]
This is still an SPFx issue, not a Fabric/Fluent UI issue. You'll need to ask for help in some SPFx support forum or Stack Overflow, not here.

**Comment by srujalsk** [comment]
Thank You @ecraig12345 @chelobone @KevinTCoughlin Foy your help, I was able to fix this issue & deploy it to the production.

**Thank You Once Again**

**Comment by srujalsk** [comment]
@nsksaisaravana I did faced this issue, but solved it by upgrading my SPFx webpart version to 1.10 & including following import in root webpart component

`import '../../../node_modules/office-ui-fabric-core/dist/css/fabric.min.css'`

**Comment by chelobone** [comment]
@nsksaisaravana hi! in the render section, add this

> {SPComponentLoader.loadCss('https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css')}

You  have to import this

> import { SPComponentLoader } from '@microsoft/sp-loader';

I hope this helps!

**Comment by nsksaisaravana** [comment]
@srujalsk @chelobone tons of thanks and it works like charm.

**Comment by pcostarg** [comment]
@ecraig12345 it might be it that the core styles were never bundled but then we have wrong documentation and with the bug, people built broken stuff, including from Microsoft own teams that did the documentation.
![image](https://user-images.githubusercontent.com/7914780/84625710-bd95bf80-aedb-11ea-8ae1-644e928f062e.png)

**Comment by ecraig12345** [comment]
@pcostarg Good catch--I'd recommend filing an issue at [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs) about that assuming it's still live. They're the ones who maintain that documentation.
