### ISSUE TITLE
DatePicker onFocus event issue

### ISSUE THREAD

**Issue by llynxs** [microsoft/fluentui#13135]
### Describe the issue:
The error message does not disappear when input is being focused second time.
These attributes should be added to DatePicker:
```
disableAutoFocus={true}
isRequired={true}
```

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:
When input was unfocused and no data in there the error message appears under the input it disappers only if user enter some value or clicks to the date picker icon.

#### Expected behavior:
If no data and error message is present, when user clicks input and it becomes focused - error mesage should be hidden and to be appeard only if no data entered.

**Comment by aneeshack4** [comment]
@llynxs Thanks for reaching out to us. The codepen link you provided leads to an untitled pen - please provide one that has a repro of this behavior. This sounds like a feature request to add those attributes. @lorejoh12 do you and the calendar team think this is in the scope of the component? Or is there a workaround to achieve the same expected behavior with the existing functionality?

**Comment by lorejoh12** [comment]
The current behavior, continuing to show the error message until the issue is actually resolved, is intentional. Just focusing into the component shows intent to fix it, but I think it's more a design preference than an actual bug that the error remains visible until actual data is entered.

I also think you could probably work around this issue by forcing the component to rerender by changing the key when focusing in if you wanted the error message to go away, although I haven't tried it.

**Comment by llynxs** [comment]
@aneeshack4 sorry for the long response, I had to create normal codepen.
https://codepen.io/_ololo_/pen/oNbjRgR - follow this link you can check the behavior I've mentioned in my first commentary.
