### ISSUE TITLE
After pressing "shift + tab" while being on a Callout, focus doesn't go back to the control on which Callout is shown

### ISSUE THREAD

**Issue by SarveshNamjoshi** [microsoft/fluentui#13148]
**Environment Information**
         Package version(s): current

**Repro-steps**
  1. Visit the Office UI Fabric Home site (Callout): https://developer.microsoft.com/en-us/fluentui#/controls/web/callout
  2. Use keyboard "tab" button and navigate till **Show Callout** and press keyboard "enter" button to open the Callout. Observe that the focus is on the "Go to microsoft" link inside the Callout. 
  3. Use keyboard "shift + tab" button and observe the focus.
	  
**Actual behavior:**
On keyboard "shift + tab", focus comes to the last element i.e. "About our ads" link on the page.

**Expected behavior:**
On keyboard "shift + tab", focus should go to **Show Callout** button on which the Callout was opened.

**Priorities and help requested:**
Requested priority: High

**Comment by aneeshack4** [comment]
@SarveshNamjoshi Thanks for reaching out and reporting this. I see this behavior repro - I also see that the remaining callout examples show the callout on the default instead of on their own buttons... I see that there was a recent change to the Callout examples PR #13053 wonder if this is a regression... @joschect what do you think?
