### ISSUE TITLE
Fluent UI React Icons sometimes render as default square icon

### ISSUE THREAD

**Issue by The-ARMR** [microsoft/fluentui#13157]
Hi,
I have created a spfx webpart using react for sharepoint online and have used the fluent ui icons in it, now the issue i face is that sometimes the icon is not shown properly and instead of the required icon a square icon renders at its place, 
i have also found that this happens at the beginning of the icon rendering i.e when the page is loading the icon starts with square icon and changes when the page is loaded and shows the final icon which we want.
An explanation and solution will be really helpful

**Comment by ruslan-s** [comment]
We observe almost same behavior with Core version. Instead of icons we have anywhere squares. Only in case that any SP Default webparts use same icon as our custom webparts, issue does not exists. 
It seems to be, that FabricMDL2Icons is now scoped to the only 'needed' Icons and contains not a full icon set.

**Comment by aneeshack4** [comment]
@The-ARMR @ruslan-s Thanks for reaching out to us. Are you using the icons from here? https://uifabricicons.azurewebsites.net/ Because those are rendering fine in the site... could you provide more details as to how you're pulling them with a codepen?

**Comment by ecraig12345** [comment]
The squares mean that the icon font isn't loaded, or is loading with a bit of a delay (could happen if network is slow, which is not something we can fix for you). 

If icons aren't loading at all, typically that means you're missing a call to `initializeIcons()`. However, I'm not sure if that guidance applies in SPFx (not familiar with that environment).

If icons were previously working in your SPFx app but now aren't, it may be related to https://github.com/microsoft/fluentui/issues/13112#issuecomment-627632927 which actually is related to a change on the SPFx side, not in our code.

I'm going to close this as external because all of the issues described appear to be specific to the SPFx environment, which is not something we directly support here.

**Comment by The-ARMR** [comment]
@aneeshack4 I make use of icons in my project as explained in this url
[https://developer.microsoft.com/en-us/fluentui#/styles/web/icons](url)
but i was not making use of `initializeIcons();`  as @ecraig12345 has replied i will try that.
Thank you everyone for the reply.

**Comment by Alex1100** [comment]
I am also seeing this error and I am not using SPFx. My app is an internal Microsoft App and we had always had the initializeIcons called at the root of our application. For some reason, the MessageBar component won't render the icon when I pass in the iconName property.

<img width="912" alt="Screen Shot 2020-06-07 at 10 12 06 AM" src="https://user-images.githubusercontent.com/14917749/83975200-72f6c080-a8a7-11ea-9a94-b0ee2b4de2c5.png">


```ts
<MessageBar
  onDismiss={actions?.onDismiss}
  dismissButtonAriaLabel="Close"
  messageBarIconProps={{
    iconName: iconName || 'Error',
  }}
  styles={actions?.styles}
  actions={actions?.elements}
>
  {bannerText}
</MessageBar>
```

**Comment by ecraig12345** [comment]
@Alex1100 Can you please either open a separate issue or post in Fluent UI Community - Fluent UI React on Teams?
