### ISSUE TITLE
TeachingBubble callout not resetting focus with multi-step

### ISSUE THREAD

**Issue by kejatura** [microsoft/fluentui#13169]
### Environment Information

- **Package version(s)**: 7.98.0
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:

Code pen: https://codepen.io/kejatura/pen/bGVxrqK?editors=0010

1. Click 'Step 1' button to see teaching bubble.
2. Click 'Next', continue to the end.

Gif example: 

![teachingbubble-focus-not-reset](https://user-images.githubusercontent.com/58444231/81988692-bb94c400-95f0-11ea-819e-d3f92a70d4bd.gif)

1st pass is using mouse click event, the second pass is using keyboard to navigate.

#### Actual behavior:

Notice the callout behavior always sets focus to the last 'clicked' button in the content area, even when the `setInitialFocus` prop is set to false. 

#### Expected behavior:

Focus should be reset upon re-render when setting `setInitialFocus` to false (?). 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for reporting this and for the repro info, but I'm still a little confused, sorry. In your example, which button do you think ought to be focused at each step?

**Comment by kejatura** [comment]
@ecraig12345 - None should be focused on each step. 

The 'Next' button in my example is highlighted with a blue overlay at every step, when I thought it should be at a rest state (non-focused) if the callout's `setInitialFocus` prop is false.

**Comment by ecraig12345** [comment]
Thanks, that helps! Looks like you can fully disable initial focus by also passing `focusTrapZoneProps={{ disableFirstFocus: true }}` to the TeachingBubble ([codepen](https://codepen.io/ecraig12345/pen/oNjavYo?editors=0010)). 

Since there's a way to do what you want with existing props, I'd rather leave the default behavior here as-is.

**Comment by kejatura** [comment]
Thanks for investigating, I took a look at your codepen, it doesn't look like the `focusTrapZoneProps={{ disableFirstFocus: true }}` is disabling focus. I still see the blue overlay on each step in the teaching bubble.

![teachingbubble-focus-not-reset-still](https://user-images.githubusercontent.com/58444231/82244547-411cba80-98f6-11ea-88ad-a25bdf374eca.gif)

**Comment by ecraig12345** [comment]
With the codepen I'm no longer seeing the focus overlay on open, only when I tab in. At least to me it also looks like that's what your new GIF is showing. So I'm not quite understanding what behavior you want.

If what you want is to entirely disable focusing on buttons within the teaching bubble (even by tabbing in), I wouldn't recommend that because it makes the experience completely inaccessible for keyboard-only users, and we're not going to do work in our components to support that.

**Comment by kejatura** [comment]
@ecraig12345 Sorry for the delay. 

My intention is not to disable focus on buttons entirely, but only on render for the callout _until_ user tabs in, or hovers over. I agree that disabling focus would would cause accessibility issues for keyboard-only users, and we are working towards full accessibility for our product. What I was hoping, is to be able to set the button to not be focused after clicking the 'Next' button. Only after clicking 'tab' key (or hover), will enable the focus state for the 'Next' button. 

So the experience for each step would be something like:  

enable callout ->
initial 'rest' state (no overlay) -> tab-in -> enable focus overlay -> click 'Next' button->
'rest' state (no overlay) -> tab-in -> enable focus overlay -> click 'Next' button ->
'rest' state (no overlay) -> tab-in -> enable focus overlay -> click 'Done' button ->
exit callout

Hope this makes more sense.

**Comment by ecraig12345** [comment]
Ah I see what you mean now. The easiest way to achieve this would be by setting `key` on the TeachingBubble to `this.state.current` so that it will be re-created on each step--I've updated my codepen to show this. There's a slight behavior change in that it now displays the callout open/close animations on every step, but it does what you want with focus.
