### ISSUE TITLE
How can I use tab navigation to go from one pivot to another?

### ISSUE THREAD

**Issue by reutann** [microsoft/fluentui#13170]
In all of the example codepens, the `tabindex` attribute is -1 for the non-selected tab. Naturally, when someone clicks on one tab, its tabindex becomes 0 and all others become -1 but how would someone limited to tab navigation be able to access another tab with this being the case? 

Asking because I'm trying to solve a recent accessibility issue that was opened up against me.

**Comment by ecraig12345** [comment]
Once you tab into the pivot, you can use the arrow keys to select the other pivot items.

In the future, please don't blank our issue template, and please use Stack Overflow not GitHub for tech help questions (GitHub is for reporting bugs and feature requests). I'm going to close this now since it's a question, not an issue.
