### ISSUE TITLE
ContextualMenu disabled items do not show as green in highcontrast mode

### ISSUE THREAD

**Issue by nickdurak** [microsoft/fluentui#13188]
![contextual menu disable high contrast](https://user-images.githubusercontent.com/2531806/82096045-214a8400-96b5-11ea-9988-ef53b75681cb.PNG)

### Environment Information

- **Package version(s)**: 7.x
- **Browser and OS versions**: Edge, Windows 10
### Describe the issue:
When turning on high contrast mode in windows 10, it is expected that disabled buttons and menu items appear using the windows high contrast "Disabled Text" color (typically green). However, ContextualMenuItems which have disabled set to true are not rendered in this color. The root cause seems to be around the logic in Frabric which explicitly deletes the "disabled" property from the button props prior to rendering menu item. This seems to be leading to windows detecting the button as enabled and thus not using "Disabled Text" color.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/nickdurak/pen/zYvmGZN?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

Just need to render at least one contextual menu item with disabled set to true, and windows high contrast mode enabled.

#### Actual behavior:
disabled menu item text appears as white when the associated menu item is marked with property disabled true when in high contrast mode.

#### Expected behavior:
Disabled menu item text should appear as the "Disabled Text" color when in high contrast mode

**Comment by ecraig12345** [comment]
Thanks for reporting this, and I see what you're talking about from the default example at https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu. (FYI the codepen link you included is just to a blank template--you have to click save to create a persistent URL.)

I also confirmed this works fine in IE/old Edge, but not in Edge Chromium, which means it's caused by high contrast issues specific to the new Edge Chromium. @xugao is tracking these fixes under #11742. There's also #13012 with the status of different components.
