### ISSUE TITLE
DatePicker styling issues using IDatePickerStyles interface

### ISSUE THREAD

**Issue by kevinvangelder** [microsoft/fluentui#13192]
Related: https://github.com/microsoft/fluentui/issues/10312

### Environment Information

- **Package version(s)**: 7.110.1
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/kevinvangelder/pen/vYNVNjY

#### Actual behavior:

Styles for `textField` are applied to the label and some styles are not applied at all, such as `fontSize`, even to the incorrect element. `label` and `subCompnonentStyles.label` styles are not applied anywhere.

#### Expected behavior:

Styles for `textField` should be applied to the text input. `label` styles should be applied to the label, though the documentation appears to indicate that styling the label is not supported via IDatePickerStyles interface, only via IDatePickerStyleProps interface, so maybe this should be a separate issue?

Additionally, the `<div aria-haspopup=true>` portion of the DOM appears to not support styling through either styling interface, which prevents me from `flex-grow`ing my field to be the full width of it's parent.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Learn Student Ambassador site

**Comment by aneeshack4** [comment]
@kevinvangelder This looks like a TextField issue not a DatePicker right... since you filed #13195 we can track this there right?

**Comment by kevinvangelder** [comment]
Oh, yeah, my bad. I wasn't paying enough attention to realize it inherits.

**Comment by ecraig12345** [comment]
I think this is worth investigating separately--probably a slightly different underlying issue since DatePicker applies styles/props differently.

**Comment by ecraig12345** [comment]
Finally looking back at this, sorry.

The props `IDatePickerStyles.label` and `IDatePickerStyles.subComponentStyles` don't exist, so that's why they don't do anything.

`IDatePickerStyles.textField` is applied to the root of the TextField, which contains both the label and the field itself.

There are two possible approaches for styling the label and field. (demo of both:  
https://codesandbox.io/s/13192-datepicker-styles-05f9i?file=/src/index.tsx)

One approach is to use selectors on `IDatePickerProps.styles.textField` to target the input and label.
```tsx
const datePickerStyles: Partial<IDatePickerStyles> = {
  textField: {
    selectors: {
      input: { backgroundColor: 'red' },
      label: { backgroundColor: 'lightblue', fontSize: 30 }
    }
  }
};
// later
<DatePicker styles={datePickerStyles} ... />
```

The other (and probably preferred) approach is to use `IDatePickerProps.textField.styles`.
```tsx
const labelStyles: Partial<ILabelStyles> = { // this allows full typing support for the label props
  root: { backgroundColor: 'lightblue', fontSize: 30 }
};
const textFieldProps: ITextFieldProps = {
  styles: {
    field: { backgroundColor: 'red' },
    subComponentStyles: { label: labelStyles }
  }
};
// later
<DatePicker textField={textFieldProps} ... />;
```
