### ISSUE TITLE
Theme Designer is classified as suspicious site by Microsoft Edge

### ISSUE THREAD

**Issue by lafe** [microsoft/fluentui#13229]
### Environment Information

- **Package version(s)**: n/a
- **Browser and OS versions**: Windows 10, Microsoft Edge (Chromium, version 84.0.508.0)

### Please provide a reproduction of the bug in a codepen:

n/a

#### Actual behavior:

Opening the [Theme Designer](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/index.html) through the [official Fluent UI page](https://developer.microsoft.com/en-us/fluentui?fabricVer=5?fabricVer=5#/styles/web/colors/theme-slots) opens a warning panel that states that the site is suspicious.

![image](https://user-images.githubusercontent.com/4070008/82323692-b82a7f80-99d8-11ea-8aed-68ff19387acf.png)

#### Expected behavior:

Theme designer opens without any warning.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: n/a

**Comment by aneeshack4** [comment]
Hi @lafe Thanks for reporting this to us! I see it repro on Edge Chromium + Windows but not Edge Chromium + Mac... 
![image](https://user-images.githubusercontent.com/4161791/82347583-73451f80-99bd-11ea-82ee-36345b023e21.png)

**Comment by ecraig12345** [comment]
There's nothing wrong with the site, but it's repeatedly been incorrectly flagged as malicious--in the past by Google screening and now apparently by Microsoft SmartScreen (since this only happens in Edge Chromium). 

We'll work on getting the warning cleared and potentially also moving Theming Designer to a different domain which is less prone to getting flagged incorrectly.

**Comment by ecraig12345** [comment]
Closing since this is resolved for now. If anyone sees it come up again, please file a new issue.
