### ISSUE TITLE
CommandBar collapses even when it has enough space

### ISSUE THREAD

**Issue by obvioussean** [microsoft/fluentui#13238]
I'm using a CommandBar inside of a Stack, with the intention of having some text on the left, and the CommandBar to the right.  On first render, it works great.  But if the items on the CommandBar change and are bigger than what is initially rendered, it collapses instead.  I wouldn't expect it to collapse since there is plenty of space.

Codepen:
https://codepen.io/sferg/pen/WNQLpGp

I've seen #8897 and have used the `onReduceData={() => undefined}` workaround, but ideally I shouldn't have to do this.

**Comment by aneeshack4** [comment]
@obvioussean Thanks for reaching out to us and providing a codepen! I don't see anything besides the Text even on first render... is there something missing from the codepen or more repro steps?
![image](https://user-images.githubusercontent.com/4161791/82465387-d51c8c80-9a84-11ea-85ea-a3e2714dff3a.png)

**Comment by obvioussean** [comment]
@aneeshack4 What browser did you run the codepen in?  I'm sorry I didn't specify, but for me it repros in Chrome, Edge Chromium and Firefox. 

![image](https://user-images.githubusercontent.com/15038374/82477879-e82f5c80-9a84-11ea-8eb0-e7e7d69c2b5d.png)

**Comment by ecraig12345** [comment]
I see what you're talking about, but I'm not familiar with how the CommandBar resizing logic works. @micahgodbolt do you happen to have any idea why this would be happening (since you worked on the previous issue and may be more familiar with flexbox)?

Just to set expectations, this is probably not something we'll be able to address right away, since a workaround exists and we’re currently focusing on larger improvements to performance and coherence.

**Comment by NitsanAmit** [comment]
@ecraig12345 @obvioussean Hey, any other workaround out there / ETA on a fix? I'm experiencing the same issue trying to align a command bar to right, and the ()=>undefined trick didn't work.
