### ISSUE TITLE
TextField autoCapitalize='off' not working

### ISSUE THREAD

**Issue by bdombro** [microsoft/fluentui#13231]
### IOS with Safari, Firefox, Chrome

- **Package version(s)**: 3.0.1
- **Browser and OS versions**: IOS 13.4.1 with latest Safari, Firefox, Chrome

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/hopeful-hodgkin-8v6sz?file=/src/App.js

#### Actual behavior:

TextField with autoCapitalize='off' does not prevent the first letter to be capitalized in IOS input field. I suspect it doesn't actually add autocapitalize='off' to input field.

#### Expected behavior:

The first letter entered in the input field should be lowercase.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe, depends how involved. I'm new to FluentUI.

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for reporting this! It looks like we're not passing the `autoCapitalize` prop through to the `<input>` because `autoCapitalize` is missing from `inputProperties` and `textAreaProperties` in  our [`getNativeProps` utility](https://github.com/microsoft/fluentui/blob/master/packages/utilities/src/properties.ts). 

If you're willing to submit a fix, that would be great! Note that you will have to fork and clone the repo because we use "change files" that must be generated locally to populate our changelogs (see the [Contributing instructions](https://github.com/microsoft/fluentui/wiki/Contributing)), but otherwise it's pretty straightforward.

**Comment by bdombro** [comment]
Awesome!!!
