### ISSUE TITLE
Shortcut key is not provided to navigate to MessageBar

### ISSUE THREAD

**Issue by sophiafeng2017** [microsoft/fluentui#13258]
### Environment Information

- **Package version(s)**: 7.114.1
- **Browser and OS versions**: Edge

### Describe the issue:

Shortcut key is not provided to navigate to MessageBar

#### Actual behavior:

Shortcut key is not provided to navigate to the MessageBar.

#### Expected behavior:

Shortcut key should be provided to navigate to the MessageBar and screen reader should announce the shortcut key to navigate to that particular control.

**Comment by ecraig12345** [comment]
Thanks for reporting this, but it's not clear what you mean, since I don't think MessageBar has any shortcut key functionality built in. It would help if you can add specific repro steps as well as a codepen showing what you've tried so far--you can start from one of the [MessageBar examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/messagebar) (click "Export to CodePen") or https://aka.ms/fluentpen.

**Comment by sophiafeng2017** [comment]
Hi Microsoft/Fluentui,
Thanks for reaching out. As "MessageBar has any shortcut key functionality
built in", could MessageBar provide a shortcut key? Like when using the
Narrator, "H" is the shortcut key for Header.
It's a bug opened by the Accessibility test.


Thanks

**Comment by ecraig12345** [comment]
I'm still not sure what you mean by provide a shortcut key. We certainly don't have the ability to modify Narrator to provide custom shortcuts.

What are the specific steps you followed in an accessibility test which make you think this is a bug?
