### ISSUE TITLE
Tooltip of dismiss button in Dialog control is not opened on tabbing through keyboard

### ISSUE THREAD

**Issue by Harkesh030679** [microsoft/fluentui#13286]
Tooltip of cross button in Dialog control is not opened on tabbing through keyboard

### Environment Information

OS: Win10
Browser: Chrome, Edge

### Describe the issue:

Tooltip of cross button in Dialog control is not opened on tabbing through keyboard, Tooltip is opened on hover properly

### Please provide a reproduction of the issue in a codepen:

Link
https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog
Snap
![Dialog](https://user-images.githubusercontent.com/62233836/82655665-258c1980-9c40-11ea-89ad-739a2658a2cf.png)

#### Actual behavior:

Tooltip of cross button in Dialog control is not opened on tabbing through keyboard

#### Expected behavior:

Tooltip of cross button in Dialog control should be opened on tabbing through keyboard

**Comment by aneeshack4** [comment]
@Harkesh030679 You can wrap it in TooltipHost like in the examples here https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip

**Comment by aneeshack4** [comment]
Oops my bad - there's actually no custom renderer available. @ecraig12345 has more details on this.

**Comment by ecraig12345** [comment]
At this point it's expected that the tooltip won't open on keyboard focus of the dismiss button because we're using only the browser's native tooltip (`title` property), which doesn't work that way. @aneeshack4 is right that we could add a tooltip that opens on keyboard focus by wrapping the button in a TooltipHost, but this isn't something we'd want to add by default due to bundle size concerns.

We could however consider adding a custom renderer `onRenderDismissButton` which would let you wrap with the button with a TooltipHost yourself. I've marked this as a feature for backlog review (if we do this it should also be added to Panel and other controls with dismiss buttons), though we may not get to it for awhile since we're currently focused on larger work items around performance and coherence. It's also possible we may want to defer this until a later version where we have slots available instead of custom render functions.
