### ISSUE TITLE
[Selection] Numeric key with zero as value causes selection problem

### ISSUE THREAD

**Issue by avenezia** [microsoft/fluentui#13299]
### Environment Information

- **Package version(s)**: 7.107.3
- **Browser and OS versions**: Edge version 83.0.478.37 on Windows 10

#### Actual behavior:
When using a numeric key with zero as value, the isKeySelected method of the selection returns wrong information. This seems due to a problem in the [defaultGetKey function](https://github.com/microsoft/fluentui/blob/7a2822b05a9a816056784a7b27acc3806315d9b9/packages/utilities/src/selection/Selection.ts#L491): since the key with zero as value evaluates to false, the function returns the index instead of the key.

#### Expected behavior:
The check for undefined in the defaulGetKey function should be explicit so that the key should be used instead of the index.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for noticing this! I'll make a change so it considers either 0 or empty string to be a valid key.

**Comment by ecraig12345** [comment]
Actually I'm just going to make it accept 0 because accepting empty strings would require some other logic changes (plus it's a less likely scenario and not specifically what was requested here). If anybody comes across this in the future and wants empty strings to be accepted as keys, please file a new issue about that including details of your use case.
