### ISSUE TITLE
Add "initialsTextColor" to Persona Component

### ISSUE THREAD

**Issue by Arknev** [microsoft/fluentui#13323]
#### Describe the feature that you would like added

Set the initials text color just like the coin background color prop: "initialsColor"

#### What component or utility would this be added to

Persona Coin

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

When setting the initials background color, for a WP that supports theme variants, we need to be able to set the text color as well.

**Comment by aneeshack4** [comment]
I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items and enhancements to our performance (see pinned v8 issue). There are also accessibility concerns wrt allowing changing the initalsTextColor because color contrast might not be met.

**Comment by Arknev** [comment]
Thanks for the update.

Contrast is my concern here. We can set the background color to any color but without the ability to set the text color then we run into accessibility concerns when the theme or section variants are changed. So I can use "themeVariant.semanticColors.primaryButtonBackground" to make the coin stand out with the theme color but without being able to set the text to something like "primaryButtonText," then I'm left with a contrast issue.

**Comment by JustSlone** [comment]
Tagging this help wanted and good first issues, this would be a great contribution for someone getting ramped up on the project
