### ISSUE TITLE
CoachMark className doesn't tell if the animation is done and if the teaching bubble isCollapsed or not.

### ISSUE THREAD

**Issue by chaofeng2014** [microsoft/fluentui#13332]
#### Describe the feature that you would like added

We want the root className of the CoachMark tell us if the CoachMark is currently showing a drop or the whole content of teaching bubble. So we can overwrite the style if needed.

#### What component or utility would this be added to

CoachMark

#### Have you discussed this feature with our team, and if so, who

No, need add Wendy Lu (designer) of ODSP as well. 

#### Additional context/screenshots

So the following is what we want, when the CoachMark is showing an drop, we want the drop be dark blue, and once the animation is done and the teaching bubble content is showing, we want the beak to be light blue. To achieve this, we need at least differentiate the isCollapsed state. Here is the code I checked in fabric, seems we don't mark it in any className of CoachMark. https://github.com/microsoft/fluentui/blob/master/packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx
![image](https://user-images.githubusercontent.com/6550896/82965551-4c6a8880-9f7d-11ea-85e4-2dd3c0e24ab1.png)

**Comment by chaofeng2014** [comment]
Potential solution here: 
add the isCollapsed in the root className:
![image](https://user-images.githubusercontent.com/6550896/82965776-fc3ff600-9f7d-11ea-82a7-5c4bea4ad4f9.png)

**Comment by aneeshack4** [comment]
@chaofeng2014 Thanks for reaching out to us Chao! Are you able to submit a PR for this? Tagging @leddie24 Coachmark's owner - he might have input on whether this solution is ok and may be able to help review the PR.

**Comment by ecraig12345** [comment]
You can already do this with existing style props by passing in a `styles` function to the Coachmark (rather than manual overrides with class names), [as shown here](https://codepen.io/ecraig12345/pen/bGVyPoa?editors=0010).
```tsx
const coachmarkStyles: IStyleFunction<ICoachmarkStyleProps> = styleProps => {
  // You can get the real colors you want from the theme.
  // Hardcoding red (closed) and green (open) for demonstration purposes.
  const { isCollapsed, theme } = styleProps;
  return {
    // bubble/rectangle
    entityHost: isCollapsed && { backgroundColor: 'red' },
    rotateAnimationLayer: {
      selectors: {
        // beak
        svg: { fill: isCollapsed ? 'red' : 'limegreen' }
      }
    }
  };
};

// later
<Coachmark styles={styleProps} ... >
```

For some reason the beak color is hardcoded, which is why I had to target it with an `svg` selector inside `rotateAnimationLayer` (one of the wrapping elements). Really there should be a separate prop to control that, but it's not something our team will be able to add since we're currently focused on larger work items around performance and convergence. (In general, Coachmark is not a high priority for us, so it would be best for you within ODSP to coordinate design and implementation of any changes amongst yourselves.)

**Comment by chaofeng2014** [comment]
@aneeshack4 @ecraig12345  thank you both. I will use the style overwrite that Elizabeth mentioned above. So maybe we can just close this one.
