### ISSUE TITLE
Screen reader is providing irrelevant information along with the list elements of combo boxes. (Combobox)

### ISSUE THREAD

**Issue by sereymonyros** [microsoft/fluentui#13349]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Screen reader is providing irrelevant information along with the list elements of combo boxes.

#### Expected behavior:

Screen reader should not read the irrelevant information along with the list elements of combo boxes.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@sereymonyros You must follow our issue template and actually provide a codepen and repro steps... since these weren't provided, I ran Narrator on the ComboBox example on our examples page and it is providing relevant information and not irrelevant. Resolving this as not an issue.
![image](https://user-images.githubusercontent.com/4161791/83041216-dbbb7e80-a005-11ea-825a-68966a502e7f.png)
