### ISSUE TITLE
 The link without href( the link is rendered as a button) looks like non actionable texts under high contrast white/black

### ISSUE THREAD

**Issue by v-kusudh** [microsoft/fluentui#13419]
Environment Details: #URL: https://developer.microsoft.com/en-us/fluentui#/controls/web/link

Browser & Version: Chromium edge: Version 81.0.416.53 (Official build) beta (64-bit)

OS Details: Microsoft Windows 10 Enterprise Version 1909 (OS Build 18363.657)

**Repro Steps:​**

1. Enable high contrast black/white by Select Start > Settings > System > Turn on High contrast, enter URL https://developer.microsoft.com/en-us/fluentui#/controls/web/link.
2. Navigate to Usage section.
3. Check if the link without href( the link is rendered as a button) looks like non actionable texts under high contrast white/black

**Actual Result:​**
The link without href( the link is rendered as a button) looks like non actionable texts under high contrast white/black

**Expected Result:​**
The link without href( the link is rendered as a button) should looks like actionable buttons under high contrast white/black

**User Impact:​**
Screen reader users will face difficulties in understanding where their focus is present on the page

**Normal Mode** 
<img width="960" alt="NormalMode" src="https://user-images.githubusercontent.com/64893219/83402533-9099d500-a424-11ea-8ee2-d4bd37b709e9.png">

**High Contrast Mode Black**
<img width="960" alt="HighContrastBlack" src="https://user-images.githubusercontent.com/64893219/83402528-8ed01180-a424-11ea-95cd-08fa13083ff6.png">

**High Contrast Mode White**
<img width="960" alt="HighContrastWhite" src="https://user-images.githubusercontent.com/64893219/83402530-90013e80-a424-11ea-8252-f109d554580f.png">

**Comment by jdhuntington** [comment]
@betrue-final-final Can you please comment on what these links should look like in high contrast? Feel free to assign it back to me and will get the changes folded it.

**Comment by ecraig12345** [comment]
This happens because we render href-less links as buttons, which render with a different color in high contrast. There's unfortunately not a good way to work around it because the default color used for links is not available as a [system color](https://www.w3.org/wiki/CSS/Properties/color/keywords#System_Colors), and we can't hard-code the color say to yellow because that won't match all high-contrast themes and won't respect user customizations. 

So the only workaround here is on the consumer side: don't use href-less links. If you must have a link without a href, use `href="#"` and then call `ev.preventDefault()` in the click handler.
