### ISSUE TITLE
javascript example ?

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/fluentui#13501]
Hey guys where your javascript example ?
All js example here not work ?!
https://fluentsite.z22.web.core.windows.net/components/list/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#types-selectable

And all code on MS site are buggy and write in ts ! also no (codeSandBox) ?

**Comment by marcosteam** [comment]
Oh-Oh, another one who is confused by the document.
First, you should use [Fluent UI doc](https://developer.microsoft.com/en-us/fluentui) instead of that one named-very-weird.
Second, maybe you can learn something about [TypeScript](https://www.typescriptlang.org/), most of the example are written by this.
