### ISSUE TITLE
Can't load Fluent UI CSS to iframe

### ISSUE THREAD

**Issue by nirtz89** [microsoft/fluentui#13502]
### Environment Information

Fluent UI React

- **Package version(s)**: 7.75.0
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Link to codesandbox: [https://codesandbox.io/s/github/nirtz89/fluent_ui_iframe_test](https://codesandbox.io/s/github/nirtz89/fluent_ui_iframe_test)

#### Actual behavior:

I'm Trying to use React.Portal to render a fabric ui component inside an iframe, the component gets rendered with the correct Fluent UIs classes, but has no Fluent UI CSS.

#### Expected behavior:

Fluent components inside iframe should have Fluents CSS.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment]
@jdhuntington Please investigate to see if we actually support this type of scenario. Thanks! 😄

**Comment by jdhuntington** [comment]
Hi @nirtz89 - thanks for the report and the clean repro.

Unfortunately, due to the implementation of Fluent UI's CSS engine (`merge-styles`), there's no trivial workaround to make this work. When rendering a rule, merge-styles checks to see if the rule already exists in the styles, and adds them if it does. However, it only does so in the document hosting the Fluent controls, so styles are never added to the iframe.

Linking #8192 which talks about the feature required to make this work, but I'm afraid it's not likely to happen any time soon.

**Comment by Psvensso** [comment]
We were looking at implementing FluentUi components inside a shadow dom, we can render some styles inside she shadow with 
 some hacks in StyleSheet.config but a solution like styled-components [StyleSheetManager](https://styled-components.com/docs/api#stylesheetmanager) would be much easier and concise API. 
 
 @dzearing whats the way forward regarding themes and css-in-js for FluentUI? Is scoping / multi-instance considered?

**Comment by Psvensso** [comment]
Linking https://github.com/microsoft/fluentui/issues/9591 as i believe they are related.
