### ISSUE TITLE
"StatusCircle" icons does not have the outer circle

### ISSUE THREAD

**Issue by eugene-beliaev** [microsoft/fluentui#13542]
### Environment Information

- **Package version(s)**: Don't know
- **Browser and OS versions**: Any

### Please provide a reproduction of the bug in a codepen:
* Go to https://developer.microsoft.com/en-us/fluentui#/styles/web/icons
* Type in the icons search: "StatusCircle"
* Observe shown up icons
![image](https://user-images.githubusercontent.com/17223765/84214714-d9a8f380-aacc-11ea-9897-2e09fb3e8620.png)

#### Actual behavior:

Icons does not have outer circle

#### Expected behavior:

Icons must have outer circle

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: -

**Comment by eugene-beliaev** [comment]
@paulgildea Since all these icons have "Circle" in their names and their content is much smaller than their size, it makes a perception that there were an outer circle some time ago but it disappeared. I just need these outer circles back. Or I'm wrong and it's not a bug?

**Comment by paulgildea** [comment]
@eugene-beliaev - Typically we don't remove icons due to compat reasons. I'll follow up with some folks on the design team to understand that supported usage scenario.

Would you mind sending me screenshot of the desired experience you are trying to create? That will help give me a better idea of what icons could help here. Thanks!

**Comment by eugene-beliaev** [comment]
I cannot do that, sorry

**Comment by eugene-beliaev** [comment]
Hey @paulgildea! Any news?
