### ISSUE TITLE
Allow `preventDismissOnScroll` for Dropdown/ContextualMenu to pass to CallOut

### ISSUE THREAD

**Issue by spideeee** [microsoft/fluentui#13592]
#### Describe the feature that you would like added

At present the dropdown/context menu closed on scroll, which is a bad experience according to me. We already have a prop in CallOut named `preventDismissOnScroll` to prevent such behaviour.

#### What component or utility would this be added to

DropDown
ContextualMenu

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

https://codepen.io/spideeee/pen/zYrBoqE?editors=0010

**Comment by paulgildea** [comment]
@paulgildea Determine if the behavior of the dropdown and contextmenu is by design or if this is a good feature request.

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/Rwrgvdp?editors=0010

The current behavior is by design, but there is a (rather awkward) way to opt out of that design;

Provide the preventDismissOnScroll to calloutProps, and also doNotLayer flag is required to render it inline, rather than on a layer outside the scroll region.

**Comment by spideeee** [comment]
I believe `Dropdown` does not support `doNotLayer` flag.
