### ISSUE TITLE
@fluentui/react-button: does not render `children`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#13665]
### Environment Information

- **Package version(s)**: @fluentui/react-button@0.3.2

```tsx
<Button>I am a button</Button>
```

https://codesandbox.io/s/mystifying-morse-mxf67?file=/src/App.js

#### Actual behavior:

Renders nothing.

#### Expected behavior:

A button with "I am a button" text.

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by dzearing** [comment]
What happens when you use both content AND children?

```tsx
<Button content="hi">world</Button>
```

**Comment by khmakoto** [comment]
@dzearing so the expectation is that `children` always wins over `content` correct?

**Comment by layershifter** [comment]
Our components existing do not render slots if `children` exist:

```tsx
<Button content="Click here" />
// &
<Button>
  <Button.Content>Click here</Button.Content>
</Button>
```

Both above are equal.

**Comment by dzearing** [comment]
@layershifter Checkbox seems to ignore children; is this a bug or are there special cases?

**Comment by layershifter** [comment]
There are special cases, for example `Input` it's the same case.

**Comment by dzearing** [comment]
OK. I think that makes sense mostly, because certain primitives which the components model after can't render children. Image probably is another.

In Button for static slots it seems that only Content and Group are available statically; Icon doesn't seem to work. is the expectation that all slots would be available as statics?

```tsx
<Button icon="O" content="Click here" />

<Button>
  // icon is missing.
  <Button.Icon>O</Button.Icon>
  <Button.Content>Hi</Button.Content>
</Button>
```

Are there pitfalls you ran into with this such that we shouldn't do this, or is it beneficial? I like it because things get way more composable, but also I think it will add slot wrappers to the React hierarchy and create a lot more edge cases in styling. (styles assume a particular shape but this would allow the shape to be altered which styles wouldn't always anticipate.)

**Comment by dzearing** [comment]
For this bug, let's adjust to replace the content as v0 does.

**Comment by dzearing** [comment]
```tsx
(state, ref, options) => {
  const { slots, slotsProps } = ...;

  return (
    <slots.root ...>
       { state.children ? state.children : (
       ) }
    </slots.root>
  );
```

**Comment by dzearing** [comment]
This now works as expected:

https://codesandbox.io/s/aged-feather-gjnf9?file=/src/App.js

These all work, with content taking precedence over children:

```jsx
      <Button>I am a children</Button>
      <Button content="I am a content" />
      <Button content="I am content">I am children</Button>
```
