### ISSUE TITLE
TextField - To show error style by passing a boolean property

### ISSUE THREAD

**Issue by wuwei8372** [microsoft/fluentui#13719]
#### Describe the feature that you would like added

This example below shows the error styling (red boarder) of the TextField by passing "errorMessage" property. Could it be possible to pass a boolean variable (instead of a string type errorMessage) to decide whether to show the error styling? Because we want to show the error styling without any error message.

<TextField label="With error message" errorMessage="Error message" />

#### What component or utility would this be added to

TextField 

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Example TextField in the following image. (Would like to show the same red boarder but without errorMessage)
![image](https://user-images.githubusercontent.com/17853354/85183351-48f6b400-b240-11ea-9154-78fcbcd7bd3d.png)

**Comment by paulgildea** [comment]
@ecraig12345 we found a that passing `true` or `false` to the `errorMessage` property. If you assign it to `false` it won't render the message. 

Is this the expected behavior? 

@wuwei8372  if you pass `false` does this get your desired behavior?

**Comment by ecraig12345** [comment]
`errorMessage` wasn't intended to take a boolean, so any behavior you happen to see in that case today is unintentional and probably shouldn't be relied upon.

I don't think we should add this type of feature to TextField right now, but it's something we could consider when working on converged TextField form components in the future.

**Comment by wuwei8372** [comment]
Thanks for the response @ecraig12345 and @paulgildea! I found passing true to errorMessage is the desired behavior, which shows the red boarder without showing any error message. So if errorMessage wasn't intended to take a boolean, may I know is there another way to get the same behavior (red boarder without error message)? (is this possible to create another boolean property of TextField for this?). Thanks!

**Comment by ecraig12345** [comment]
You can continue to pass a boolean for now if you want, and it's likely to continue working for now, but I wanted to be clear that since it's not an intentionally added behavior it may change in the future (particularly across major versions).

We're currently trying to be very careful and selective about adding new props, because adding a new prop any time anyone wants one results in components with bloated, inconsistent API surfaces which are hard to use and maintain, and often also bloats the size and/or slows down the performance of components. (Quite a few of the problems we're dealing with trying to improve component performance and API usability right now are the result of not being so selective in the past.) This suggestion seems reasonable and we might consider it for future work, I'm just hesitant to act on it right now.

**Comment by wuwei8372** [comment]
Thanks very much for the clarification, this is very helpful!
