### ISSUE TITLE
ICommandBarItemProps doesn't support focus method

### ISSUE THREAD

**Issue by yanbxice** [microsoft/fluentui#13749]
### Environment Information

- **Package version(s)**: Latest version
- **Browser and OS versions**: All

### Describe the issue:

I'm implementing a command bar with several buttons on it. The buttons are of type ICommandBarItemProps and assigned to attribute "items" of CommandBar. Now I want to set focus for one of the buttons using componentRef, but it says cannot find focus() on IContextualMenuRenderItem. I checked the doc for this interface and not found focus() supported. https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu#IContextualMenuRenderItem

#### Actual behavior:

Not able to find a focus method on a command bar button with type ICommandBarItemProps.

#### Expected behavior:

We should be able to set focus on any button.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@joschect is this the preferred method for setting focus on a `CommandBar` button?

**Comment by yanbxice** [comment]
Hi @joschect, any update for this?

**Comment by meghanking** [comment]
Hi @joschect, any update for this?

**Comment by joschect** [comment]
@meghanking and @yanbxice sorry for the slow reply! This is due to the fact that CommandBarItemProps inherits from IContextualMenuItemProps but doesn't actually create a contextualmenu item. You can see that focusing an element in this way does actually work even though the compiler complains. You can see it working in [this codepen](https://codepen.io/slimemold/pen/ExgyzoR?editors=0010) . I'm not sure if we can have a good fix since within the commandbar it passes the props to both contextualmenuitem and commandbaritem depending on if it's in overflow or not. In the short term as a workaround I'd suggest doing

```typescript
  const testRef = React.useRef<any>(null);
```

Although again that's not ideal. We'll mark this as a bug and get it fixed, maybe in  a later release since it could be breaking but this should unblock you for now.
