### ISSUE TITLE
Horizontal scroll of header column in scrollablePane with sticky header

### ISSUE THREAD

**Issue by reijam** [microsoft/fluentui#13760]
Not sure if this is a bug, a new feature or just missing documentation.

i have gone through the ScrollablePane, DetailsList and Sticky components in detail and it seems that horizontal scrolling is not a degree of freedom allowed for a sticky header.

My goal is to have the column headers stay at the top of the page while scrolling down but at the same time when scrolling right have those same headers move in conjunction with the underlying table of data. 

Presently columns that are scrolled to the right no longer line up with a sticky header

 

Stack Exchange has nothing on this topic related to fabric or fluent... There are no examples and the docs do not show how to do this.

Any guidance would be appreciated.... or if it has not been contemplated please let me know so i can help with a pr on the underlying components

**Comment by reijam** [comment]
Further to my inquire/bug report i have discovered a bug (or deliberate oversight) in the ScrollablePaneBase.js module.

For some bizarre and unknown reason horizontal scroll events are not picked up by an individual component  they have to be grabbed the same way as a resize event (through the window).

  ` window.addEventListener('scroll', this.doScroll, { passive: true }) `


In the ScrollablePaneBase.js  module in you instantiate the scroll events as follows

```
  public componentDidMount() {
    const { initialScrollPosition } = this.props;
    this._events.on(this.contentContainer, 'scroll', this._onScroll);
    this._events.on(window, 'resize', this._onWindowResize);
    if (this.contentContainer && initialScrollPosition) {
      this.contentContainer.scrollTop = initialScrollPosition;
    }
```


by changing it to 

   ` this._events.on(window, 'scroll', this._onScroll);`

you will have at least trapped the scroll event.

The next problem is getting the scrollLeft to actually work properly.

I am stuck on that one (it does not work when i try to scroll  the ref from my code.

I am hoping that sending me a scroll event so that i can scroll my own component will fix the problem.

**Comment by reijam** [comment]
Adding another insight.

It appears that there is no way to get the window.scrollX data from within the ScrollablePane component.  It appears that the horizontal scroll event is generated in the DetailsListBase... and is from the root of that component.

Presently there is no scroll  trapping in that component and therefore it is not possible to capture that scroll in order to relay it back to the HOC controlling the column header scroll.

I realize that in all likelihood this is a rather subtle and complex bug to resolve but it is most definitely a limitation that affects the ability to make column headers useful if there are  many columns  in a grid.

If someone knows of a workaround please do let me know... 

In terms of addressing this issue it is non trivial and my guess is going to require a rethink about how to integrate sticky , details list and scrollable pane... (or not... and just keep them as one unit with more callbacks.).

I have some thoughts about how to re-architect this area of code if anyone is interested.

cheers

**Comment by paulgildea** [comment]
@reijam Thanks for your detailed insight! That's really helpful.

I'll follow up to see if `Sticky` was ever really meant to be used in horizontal scrolling case. My assumption is that it was not - but I could be mistaken.

I'll include @dzearing here for any insight on a possible work around, but we've lost some of the expertise on the team in this specific domain so to your point will most likely be a complex bug to resolve. 

I'm going to mark this as a question for now - as I don't think realistically if we will be able to address as a fully supported feature.

**Comment by reijam** [comment]
As I said I am willing to dig in on this if I can get a modicum of support.  let me know

**Comment by jeffersoneagley** [comment]
I just ran into the same issue.

**Comment by gmonb** [comment]
https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane

Doesn't this second example show you how it works ?

Or in codepen exported: https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2F

**Comment by PooLP** [comment]
Hi,
Same problem for me.
on demo page (https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane)

If you scroll only with horizontally scrollBar, all content scroll, include sticky part -> bug
Il you scrolling one or two pixel vertically scrollbar, only scrollable content scroll, the sticky part is really "Sticky" -> work, but unusable

i'm use 7.155.0 version of Fluent UI and the bug is not resolved.

**Comment by JustSlone** [comment]
If someone wants to dig in and investigate. The issue seems that the Sticky behaves as desired here when isStickyTop is true. The code appears to only set isStickyTop when the vertical scroll is used. It seems that Sticky isn't really built as a horizontal sticky even though it works as one (because once it sticks, it stays there irrespective of vertical or horizontal scroll)

Here's a codepen that better demonstrates the desired behavior of the sticky. If there is content above the sticky you want that content to scroll past before the sticky sticks. This is why the sticky isn't "sticky" unless there is some scrolling in the other example. Though perhaps the check should be >= rather than > so that in the example it does stick when it's at the top.
Updated code pen:
https://codepen.io/justslone-the-encoder/pen/jOMwqRR?editors=1010

Here's the line of code that seems to cause the sticky to become sticky
https://github.com/microsoft/fluentui/blob/cbc0b9a2f9b569eeabd7bba3812002edcca948e8/packages/react-internal/src/components/Sticky/Sticky.tsx#L176

Here's the line of code i think sets isStickyTop (which causes the sticky to become sticky)
https://github.com/microsoft/fluentui/blob/cbc0b9a2f9b569eeabd7bba3812002edcca948e8/packages/react-internal/src/components/Sticky/Sticky.tsx#L271

Sorry, this investigation is incomplete, someone will have to take this and debug/confirm this and figure out possible fixes. I'm not super familiar with this logic and won't be able to dig in more here. Hopefully this is a good start for someone else to pickup and run with.

And lastly, because everything is better with gifs. Here's a gif of the repro
![ScrollSticky](https://user-images.githubusercontent.com/40304143/102585931-14b06300-40be-11eb-8693-e829e9c0c7ce.gif)

**Comment by gmonb** [comment]
@JustSlone I really appreciate the effort. I should have added a gif right away !

Just as extra clarification, my desired behavior would be that everything above the sticky table sticks all the time.

Thanks for the help so far.

**Comment by JustSlone** [comment]
One thing to consider, is that you maybe just be able to make something that is absolute positioned with html and CSS. The reason Sticky exists is to coordinate with the scrollable pane and respond to scroll position, which is complex logic. 

If you need something that is just always there, that probably could be achievable with some absolute positioned items plus a bit of margin.
