### ISSUE TITLE
autoClose calendar component when user select date.

### ISSUE THREAD

**Issue by omerquyyum12** [microsoft/fluentui#13761]
### Environment Information

- **Package version(s)**: (6.27.0)
- **Browser and OS versions**: (chorme)

#### Actual behavior:
when i select date from date picker the calendar automatically close it self.

#### Expected behavior:
it should remain open . i am making a component based on DatePicker where i can select multiple random dates. issue is each time i select date the calendar callout close and then user has to reopen the calendar comonent by clicking button on the field. it should remains open so user can select multiples dates and when press ESC it should close or mayb onBlur it should close (closing is not relevent right now)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (for me it is very high)

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@omerquyyum12 Thanks for the feedback.

Currently our `DatePicker` only allows the selection of one date as opposed to a DateRange. 

I'm going to mark this as by Design for now. 

I don't have a good workaround for this issue off hand - other than composite two `DatePicker` components together to give you a range to reason over.

Adding @lorejoh12 for any other insight.

**Comment by omerquyyum12** [comment]
@paulgildea Hi, selection of one date is not an issue issue is with closing of date picker upon date selection. is there anyway datePicker remains open after date selection?
