### ISSUE TITLE
DatePicker UI change language like dutch

### ISSUE THREAD

**Issue by DesireTushar** [microsoft/fluentui#13802]
When select Date from date picker , Can we display date in dutch language
![image](https://user-images.githubusercontent.com/51224740/85733740-0e968680-b71a-11ea-9fe1-f472aa95fa8e.png)

**Comment by paulgildea** [comment]
Thanks for the feedback @DesireTushar !

Are you asking how to display the date in a specific language or you can't display the date in a specific language?

We need a little more clarity on this issue to help us determine if this is an issue or not?

Thanks!

**Comment by DesireTushar** [comment]
yes i am not able to display in specific language

**Comment by paulgildea** [comment]
@lorejoh12 - Any thoughts on this one? Does the `DatePicker` provide a localized API?

**Comment by lorejoh12** [comment]
The DatePicker component itself does not handle localization, it only natively supports en-us. However, there is support for consumers to add whatever localization they need.

To display the date in a different format (day month year, for example, instead of month day year), you can use the property `formatDate`, which is an optional callback that takes the Date and returns a string to display. moment.js is a popular library for formatting if you want to go this route.

To change the strings that are displayed to a different locale, the property `strings` allows passing of an `IDatePickerStrings` type, which allows for overriding all the different strings in the chosen language. To keep the package small, we don't have any of those strings in different languages by default.
