### ISSUE TITLE
ComboBox, when we open the dropdown and press down arrow, second option is highlighted instead of first

### ISSUE THREAD

**Issue by Ashwin-Nikam** [microsoft/fluentui#13866]
### Environment Information

- **Package version(s)**: 7.120.0
- **Browser and OS versions**: Chrome + Win10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/ashwin-7/pen/pogdyqW

#### Actual behavior:

When multiSelect is set to true and we open the dropdown in the ComboBox and press the down arrow key, second option is highlighted.

#### Expected behavior:

When pressing the down arrow key the first time, the first option should be highlighted and not the second.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA

**Comment by paulgildea** [comment]
Thanks for the repo @Ashwin-Nikam !

I'm able to repo the behavior you describe in the codepen.

**Comment by adilmahmood2020** [comment]
Hi, 
We have implemented a new Activity Type Filter for activities in the Dynamics 365 Sales UCI App. The activity filter is a ComboBox with multi selected options enabled. On Pressing the down arrow button, focus is going to the second option instead of first as mentioned in this issue. Are there any workarounds for this issue and can we have an ETA for fixing this bug?
