### ISSUE TITLE
How to style Menu focused via Keyboard

### ISSUE THREAD

**Issue by jacargentina** [microsoft/fluentui#13911]
I have this Menu, which gets "broken" (in styling) when using keyboard to navigate (second item, text not nice, which is focused via keyboard)

I've not found on how to style this "keyboard focused" thing anywhere on docs https://fluentsite.z22.web.core.windows.net/theming-examples

<img width="204" alt="Captura de Pantalla 2020-07-02 a la(s) 19 59 01" src="https://user-images.githubusercontent.com/517228/86415876-b671fe00-bc9e-11ea-8b98-1a77ace87ca4.png">

**Comment by paulgildea** [comment]
@jurokapsiar Not clear if this is an issue or a question.

**Comment by mnajdova** [comment]
@jacargentina  can you please create a repro for this in codesandbox, so we can test this. In dark mode the focusing on the menu looks good, so it may be some local override in your case

![image](https://user-images.githubusercontent.com/4512430/86913538-18a78480-c11f-11ea-8176-20ab059dd61a.png)

For override the `MenuItem` styles, you can use the `isFromKeyboard` property in order to apply styles for the focusing state, see an example here:
https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/themes/teams/components/Menu/menuItemStyles.ts#L166

**Comment by jacargentina** [comment]
```
const theme = {
  componentVariables: {
    Menu: {
      color: '#bbb'
    },
    MenuItem: {
      colorHover: '#fff',
      colorActive: '#fff'
    },
    MenuItemWrapper: {
      backgroundColorHover: '#222331',
      backgroundColorActive: '#1e1e29',
      wrapperColorActive: '#fff'
    }
  },
  componentStyles: {
    MenuItem: (props) => {
      return {
        colorHover: 'red',
        colorActive: 'blue'
      };
    }
  }
};

export default theme;
```

Tried adding `componentStyles` key to my theme, but its not working (breakpoint on the given function dont stops), any advice?
