### ISSUE TITLE
DetailsList compact view separator lines

### ISSUE THREAD

**Issue by Jacqueline-ms** [microsoft/fluentui#13935]
### Environment Information

- **Package version(s)**: All versions
- **Browser and OS versions**: All browsers

### Describe the issue:
- DetailsList component exhibits line separator between rows by default, however in compact = {true} the lines disappear.

- Compact View = true (no lines):
![image](https://user-images.githubusercontent.com/30805892/86809871-30a0da80-c031-11ea-87e2-a861af6728bb.png)
- Compact View = false (lines visible):
![image](https://user-images.githubusercontent.com/30805892/86809885-34ccf800-c031-11ea-8b11-dcf42cd4706c.png)

### Please provide a reproduction of the issue in a codepen:
 https://codepen.io/pen/?&editable=true=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:
![image](https://user-images.githubusercontent.com/30805892/86811332-a5284900-c032-11ea-990b-64c91b3ffe92.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/30805892/86811342-a78aa300-c032-11ea-9be9-990cb84c30da.png)

**Comment by paulgildea** [comment]
@dzearing - Is this by design? Who can we follow up with to determine if the separator drop is part of the compact design?

**Comment by dzearing** [comment]
@paulgildea I believe that this is the design. @betrue-final-final or Christopher I believe are the designers.

**Comment by dzearing** [comment]
@Vitalius1 might have some background here; I'm not 100% sure tho

**Comment by Vitalius1** [comment]
This are some screenshots that I got from the FluentUI toolkit here: https://www.figma.com/file/F5BN2yodUyHlOfpL4KJCFK/Fluent-Web?node-id=850%3A0

Looks like it is by design. Also, looking from the code ([link](https://github.com/microsoft/fluentui/blob/209102879028aa62a445ac6c041b79b9d203c8e1/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.styles.ts#L223-L226)) it doesn't seem like it was done by accident. At the same time will leave @betrue-final-final have the final word.

# Base
![image](https://user-images.githubusercontent.com/29514833/86979244-ac844b00-c135-11ea-8052-9d9ee6b2a07c.png)
# Compact
![image](https://user-images.githubusercontent.com/29514833/86979294-c3c33880-c135-11ea-91a2-07cd66cc209c.png)
