### ISSUE TITLE
react-northstar Dropdown search with japanese IME broken

### ISSUE THREAD

**Issue by chgi** [microsoft/fluentui#14052]
### Environment Information

- **Package version(s)**: @fluentui/react-northstar at least 0.49.0 and 0.50.0
- **Browser and OS versions**: Windows 10, Chrome 83.0.4103.116 and Firefox 78.0.2

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/tender-bhaskara-xzl9h?file=/example.tsx

#### Actual behavior:

Trying to input こんにちは (k-o-n-n-n-i-c-h-i-h-a on the keyboard) into the search field of the Dropdown control using Microsoft IME. Compose and convert is not working, text is getting garbled.
In Firefox
![firefox_78 0 2](https://user-images.githubusercontent.com/16658192/87613895-984dd880-c749-11ea-976e-69cc8ef7df9e.png)
In Chrome
![chrome_83 0 4103 116](https://user-images.githubusercontent.com/16658192/87613903-9d128c80-c749-11ea-9681-4642709b886f.png)

#### Expected behavior:

Can compose and convert text in the input field without text getting garbled

### Priorities and help requested:

Are you willing to submit a PR to fix? **No** (not skilled enough)

Requested priority: **High**

Products/sites affected: app in development

**Comment by layershifter** [comment]
![dropdown-050](https://user-images.githubusercontent.com/14183168/89293036-9054ca80-d65d-11ea-9d89-ceefb1abfa86.gif)
![dropdown-051](https://user-images.githubusercontent.com/14183168/89293042-92b72480-d65d-11ea-948c-6dc82b0a499d.gif)

@chgi This issue was fixed in 0.51.0. Please check 🙏 

- 0.50.0: https://codesandbox.io/s/tender-bhaskara-xzl9h
- 0.51.0: https://codesandbox.io/s/kind-moser-fih5w

**Comment by chgi** [comment]
I checked it out and it works now. Thanks for the fast fix!

**Comment by layershifter** [comment]
Great, closing it 👍
