### ISSUE TITLE
FluentUIv0 - Button with loading=false has slightly more padding than loading=undefined

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluentui#14060]
### Environment Information

- **Package version(s)**: `@fluentui/react-northstar@0.50.0`
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/fluentui-button-loading-false-issue-rtfb6?file=/example.js

#### Actual behavior:

The following usages of button should yield the same result.

```
<Button loading={false} content="Click here" />
<Button content="Click here" />
```

#### Expected behavior:

There are padding differences between the two implementations - 

![image](https://user-images.githubusercontent.com/2114206/87665290-89503180-c71b-11ea-8901-3f68a8e1c58a.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable) NA

**Comment by YuanboXue-Amber** [comment]
Seems to be caused by 
```ts
minWidth: _.isNil(p.loading) ? v.minWidth : v.loadingMinWidth,
```
in [buttonStyles.ts](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-northstar/src/themes/teams/components/Button/buttonStyles.ts)

**Comment by YuanboXue-Amber** [comment]
After discussion with designers, I revert the previous PR that 'fixes' this issue for reason below: 

Button within the same action flow should have the same size.
For a loading button, when loading=true, button is wider than regular button. Then when loading=false, button should keep the same size, because it is still in the same action flow.
