### ISSUE TITLE
Shimmered DetailsList - Shimmers are squashed to the left in IE11

### ISSUE THREAD

**Issue by janjachacz** [microsoft/fluentui#14162]
### Environment Information

- **Package version(s)**:  v7.123.6
- **Browser and OS versions**: Internet Explorer 11, Windows 10

### Fluent Demo Site:
https://fabricweb.z5.web.core.windows.net/oufr/7.123.6/#/examples/detailslist/shimmer

#### Actual behavior:
Shimmer are squashed to the left and taking only approximately half of the available width. 

#### Expected behavior:
Shimmer should be displayed the same in all browsers, thus taking all the available space in the DetailsList

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Power Apps

![image](https://user-images.githubusercontent.com/6408904/88162062-1b22d780-cc11-11ea-8033-874356ebd25b.png)

**Comment by paulgildea** [comment]
@xugao Please determine if this is a recent regression or if this behavior has been present. While the experience is not ideal, we might be able to address this because of the complexity of the `DetailsList`

@janjachacz Just trying to set expectations here. Depending on if this is recent regression we might not address this issue as we are limiting the amount of code changes to the `DetailsList` and IE11 in general - unless it's a high severity issue.

**Comment by janjachacz** [comment]
@paulgildea feel free to not fix as this is only cosmetic and not functional

**Comment by paulgildea** [comment]
@janjachacz Thanks for the realistic feedback on the impact 😄 . The `DetailsList` is a tricky component for us as it has some legacy aspects to it. 

We'll do a proper investigation - I'm curious if the behavior was always like this or if there was a recent regression that was introduced... and if so, how can we prevent similar regressions from happening in the future.

So thank you for filing the issue!
