### ISSUE TITLE
Accessibility - Focus doesn't remain on the button itself after selecting an item from dropdown

### ISSUE THREAD

**Issue by yanbxice** [microsoft/fluentui#14185]
### Environment Information

- **Package version(s)**: 7.121.4
- **Browser and OS versions**: Safari, Voiceover, iOS 13.3

### Describe the issue:

The issue is when Voiceover is turned on, after selecting any option from the dropdown, the dropdown is collapsed. But the focus is on a random invisible element on the page. This is confusing to customers.

### Please provide a reproduction of the issue in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/7.121.4/#/examples/commandbar

#### Actual behavior:

It focuses on some random element on the page.

#### Expected behavior:

The focus should remain on the command bar item after an option is selected and dropdown collapsed.

**Comment by paulgildea** [comment]
@smhigley FYI

**Comment by xugao** [comment]
@yanbxice - this is a VoiceOver issue and you can repro the same behavior in this ARIA [example](https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-2/menubar-2.html). I don't think there is anything we can do here. If you think otherwise, feel free to suggest potential fix

**Comment by smhigley** [comment]
Yup, this is a known issue with the way iOS VoiceOver handles moving the virtual cursor. I don't fully know the reasoning behind it, but I believe it's because they're trying to do some fancy logic to maintain the [x, y] position on the screen of VoiceOver focus when DOM changes happen, likely to make up for certain sorts of author errors.

It's definitely a bug on Apple that VoiceOver focus doesn't follow keyboard focus when keyboard focus is explicitly managed in cases like these.
