### ISSUE TITLE
The 'label' prop on various components should be typed to include JSX.Element

### ISSUE THREAD

**Issue by demoran23** [microsoft/fluentui#14235]
The types for label are incorrect.  Label will accept a JSX.Element (the value of the label prop is eventually passed down to `Label` as children).

Example: `DatePicker`

**Comment by paulgildea** [comment]
@demoran23 Which package are you referring to in your issue?

**Comment by demoran23** [comment]
> @demoran23 Which package are you referring to in your issue?

    "@fluentui/react": "7.121.11",

**Comment by xugao** [comment]
@demoran23 - i agree with you here but we can't make this change in current 7.* release, but this will be fixed in future releases. relaxing the typing for `label` is a breaking change.  for instance, if user is doing
```
string foo = props.label;
```
It will cause TS error. instead they need to do
```
string foo = props.label as string
```

to unblock you, we can use DatePickerProps.textField.onRenderLabel to customize the label to what you need.
