### ISSUE TITLE
Visio Brand Icons still old

### ISSUE THREAD

**Issue by barisbikmaz** [microsoft/fluentui#14253]
### Environment Information

- **Package version(s)**: 7.98.1

### Reproduction 

.ms-BrandIcon--visio displays still the old visio icon.
https://static2.sharepointonline.com/files/fabric/assets/brand-icons/product-fluent/png/visio_96x1.png

The documentation but shows the new brand icon.
https://developer.microsoft.com/en-US/fluentui#/styles/web/office-brand-icons

Are you willing to submit a PR to fix? (No)

Requested priority: (Low)

**Comment by paulgildea** [comment]
Thanks for the feedback @barisbikmaz !

**Comment by xugao** [comment]
@Jahnp - could you advice here?

**Comment by Jahnp** [comment]
Hi @barisbikmaz , thanks for reporting this.

First, just to be clear, the `.ms-BrandIcon--visio` code you shared indicates you're seeing an issue with Fabric Core. Fluent UI does not have a component for handling brand icons specifically; see #14151.

However, you are right in that the [default icon font ](https://github.com/microsoft/fluentui/tree/master/packages/icons) in Fluent UI is a little older, and as a result, some of the branded icons that've been updated elsewhere aren't shown on [this page](https://developer.microsoft.com/en-us/fluentui#/styles/web/icons):
![image](https://user-images.githubusercontent.com/307118/89237275-a1430480-d5a7-11ea-90bd-c72e267a8d63.png)

The reason is that we made the choice *not* to update the `@uifabric/icons` package in #12088 because of concerns of the linearly growing size of the package, both from a package size and memory footprint perspective. That means Visio didn't get its new icon.

This leaves two paths, one that can unblock you and one for Fluent UI & Fabric Core:
1. You can use the [Fabric Icons tool ](https://aka.ms/uifabric-icons) to create your own subset that *does* include the new Visio icon. This is straightforward to create and the icons are drop-in replacements for existing Fluent UI icon uses.
1. Fluent UI team chooses to allow one remaining update to the `@uifabric/icons` package to allow these icons to be patched. The same would need to be done in Fabric Core.
 - The cost of doing this would be an increased runtime memory footprint due to the greater number of icon strings. This would have a detrimental effect on users of platforms like the SharePoint Framework, which bundles Fluent UI.

Given the cost and risks, I'd need the Fluent UI team's approval for us to proceed on # 2. I don't personally have a lot of bandwidth here (my focus is on ODSP products) and would need help from someone on the team willing to assist or go to bat with any disagreements.

@xugao , @paulgildea , let me know how we should proceed here!

cc @micahgodbolt for visbiility

**Comment by barisbikmaz** [comment]
Created an issue on fabric/core https://github.com/OfficeDev/office-ui-fabric-core/issues/1232
