### ISSUE TITLE
DetailsList width increases when moving from empty to non empty list, causing a horizontal scroll to appear

### ISSUE THREAD

**Issue by ron-b** [microsoft/fluentui#14284]
### Environment Information

- **Package version(s)**: 7.121.1

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/ron-b-the-bold/pen/gOPVmzV

#### Actual behavior:

On initial population of the DetailsList (from 0 items to something else) - the list expands its width, likely to accommodate the group/ungroup visual, creating a horizontal scroll that is unrequired.
Every following change in model fixes it. 

#### Expected behavior:

Adjust width so that scroll does not appear.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not sure I'm proficient enough

Requested priority: Normal

Products/sites affected: working on a feature in Excel that is impacted by this.

**Comment by paulgildea** [comment]
Thanks for the feedback @ron-b !

@khmakoto - Can you determine if this is a regression or if this behavior is an issue? If possible does setting a max-width provide a workaround?

To set expectations - Due to the complexity and dependencies of our List components, we are actively trying to minimize risk of regressions. We may not be able to fix this issue with a low risk solution if a reasonable workaround is available.

**Comment by khmakoto** [comment]
I can confirm that I'm able to repro this behavior.

@cschlechty what do you think should be the path forward here?
