### ISSUE TITLE
Is there an idea to made a port on Vue.JS?

### ISSUE THREAD

**Issue by biapar** [microsoft/fluentui#14334]
Is there an idea to made a port on Vue.JS?
If no, Which is a good starting point to do?

**Comment by khmakoto** [comment]
Thanks for the feedback! Currently we are focused on building out a React offering for this repo at this time.
We like to hear this type of feedback from the the community and we are always evaluating what libraries to support for the Fluent Design Language.
This currently isn’t on our roadmap - but thanks for the feedback!

**Comment by beetaa** [comment]
@khmakoto why there's still not thinking about vuejs? and when about the team thinking about vuejs? in my personal opinion, fluentui is abractive but, is also new to developers and end-users, vuejs is a good chance to improve the influence by adapting it. WHY NOT STILL NOT THINKING ABOUT THAT? confusing.

**Comment by biapar** [comment]
Which is a starting point to port to Vue?

**Comment by khmakoto** [comment]
@paulgildea could you help here?

**Comment by paulgildea** [comment]
@beetaa @biapar Thanks for the feedback. 

You are not alone in your feedback for having a supported VueJS implementation so I want to acknowledge that yes we have received this feedback before.

Currently our team has been focused on a React solution since a majority of our partners and product teams use various React based solutions in their products today. Our current focus has actually been around converging two different React based Fluent UI libraries into one common on for customers to use. 

The decision to fully support a new JS framework is a combination and blending of customer usage data, product needs, team skill sets, folks to staff the team, and technical legacy support. And those variables are constantly changing.

Right now, our goals are creating stability, reliability, and convergence with the current set of ReactJS customers. At this time we're not actively looking to increase Fluent adoption across many different frameworks and spread out team thin, but it is something that we are always actively looking towards as usage data and product needs change quickly in the web space.

Hope that helps!

**Comment by biapar** [comment]
> @paulgildea could you help here?

How?

**Comment by biapar** [comment]
> @beetaa @biapar Thanks for the feedback.
> 
> You are not alone in your feedback for having a supported VueJS implementation so I want to acknowledge that yes we have received this feedback before.
> 
> Currently our team has been focused on a React solution since a majority of our partners and product teams use various React based solutions in their products today. Our current focus has actually been around converging two different React based Fluent UI libraries into one common on for customers to use.
> 
> The decision to fully support a new JS framework is a combination and blending of customer usage data, product needs, team skill sets, folks to staff the team, and technical legacy support. And those variables are constantly changing.
> 
> Right now, our goals are creating stability, reliability, and convergence with the current set of ReactJS customers. At this time we're not actively looking to increase Fluent adoption across many different frameworks and spread out team thin, but it is something that we are always actively looking towards as usage data and product needs change quickly in the web space.
> 
> Hope that helps!

So we need to start to study ReactJS

**Comment by vipulw2011** [comment]
Even I was building a custom Tab for Teams but to support theme without much of external work on my Vue.js application, I feel the need of this library to support Vue.js as well

**Comment by biapar** [comment]
I think that Microsoft support more React. All its web applications are on React. Maybe we need to study React?

**Comment by vipulw2011** [comment]
Even I guess so. But there should be something similar to support all client-side frameworks

**Comment by biapar** [comment]
All is a bit impossibile...I think how to start to port on VUE? Is there some generic guide to port a Javascript lib or how to rewrite a React Lib under Vue?

**Comment by vipulw2011** [comment]
@biapar Look at this https://github.com/arturmiz/vuent

**Comment by biapar** [comment]
> @biapar Look at this https://github.com/arturmiz/vuent

Is't from scratch or from MS Fluent Design?
