### ISSUE TITLE
can't set custom width and height of dialog component

### ISSUE THREAD

**Issue by iqbal99** [microsoft/fluentui#14385]
can't set custom width and height of Dialog component in fluent UI for web

**Comment by khmakoto** [comment]
Hi @iqbal99, you can set it but it's more involved than with other components because the `Dialog` component has a `media` query that needs to be overloaded. You can find an example of how to do that is in [this codepen](https://codepen.io/khmakoto/pen/MWyYJVq). Let me know if there's anything else we can do for you but otherwise feel free to close this issue. Thanks!
