### ISSUE TITLE
Determine items in view for DetailsList

### ISSUE THREAD

**Issue by dehoward** [microsoft/fluentui#14409]
We have a use case where we want to determine the list of items in the user's current viewport. I know that `IDetailsList` provides a `getStartItemIndexInView` function, but is there a way to get either the full page or list of items that is currently being rendered?

**Comment by khmakoto** [comment]
Hi @dehoward, I don't believe there is an automated way to do it. The way I can think of working around this would be to use `getStartItemIndexInView` in conjunction with the `height` of the `viewport` prop in `IDetailsListProps` to iterate over the rows given the index and check the height of each to get which rows are in the viewport currently.

I also don't think we're going to add this kind of functionality to the component since due to the complexity and dependencies of our `List` components, we are actively trying to minimize risk of regressions.
