### ISSUE TITLE
@fluentui/react-button: Address polymorphic typings

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#14414]
We need to straighten out typings of Button and other components which use `as`. There is a way!

Expected:

```tsx
const props: ButtonProps = {
  as: 'a',
  href: 'url', // Good to go!
};

const props2: ButtonProps = {
  as: 'button',
  href: 'url', // Build error
};
```
Resulted:

Typings are loose right now, extending `React.AllHTMLAttributes`.

**Comment by dzearing** [comment]
I have this working, but if `as` is not specified, i haven't found a way to default to a particular assumption.

**Comment by joschect** [comment]
It is currently impossible to do this if `as` can be undefined. If `as` is non-optional then this will mostly work as intended. Here's a [typescript playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgILIN4ChnIG5wA2ArhAPwBcyA5AEaFwAW1A3DsgkYbYgNaXIAFAEoAvAD58Ae2AATNgF8sWUJFiIUAIUzsCJCFWowpU1uzgAFKFIAOVAM5gooAOaLlYAJ42Us4PYRnAFtkUWRtAB80NixCCDBkYykqPwDg0J1cS2s7GiTqABp2TkJuPioRUMkEKRB7KTiAOkIpFxEsBSA) that demonstrates how this works if `as` can be undefined in one of the interfaces. 

Additionally, here is an [issue](https://github.com/microsoft/TypeScript/issues/31404) in the typescript repo that indicates that this is likely a limitation of the language rather than something that can be fixed.

Recommendation, it is possible to make a `MutuallyExclusive` type that will ensure that a discriminated union is correct. There will need to be some work done to ensure that this works smoothly.

Here is a prototype that works, although it it is inefficient.
```
type MakeExclusive<T, K extends string> = {
  [P in Exclude<keyof T, K>]?: undefined;
};
```

**Comment by ecraig12345** [comment]
Do we still need this?

**Comment by khmakoto** [comment]
Folding into #16746.
