### ISSUE TITLE
Security issues with prism and markdown-to-jsx dependencies in @uifabric/example-app-base

### ISSUE THREAD

**Issue by christiango** [microsoft/fluentui#14453]
We now have 2 component governance alerts related to security issues with the dependencies of @uifabric/example-app-base:

These issues include:
* Prism 1.17.1 - pulled in via refractor v 2.10.1, which is a dependency of react-syntax-highlighter v10.3.5. Updating to react-syntax-highlighter 13.3.1 addresses this issue. [Advisory](https://github.com/PrismJS/prism/security/advisories/GHSA-wvhm-4hhf-97x9)
* markdown-to-jsx 6.6.1. Updating to 6.11.4 or later addresses this. [Advisory](https://github.com/probablyup/markdown-to-jsx/commit/226f133adaf91c228b91975b6a3dd2ad1ad489a6)

**Comment by khmakoto** [comment]
@christiango I have a PR out that updates the `markdown-to-jsx` package version. Regarding the `react-syntax-highlighter` package, we've chosen not to update it since it would lead to duplicated package versions due to the fact that it is also pulled from `@storybook/components`. We've chosen to do this given that we don't actively use `prism` which is the package that is triggering the vulnerability.

**Comment by christiango** [comment]
Thanks for the update!
