### ISSUE TITLE
Date Picker pop up-WCAG 4.1.1, WCAG 4.1.2: Ensures ARIA attributes are allowed for an element's role (button[aria-label="August\ 1\,\ 2020"]).

### ISSUE THREAD

**Issue by Payne-Yan** [microsoft/fluentui#14464]
### Environment Information

- **Package version(s)**: 7.115.1
- **Browser and OS versions**: Chrome Version 84.0.4147.105 (Official Build) (64-bit)

### Describe the issue:

 Ensures ARIA attributes are allowed for an element's role.

Element path
#button[aria-label="August\ 1\,\ 2020"]

Snippet

How to fix
Fix the following
- ARIA attributes are not allowed: aria-readonly="true", aria-selected="false"

#### Actual behavior:

ARIA attributes are not allowed for an element's role (button[aria-label="August\ 1\,\ 2020"]).

#### Expected behavior:

Ensures ARIA attributes are allowed for an element's role (button[aria-label="August\ 1\,\ 2020"]).

**Comment by Payne-Yan** [comment]
Repro-Detail
![image](https://user-images.githubusercontent.com/69501015/89877131-3cfcf200-dbf2-11ea-8543-5d399dc4769d.png)

**Comment by paulgildea** [comment]
@smhigley FYI

@lorejoh12 - I feel like this might be a dupe - not sure though.

**Comment by lorejoh12** [comment]
We have had a bunch of issues relating to similar discussions about what roles are appropriate for buttons in the grid, while still letting us get all the information across. #13919, #10793

This one is specifically complaining about roles aria-readonly (which is a new issue) and aria-selected (which is same as in 10793, and the fix made to resolve that seems to be what this bug is complaining about)

If we change the role back to gridcell, we'll have the same issues as before with not announcing button semantics. If we remove those two properties, then we're no longer announcing which day is selected. We might be able to get around it by making the aria-labels more verbose, but not sure if that's the best option here.

**Comment by Payne-Yan** [comment]
@lorejoh12 Regarding this issue, how are you going to fix it?

**Comment by Payne-Yan** [comment]
@lorejoh12 This issue hasn't been solved on the official website. Would you please solve it first?

**Comment by Payne-Yan** [comment]
@khmakoto @paulgildea This issue hasn't been solved on the official website. Would you please solve it first?

**Comment by v-ajrai** [comment]
I am also facing similar issue . Do we have any ETA around this??

**Comment by smhigley** [comment]
This is fixed in v8 :). Let me know if you still run into any issues after updating.

Quick note -- there will still be an aria-required-children automated error on the combobox itself, but that's a known false positive that already has an issue logged and fix in progress on the testing tool.

**Comment by smhigley** [comment]
Closing this as fixed
