### ISSUE TITLE
[Callout]  Decide whether to prevent dismiss on lost focus dynamically

### ISSUE THREAD

**Issue by lamha-lagoe** [microsoft/fluentui#14527]
#### Describe the feature that you would like added

Update `preventDismissOnLostFocus` in `Callout` to be a callback instead of a boolean. This would enable deciding per event whether we want to dismiss or not.

#### What component or utility would this be added to

`Callout` (in `ICalloutProps` in `Callout.types`)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

We are working on a functionality where we need to show a context menu on right click on a gallery. The gallery is built over `ContextualMenu` (which I understand is built over `Callout`). Since the gallery is configured to dismiss on losing focus, the moment we display the context menu, the gallery dismisses. The prop `preventDismissOnLostFocus` can be set to prevent dismissing it, but then it would not dismiss on losing focus in any case. What we need is sort of a middle ground where we can choose whether or not to dismiss depending on the event. (Like in this case, we want it to dismiss if user clicks outside the gallery, but not if they right click on the gallery and the focus shifts to context menu).
One possible suggestion that came from within our team was if `preventDismissOnLostFocus` is updated to be a callback instead of a boolean. Then looking at the event in the callback, we could decide whether or not to dismiss the gallery.

**Comment by paulgildea** [comment]
Thanks for the feedback @lamha-lagoe ! 

@joschect - Do you think this is something that could be added that's non-breaking to the API?

If it could - @lamha-lagoe would you be interested in making a contriubtion?

@JustSlone - FYI

**Comment by joschect** [comment]
@lamha-lagoe I think our naming isn't great because you can already accomplish this using the onDismiss callback that the callout provides. https://codepen.io/slimemold/pen/GRZZqeb?editors=0010 That codepen demonstrates how you can opt to not dismiss based on the dismiss callback. Really the onDismiss callback should be something `onDismissableEvent` or something along those lines.

**Comment by lamha-lagoe** [comment]
Thanks for the quick responses!
@joschect Thanks, I did try it out with onDismiss before, but unfortunately it can't help for all cases. Like in our case, the ContextualMenu itself is build by a BaseButton (in its `_onRenderMenu`), thus the onDismiss is set by BaseButton itself. While it still calls, `menuProps.onDismiss(ev)` to allow me to specify my own dismiss behavior, I'm not able to avoid dismissal using that - it seems Focus events are non-cancellable events, and thus even if I call `preventDefault()` on the event, it doesn't have an effect, and the `BaseButton` ends up hiding the menu (`this.setState({ menuHidden: true })`).
Since preventDismissOnLostFocus is the first point to see the focus event, and decide whether or not we want to dismiss, it seems like the right place to decide this. Please let me know if I'm misunderstanding something.

@paulgildea If we agree on making the change in the API, I'd be happy to contribute to the repository to update it!

**Comment by joschect** [comment]
@lamha-lagoe That's a good point. It's possible that BaseButton should allow for you to completely override the dismiss on callout. I'm a bit hesitant to have dismissOnFocusLost be more expansive when it might make more sense to have that same kind of behavior apply to all the potential dismiss events and not just dismissOnFocusLost. Since it seems like onDismiss won't work, maybe there should be another callback called what I suggested above, the `onDismissableEvent` that allows the consumer to decide if the event is actually dismissable, and then all of the other "preventDismissOnFocus" can be deprecated.
