### ISSUE TITLE
[Safari] Dropdown style issue after select item.

### ISSUE THREAD

**Issue by gpaniagua013** [microsoft/fluentui#14526]
### Environment Information

- **Package version(s)**: 7.128
- **Browser and OS versions**: Safari in Mac

#### Actual behavior:

After select an item on the drop-down, a blue line remains in the selected element.

*You can reproduce the issue in the Demo page.

![image](https://user-images.githubusercontent.com/7999793/90239199-75394600-de27-11ea-8f74-8013e4c0dffe.png)

#### Expected behavior:

No blue line should be there.

### Priorities

Requested priority: (Normal)

**Comment by YuanboXue-Amber** [comment]
Related to #12279, which is a similar issue, but on `input` element, while this issue is on `button`.
The merged fix is to use `outline: 'none'` instead of `outline: 0`, when styling `input` component.
I tried the similar fix on `button`, and it resolves this issue.

To remove this kind of issue for Safari once and for all, I purpose to use `outline: 'none'` [here](https://github.com/microsoft/fluentui/blob/a6337607bf1742ce64f73eb6ddb420960919bdb9/packages/fluentui/react-northstar/src/themes/teams/getBorderFocusStyles.ts#L61) in `getBorderFocusStyles` (I haven't test if it would break anything yet)

What still confuses me, is **why Safari behaves differently towards `outline:0` and `outline:'none'`**? 
It would be great if anyone knows and shares :)
