### ISSUE TITLE
Shimmer on grouped ShimmeredDetailsList does not disappear

### ISSUE THREAD

**Issue by alexlundborgopticon** [microsoft/fluentui#14556]
### Environment Information

- **Package version(s)**: 7.128.0

### Please provide a reproduction of the bug in a codepen:

[link to codepen](https://codepen.io/alexanderlundborgopticon/full/MWyeygX) (in full page view)
 
#### Actual behavior:

The shimmer remains although the interval delay (2500 ms) has passed. It disappears when the user scrolls or collapses and re-expands a group.

#### Expected behavior:

The table content should be displayed after the interval delay has passed.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by paulgildea** [comment]
Thanks for the feedback @alexlundborgopticon !

**Comment by paulgildea** [comment]
@alexlundborgopticon Are you seeing this behavior in all browsers?

**Comment by alexlundborgopticon** [comment]
I'm seeing it in the browsers I have tested: Chrome (version 84) on Windows and MacOS, Firefox (72) on MacOS and Safari (13) on MacOS.

**Comment by khmakoto** [comment]
Hi @alexlundborgopticon, I can confirm this is indeed happening. You'll notice, however, that after the time has passed they render if you interact with the `DetailsList` in any way. This happens because the outer `DetailsList` is being re-rendered, but the groups inside are not re-rendering. I don't think we'd fix this due to the complexity and dependencies of our List components, reason for why we are actively trying to minimize risk of regressions.

However, there is a workaround for this as can be seen in [this codepen](https://codepen.io/khmakoto/pen/LYNRBwz?editors=0010). Everything in here works as expected. The workaround is in line 92, where, on setting the new state, you trigger a change in the groups by doing `groups: [...groups]`. That in turns makes the groups re-render. Hopefully this helps with your issue!

**Comment by alexlundborgopticon** [comment]
Thank you, that helped! I'll go ahead and close the issue.
