### ISSUE TITLE
ChoiceGroup option unselectable if keyed as "constructor"

### ISSUE THREAD

**Issue by cchengt** [microsoft/fluentui#14591]
### Environment Information

- **Package version(s)**: 7.128.3
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/cchengts/pen/qBZNGBw?editable=true%3Dhttps%3A%2F%2Ffabricweb.z5.web.core.windows.net%2Foufr%2F7.128.3%2F

#### Actual behavior:

Option A is not selectable

#### Expected behavior:

Option A is selectable

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
ml.azure.com

**Comment by khmakoto** [comment]
Hi @cchengt, I think this might have something to do with React itself since we don't have any logic to handle that case specifically.

**Comment by cchengt** [comment]
Could somewhere be using {} as a dictionary for the options keys? {} contains "constructor" from Object.prototype.

**Comment by behowell** [comment]
Hi @cchengt, it looks like this issue has been fixed in the next release of `@fluentui/react`, version 8. See this CodeSandbox: https://codesandbox.io/s/issue-14591-repro-in-v7-vs-v8-gyy2o

Given that this should be relatively easy to work around in the meantime, by just not using `"constructor"` as a key, I'm going to close this issue. If this is blocking you, please re-open. Thanks.
