### ISSUE TITLE
Pivot's 'root' styles get applied to the Pivot links and not their root container

### ISSUE THREAD

**Issue by jayantdhawan** [microsoft/fluentui#14790]
### Environment Information

- **Package version(s)**: 7.105.12
- **Browser and OS versions**: Chrome, Edge Chromium

#### Actual behavior:
Styles in the 'root' object for IPivotStyles apply only on the Pivot Links. The Pivot component has a [`<div role="toolbar" {..divProps}>`](https://github.com/microsoft/fluentui/blob/ff8ef5b7d6b01e793c9fa99e20004330e5eb3f0a/packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx#L105) wrapper around Pivot Links and Items, that does not consume any of the styles passed to the component. 

#### Expected behavior:
From the description it sounds like the 'root' styles should apply to the root container of the Pivot component, that is the parent of the Pivot Links and the Pivot Items.

I was looking to apply a height of "100%" to the Pivot component using the 'root' styles, but it didn't work.

### Priorities and help requested:

Requested priority: Normal

**Comment by paulgildea** [comment]
@jayantdhawan Thanks for the feedback.

I'm inclined to mark this as by Design because if we were to change the style mappings at this point it would be a considerable breaking change.

@behowell / @khmakoto - Do you have any potential work arounds that would allow someone to target the parent container so that percentage based sizing could be preserved? Also if you think an additive API approach could work if we don't want to change the current mapping?

**Comment by jayantdhawan** [comment]
A work around I found was to wrap the `Pivot` component under another element, and use the child selector `> div` on the wrapping element to target the Pivot's root div. A change to the element structure in Pivot component might break this workaround.

**Comment by khmakoto** [comment]
Hey @jayantdhawan, thanks for filing this issue!

@paulgildea I think it's fair to mark this by design for now and take this into account as we move forward with our component revamps.

Another workaround is to pass a `className` to the `Pivot` with the styling as this will be passed as part of `divProps`. You can see an example of this in [this codepen](https://codepen.io/khmakoto/pen/OJNgNwq?editors=0110).
