### ISSUE TITLE
Shimmer width and height support em and rem

### ISSUE THREAD

**Issue by NewFuture** [microsoft/fluentui#14896]
#### Describe the feature that you would like added

The value of shimmer components only can be set a number (`px`);
How to set it with other units such as `rem`.
```jsx
<ShimmerLine width height={'20rem'} />
```

#### What component or utility would this be added to

`Shimmer `

**Comment by paulgildea** [comment]
@NewFuture Thanks for the feedback!

I’ll mark this as a feature request and add it to our backlog, but to set expectations - we’re likely not going to get to it for a while as we’re currently focused on larger coherence work items. We'll take this into consideration when we converge the `Shimmer` component across our two React packages.

@dzearing - Can this be achieved using styling rather than the `width` and `height` props?

**Comment by NewFuture** [comment]
@paulgildea  thanks

And it can be achieved using `styles` as a workaround.
