### ISSUE TITLE
Add componentRef property to Text componenet

### ISSUE THREAD

**Issue by alnasar** [microsoft/fluentui#14925]
#### Describe the feature that you would like added

add componenet Ref to the Text component

#### What component or utility would this be added to

Text https://developer.microsoft.com/en-us/fluentui#/controls/web/text#ITextProps

#### Additional context/screenshots

i want to be able to focus the text component that tell the user there is no data found for the search query (i know that there is search query error message , but i want the message to be render on other component).

**Comment by paulgildea** [comment]
@alnasar Thanks for the feedback.

@JustSlone / @ecraig12345 - Is this something that can be done additively for the current version?

**Comment by JustSlone** [comment]
We are working on refreshing and converging Text shortly, if this isn't urgent I'd rather address this as part of the update. 

@alnasar how urgent is this request in your mind? Is it blocking you in a major way?

**Comment by ecraig12345** [comment]
Text is typically not focusable, so I'm not sure that calling a focus method (if it was available) would do what you want. Also, even if we added a `componentRef` prop, that would expose a custom `IText` type (not a raw HTMLElement), and we wouldn't want to put a focus method on that interface for the aforementioned reason.

Once Text is converted to a function component (which could happen as part of version 8), you'll be able to pass `ref` to get the underlying HTMLElement. Text wasn't on our list of priority components to convert, since it doesn't have any strict mode violations, but we could do it anyway since the conversion would be very easy.
