### ISSUE TITLE
<SearchBox> inside <Sticky> does not work

### ISSUE THREAD

**Issue by asit-baran-das** [microsoft/fluentui#14948]
### Environment Information

- **Package version(s)**:  I am using "office-ui-fabric-core": "^11.0.0", "office-ui-fabric-react": "7.117.1",
- **Browser and OS versions**: Reproducible in both Edge and Chrome

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/asitbarandas/pen/jOqZJXd

#### Actual behavior:
[NOTE: this codepen is prepared by using "Export to codepen" option from [scrollablpane ](https://developer.microsoft.com/en-us/fluentui#/controls/web/scrollablepane)]

"SearchBox" outside "Sticky" works as expected(line no 48 in codepen). But if you copy "SearchBox" from line 48 to the line 51 in the codepen, the browser will hang. In local I am getting the below error in console - 

![image](https://user-images.githubusercontent.com/24957976/92574501-cb719b80-f2a4-11ea-8a10-75f9d8cef217.png)

#### Expected behavior:

"SearchBox" should work as usual inside "Sticky" as well

### Priorities and help requested:

Requested priority: High

**Comment by paulgildea** [comment]
@asit-baran-das Thanks for the feedback.

**Comment by asit-baran-das** [comment]
Hello team, can you please give us the ETA for the fix. We have a production launch in Sep last week. Is it possible to get it addressed by then?

**Comment by miroslavstastny** [comment]
Not sure that the error message is directly related to the issue.

Once I try to scroll the ScrollablePane, I see an infinite re-render loop of the `Sticky`:
![image](https://user-images.githubusercontent.com/9615899/92741712-2e376580-f37f-11ea-9ae0-72a22c64fa15.png)

[profiling-data.10-09-2020.15-58-18.json.zip](https://github.com/microsoft/fluentui/files/5202141/profiling-data.10-09-2020.15-58-18.json.zip)

This is probably caused by `Sticky._onScrollEvent` which calls `setState` which causes rerender which causes a scroll event?
