### ISSUE TITLE
Disabling tab on non interactive lists

### ISSUE THREAD

**Issue by abhishekpatwal** [microsoft/fluentui#14953]
### Environment Information

- **Package version(s)**:  7.134
- **Browser and OS versions**: Browser- Version 85.0.564.44 (Official build) (64-bit) & OS 19041.450

### Describe the issue:

Upon Tabbing through the DetailList component, the Tab passes through the first row in list. This is not needed if the rows are non interactive. As a result the tab resulting in the row selection is redundant, since no action can be performed on it.

### Please provide a reproduction of the issue in a codepen:
The mentioned behavior is reproducible in the documentation URL itself: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist . Try to navigate the list by tabbing through. The focus moves to the first row and then leaves the component. Since the row is non interactive, actions such as entering or pressing space will result in nothing. 

#### Actual behavior:

The DetailList allows tab to focus on first row despite the row being non interactive.

#### Expected behavior:

If the list is non interactive, the focus should not appear on them upon tabbing to the list.

**Comment by paulgildea** [comment]
@abhishekpatwal Thanks for the feedback.

My initial thought here is that this is by design and that the `DetailsList` doesn't special case tabbing for non-interactive/interactive content in the component itself. 

@dzearing - Thoughts on a workaround here? Can you manually set `tabIndex` to hop over the `DetailsList`

@betrue-final-final Any thoughts on the default tabbing behavior? I'm assuming it's by design?
