### ISSUE TITLE
Increase/decrease button cannot be triggered/clicked by automated js function.,

### ISSUE THREAD

**Issue by KeXu444** [microsoft/fluentui#14965]
### Environment Information

- **Package version(s)**: all
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:

increase/decrease button cannot be triggered by code, this makes e2e test be impossible.
https://codepen.io/x444/pen/YzqaVWB

#### Actual behavior:

The value in spin input does not change

#### Expected behavior:

Value should increase every 1 sec, since there is an "interval" to trigger button click every 1000ms.
increase/decrease button should be same as default button which is clickable in automated js

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: ml.azure.com

**Comment by paulgildea** [comment]
@KeXu444 Thanks for the feedback.

@khmakoto - Outside of automating actual clicks... is their a way to automate changing the value of the `SpinButton`?

**Comment by KeXu444** [comment]
Just found the up and down arrow in the value box does work.
It will be great to trigger button click as well to make sure that function is working.
All other office fabric component are working fine, just this 2 buttons not clickable in ui testing.

**Comment by miroslavstastny** [comment]
Spin input buttons does not change the value on `click` but on `mousedown`. The motivation for that is that when you press the button and keep it pressed, it should keep incrementing/decrementing as long as the button is pressed. This is intentional behavior.

As you've already found out, you can use keyboard to inc/dec the value, if you need to stick to mouse events, you can pass the `mousedown` event to the button:

```js
mouseDownEvent = document.createEvent ('MouseEvents');
mouseDownEvent.initEvent ('mousedown', true, true);
spinButtonElement.dispatchEvent(mouseDownEvent);
```
