### ISSUE TITLE
DetailList selection with sorting relies on special property in data model

### ISSUE THREAD

**Issue by Kelvinlinzer** [microsoft/fluentui#14986]
### Environment Information

- **Package version(s)**: 7.101.0
- **Browser and OS versions**: irrevelant

#### Actual behavior:

When the first rows is selected, do sorting. The first row is still selected. Actually, the content of first row has changed. Sample in code pen.

https://codepen.io/kelvinlinzer/pen/KKzoJEv

#### Expected behavior:

The selected row goes to the proper location, instead of the row number's not changing. Just as the following Codepen

https://codepen.io/kelvinlinzer/pen/qBZovGZ

The selection relies on special attribute 'key' in item, the only difference between the two code fragments are the name of the key attributes, the working one is key, while the failed one is dummyKey. Both of them have proper getKey function.

There is an [Pull Request](https://github.com/microsoft/fluentui/pull/9428) to address the DetailList example is not working. It does provided a working example, but this issue still remains.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by paulgildea** [comment]
@Kelvinlinzer Thanks for the feedback.

@dzearing Is this expected behavior of the API of the component?

**Comment by dzearing** [comment]
This is by design.

In the example where you have "dummyKey" on items, you're providing the `getKey` override on `DetailsList`, but you're also providing your own `Selection` instance, which means `DetailsList` does not own the selection object, and therefore can't pass along the `getKey` callback to it.

If you move the `getKey` call to the `Selection` options, this works. See here:

https://codepen.io/kelvinlinzer/pen/KKzoJEv?editors=0010
