### ISSUE TITLE
Background Panel captures foreground Modal input

### ISSUE THREAD

**Issue by agg23** [microsoft/fluentui#15025]
### Environment Information

- **Package version(s)**: `office-ui-fabric-react@7.137.1`
- **Browser and OS versions**: Firefox 80.0.1 and Chrome 85.0.4183.102

### Please provide a reproduction of the bug in a codepen:

The "Confirm light dismiss" example.
https://fabricweb.z5.web.core.windows.net/oufr/7.137.1/#/examples/panel

#### Actual behavior:

1. Click somewhere to perform a light dismiss of the Panel
2. Confirmation dialog will appear
3. Clicking anywhere on the page, including on the text of the confirmation dialog, will cause the Panel to close from behind the Dialog

#### Expected behavior:

The Panel stops receiving events until it becomes the foreground Layer.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by miroslavstastny** [comment]
Workaround #1 - only close the panel in `onDismiss` if the dismiss comes from a close button - see *Panel - Detect dismissal method* example for inspiration:
```jsx
const onDismiss = React.useCallback(
  (ev?: React.SyntheticEvent<HTMLElement>) => {
    if (!ev) {
      console.log('Panel dismissed.');
      return;
    }

    // eslint-disable-next-line deprecation/deprecation
    const srcElement = ev.nativeEvent.srcElement as Element | null;
    if (srcElement && srcElement.className.indexOf('ms-Button-icon') !== -1) {
      dismissPanel();
    }
  },
  [dismissPanel],
);
```

Workaround #2 - pass an empty callback as `onOuterClick` prop.

According to the comment in the example, when `onLightDismissClick` is set, `onDismiss` is supposed to be called only when dismiss button is clicked:
 
https://github.com/microsoft/fluentui/blob/a89efd72e645e6e20869d6f33717f11554a8711a/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.LightDismissCustom.Example.tsx#L44-L45

As described in the issue, the problem is that when the confirmation dialog is opened, clicks to that dialog and its overlay are considered outer clicks from the Panel's point of view and `_dismissOnOuterClick` calls the `onDismiss`.

I am not sure what the expected contract of `isBlocking`, `isLightDismiss` vs `onLightDismissClick`, `onDismiss` and `onOuterClick` is.
