### ISSUE TITLE
Command bar buttons that are disabled should not be focusable or tab accessible.

### ISSUE THREAD

**Issue by vivianysun** [microsoft/fluentui#15175]
### Environment Information

- **Package version(s)**: 7.131.0
- **Browser and OS versions**: Chrome/Firefox, Windows 10  

### Describe the issue:
Disabled buttons should not be focusable

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/vivianysun/pen/LYNMLVZ?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Ffluentui

#### Actual behavior:

Tab focus goes to first disabled button (New) in command bar. 

#### Expected behavior:
Disabled buttons should not be tab focusable, so tabbing should go to the second button (Upload). 

### Documentation describing expected behavior
https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html
"Focusable components need to receive focus in an order that preserves meaning and operability only when navigation sequences affect meaning and operability."

https://usability.yale.edu/web-accessibility/articles/focus-keyboard-operability
> Understanding Focus
> When an HTML element is able to handle keyboard input, it is said to have focus. Exactly one element is able to have focus in a > time. In most browsers, users can move focus by pressing the Tab key and the Shift + Tab keys.

> The following elements can receive focus:
> * <a> tags with an href attribute
> * Form controls and buttons (unless the element is disabled)
> * Any element with a tabindex.

**Comment by paulgildea** [comment]
@vivianysun Thank you for the feedback.

@smhigley / @dzearing / @JustSlone - I feel like this might be by design, I thought I remember that we've gotten conflicting feedback on where folks want `Commandbar Buttons` that are disabled to be keyboard focusable so that screen readers will announce them, but will announce that they are disabled for discoverability reasons.  Do folks remember the final outcome of this discussion?

@miroslavstastny I'm going to mark this as a question for now, until we get decision and determine that this is an issue.

**Comment by dzearing** [comment]
By design currently; it is not an accessibility issue that it receives focus on disabled (it is an a11y issue if an interactive element is not focusable.) The background: Office a11y experts at the time of the decision (years ago) felt that it would be a better screenreader experience if blind users didn't have to turn on scan mode to know that a ribbon button was there but disabled.

In the new button, we've resolved buttons to not be focusable by default. We may add a way to opt into supporting disabled focusable buttons specifically for edge cases like ribbon where disabled buttons are used frequently, but it shouldn't really be the default as it is not consistent with web browser defaults or any other framework, and that violates expecations.

**Comment by dzearing** [comment]
Unless there are further questions, there's no action to take here.

**Comment by vivianysun** [comment]
Thanks for the speedy responses. I would love to see this incorporated in v8 if it will be available for buttons.

**Comment by paulgildea** [comment]
@vivianysun I'm working with folks to try and get a public version of our rough sequence of components we'll be converging so folks can get an idea of when things will be addressed.
