### ISSUE TITLE
Icon elements is not displayed using SPFx in Teams tab

### ISSUE THREAD

**Issue by karamem0** [microsoft/fluentui#15188]
### Environment Information

- **Package version(s)**: 7.139.1
- **Browser and OS versions**: Chrome and Mac OS Catalina 10.15.6

#### Actual behavior:

When I built SharePoint Framework web part and added in Microsoft Teams tab, There is no icon displayed even though using Icon elements.

#### Expected behavior:

For example, `<Icon iconName="Add" />` will be `+`.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@karamem0 Thanks for the feedback. This might be a difficult for us to look into because it needs to be hosted with in a Teams Tab. But if you could point us to a live codepen that would be super helpful.

One suggestion to try in the meantime is to add a call to `initializeIcons()` before rendering your UI. My hypothesis is that SPFx might call that on your behalf where a Teams Tab does not. 

Let us know if you can provide a codepen or try out that suggestion.

Thanks!

**Comment by karamem0** [comment]
@paulgildea Thanks for the idea, I was able to fix the problem by calling `initializeIcons()`.
