### ISSUE TITLE
Container/page scrolling issue with Slider web component on touch devices

### ISSUE THREAD

**Issue by wnbittle** [microsoft/fluentui#15247]
### Environment Information

- **Package version(s)**: 7.138.0 Web
- **Browser and OS versions**: Chrome 85.0.4183.121, Windows 10

### Please provide a reproduction of the bug in a codepen:

No codepen required, see the demo here: https://developer.microsoft.com/en-us/fluentui#/controls/web/slider
Enable device emulation and emulate a touch device like iPad
Attempt to touch-drag the slider thumb of an enabled Vertical slider

#### Actual behavior:

The scrollable area the slider is in moves up and down with the thumb movement

#### Expected behavior:

Only the thumb would move

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, but would have no idea where to start.  I'm assuming the touch event isn't being consumed when the thumb detects the touch.

Requested priority: Normal - will use an alternate control in the meantime for touch enabled devices

Products/sites affected: N/A

**Comment by paulgildea** [comment]
@wnbittle Thanks for the issue and thanks for the offer to fix. We'll try to reduce it down to the solution and if we think it's straightforward enough we can help you submit a PR.

**Comment by miroslavstastny** [comment]
The root cause of the issue is that `Slider` fails to prevent default on `touchmove` event.

Move handler is supposed to prevent default:
https://github.com/microsoft/fluentui/blob/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx#L275-L278

But it fails because the event listener is registered as passive: 
https://github.com/microsoft/fluentui/blob/7fc8435387fa90c21cdc396b41ed43f6f9e7979b/packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx#L230

Changing the options to `{ capture: true, passive: false }` fixes the issue.

**Comment by miroslavstastny** [comment]
FYI @joschect
