### ISSUE TITLE
Ensures ARIA attributes are allowed for an element's role in DatePicker

### ISSUE THREAD

**Issue by belozerovany** [microsoft/fluentui#15332]
### Environment Information

- **Package version(s)**: (7.0.1))
- **Browser and OS versions**: (all)

### Describe the issue:
When we testing with [Accessibility Insights for Web](https://accessibilityinsights.io/docs/en/web/overview/) In DatePicker control find Accessibility error with aria-label attributes. Please check. https://prnt.sc/uratix
Issue: Ensures ARIA attributes are allowed for an element's role (aria-allowed-attr - https://dequeuniversity.com/rules/axe/4.0/aria-allowed-attr?application=msftAI)
How to fix:
Fix any of the following:
ARIA attributes are not allowed: aria-readonly="true", aria-selected="false"

You may reproduce this error in mode "debug"
https://prnt.sc/urbk8w

Also this bug we may reproduce on the official site Ui Fabric

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/belozerovany/pen/LYNKyGy

#### Actual behavior:
Ensures ARIA attributes are allowed for an element's role (button[aria-label="September\ 5\,\ 2020"])

#### Expected behavior:
After checking with Accessibility Insights for Web we should not get an  Accessibility errors

### Documentation describing expected behavior
Are you willing to submit a PR to fix? No
Requested priority: High
Products/sites affected: Products

**Comment by paulgildea** [comment]
@belozerovany Thanks for the issue.

@smhigley FYI on the pattern

@lorejoh12 FYI on the issue - not sure if you've seen this one before.

**Comment by musema** [comment]
We are also facing this issue in both `DatePicker` and `Calendar` components

**Comment by yanbxice** [comment]
Is there a fix for this? I'm seeing the same issue in `Calendar` as well.

**Comment by smhigley** [comment]
This gets down to a fundamental grid problem of whether to put focus on grid cells where those attributes are valid, but there's less information about what type of control it is, or an interactive element within them (button in this case), which has benefits for high contrast mode, usability in virtual cursor, and potentially voice control.

We could revisit that choice in the future, and see if putting focus on buttons rather than gridcells is still a good choice. In the short term, we can also remove `aria-readonly` on the buttons, and look into using `aria-current="date"` or `aria-pressed` rather than `aria-selected`. There are some problems with each of those -- I think `aria-current` is already used to indicate "today" on the calendar which is more what it's for, and toggle buttons aren't really the right fit for selection within a group. I'm not currently thinking of a better solution, though.

**Comment by yanbxice** [comment]
@smhigley was this fixed in a recent release? I couldn't repro it in https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar.

**Comment by smhigley** [comment]
Yes, in v8 the calendar was updated to have the focusable role be gridcell rather than button. I'll close this issue as fixed since the automated error is resolved. If you have any feedback relevant to gridcell vs. button focus in calendars for future versions, please let us know!
