### ISSUE TITLE
Pivot: handle either enum or string values (deprecate the enum)

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15384]
Previously in `IPivotProps` we had `linkSize` and `linkFormat` defined using the `PivotLinkFormat` and `PivotLinkSize` numeric-valued enums. But now they're defined as string unions, which is a breaking change (though probably the direction we want long-term).

Since we didn't really provide any warning for this breaking change, if possible we should update Pivot to internally handle both for this release. Typings and docs would be like this.

```ts
  /**
   * Link size. Use the strings `'normal'` or `'large'`; the `PivotLinkSize` enum is deprecated
   * and will be removed in a future release.
   */
  linkSize?: PivotLinkSizeType | PivotLinkSize;

  /**
   * Link format. Use the strings `'links'` or `'tabs'`; the `PivotLinkFormat` enum is deprecated
   * and will be removed in a future release.
   */
  linkFormat?: PivotLinkFormatType | PivotLinkFormat;
```

**Comment by behowell** [comment]
@ecraig12345 This was not a breaking change because the values of the enum were changed to be the same strings. It works fine to write either `linkSize="large"` or `linkSize={PivotLinkSize.large}` (the latter evaluates to the string "large"). See the usage of the PivotLinkSize enum in [apps/vr-tests/src/stories/Pivot.stories.tsx](https://github.com/microsoft/fluentui/blob/cbc0b9a2f9b569eeabd7bba3812002edcca948e8/apps/vr-tests/src/stories/Pivot.stories.tsx)
