### ISSUE TITLE
Not able to change the slider values with the keyboard while using Windows Narrator

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#15420]
### Environment Information

- **Package version(s)**:  7.142.0
- **Browser and OS versions**: Edge 85.0.564.70, Windows 10.0.19041

### Describe the issue:

I'm not able to change the slider values with the keyboard when Windows Narrator is running.

#### Actual behavior:

Turn on Windows Narrator.
Use the keyboard to navigate to the slider.
Notice that arrow keys do not change the value of the slider.

#### Expected behavior:

I wish I could modify the value of the slider with my keyboard while I've got the narrator on.

**Comment by mltejera** [comment]
Note that I don't have the same issue with NVDA... the issue is likely with the built in Windows Narrator.

**Comment by paulgildea** [comment]
@mltejera Thanks for the issue.

@smhigley FYI

@tomi-msft Try to determine if it's an issue on our end or if this is something specific to Narrator.

**Comment by smhigley** [comment]
@mltejera this happens when Narrator is in scan mode (and the same thing occurs in NVDA in browse mode). In scan/browse mode, all key presses are handled first by the screen reader and used to navigate, then conditionally passed through to the DOM. This is why screen readers generally need to be in forms/app mode to change the value of controls like text inputs, comboboxes, and range inputs.

I have noticed that Narrator hasn't been auto-switching between modes at all for me lately, which is a bit odd. The reason you didn't notice it in NVDA is you likely have auto-mode-switching on, and NVDA automatically changes to the correct mode when you tab into something like a range input (you should hear something that sounds like an electronic click when it does this).

That's not an issue with the control though, that's a part of general screen reader UX on Windows screen readers, and something actual Narrator users would likely be familiar with.

**Comment by brandonthomas** [comment]
I just looked at this again @smhigley and native sliders work appropriately with Narrator in scan mode (left and right increment and decrement). One way I've fixed these types of issues in the past is to render a native input control and only use supplemental DOM to show visuals. The interaction is purely native as far as AT can tell though. 

I'm curious if rebuilding with <input type="range"/> would help here. It would also significantly reduce the amount of event handler code Fluent would have to carry.
