### ISSUE TITLE
Unclear wording for the Fabric/Fluent UI Assets license

### ISSUE THREAD

**Issue by MJomaa** [microsoft/fluentui#15470]
**Introduction**
We have an asp.net web application that leverages some Azure APIs (especially cognitive services) and we would like to use the Segoe UI icon font.

**Problem**
Looking at
https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_nov_2019.pdf

the wording is a bit unclear. We fulfil point 1a but not 1b.
![image](https://user-images.githubusercontent.com/9029497/95762305-d0fc4000-0cad-11eb-929b-f9bccf0c96a7.png)

**Questions**
- Do we need to fulfil both points (1a and 1b) or just one of them?
- Can we use the Segoe UI icon font outside Fluent UI (i. e. Bootstrap)?

Kind Regards

Mahmut Jomaa

**Comment by paulgildea** [comment]
@MJomaa Thanks for filing this issue. We know this is a point of confusion with customers.

Currently we are working to separate out the icons set into an open source licensed solution. 

I don't have any specific timelines on when it will be available but it is on our [quarterly objectives](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-OKRs-Q4-2020) for this quarter

**Comment by MJomaa** [comment]
@paulgildea Thanks for the quick response, Paul. Well this would be awesome :)

We can work with almost any point in the current license except we don't know if you need to fulfil 1a AND 1b. Could you give me a feedback on this real quick? Then I can close this issue.

**Comment by paulgildea** [comment]
I apologize for the unclear wording. We know this is frustrating for folks and we're working on it to essentially divide out and open source the icons from the brand icons. 

Since the license is mostly in place to protect the branded icons (again I'm not a lawyer), if your application is mostly leveraging icons like checkboxes, plus signs, etc. it should be  good to use.

Since you are leveraging ASP.NET / Azure APIs I would assume it meets those points. 

Thanks for enduring through this with us - the team is working to try and make this more clear by making icons open source so that there is no license ambiguity. It's just taking time.

**Comment by MJomaa** [comment]
@paulgildea Sorry for the late response. Ty very much, I close this issue 👍
