### ISSUE TITLE
Can't finger pinch-to-zoom in / out the iPhone screen when Fluent UI Dialog is open

### ISSUE THREAD

**Issue by sergul** [microsoft/fluentui#15477]
### Environment Information

- **Package version(s)**: (7.123.1)
- **Browser and OS versions**: (Safari and iOS 14.0.1)

### Describe the issue:

I'm unable to zoom in / out the iPhone screen with two fingers pinch when a Fluent UI Dialog is open.

### Please provide a reproduction of the issue in a codepen:

1. Go to https://codepen.io/sergulo/pen/MWeaWNg in Safari browser
2. Click on "Open Dialog" button to open the Dialog
3. Put 2 fingers on the Dialog area of the screen and try to zoom in / out the screen by moving the fingers

#### Actual behavior:

The iPhone screen is not being zoomed in / out by 2 finger pinch when a Fluent UI Dialog is open

#### Expected behavior:

The iPhone screen should be zoomed in / out by 2 finger pinch when a Fluent UI Dialog is open

**Comment by mimi-msft** [comment]
Hey @paulgildea / @joschect - can you give an update on this? The current behavior is breaking one of our experiences. Will you be fixing this or is it by design?

(If it is by design, I'd love to know the reasoning behind it; we are hoping to allow pinch zoom to facilitate better readability/accessibility)

**Comment by joschect** [comment]
@mimi-msft I believe that this is working as intended for right now. There was work done to prevent IOS from scrolling which blocks a lot of touch features. As a work around, a prop was added to enable it. You can see how it works appropriately in this [codepen](https://codepen.io/slimemold/pen/gOMvovM?editors=0010)

**Comment by sergul** [comment]
Worked for me too. Thanks for the help @joschect

**Comment by joschect** [comment]
@sergul That is likely, the body scroll and the way that it works depends on what environment that it's in. Most likely the effects that body scroll will have won't be a huge impact, but it can impact the behavior of an app. I'd recommend doing a little bit of testing because the effects could be minimal enough that you don't need to worry about adding a check!

**Comment by sergul** [comment]
OK @joschect thanks.
