### ISSUE TITLE
DetailsList shows up random blank spaces in between list items

### ISSUE THREAD

**Issue by Ganeshrockz** [microsoft/fluentui#15527]
### Environment Information

- **Package version(s)**: 5.112.1050
- **Browser and OS versions**: Chrome Version 86.0.4240.75 (Official Build) (64-bit) and Windows 10

#### Actual behavior:
We are using **DetailsList** in one of our UI flows. In case of a huge list we see a blank div of a certain height that gets generated in the DOM like this

![image](https://user-images.githubusercontent.com/17287148/96120201-c808aa00-0f0b-11eb-934a-148afba3cdbe.png)

I went through some similar issues and I see that this is by design to allow scrolling on a virtualized list. We tried setting up the `onShouldVirtualize` prop to `false`. This works fine for smaller list but the browser starts slowing down when the list size starts growing up. Also a browser resize shows up some hidden content and the blank div starts appearing below that. Is there a way to circumvent the issue

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable) Azure Devops

**Comment by paulgildea** [comment]
@Ganeshrockz Thanks for filing this issue.

@dzearing Is this related to #15492 ?

**Comment by paulgildea** [comment]
@tomi-msft If this is indeed a duplicate feel free to resolve.

**Comment by dzearing** [comment]
If there is a repo you can set up in codesandbox, that would help. Otherwise, there are too many factors external to the list that can cause this.

For example, if you are hosting the list in a scrollable div, the list needs to be able to identify it as a scrollable so that it can attach event handlers to the appropriate layer. You will need to make sure that `data-is-scrollable="true"` is set on that div.

If that's already the case and this is happening sporadically, it might be because the sizes of the items are changing dynamically.

It could be something with the styling that causes it.

So if you have a repro, we will better be able to help.

**Comment by Ganeshrockz** [comment]
Had a discussion offline with the FluentUI team and the suggestion is to upgrade the Fabric version.

**Comment by mahesh-shinde-13** [comment]
I also faced this issue when items are huge.

![image](https://user-images.githubusercontent.com/74227921/102776902-930a4f00-43b5-11eb-98eb-ebc3386a067e.png)

**Comment by Martype** [comment]
@Ganeshrockz @mahesh-shinde-13 I just saw you have the same problem as I had. I found a solution for it: https://github.com/microsoft/fluentui/issues/16178#issuecomment-756913742

**Comment by Ganeshrockz** [comment]
This was caused by the improper placing of divs causing the underlying DetailsList not listening to the parent div's scroll event. Modifying the div's position and assigning the `data-is-scrollable` property solved the issue.
