### ISSUE TITLE
Calendar days are un-focusable when rendered as a custom submenu in contextual menus

### ISSUE THREAD

**Issue by andrewhwng** [microsoft/fluentui#15635]
### Environment Information

- **Package version(s)**: 7.147
- **Browser and OS versions**: Chrome - Windows 10 19042.572

### Describe the issue:

In contextual menu component, inaccessible focus behavior with contextual menus and calendars. When rendering a fabric calendar component (either from the date-time package or the normal fluent-ui package) inside a custom submenu, users cannot focus on the days, only the month header, navigation arrows, and the go-to-today button. Only way to access the dates is to press the 'Go to today' button and focus will automatically shift to the days.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/anhw/pen/NWrbbpB

#### Actual behavior:

Cannot access days via keyboard.

#### Expected behavior:

Press tab to navigate through controls, with one of the tab stops stopping on the day rows inside the calendar.

**Comment by paulgildea** [comment]
@andrewhwng Thanks for the feedback!

**Comment by paulgildea** [comment]
@lorejoh12 FYI

**Comment by tomi-msft** [comment]
Hello @andrewhwng, thanks for filing the issue! This is probably due to some FocusZone shenanigans in ContextualMenu that prevents focus from going into the Calendar component. You can declare your own onRender function for the Calendar component as a workaround, and it should allow you to bypass the focusing issue. Here is a codepen for reference:  https://codepen.io/slimemold/pen/PozjBqb?editors=0010
