### ISSUE TITLE
Unable to get ref to DOM element from Link

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#15688]
### Environment Information

- **Package version(s)**: 7.147.0
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/brandonthomas/pen/gOMgXGB

#### Actual behavior:
Ref is only to the LinkBase component are coming back through either ref or componentRef

#### Expected behavior:
I am able to, through some API, get the underlying DOM refs.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not at the moment

Requested priority: (Blocking, High, Normal, Low): normal

**Comment by paulgildea** [comment]
@brandonthomas Thanks for the heads up!

@tomi-msft Feel free to coordinate with @brandonthomas on the specific case or if there is a workaround.

**Comment by brandonthomas** [comment]
Any update here?

**Comment by layershifter** [comment]
### OUFR v7 / Fluent v7

According to [React Guidelines](https://github.com/microsoft/fluentui/wiki/React-Guidelines#ref-usage) the right way is to use `componentRef`, it matches `ILink` type and provides `.focus()` method:

https://github.com/microsoft/fluentui/blob/7.0/packages/office-ui-fabric-react/src/components/Link/Link.types.ts#L11-L14

`componentRef` & `ref` are the same in this case only because `Link` is built with React's class component. The single workaround to get a DOM node is to use deprecated [`findDOMNode`](https://reactjs.org/docs/react-dom.html#finddomnode).

### Fluent v8

In v8 (still in beta 💣 ) [we're using `React.forwardRef()`](https://github.com/microsoft/fluentui/wiki/Version-8%3A-Migration-guide#ref-returns-a-dom-element-not-class-instance) there now, so you will get a ref to DOM node. I created a CodeSandbox to show it:
https://codesandbox.io/s/festive-diffie-9hgh2?file=/src/index.js

**Comment by ecraig12345** [comment]
I'm closing this as fixed because as @layershifter noted, it's fixed in version 8. If you absolutely need it sooner than then, let us know and there's another approach we've taken with some components which we could consider here.
