### ISSUE TITLE
Update getting started guide and templates

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#15776]
Our getting started docs are super out of date (still "fabric" everywhere) and I'm not sure the tech being recommended is even the current thing to recommend.

- [x] Update `@fluentui/react` (and repo?) readme to use new CRA template
  - [x] ensure it's installing 8
- [x] Remove outdated templates from website (7 and master)
- [ ] Archive outdated template repos
- [x] Update current templates to install/reference `@fluentui/react` not OUFR (Ken is the point of contact/approver for most of these still)
  - [ ] Track down and update, deprecate, or remove old templates
- [x] Update the wiki
- [ ] Update the website getting started page (7.0)
- [x] Update the website getting started page (master)

Website (live version): https://developer.microsoft.com/en-us/fluentui#/get-started/web

Wiki page: https://github.com/microsoft/fluentui/wiki/Getting-Started-with-UI-Fabric

**Comment by jeffmcaffer** [comment]
This issue is great, very much needed. Given all the changes that have happened lately, it is currently very hard for folks to get started. Neither of the paths outlined in the Getting started guide work for users. 

Stepping back a bit, I spent ~5 hours trying to get a basic app (beyond the example but not radical) working and was unable. Too many places mix the old and new and cross metaphors (Core vs React). It would be super useful to have a somewhat less trivial example that had some styling, some layout used a few standard components, and a few custom components. In the end that will give folk 90% of what they need. Header, footer, nav and some content.

Any pointers to such an example?
