### ISSUE TITLE
Can comboboxes on mobile browsers automatically open when they have focus?

### ISSUE THREAD

**Issue by sarahkang58** [microsoft/fluentui#15779]
# Environment Information

- **Package version(s)**: v7
- **Browser and OS versions**: Mobile Chrome and Safari browsers on Android and iOS

### Describe the issue:

We have a combobox with openOnKeyboardFocus set to True.  So when the user tabs to the combobox or clicks on the text field on web browsers, the dropdown automatically opens up with the options.  However, on mobile browsers, when we tap on the combobox (the text field, not the caret button), the dropdown does not open up.  Is this by design?

We noticed that this also happens on the mobile FluentUI site with the sample comboboxes.

**Comment by paulgildea** [comment]
@sarahkang58 Thanks for filing this issue.

I would say that currently this is by design. While not ideal, the intended behavior is to allow freeform text input for `ComboBox` in most desktop situations.

@joschect Is it possible to listen to `onFocus` events and manually open the `ContextualMenu` as a workaround in the mean time.

It's unclear to me if you can differentiate between a tap and the keyboard showing up on screen "like it was a keyboardFocus"

@tomi-msft If the work around is straight forward please mark as by design for now.

**Comment by joschect** [comment]
@sarahkang58 Could you confirm that this is still happening? It definitely should be opening when it gets focus. I see that it appears to open when I use Safari mobile. I wonder if something else is going on and the menu is dismissing too aggressively.

**Comment by sarahkang58** [comment]
@joschect Now that i looked more closely, the menu seems to flicker, so it might be dismissing aggressively as you said (this is on Safari mobile as well).

I also noticed that the first time I tap on the white input space, the text is highlighted and the keyboard drawer comes up, but the menu doesn't open or it flickers.  Tapping on the white input space a second time though will successfully open the menu.
