### ISSUE TITLE
Details list with resizable columns does not allow resizing of columns over horizontal width

### ISSUE THREAD

**Issue by Parth-Rathore** [microsoft/fluentui#15786]
### Environment Information

- **Package version(s)**: 7.149.0
- **Browser and OS versions**: Microsoft Edge (Chromium) 86.0.622.56, Windows 10 20H2 Build 19042.572

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/itsparth/pen/KKMdqXx

#### Actual behavior:
With Details list with many columns leading to horizontal scroll, setting the constraint mode to unconstrained, the isResizable property doesn't seem to work as expected. Only the first column is re-sizable, rest all columns are not resizing.
In the codepen, only column 1 have width resizable, rest columns don't resize

#### Expected behavior:

All columns should be resizable to any width as was in fluent ui version 7.128.0

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)

**Comment by paulgildea** [comment]
@Parth-Rathore Thanks for filing this issue!

@tomi-msft Try to see if you can track down if there was a PR that may have introduced this regression.

**Comment by ThomasMichon** [comment]
In the linked codepen, there are a couple of bugs:

1. Every `IColumn` you pass into the `columns` prop must have a unique `key` value. Otherwise, the state stored for a column might accidentally get applied to other columns, causing visual glitches.
2. You have `layoutMode` and `contrainMode` conflated. You need to fix your render of `DetailsList` to do this:
```tsx
        <DetailsList
              items={['','','','','','','','','','','','','','','','']}
              columns={columns}
              selectionMode={SelectionMode.none}
              layoutMode={DetailsListLayoutMode.fixedColumns}
              constrainMode={ConstrainMode.unconstrained}
              isHeaderVisible={true}
            />
```
What was happening is that `DetailsListLayoutMode.unconstrained` was evaluating to `undefined`, leaving you with the default settings of `DetailsList`, which is 'justified' columns and 'constrained' scrolling. The issue was that since all of your columns have a `minWidth` of `100`, it's not possible to actually fit them all in. But there's also no room to allow resizing to make columns larger.

**Comment by tomi-msft** [comment]
Here is a codepen with resize working for reference: https://codepen.io/tomi-msft/pen/VwjBNEx

**Comment by Parth-Rathore** [comment]
Hi @ThomasMichon. thanks for the solution. Thanks @tomi-msft for the codepen. I was able to successfully resolve issue :).
