### ISSUE TITLE
ComboBox custom input onChange handler

### ISSUE THREAD

**Issue by VerHext** [microsoft/fluentui#15827]
### Environment Information

- **Package version(s)**: 7.145.0
- **Browser and OS versions**: Edge (chromium) on Linux ubuntu 18.04

#### Actual behavior:
I not been able to insert my own text, after insert and press enter the text disappears. The option selection works without problems. This appears only when I implement the onChange handler.

#### Expected behavior:

Actually I expect a result like in microft teams (combobox calendar -> time) or the time settings in outlook online. But I couldn't find a working solution to save user defined entries and dropdowns.

**Comment by paulgildea** [comment]
@VerHext Thanks for submitting this issue.

First thank you for providing a codepen that is super helpful for us to iterate on. Could you provide a little more detail on what your expected outcome to be when you provide your own `onChange` handler? Sounds like you can provide a handler right?

@behowell Please coordinate once we get a little info on desired outcome for this isuse.

**Comment by DRamalho92** [comment]
Go the exact same problem.
The expected outcome of this scenario would be that the text that we put on the ComboBox would show on the ComboBox. However, the value disappears if that value doesn't belong to the options available on the dropdowns of the ComboBox.

**Comment by JustSlone** [comment]
after a little digging this looks like what might be happening.
 
The use of onChange causes ComboBox to behave as a controlled component. This means it's expecting another component (usually it's parent) to store/control the current value. This effectively disables the "allowFreeForm" behavior where new options can be added to the list, since onChange sets up combobox to expect a parent to control the list through the use of the options prop, allowFreeForm does nothing. 
 
Here's the line of code that controls the behavior: https://github.com/microsoft/fluentui/blob/0ecf05881398b6b72c20a20e1cd905a17f057fba/packages/react/src/components/ComboBox/ComboBox.tsx#L1173
