### ISSUE TITLE
[DatePicker][ScreenReader]: Activating ScreenReader alters the behavior of arrow key navigation in date pickers

### ISSUE THREAD

**Issue by stupparde** [microsoft/fluentui#15859]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Edge Beta, OS version 10.0.19042

### Describe the issue:

Narrator seems to be changing the behavior by which arrow key presses are used to move the focus within the date picker control.

1. Navigate to the sample date picker here: https://codepen.io/Stuppard/pen/yLJxPyp?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

2. Open the date picker and navigate through the dates using the arrow keys. This should work as expected, with the focus moving according to the arrow key inputs.

3. Turn on Narrator and try navigating through the dates again using the arrow keys.

4. The behavior of arrow key presses is clearly altered - sometimes an input key needs to be pressed twice, and sometimes the input direction does not correspond to where the focus moves

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/Stuppard/pen/yLJxPyp?editable=true%3Dhttps%3A%2F%2Fdeveloper.microsoft.com%2F

#### Actual behavior:

When Narrator is on, the arrow key inputs do not always correspond to the manner in which the focus moves through the dates in the date picker

#### Expected behavior:

Arrow key inputs correspond to the direction the focus moves, even with Narrator on

### Documentation describing expected behavior

https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7bb24201d1-2276-4471-8183-e1e5353031ad%7d

**Comment by paulgildea** [comment]
@stupparde Thanks for filing this issue. We'll take a look.

@lorejoh12 / @smhigley FYI.

**Comment by smhigley** [comment]
@stupparde this is what happens when using Narrator's scan mode, where keyboard interactions are captured and handled by Narrator itself, in order to provide a rich interface for interacting with UI. If you switch to Narrator's app mode (which is the expected mode to interact with form fields like comboboxes, radios. etc.), keyboard commands will be passed through to the page, and you'll see arrow key behavior work as you're expecting.

You can also use Narrator's table commands in scan mode to move through the date grid, which is also a helpful way for screen reader users to navigate the DatePicker.

Léonie Watson has a good article on screen reader interaction modes that might help go over the difference in more depth: https://tink.uk/understanding-screen-reader-interaction-modes/
