### ISSUE TITLE
Can't select dropdown option when using browser translation

### ISSUE THREAD

**Issue by linrosales** [microsoft/fluentui#15930]
### Environment Information

- **Package version(s)**: 7.142.1
- **Browser and OS versions**: Chrome 86.0.4240.75

### Please provide a reproduction of the bug in a codepen:
I can't put this in codepen because it is a browser setting.

#### Actual behavior:

For Fluent UI Dropdown element, if you have the browser translator on, the options you select, don't show up as the title. To the user, it looks like the selection did not happen even though the selections happens successfully in the code. 

#### Expected behavior:

Title should update in the dropdown even if the translator is on.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: clarity.microsoft.com an any other website using fluent ui's dropdowns (https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown)

**Comment by paulgildea** [comment]
@linrosales Thanks for filing an issue. Can you clarify the repo steps for this issue or provide a short video/image of the issue that you are specifically seeing? That would help us try to reproduce this issue. Thanks!

@behowell Not sure if you can make progress turning on the browser translation tool on the website - but I'm still not sure what title is supposed to update.

**Comment by linrosales** [comment]
@paulgildea Thanks for your answer! I am attaching a video with the current behavior, let me know if this works for you. 
[Home - Fluent UI - Google Chrome 2020-11-13 09-09-57.zip](https://github.com/microsoft/fluentui/files/5538402/Home.-.Fluent.UI.-.Google.Chrome.2020-11-13.09-09-57.zip)

**Comment by behowell** [comment]
This appears to be a bug/incompatibility between React and Chrome's translate feature. The dropdown's value is rendered inside a React fragment, like `<>{displayTxt}</>`. I'm guessing that the problem is that Chrome changed the text in the DOM, and React can't find the text to replace when the fragment's value changes.

Here's a sample CodeSandbox that doesn't use fluentui: https://2mfxy.csb.app/ (open in Chrome and translate to Spanish)

CodeSandbox code is here: https://codesandbox.io/s/cool-bash-2mfxy
