### ISSUE TITLE
Add CDN to download icons from government clouds

### ISSUE THREAD

**Issue by izikl** [microsoft/fluentui#15932]
#### Describe the feature that you would like added
Many services in Microsoft will need to be exposed in government clouds (Fairfax, USSec, USNat). 
Today Icons used by Fluent UI are download from Akamai CDN (For example: https://spoprod-a.akamaihd.net/files/fabric/assets/icons/fabric-icons-1-4d521695.woff) which is not exposed from those clouds.

Instead of having every service in Microsoft that is deployed on those clouds to implement their own CDN, it can be useful if Fluent UI can expose a CDN for icons on those clouds (same as in public clouds)

#### What component or utility would this be added to

None.

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

console error when failing to fetch icon from Akamai CDN:  
![image](https://user-images.githubusercontent.com/8294298/99011423-efe63000-2500-11eb-97e8-868bab4caa3d.png)

**Comment by paulgildea** [comment]
@izikl Thanks for filing this issue. 

@JustSlone / @dzearing  FYI

Our icon approach is moving more to an SVG icons that are bundled to service and are depending less on font based icons. I'll mark this as a feature request for now and follow up.

Thanks!

**Comment by TheInvoker** [comment]
@paulgildea Do you know if there is any latest css reference to the latest fabric UI set? I have created a question here based on my scenario. 

https://github.com/microsoft/fluentui/issues/15939
https://stackoverflow.com/questions/64828031/where-to-get-the-latest-office-fabric-ui-icon-set

But it seems this one https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css doesn't seem to support "AcceptMedium". But if you go to https://uifabricicons.azurewebsites.net/ and search it there, it is found. Do you know why?

**Comment by ecraig12345** [comment]
Regardless of whether you're using the icons via fonts or pure CSS, it's not a bad idea to just generate a custom subset rather than using the full icon set. This will result in smaller bundle sizes and faster downloads/rendering for your users.

If you still want to use the full icon set...

- If you're using the icon fonts through JS via `initializeIcons`, [this zip file](https://fabricweb.blob.core.windows.net/fabric/assets_20201117.001.zip) has the latest versions. You can upload the contents to your CDN and then call `initializeIcons(/*your CDN*/)`. More details about CDN customization [here for icons](https://github.com/microsoft/fluentui/wiki/Using-icons) and [here for text fonts](https://github.com/microsoft/fluentui/wiki/Customizing-fonts). (Ideally we should generate and upload this zip file automatically as part of the asset deployment job, but that may not happen right away--see #10363 for progress.)

- If you're using the icons via CSS only (not via `initializeIcons` and icon names), the file you linked is the latest version of Fabric Core. However it doesn't contain all of the latest icons, so to access newer icons via CSS you'd need to generate a custom subset.

Regarding your original question about a CDN for government clouds, setting up and maintaining something like that is out of scope for our team. There's likely a good bit of variation between different teams' government cloud setups, and it just doesn't make sense for us to be responsible for keeping up with all those requirements and maintaining a fully compliant CDN. All that work probably wouldn't even add much value overall since most apps with these type of requirements use custom subsets already for bundle size reasons, so they won't encounter this issue (in addition to what @paulgildea mentioned about moving towards SVG icons).

**Comment by TheInvoker** [comment]
If I use the FontIcon component in fluent UI, is it always gaurunteed to show the latest icon? Do I need to rebuild the app sppkg?
