### ISSUE TITLE
Website docs: No Feedback section for DetailsList page

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/fluentui#15940]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

1. Navigate to the [main DetailsList page](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist)
1. Look for the "Submit GitHub Issue" button that's on every other page (or anything in the "Feedback" section
1. It's not there

#### Expected behavior:

Same as above, except it is there.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) Low

Products/sites affected: (if applicable) [Main DetailsList page](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist)

**Comment by paulgildea** [comment]
@mark-wiemer Thanks for finding this issue.

To set expectations, we most likely won't get to this issue right away because the subsequent examples provide a submit GitHub issue. I'll mark this a feature request for now, but @JustSlone feel free to resolve as won't fix as we are planning on updating the website in the near future.

Thanks for the find though!
