### ISSUE TITLE
SpinButton should support styles function in v7 to simplify v8 transition

### ISSUE THREAD

**Issue by Dalimil** [microsoft/fluentui#15954]
#### Describe the feature that you would like added

SpinButton should support styles function in v7 to simplify v8 transition.
We'd need to change `styles?: Partial<ISpinButtonStyles>;` in v7 to `styles?: IStyleFunctionOrObject<ISpinButtonStyleProps,ISpinButtonStyles>;`. This would enable us to do the conversion in v7 before upgrading the whole repository to v8

current v7 styles:
https://github.com/microsoft/fluentui/blob/7.0/packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts#L166

current v8 styles:
https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/components/SpinButton/SpinButton.types.ts#L174

#### What component or utility would this be added to

SpinButton

**Comment by Dalimil** [comment]
@ecraig12345 @dzearing What do you think?

**Comment by ecraig12345** [comment]
I'm not sure it will be possible to add function support to the `styles` prop within v7 since under the hood the style function support typically uses a completely different approach (v7 SpinButton for some reason still used `@customizable`, whereas style functions use the newer `styled` helper). Would be interested in @dzearing's input though about how we've handled this type of migration in the past, and if any part of it can be done within a major version.

As an alternative or additional change to help with migration, we should probably bring back (and deprecate) `ISpinButtonProps.getClassNames` and maybe the removed `ISpinButtonStyles` props for v8. None of these props were deprecated or had alternatives provided within v7, so per our standard policy they should not have been removed yet in v8. Supporting both `getClassNames` and `styles` will be a bit awkward, but I'm pretty sure we have other examples of it that we could follow.

For reference, here's the current list of breaking changes to SpinButton as described in the [migration guide](https://github.com/microsoft/fluentui/wiki/Version-8%3A-Migration-guide#spinbutton-1):

> - Simplified props to `ISpinButtonStyles` to include only the parts of the component to bring in line with other components. As a result, the following props have been removed (see below for migration tips):
>   - `arrowButtonsContainerDisabled`
>   - `inputDisabled`
>   - `inputTextSelected`
>   - `labelDisabled`
>   - `spinButtonWrapperDisabled`
>   - `spinButtonWrapperFocused`
>   - `spinButtonWrapperHovered`
>   - `spinButtonWrapperTopBottom`
> - Replaced `getClassNames` legacy prop with `styles` prop to bring component consistent to other components and improve cacheability of internal styles.

**Comment by Dalimil** [comment]
@ecraig12345 @dzearing I think I have figured out way to convert everything that we had into the styles object, so we won't need it to be ported back for compatibility anymore. Feel free to close this issue. Although it might still be something to think about if more consumers run into this issue.

**Comment by dzearing** [comment]
Cool. I think we should keep going with the changes; if we do need to add styles props to make it a little easier, we can also consider that as well.
