### ISSUE TITLE
[TextField] TextField allows JSX error message withing paragraph (<p>) element

### ISSUE THREAD

**Issue by hatpick** [microsoft/fluentui#16049]
### Environment Information

- **Package version(s)**: 7.152.2
- **Browser and OS versions**: Edge 87.0.664.41 (Official build) (64-bit), Windows 10 OS Version 2009 (Build 19042.630)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/hatpick/pen/KKMOoxB

#### Actual behavior:

TextField component wraps errorMessage prop in a p tag, while this is file for string messages, it will violate DOM nesting where many tags can't be children of p tag, leading to warnings in the console. (Check console on the provided pen)

```
index.js:1446 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by MessageBarBase)
    in div (created by MessageBarBase)
    in div (created by MessageBarBase)
    in MessageBarBase (created by StyledMessageBarBase)
    in StyledMessageBarBase (created by ErrorMessage)
    in ErrorMessage
    in span (created by TextFieldBase)
    in p (created by TextFieldBase)
    in DelayedRender (created by TextFieldBase)
    in div (created by TextFieldBase)
    in span (created by TextFieldBase)
    in div (created by TextFieldBase)
```

#### Expected behavior:

Based on the type of errorMessage, pick a better element to prevent violating the DOM nesting.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

**Comment by ecraig12345** [comment]
Thanks for reporting this! In general with custom renderers I'd say that it's the user's responsibility to ensure the content passed in is valid. However, it does seem weird that we're using a `<p>` tag as the wrapper instead of a plain `<div>` since that can have unpredictable (and likely undesirable) styling applied by global overrides, as well as the nesting issues you mentioned. So if you want to submit a PR changing the wrapper to a `<div>` I think that would be fine.

**Comment by hatpick** [comment]
@ecraig12345 it's been 16 days and the PR is still untouched. Is it normal? or does it usually takes that long?

**Comment by ecraig12345** [comment]
@hatpick That's strange, I should have been added as a codeowner, but it looks like that didn't happen because your PR was based on a very old version of `master` where a lot of the files were under different paths. I'll review it now but you'll also need to merge with the latest version of `master` before it can go in.
