### ISSUE TITLE
Tiny Documentation bug: Type error in onFormatDate handler in "DatePicker allows dates to be formatted" example

### ISSUE THREAD

**Issue by priyankark** [microsoft/fluentui#16043]
The date has been initialized with Date | null | undefined and so the function signature of onFormatDate which is currently:
`const onFormatDate = (date: Date): string => {}
`
needs to have it modified to the same and it should handle the undefined case (else it gives type errors when you copy paste the example). Apologies if I have missed something.

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for reporting this! I think this is only an issue when `strictFunctionTypes` (or `strict`) is enabled, and we don't have that enabled in the project containing our examples. However I'll go ahead and fix this since we want our examples to work as written even if people do have stricter options.
