### ISSUE TITLE
Chevron arrows misaligned on grouped details list when selectionMode={SelectionMode.single}

### ISSUE THREAD

**Issue by johnwu0604** [microsoft/fluentui#16120]
In the grouped details list, when I change the list to single select via selectionMode={SelectionMode.single}, the chevron arrows become misaligned.

![image](https://user-images.githubusercontent.com/44329080/100917982-be6fdd00-348c-11eb-8948-ea32b95de281.png)

However, when I change it to multi-select via selectionMode={SelectionMode.multiple}, the chevron arrows are aligned.

![image](https://user-images.githubusercontent.com/44329080/100917872-97191000-348c-11eb-891b-210914535c4e.png)

**Comment by JustSlone** [comment]
@johnwu0604 thanks for the filing this!

Yep, confirmed the issue here's a [CodePen with Repro](https://codepen.io/justslone-the-encoder/pen/NWRxyJM?editors=1010). Looks like this is not a recent regression and it's been like this for quite awhile.

**Comment by ecraig12345** [comment]
The issue is from this line in `GroupHeader`, where it renders a `GroupSpacer` in cases where the group selection checkbox is not visible:
https://github.com/microsoft/fluentui/blob/51c6c169df10a6c63dfbe6e408fda645df544929/packages/react/src/components/GroupedList/GroupHeader.base.tsx#L140
`indentWidth` (from `IGroupHeaderProps`) is not the correct value to use for the `GroupSpacer` width in this case. Instead, it should use `CHECK_CELL_WIDTH` from `../DetailsList/DetailsRowCheck.styles.ts`, same as `IGroupHeaderStyles.check` uses.

Here's a simplified codepen which compares the behavior in single-select and multi-select mode, with the bad spacer elements colored red to make the cause of the issue obvious. (There's also a commented line in the CSS with the fix.) https://codepen.io/ecraig12345/pen/zYKEozM

Since this appears to be an extremely simple fix, I'll probably just go ahead and do it.
