### ISSUE TITLE
[Facepile][Edge] Focus is set on the wrong element and Narrator skips announcing the aria-label

### ISSUE THREAD

**Issue by subashbhujel** [microsoft/fluentui#16149]
### Environment Information

- **Package version(s)**: 
"office-ui-fabric-react": "7.84.1",
"@uifabric/utilities": "7.12.0"

- **Browser and OS versions**: 
`Microsoft Edge` is up to date. Version 87.0.664.55 (Official build) (64-bit)
`OS` Processor	Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

#### Actual behavior:
Turn the Narrator ON and tab through the facepiles. 
The focus is set below the <Span/> element where aria-hidden is set to true. When it's set to true Edge is doing the right thing by not announcing the aria-label set on the `<LI/>` element. 
![image](https://user-images.githubusercontent.com/7033087/101229177-d2197000-3653-11eb-88ec-caebdb97c396.png)
![image](https://user-images.githubusercontent.com/7033087/101229114-8c5ca780-3653-11eb-8c43-fbca3bce1ce4.png)

#### Expected behavior:

1. Aria-hidden must not be set to true. 
2. Focus should be set to `<LI/>` element so aria label is announced correctly. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: Microsoft Planner

**Comment by xugao** [comment]
re-assigned to current Shield @ecraig12345 to take a further look

**Comment by ecraig12345** [comment]
Version 7.84.1 is almost a year old, and I think this issue was fixed sometime since then: the issue repros when I use aka.ms/fabricdemo to find the [facepile examples as of 7.84.1](https://fabricweb.z5.web.core.windows.net/oufr/7.84.1/#/examples/facepile), but it doesn't repro on the [latest version](https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile) on our website. So the solution here is to upgrade your library version.
