### ISSUE TITLE
TextField tests created with use of @testing-library/react are failing after upgrade to office-ui-fabric-react v7.25.0

### ISSUE THREAD

**Issue by WojciechKulpa** [microsoft/fluentui#16143]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.25.0",
- **Browser and OS versions**: not relevant

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/stoic-johnson-rs5ct

#### Actual behavior:
After upgrade to v7.25.0 or any next (7.24.0 is ok) during tests execution in onChange event.target.value doesn't have correct (updated) value (see output in console).

#### Expected behavior:
Same result as on v7.24.0 - event.target.value to have correct (updated) value.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by JustSlone** [comment]
@WojciechKulpa thanks for the issue! I took a look and confirmed the repro, the CodeSandbox was super helpful thank you!

This is issue is really strange, however it doesn't seem to be a regression from v7.24.0 I updated the CodeSandbox to v7.24.0 and I still saw the issue. 

I also created a further isolated sandbox that continues to repro the issue: https://codesandbox.io/s/laughing-river-cx9qo?file=/src/form.js

This is going to need further investigation.

**Comment by WojciechKulpa** [comment]
Hi @JustSlone I suppose that same results on v7.24.0 and v7.25.0 are caused by some kind of caching problem on codesandbox. Please reload the page after you switch version of package and you should see that on v7.24.0 it was ok.
Here is forked sandbox with v7.24.0 https://codesandbox.io/s/strange-solomon-yigl8?file=/src/form.js and in console we have correct output:
`value 1234 target.value 1234`

I suppose that this problem is somehow related to changes introduced in this PR: https://github.com/microsoft/fluentui/pull/10016

**Comment by JustSlone** [comment]
@WojciechKulpa thanks for pointing that out, yes I am able to confirm no repro with v7.24.0. I've created 2 codepens so we don't run into caching problems

- No Repro v7.24.0: https://codesandbox.io/s/16143-no-repro-v7240-cx9qo
- Repro v7.25.0: https://codesandbox.io/s/16143-repro-v7250-ls18d

Also thank you for pointing out the related PR (#10016), @ecraig12345 is on shield right now, so she can take a deeper look.

**Comment by layershifter** [comment]
Confirmed with office-ui-fabric-react@7.155.3 & @fluentui/react@8.0.0-beta.32. It's definitely caused by #10016.

---

I went through code with debugger and noticed the following behavior:

```tsx
    const value = element.value; // ✅  will contain a proper value (changed value, "1234")
    // ...

    this.setState(
      (prevState: ITextFieldState, props: ITextFieldProps) => {
        const prevValue = _getValue(props, prevState) || '';
        isSameValue = value === prevValue; // ✅ `prevValue` ("44") and `value` ("1234") are correct

        // 🟥 if I will query `event.target.value` in this call it will be an invalid value ("44", we expect "1234")
```

This happens only in tests, I checked the same in demo on the same CodeSandbox and it works as expected.

---

For curiosity I rewrote the test with `react-dom/test-utils`:

- CodeSandbox: https://codesandbox.io/s/optimistic-sound-qxmlj
- Output: `value 1234 target.value 1234` 😮

It looks that there was a similar issue reported https://github.com/testing-library/react-testing-library/issues/640. It looks that there is an issue persisting events.

@JustSlone should we investigate this issue more?

**Comment by ecraig12345** [comment]
Sorry, I actually looked into this in December but never finished writing up what I found. 

I think what happened here is that prior to #10016, `onChange` was called synchronously for a controlled TextField after the event was fired, and asynchronously (after re-render) only for an uncontrolled TextField. Now it's called asynchronously in either case. This is rather odd compared to the behavior of other components, and there's no clear reason for the difference; it's just been that way ever since `onChange` was added in #5764 (it's also where the old callback `onChanged` was called...but [no clear reason](https://github.com/microsoft/fluentui/pull/1142/) for that either). 

Since the timing is non-standard, we could consider changing all cases to call `onChange` synchronously in v8.

For the more immediate testing issue, @WojciechKulpa is there a specific reason that you need to update based on `ev.target.value` rather than `value` as passed to `onChange`? In general it's recommended to use `value`. This issue also appears to be highly specific to implementation details of how `@testing-library/react` implements events.

**Comment by WojciechKulpa** [comment]
Hi thank you all for looking into that and details.
@ecraig12345 to answer your question, we are using TextField with other components that are using ev.target.value. One of them is Formik (as presented in initial sandbox) - theoretically in this case we could modify all occurrences of TextField to relay on value instead of using default formik behavior (I would definitely like to avoid that), but there are also other components that are internally reading ev.target.value and in that case we are blocked.

**Comment by ecraig12345** [comment]
I can fix the actual issue by calling `onChange` synchronously in version 8, but I'm hesitant to change the timing again within version 7 at this point--especially since this seems to only be causing issues running under `@testing-library/react` and not in production (if I'm understanding right).

One workaround would be always setting `ev.target.value = value` in the TextField `onChange` handler, but it's not ideal to do this in your production code (though it [doesn't cause obvious problems](https://codepen.io/ecraig12345/pen/ZEpMVNr) that I could find).

Another workaround would using Jest mocks to set `ev.target.value = value` only in tests. This is pretty straightforward using member mocks if you're willing to make a class component wrapper for TextField, but more awkward with function components due to limitations of module mocks. I'm also not sure what issues (if any) this might cause with other tests. Here's a demo of the two approaches: https://codesandbox.io/s/16143-textfield-testinglibrary-o1c5r

**Comment by WojciechKulpa** [comment]
Hi All,
Thanks a lot for your support and fix!!! I have just upgraded our project to @fluentui/react v8.1.0 (from 7.24.0).
Process was extremally smooth - all tests are passing, no issues detected!

So again great thanks to you @ecraig12345, @JustSlone and @layershifter! This is awesome🎉

**Comment by ecraig12345** [comment]
@WojciechKulpa You're welcome, and great to hear the upgrade went well for you!
