### ISSUE TITLE
Hovering items (with icons or not) makes elements jump to up/down or left/right

### ISSUE THREAD

**Issue by gencer** [microsoft/fluentui#16153]
### Environment Information

- **Package version(s)**: @fluentui/react 7.153.4
- **Browser and OS versions**: Latest Edge + Chrome has this issue (Chromiums. Firefox is smooth). I've tested with **87.0.664.52** and Edge Canary **v89.x**.
   - [edit] Does not repro on Chromium **v86.x**

### Please provide a reproduction of the bug in a codepen:
When I hover elements like ContextualMenu or any element that opens via user interaction on click, if you hover elements (menu items) icon and text moves few pixel up, down, left or right. Randomly.

Chromium browsers has this issue but Firefox seems very smooth with it. I don't know if this is something Chromium thing or FluentUI-side but still not good for eyes. I've attached 2 screencasts. First one is from your FluentUI React Demo Site and second one from my app.

#### Actual behavior:

Elements (Text and/or icon) moves/kjump few pixels upon arrival or hover.

#### Screencasts:

1. From FluentUI Site:

![jumping around](https://user-images.githubusercontent.com/1711576/101271028-304b6d80-3790-11eb-8a87-35d939836481.gif)

2. Personal site:

![jumping around2](https://user-images.githubusercontent.com/1711576/101271031-32153100-3790-11eb-89ce-edf58123d879.gif)

**Note**: Gifs are 30fps so be patient and watch icons and text closely. You'll see the movements.

#### Expected behavior:

No moving/jumping around.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No. I have no idea where this come from.

Requested priority: (Blocking, High, Normal, Low) High. Probably. Most likely Normal.

Products/sites affected: Your whole FluentUI library site using Chromium browsers.

**Comment by JustSlone** [comment]
@gencer thanks for the issue! However, I'm not seeing repro locally ☹️ 

I'm using [this codepen](https://codepen.io/justslone-the-encoder/pen/poEydNG)

And I don't see any jitter, even in the second part where I refresh the page with throttled network and no cache (so it takes a second for the icons to load).

Here's a gif showing what I see. This is the same at multiple zoom levels.
![menu](https://user-images.githubusercontent.com/40304143/101271630-63164700-3739-11eb-8045-41b52d4944a2.gif)

I wonder if there is some conflicting CSS somewhere resulting in the jitter. If you are able to get this to repro consistently in an isolated CodePen that would help narrow it down. (even our doc website sometimes has extra CSS, though I don't see repro there either)

**Comment by gencer** [comment]
Hey @JustSlone!

Thanks for the fast reply. At first your example worked smoothly here too. Than I thought maybe this was a DPI issue. At my right, I have an another PC+Monitor which is 1080p and 100% DPI rather than 4K +125% DPI as my primary display. Your codepen also worked there BUT my site & Fluent UI Site still jittering. So this was **not** the source. At least I eliminated DPI-thing.

Then I just forked your example, added few more buttons with new lines. Woala. I repro. See screencast and codepen link below:

![jumping around3](https://user-images.githubusercontent.com/1711576/101271856-cb941100-3797-11eb-8b75-7ebad60dd6b5.gif)

Take a closer look at 5th button. Hope you can reproduce on your end.

**Codepen**: https://codepen.io/gencer-the-typescripter/pen/rNMeYzB

**Comment by JustSlone** [comment]
OK! I've got repro, thank you for the updated pen and investigation!

Looks like this was introduced in Chrome 87, it does not repro for me in Chrome 86, see details below (tho I would love for someone else to confirm as the repro is so subtle and finicky). I was able to find a portable version of Chrome (which uses chromium) for testing multiple versions. 

Couple notes:
- Only repros for me when the menu is repositioned due to not enough space below the button. This is probably why it only repros for the MenuButtons lower in the list
- Doesn't seem to repro at >100% zoom
- This feels like some kind of subpixel positioning or rendering layout thing, not sure if we can work around this, needs more investigation. 
- ✔️ It repros in Edge Version (87.0.664.47)  
- ✔️ It repros in Chrome Version (87.0.4280.88) 
- ❌ It does not repro in Chrome Version (86.0.4240.198)  
- ❌ It does not repro in Firefox (83.0 (64-bit))  

*Note: repro is subtle, you may need to view gifs in their own window at full size to see it*

**Chrome 87**: ✔️ Repro
![Menu-Chrome87](https://user-images.githubusercontent.com/40304143/101295307-af14ca80-37d1-11eb-945e-56eb5a7dfe76.gif)

**Chrome 86**: ❌ No Repro
![Menu-Chrome67](https://user-images.githubusercontent.com/40304143/101295232-30b82880-37d1-11eb-8199-c1935fbe3114.gif)

**Comment by gencer** [comment]
Glad you make it repro there. I also tested with latest Edge and Chromium Canary. I believe its v89. Still there.

**Just a side note**: It happens at >100% Zoom definitely. Both in 100% DPI and 125% DPI and also zooming via browser. I believe problem happens when contextual menu opens other than actual position. Lets say you create a right-click contextual menu when you right click on page. If you right click and open menu in different positions of the page randomly you will see this issue. I hope I am clear what I am trying to say here.

**Comment by gencer** [comment]
@JustSlone I also confirm that `Version 86.0.4240.75 (Official Build) (64-bit)` has no this issue at all. Seems smoothly working there.

**Comment by gencer** [comment]
@JustSlone It seems this issue fixed in the last Canary of Edge (possibly at Chrome too). The exact version I tested is `Version 89.0.739.0 (Official build) canary (64-bit)`. I do not see any jitter on this version.

**Comment by JustSlone** [comment]
@gencer great. Thanks for following up, and thanks for the report, glad this was resolved quickly

Going to close this out now, feel free to reopen if there is anymore follow up needed.
