### ISSUE TITLE
Not able to copy a column value to clipboard on DetailsList Component for multiSelect option

### ISSUE THREAD

**Issue by Teja-Git** [microsoft/fluentui#16174]
### Environment Information

- **Package version(s)**:  7.107.0
- **Browser and OS versions**: Chrome  - 87.0.4280.88 (Official Build) (64-bit)

1. Which Fluent UI component is causing the issue 
- "DetailsList"

2. Which package name and version the component is from
- "office-ui-fabric-react": "^7.107.0",

3. Specific, complete steps to reproduce the issue
- Create Any DetailsList component with "SelectionMode.multiple"
- Try to copy a column value to clipboard 

4. What behaviors and attributes are missing or incorrect
- Unable to copy a column value to clipboard

5. What you expected and what is actually happening
#### Actual behavior:
User is not able to copy the value in a grid column to clipboard even when the selection mode is "SelectionMode.multiple".
But for "SelectionMode.single", the column values can be copied to clipboard. 
#### Expected behavior:
User should be able to copy the value in a grid column to clipboard even when the selection mode is "SelectionMode.multiple"

6. Confirmation that the problem reproduces in isolation
- Yes

7.Are you willing to submit a PR to fix? (Yes, No)
No

8. Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
Microsoft's Internal site in Volume Licensing

**Comment by paulgildea** [comment]
@Teja-Git Thanks for filing this issue. Could you provide a reduced repro codepen of the issue that you are hitting this issue? This can help us troubleshoot more quickly.

If possible it might be start with one of the DetailsList samples from here: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic

**Comment by Teja-Git** [comment]
@paulgildea the issue is reproduceable even on the detailsList component in the link you shared. Nevertheless, here is the link for codepen.

https://codepen.io/teja-git/pen/dypOzQz

**Comment by ecraig12345** [comment]
Thanks for the repro. This behavior is intentional at the moment: DetailsList multi-select mode is often used with marquee (click and drag) item selection, and if that's enabled, it should take precedence over text selection. (But see more thoughts on this later.)

If you want to enable text selection, you can do this today by overriding the DetailsRow styles inside a custom row renderer:
```tsx
const rowStyles: Partial<IDetailsRowStyles> = {
  root: {
    userSelect: 'auto', // or other desired value
  },
};

const onRenderRow: IDetailsListProps['onRenderRow'] = props => {
  return props ? <DetailsRow {...props} styles={rowStyles} /> : null;
};

<DetailsList onRenderRow={onRenderRow} ... />
```
Full code here: https://codepen.io/ecraig12345/pen/YzGxBpP

----

I did some investigation of the background of this behavior: at first, DetailsList entirely prevented text selection, but after the discussion on #802, it was changed to allow text selection except in multi-select mode. Text selection remained disabled in multi-select mode to avoid interference with marquee (click and drag) selection of items.  (For reference: currently this is handled in [DetailsRow](https://github.com/microsoft/fluentui/blob/d7fdc9a9ffd9b23c9c467ac61360741af711353a/packages/react/src/components/DetailsList/DetailsRow.base.tsx#L212-L221) and [DetailsRow.styles](https://github.com/microsoft/fluentui/blob/d7fdc9a9ffd9b23c9c467ac61360741af711353a/packages/react/src/components/DetailsList/DetailsRow.styles.ts#L218).)

What that decision didn't consider is that marquee selection is an *optional wrapper* to DetailsList, as you can see in several examples:
https://github.com/microsoft/fluentui/blob/7787eab529bb011082ae510201aed6ccc4b31465/packages/react-examples/src/react/DetailsList/DetailsList.Basic.Example.tsx#L79-L80
And if the MarqueeSelection wrapper isn't used, it might be unnecessary to disable text selection (unless there's some other scenario I'm not thinking of). The tricky part would be how to detect this case without too tightly tying the DetailsList and MarqueeSelection components together, and without risking regressions. 

Since this change would be fairly high-risk for multiple partners, it would definitely require more discussion after the holidays. It's also not likely to be a high priority for our team to implement (though we could review a PR): DetailsList is currently in maintenance mode while a replacement is being developed internally, and the core team is primarily focused on larger work items related to performance and coherence across the library. So overall this may fall more into the category of "things to consider for future implementations" than a change we could realistically make today, especially since a workaround exists.
