### ISSUE TITLE
Role cannot be overridden for Pivot Items today and default role in "tab"

### ISSUE THREAD

**Issue by humaagarwal** [microsoft/fluentui#16184]
### Environment Information

- **Package version(s)**: ("office-ui-fabric-react": "7.123.5")
- **Browser and OS versions**: (Edge chromium DEV Build (Version 86.0.622.3), Firefox(75.0), Chrome)

### Describe the issue:
We are using Pivot and Pivot items for pagination UX and as per accessibility pass the we have bug that incorrect role is defined as 'Tab' for pagination link controls which we are rendering as Pivot Items. I investigated the issue and found that currently role is hardcoded as "tab" for Pivot items and there is no way to override them to "link" which is expected behavior for this use case.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/humaagarwal/pen/RwGRXXE

#### Actual behavior:

Incorrect role is defined as 'Tab' for pagination link controls using Pivot Items.

#### Expected behavior:

role should be defined as "Link" or there should be some prop exposed to override it.

### Documentation describing expected behavior

![roleissue](https://user-images.githubusercontent.com/75696779/101535887-1f485b00-394e-11eb-8690-3be26db6fa79.PNG)

**Comment by ecraig12345** [comment]
Thanks for reporting this and for the codepen. This would be pretty easy to fix if you're willing to submit a PR, but it's not something the Fluent UI team is likely to get to soon since we're currently focused on larger work items around performance and coherence.

I think the fix would be as simple as changing this line:
https://github.com/microsoft/fluentui/blob/859fe008176c28a86b24d02e2d1bc1fe3d918752/packages/react-tabs/src/components/Pivot/Pivot.base.tsx#L137
to this:
```tsx
role={link.role || 'tab'}
```

And probably the same fix here in the new Tabs component (cc @behowell):
https://github.com/microsoft/fluentui/blob/859fe008176c28a86b24d02e2d1bc1fe3d918752/packages/react-tabs/src/next/components/Tabs/Tabs.base.tsx#L134

**Comment by Hanaffi** [comment]
@ecraig12345 Can you assign it to me?

**Comment by ecraig12345** [comment]
@Hanaffi We don't typically assign issues to people who aren't members of the project, but you're welcome to work on this if you want. Let me know if you run into any trouble.

**Comment by Hanaffi** [comment]
@ecraig12345 How can I become a member?

**Comment by ecraig12345** [comment]
@Hanaffi I appreciate your interest, but we can only add Microsoft employees as organization members. However you're welcome to contribute regardless, and the fact that you're not a member shouldn't create any issues with contributing.

**Comment by zubinchopra** [comment]
Hey @ecraig12345 is this issue closed? If not then I can take a look at it :) (First time contributor here)

**Comment by Hanaffi** [comment]
@ecraig12345 
Sorry, I got busy in the previous days.
I have a problem finding `859fe008` branch, Can you help?
