### ISSUE TITLE
shimmerLines changed not taken into account

### ISSUE THREAD

**Issue by nlips** [microsoft/fluentui#16226]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.110.5
- **Browser and OS versions**: Chrome / Windows

### Codepen:

https://codepen.io/nlips/pen/eYdvZxB

#### Actual behavior:

When shimmerLines value is changed the list is not updated

#### Expected behavior:

Number of shimmer lines must match the shimmerLines property

**Comment by ecraig12345** [comment]
Thanks for reporting this and for providing a codepen. The problem is this part in the constructor of `ShimmeredDetailsList`: it creates an array of shimmer lines on initial render and 
https://github.com/microsoft/fluentui/blob/859fe008176c28a86b24d02e2d1bc1fe3d918752/packages/react/src/components/DetailsList/ShimmeredDetailsList.base.tsx#L28-L31

One easy workaround on your end is to add a `key` prop to `ShimmeredDetailsList` with the current number of shimmered lines. This will cause it to re-render when the number of lines changes. (full demo: https://codepen.io/ecraig12345/pen/WNGWPPV)
```jsx
<ShimmeredDetailsList key={String(shimmerLines)} ... />
```

If you're willing to submit a fix, it would be relatively straightforward. The trick is that we shouldn't create a brand new array on every render of ShimmeredDetailsList, because that would cause the DetailsList to re-render too often. If ShimmeredDetailsList was a function component, this would be very easy to handle with `useMemo`. Unfortunately it's still a class component, so the most straightforward fix would be to add a block like this in `ShimmeredDetailsList.render` (or there are a couple other ways you could do it with a bit more code to avoid the render side effect).
```js
    // Side effects while rendering should generally be avoided, but this one is safe, inexpensive,
    // and behaves consistently even if render() is called multiple times in concurrent mode.
    if (shimmerLines && shimmerLines !== this._shimmerItems.length) {
      this._shimmerItems = new Array(shimmerLines);
    }
```
