### ISSUE TITLE
Detailslist header for toggle selection not visually assigned in single selection mode

### ISSUE THREAD

**Issue by AkanshuGupta3299** [microsoft/fluentui#16262]
### Environment Information

- **Package version(s)**: 7.153.4
- **Browser and OS versions**:  All

### Describe the issue:

DetailsList Header for toggle selection in single selectionmode is not visually assigned, even though narrator screen reader can read it.
![image](https://user-images.githubusercontent.com/75408940/102514935-1d4f6c00-40b3-11eb-825e-03e72382a638.png)

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/akanshugupta3299/pen/rNMmbJZ

#### Actual behavior:

Column header for toggle selection is not visually assigned, even though screen reader can read it.

#### Expected behavior:

All the column headers should be visually also assigned with a column header so that low vision or keyboard only users are able to understand regarding the cell data that is present below the column header. 
There should be the selectAll icon, in disabled state.

**Comment by ecraig12345** [comment]
Thanks for filing this, and sorry for the delayed response. For some reason your codepen isn't working for me, so here's another one: https://codepen.io/ecraig12345/pen/NWRmVmZ

Regarding the actual issue, is there a particular WCAG success criterion or other standard which specifies this behavior? I can see why it might be desirable in some ways to show a disabled checkbox in this case, but it might also be confusing (perhaps making them think they can't select any items).

Also, due to the complexity of our list components and partner teams' deep dependencies on them, we're actively trying to minimize risk of regressions, so we're mostly limiting work on those components to essential fixes only.

**Comment by dawolff-ms** [comment]
@ecraig12345 I understand this issue was closed, but we just had our A11Y testing team raise this issue citing [WCAG 2.1-1.3.1: Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html). With this information, do you deem this fix essential?

**Comment by ecraig12345** [comment]
@smhigley Do you have any thoughts on this?

**Comment by smhigley** [comment]
If I understand this issue correctly, it's asking for the column header for the checkboxes to have visible text or a graphic? That's not in itself a violation of 1.3.1, since there's no visual information that lacks a programmatic representation.

I don't really have a strong opinion one way or the other on whether the checkbox column specifically should have a visual headers, but I don't think I've ever seen table columns that lack visible column headers treated as an accessibility issue. Rather, this seems like a general feature request.
