### ISSUE TITLE
Focusable content should have tabindex='-1' on FocusTrapZone

### ISSUE THREAD

**Issue by devrsi0n** [microsoft/fluentui#16277]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.154.0
- **Browser and OS versions**: (fill this out) Chrome 87.0.4280.88, macOS 11.1

### Describe the issue:

**Accessibility Insights for Web** FastPass on FocusTrapZone component:
![image](https://user-images.githubusercontent.com/7880675/102744162-1e72e880-4394-11eb-9287-78a5db49bc0d.png)

HTML:
![image](https://user-images.githubusercontent.com/7880675/102744501-ea4bf780-4394-11eb-8283-ef27b9e57a18.png)

### Please provide a reproduction of the issue in a codepen:

This issue can be repro on [official doc site](https://developer.microsoft.com/en-us/fluentui#/controls/web/focustrapzone).

#### Actual behavior:

Focusable content should have tabindex='0'

#### Expected behavior:

Focusable content should have tabindex='-1' or be removed from the DOM

### Documentation describing expected behavior

None

**Comment by gouttierre** [comment]
@devrsi0n  - Thanks for the feedback and details into the problem

@khmakoto  - Can you determine if the Focusable content being recorded by the tabindex is a regression or behavior issue?

**Comment by khmakoto** [comment]
@devrsi0n thanks for filing the issue! This is a really interesting problem because we need the bumpers to be focusable in order to trap focus but we don't want them existing in the accessibility tree because there's no reason for them to be read.

@smhigley what would you recommend in this situation.

For reference, the code exists [in here](https://github.com/microsoft/fluentui/blob/74be7e3d12c1d1d342dc3e2fcc8a6146c08fdbf7/packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx#L93).

**Comment by smhigley** [comment]
So, what I believe is happening is FocusTrapZone uses two bumper elements at the start and end to wrap tab and shift tab back to the start/end. Those are the hidden focusable elements. In practice, this doesn't cause any issues because focus never fully lands on them -- they shift it to the correct element before that happens. We can't use `tabindex="-1"`, because the bumpers need to be in the tab order to work.

axe-core doesn't like it though, because from an automated checker's point of view, there's a focusable hidden element. We could potentially look into removing `aria-hidden="true"` if the false positives from accessibility checkers end up creating a lot of churn. Theoretically, an empty `<div>` shouldn't need to be hidden, since it should already be ignored. The one sticking point is screen readers have heuristics that sometimes cause them to expose `<div>`s if they think they're interactive, and `tabindex="0"` has a chance of triggering one of those heuristics. We'd need to do some testing across screen readers and browsers to see if removing `aria-hidden` would have any negative side effects.

Right now, I'm not sure if it's worth the effort since it's purely an automated error and not a practical one.

**Comment by tianbli** [comment]
I got the exact same issue as an accessibility bug. Do you have update on your plan to solve this?
@smhigley @khmakoto @gouttierre

**Comment by tianbli** [comment]
@benkaiser Ben, this is the cause of one WEX accessibility issue
