### ISSUE TITLE
Checkbox doesn't pass through `data-` props

### ISSUE THREAD

**Issue by ibrosen** [microsoft/fluentui#16307]
### Environment Information

- **Package version(s)**: @fluentui/react - 7.153.0

### Describe the issue:

Checkbox doesn't pass through consumer-passed-in `data-` props. I looked at `BaseButton.tsx`, and it looks like it uses `getNativeProps()` from `@fluentui/utilities`, which specifically checks for `data-` props and ensures they're plumbed through.

In `@fluentui/utilities/**/properties.ts`.
![image](https://user-images.githubusercontent.com/24663638/103252782-1803e400-4933-11eb-8c3e-179416a6205a.png)

Our pages rely on a `data-bi-id` for telemetry, but for Checkbox it's sadly being lost in the sands of JavaScript object destructuring.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, if I knew the best way to do it. It looks like it should be applied to the `root` object of `Checkbox`, but I'm not sure if *every* non-destructured prop in `props` should be passed to that object too.

Requested priority: Medium/High. We have some pages live to customers at the moment that aren't collecting proper telemetry.

Products/sites affected: account.microsoft.com

**Comment by ecraig12345** [comment]
For Checkbox you'll need to include your `data-*` attributes in `ICheckboxProps.inputProps`. Unfortunately this will require casting since it's currently not possible in TS 3.7 to allow all keys with a certain prefix (this is fixed in TS 4.1, but we won't be able to use that in Fluent UI for awhile). 
```tsx
<Checkbox inputProps={{ 'data-foo': 'something' } as any } />
```

The fact that `ICheckboxProps` extends `React.ButtonHTMLAttributes` is misleading and wrong at the moment, since it doesn't actually call `getNativeProps` or any other method for passing through unhandled native props. Getting rid of the props extension would be a breaking change, but since we're about to release version 8 (which can contain breaking changes) I think I'll go ahead and make that change in master.

**Comment by ibrosen** [comment]
Thanks for the response! That makes sense, I tried passing it through `inputProps`, but I didn't think to cast it as any to overcome the type error that it threw. That works as a workaround, and I'll make sure to make a note that it'll be included in all the v8 goodness.

Thanks again!

**Comment by ecraig12345** [comment]
Originally I was going to entirely remove the native props extension, but now I'm wondering if it would be better to update the control to apply native props instead (and if so, where they should be applied). This will need more discussion once people are back from the holidays.

**Comment by ecraig12345** [comment]
I made a change in #17180 to remove the native props extension for now so that at least the props accurately reflect the behavior. Unfortunately due to TS's behavior for all React elements, it will still appear that passing `data-*` attributes to a JSX `<Checkbox>` is allowed (e.g. `<Checkbox data-foo="bar"/>` won't cause a compiler error), but this at least improves the accuracy for other props--it even helped find multiple bugs within Fluent UI React itself!

We can revisit determining the right full solution for applying native props later if needed, since it would require more discussion.
