### ISSUE TITLE
Link focus outlines with large text content

### ISSUE THREAD

**Issue by FosterSamuel** [microsoft/fluentui#16318]
Hi,

If large text inside a `span`, or other inline element, is placed inside a `Link`, it is clipped when focused:

<img width="362" alt="before" src="https://user-images.githubusercontent.com/15165138/103317743-ed706480-49e0-11eb-96a3-89a86113e802.png">

This can be fixed by forcing the Link to have `display: inline-block`:
<img width="386" alt="after" src="https://user-images.githubusercontent.com/15165138/103317753-f5300900-49e0-11eb-923f-908db089004c.png">

However, `inline-block` messes with the Link if it's meant to be inline with text around it. **The question**: is large inline text a supported case for `Link` in terms of focus?

**Comment by ecraig12345** [comment]
It looks like this issue only happens when the Link's **content** is tall; the focus outline works fine when a large `font-size` is set on the Link element itself.

While supporting proper focus outlines for tall Link content would be nice, it probably won't be a high priority, especially since multiple workarounds exist (see below). Making Link's focus outline work with wrapping and various other core scenarios is challenging and has been discussed and improved multiple times (#4883, #6944, #12033). It might be possible to support this case too, but I'm not familiar enough with the CSS box model to figure out how. If you want to pursue this further, we'd need to wait and discuss it more after people are back from the holidays.

Some possible workarounds include:
- Set `font-size` on the Link itself (not a content element)
- Set `padding-top` and `padding-bottom` on the Link itself to make the outline accommodate the content (note that with `display: inline`, this doesn't seem to change the line height, only the outline height)
- Set `display: inline-block` on the Link itself if the effects on wrapping are acceptable

Codepen demonstrating some of the workarounds, as well as the wrapping issues with inline-block: https://codepen.io/ecraig12345/pen/QWKaeVX
