### ISSUE TITLE
On pressing Esc key, the panel gets closed instead of just the callout.

### ISSUE THREAD

**Issue by manishagm13257** [microsoft/fluentui#16383]
### Describe the issue:
If the callout is present in a panel, on pressing Esc key, instead of the callout getting closed, the panel is getting closed.
To repro the issue:
1. Click on the "open panel" button.
2. When the panel gets open, tab through the "Show Callout" button and press enter.
3. The callout gets opened and then press escape key.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/manishagm13257/pen/bGwMypj

#### Actual behavior:

On pressing the Escape key, the panel is getting closed.

#### Expected behavior:

On pressing the escape key, only the callout should get closed.

**Comment by kubkon** [comment]
If there are no objections, I'd like to take a look at this one and see if I can come up with a solution. I might be in need of some mentoring as to what is where, etc., but I'll do any pinging as required.

**Comment by kubkon** [comment]
I've managed to reproduce the issue locally, and managed to play with it a little bit. As far as I can work out, the issue stems from the fact that the `Callout` component doesn't introduce a nested `FocusTrapZone` for its children, i.e., the `Popup` sub-component. This is done by default by the `Panel` component BTW. I've noticed that we do define a `FocusTrapCallout` within `@fluentui/react`, and with the `Callout` replaced by `FocusTrapCallout` the issue disappears. Internally, `FocusTrapCallout` does exactly what the `Panel` does by default, that is, introduces a new `FocusTrapZone` which means that both navigating enabled elements with a Shift-key for instance is then constrained to the last focus zone, in this case the `Popup` element, and dismissal works as expected -- pressing Esc-key will correctly dismiss the popup rather than the entire `Panel`.

Here's the demo in CodePen: [codepen/YzGOOVd](https://codepen.io/kubkon/pen/YzGOOVd)

My question here is whether we'd want to make the `FocusTrapCallout` the default for the `Callout` component? If so, there is still some work left to make the navigating not interfere with the dismissal functionality, but it looks like a step in the right direction.

Pinging @joschect as you seem to assigned the ownership of `Callout` component and @xugao who is `Panel`'s caretakers ;-) I've also updated the labels with where I think the issue resides, but feel free to correct me if I'm off. Also cc'ing @JustSlone in case I pinged not the right persons!

**Comment by kubkon** [comment]
OK, here's an update @manishagm13257, apologies it took me that long to formulate a proper answer and a resolution to your issue -- still getting used to the codebase.

So here goes. In order to achieve focus within a `Callout` component, it first of all needs to visible, have `setInitialFocus` set, and be explicitly positioned (e.g., using `target` prop). However, this is only a prerequisite to even request the `Callout` to focus on a child element within it. If it so happens that the `Callout` doesn't have any focusable elements as one of its children (children can be arbitrarily deeply nested mind you), then the `Callout` will not be focusable. This is precisely the case in your CodePen example, where all of the `Callout`s children are non-focusable. If you look at some of the FluentUI examples in the docs, e.g., the [Default Callout Example](https://developer.microsoft.com/en-us/fluentui#/controls/web/callout), the `Callout` in that example in addition to `Text` children uses also a `Link` component which is focusable, and therefore, the Esc-key behaviour is as you'd expect in that example.

Now, in order to make your example behave as intended, you could either insert a focusable component into the `Callout`, or make the `<div>` wrapping the `Text` in your example explicitly subscribe to focus via `tabIndex` prop like so:

```ts
<div tabIndex={0}>
```

To demonstrate this at work, here's the tweaked version of your CodePen with explicitly specified `tabIndex` prop on the inner `<div>` within the `Callout`: https://codepen.io/kubkon/pen/bGwZOov

In light of the above, I'm going to mark this issue as resolved, but should you feel it isn't, feel free to reopen and I'll be glad to reinvestigate.

cc @joschect so that he can verify I was accurate in my explanation :-)
