### ISSUE TITLE
NVDA is narrating entire dialog information, when Panel is displayed.

### ISSUE THREAD

**Issue by prademi** [microsoft/fluentui#16386]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@6.189.2
- **OS** : Win 10 1909 (OS Build 18363.476)
- **Browser** : Chrome (78.0.3904.70)
- **Tools used**: NVDA 2019.2.1

### Describe the issue:

NVDA is narrating entire dialog information, when Panel is displayed.

#### Actual behavior:

NVDA is narrating entire dialog information, when PANEL flyout is displayed.
Ex: When Panel flyout is displayed, NVDA is narrating entire dialog information in single stretch.

#### Expected behavior:

NVDA should not narrate entire dialog information, when Panel flyout is displayed.
Ex: When Panel flyout is displayed, NVDA should narrate as "Panel title dialog close button"

![image](https://user-images.githubusercontent.com/65328772/103737331-03e97200-5018-11eb-9525-b3fe85fa79bd.png)

**Comment by kpasagada** [comment]
Hey @layershifter do you have an ETA on this fix? We have an open accessibility bug due to this.

**Comment by JustSlone** [comment]
Confirmed repro here: https://codepen.io/justslone-the-encoder/pen/bGBKpNX

@kpasagada It seems like reading the entire Panel might be intended behavior. I think this is so that the user knows what just appeared. Is there a specific reason that the panel content should not be read out?

One quick example: http://ncamftp.wgbh.org/sp/tests/dialog/modalDialog.html where the entire dialog content is read. 

Also, CC @smhigley who probably knows more about intended behavior here.

**Comment by smhigley** [comment]
@prademi / @kpasagada in NVDA settings, go to "Browse Mode" and uncheck "Automatic Say All on page load". Then NVDA won't read the dialog as a whole when it opens, or the full page content on load.

I personally keep that setting unchecked. Other people I've talked to who use NVDA uncheck it as well; I don't know why it defaults to checked ¯\_(ツ)_/¯

**Comment by kpasagada** [comment]
@smhigley I tried what you said and it did the trick! Thank you and @JustSlone for looking into this issue :)
