### ISSUE TITLE
Items do not show when scrolling <DetailsList/>

### ISSUE THREAD

**Issue by Moiahbabi** [microsoft/fluentui#16403]
### Environment Information

- **Package version(s)**: "^7.124.1"

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/moiahbabi/pen/ExgRGrJ

#### Actual behavior:

not all list items show when scrolling down.

#### Expected behavior:

  items get rendered when scrolling.

I tried setting `data-is-scrollable={true}` on `<DetailsList/>` component, but the resultant div always hav `data-is-scrollable="false"`.

it works fine without `<Modal/>`: https://codepen.io/moiahbabi/pen/abmKPee

### Priorities and help requested:

Requested priority: Low

**Comment by gouttierre** [comment]
@Moiahbabi - thanks for the input. I took a look at it seems to occur in our latest lib release as well.

@khmakoto  - Would you be able to determine if this is a regression or if this behavior is an issue?

**Comment by khmakoto** [comment]
@Moiahbabi this happens because of how the virtualized cache is calculated, you can either calculate it yourself to account for the fact that the `DetailsList` is inside of a `Modal` or turn of virtualization so that everything renders. Both of these are achieved via the `onShouldVirtualize` prop. An example using the latter method can be found [in this codepen](https://codepen.io/khmakoto/pen/OJbrGNK?editors=0010).

Hope that helps and please let us know if you have any other questions!
