### ISSUE TITLE
Unexpected screener failures with hover state

### ISSUE THREAD

**Issue by xugao** [microsoft/fluentui#16434]
Some screeners related to hover state are failing unexpectedly: [see test failure](https://screener.io/v2/dashboard/Skgr32fUL.microsoft-fluentui/user%2Fv-jasha%2FtooltipIssue)

The failure is repro-able when running screener stories locally on Chrome 87.

Related cause: screener updated Chrome to v87
Temporary mitigation: accepted all diffs to unblock CI

**Comment by ecraig12345** [comment]
Not really sure what to do here, and I may not have time to investigate. So that we at least don't lose track of what's broken, I found permanent links to the builds with the changed states (post browser upgrade) and pasted full lists for 7.0 and master below. The screenshots in the links are from the new (probably broken) states. There's unfortunately not an easy way to view the diff with the previous version; you have to open an individual state ([example](https://screener.io/v2/states/Skgr32fUL.microsoft-fluentui/master/1024x768/Chrome/button-compat-root-rtl-hover-0)) on the branch's screener build page, open the little flyout on the left, switch to History view, scroll back to a build around 1/8 for master (or 1/11 for 7.0) to find a note "Accepted from Changed state", and manually open and compare the screenshots.
![image](https://user-images.githubusercontent.com/5864305/104252822-d7729300-5427-11eb-9439-dfa80ca5730e.png)

### Broken states for 7.0
https://screener.io/api/v2/projects/5e753c387bf3181b00090c18/branches/7.0/screenshots/5ffcdf776ede9aca2fa3398f?format=html&filter=changes

Button Default: Root - RTL: hover
Button Action: Root - RTL: hover
Button Compound: Root - RTL: hover
Checkbox Indeterminate: Uncontrolled Indeterminate defaultChecked checkbox: clicked
Checkbox Indeterminate: Controlled Indeterminate checkbox without onChange callback: clicked
Checkbox Indeterminate: Uncontrolled and Controlled Indeterminate checkbox: clicked
ChoiceGroup: Root: selected
ChoiceGroup: Required: selected
ChoiceGroup: With icons: selected
ChoiceGroup: With icons - RTL: selected
ChoiceGroup: With default size images: selected
ChoiceGroup: With large size images: selected
SpinButton: With icon: hover input
SpinButton: With icon - RTL: hover input
TagItem: Selected: Tag Item Select
TagItem: Selected - RTL: Tag Item Select
Tooltip: Default: default

### Changed states for master
https://screener.io/api/v2/projects/5e753c387bf3181b00090c18/branches/master/screenshots/5ff809b46ede9aca2fa33428?format=html&filter=changes

For these ones I didn't actually check all cases to see if the new states are broken, but I suspect a lot of them are.

Button (compat): Root - RTL: hover
Button Action (compat): Root - RTL: hover
Button Compound (compat): Root - RTL: hover
Card Next: Clickable: pressed
Checkbox Indeterminate: Uncontrolled Indeterminate defaultChecked checkbox: clicked
Checkbox Indeterminate: Controlled Indeterminate checkbox without onChange callback: clicked
Checkbox Indeterminate: Uncontrolled and Controlled Indeterminate checkbox: clicked
ChoiceGroup: Root: selected
ChoiceGroup: Required: selected
ChoiceGroup: With icons: selected
ChoiceGroup: With icons - RTL: selected
ChoiceGroup: With default size images: selected
ChoiceGroup: With large size images: selected
CompoundButton: Icon only: hover
CompoundButton Next - Teams Theme: Icon only: hover
ContextualMenu: Root: hover
DatePicker: Root - RTL: hover day
MenuButton: Inverted: hover
MenuButton: Icon only: hover
MenuButton Next - Teams Theme: Inverted: hover
SpinButton: With icon: hover input
SpinButton: With icon - RTL: hover input
SplitButton: Default: hover
SplitButton: Inverted: hover
SplitButton Next - Teams Theme: Inverted: hover
SplitButton Next - Teams Theme: Icon only: hover
TagItem: Selected: Tag Item Select
TagItem: Selected - RTL: Tag Item Select
ToggleButton: Default: checked
ToggleButton: Default: focus
ToggleButton: With icon before content: checked
ToggleButton: With icon before content: focus
ToggleButton: With icon after content: checked
ToggleButton: With icon after content: focus
ToggleButton: Circular: checked
ToggleButton: Circular: focus
ToggleButton: Size largest: checked
ToggleButton: Size largest: focus
ToggleButton: Inverted: checked
ToggleButton: Inverted: focus
ToggleButton: With styled icon from react-icons via tokens: checked
ToggleButton: With styled icon from react-icons via tokens: focus
ToggleButton Next - Teams Theme: Default: clicked
ToggleButton Next - Teams Theme: Default: focus
ToggleButton Next - Teams Theme: With icon before content: clicked
ToggleButton Next - Teams Theme: With icon before content: focus
Tooltip: Default: default

**Comment by andrefcdias** [comment]
I've come across this issue exclusively on #19022 with the `Button Action (compat): Root - RTL: hover` scenario, when adding new stories for converged `Text`. I noticed that this problem would come up whenever I had around 4 or more calls to `.addStory()` for an individual `storiesOf()`.
I couldn't really pinpoint why this would be relevant and why that specific Button scenario but I wanted to also share the information here for future investigation.

**Comment by TristanWatanabe** [comment]
Closing since we're no longer using Screener
