### ISSUE TITLE
[@uifabric/example-app-base] Tooltip is not defined for "Settings" button on homepage 

### ISSUE THREAD

**Issue by tyveille** [microsoft/fluentui#16551]
### Environment Information

Test Environments:
Version:  2004 (OS Build: 20236.1005)
Browser: Edge chromium 
Tool: Developer tool

### Describe the issue:

User Experience:
When navigating to a site using example-app-base, keyboard user will not be able to understand the purpose of the button and can not access the button efficiently if tooltip of the button is not defined.

### Please provide a reproduction of the issue in a codepen:

Unable to use codepen as the issue is located in @uifabric/example-app-base

Navigate on "Settings" button
Inspect it through developer tool
Verify the issue

#### Actual behavior:

Tooltip is not defined for "Settings" button on header of homepage.

#### Expected behavior:

title='Settings' should be defined for "Settings" button on header of  homepage.

### Documentation describing expected behavior

N/A

**Comment by gouttierre** [comment]
@tyveille - thank you for filling this item.

@khmakoto - Please can you check the validity of this issue reported - as it was described that a codepen sample on the reported problem was not possible being located in @uifabric/example-app-base. Therefore, I will need to ask for your expertise if there is enough information to carry on investigate - and if so , this is a regression, or if this behavior is an issue? Thanks

**Comment by ecraig12345** [comment]
You can repro this starting by picking the latest demo site version at https://aka.ms/fluentdemo ([example](https://fabricweb.z5.web.core.windows.net/oufr/8.14.11/)). This is the button in question on the right:

![image](https://user-images.githubusercontent.com/5864305/118921411-fb217a80-b8ec-11eb-8984-e68d6606f8e7.png)

Since using a gear icon for settings is extremely common, it may not need a tooltip (though I did verify that it has screen reader text). @smhigley Am I understanding that correctly?
