### ISSUE TITLE
Documentation doesn't show how to set a 'Teams' Theme and 'strong' scheme on v8 ThemeProvider?

### ISSUE THREAD

**Issue by rdweaver** [microsoft/fluentui#16712]
I am using ThemeProvider in my app by importing ThemeProvider from '@fluentui/react-theme-provider';

I want to be able to set the app theme to be 'Teams' Theme and the Scheme to be 'strong', like you can see in the documentation here:
https://fabricweb.z5.web.core.windows.net/oufr/8.0.0-beta.2/#/examples/themeprovider#Variants
![103558796-2c8c3300-4e83-11eb-87b9-9e96387611a5 (1)](https://user-images.githubusercontent.com/12052413/106300362-6eab5900-6224-11eb-975a-0ecf96078e0c.png)

In those examples you can select a Theme and a Scheme. But I don't see in the code for those how the Theme and Scheme are being set.
Can the documentation be updated to show how to set the Theme and the Scheme for the ThemeProvider?

Products/sites affected: ThemeProvider

**Comment by gouttierre** [comment]
@rdweaver - thank you for filling this issue. I did see that changing the states the of the themes or schemes does not update the code script according to the user selections as the  `const PartialTheme ` stays static in the snippet.

@khmakoto - Would you know if the  `theme `and `schema` selections are meant to update the code snippets dynamically by design? Or if this is a lacking functionality - we will need to add it to the backlog and address it with designers/ devs.
