### ISSUE TITLE
onClear isn't triggered when resizing a SearchBox

### ISSUE THREAD

**Issue by wamoha** [microsoft/fluentui#16725]
### Environment Information
Chrome 88+
Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/WajidHussain/pen/mdOyKVo

### Repro steps

-  Click on the Search box and type some text
-  Focus out (click somewhere outside the text box)
-  Click on the 'X' button on the search box

#### Actual behavior:
The Search box expands and the text isn't cleared.

#### Expected behavior:
The text should be cleared with the expansion. If I comment the line `setExpanded(true);` in the handleFocus, the expected functionality works.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@wamoha Thanks for submitting this and including a codepen! I'm not sure if this is an issue directly with SearchBox or if it's because of the way that resizing on focus moves the click target before the click event happens. I say that because I modified your [codepen](https://codepen.io/slimemold/pen/gOLpMXL?editors=0010) and added a delay to the resize and it appears to work as expected. 

I believe that this happens because both onBlur and onFocus are triggered before the onClick is generated.

**Comment by wamoha** [comment]
Yeah I understand it's related to the customization. I have tried a timeout value earlier and any non-zero timeout is very indeterministic. 100 doesn't work for me at all. 
Have you tried calling the props.onFocus behind a setTimeout of 0 to see if the click handler gets invoked?

**Comment by joschect** [comment]
@wamoha It does seem like this is a bug  and we can't rely on the offset. We'll get this added to our backlog!

**Comment by JustSlone** [comment]
@wamoha I'm not seeing repro anymore on this issue, perhaps it was fixed?
