### ISSUE TITLE
TextField Controlled Email Type Does Not Display Accurate Value

### ISSUE THREAD

**Issue by JaysQubeXon** [microsoft/fluentui#16732]
### Environment Information

- **Package version(s)**:
```
  "@fluentui/react": "^7.155.4"
```
- **Browser and OS versions**: (fill this out if relevant)
Currently observed only in Chrome.
OS: macOS Catalina 10.15.7

### Please provide a reproduction of the bug in a codepen:

Here is a [reproduction](https://codesandbox.io/s/controlled-email-type-textfield-yoxfu?file=/src/App.js) using codesandbox (I don't have a codepen account).

#### Actual behavior:

Controlled TextField with email type does not trim away the value displayed in the input field.

#### Expected behavior:

A controlled TextField with email type should be able to display all changes of the value including trimming it.

### Priorities and help requested:

Are you willing to submit a PR to fix? **No**

Requested priority: **Low**, removing the type property fixes the issue.

**Comment by JaysQubeXon** [comment]
Upgrading to latest @fluentui/react in the codesandbox example does not fix the issue.

**Comment by joschect** [comment]
@JaysQubeXon Thanks for the submission! This is an interesting problem. I believe it's happening because the TextField has  a check that limits the amount of times that onChange is called, so it _only_ calls it when there has been a change in the input value. The interesting thing about Email typed inputs is that they automatically trim the whitespace. You can see that in [this codepen](https://codepen.io/slimemold/pen/OJbVNYM?editors=0011) that uses vanilla html and javascript (you'll need to check the console). 

So there is a bug here but I'm not sure about the resolution. We've prevented onChange being called too often intentionally to prevent consumers from needing to worry about updating their value when nothing has actually changed. But this is clearly causing an issue for you. @ecraig12345 might have some opinions but she is pretty busy. 

Unfortunately, I don't believe that there is a work around for this right now. Can you tell me a little bit more about what you're trying to achieve with the textfield and maybe I can suggest something?

**Comment by JaysQubeXon** [comment]
Thank you for your response @joschect. I was attempting to trim the value so there would be no leading/trailing whitespaces and after digging around I figured out that somehow the `type=email` wasn't playing nice. This is not urgently needed as I've found that removing the `type` prop was good enough.
