### ISSUE TITLE
List component shows blank patches when scrolling quickly

### ISSUE THREAD

**Issue by ankraj12** [microsoft/fluentui#16789]
#### Describe the feature that you would like added

If List - https://developer.microsoft.com/en-us/fluentui#/controls/web/list has a large number of items, scrolling fast on it shows blank patches. It might be a better UX if it shows some shimmer ux while content is loading.

#### What component or utility would this be added to

https://developer.microsoft.com/en-us/fluentui#/controls/web/list

#### Have you discussed this feature with our team, and if so, who
No

**Comment by joschect** [comment]
@ankraj12 Thanks for the submission! We do have a [Shimmering Details List](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/shimmer) although there is still some white gaps that can appear. I believe that this is because the list is virtualized and so it doesn't know how many items to add if fast scrolling is occurring. @dzearing might have more comments but we could add this as a feature potentially.
