### ISSUE TITLE
DatePicker not announcing selected state

### ISSUE THREAD

**Issue by nikhilpuria** [microsoft/fluentui#16919]
### Environment Information

- **Package version(s)**: 7.121.7
- **Browser and OS versions**: All Browser / OS combination

### Describe the issue:

The DatePicker component doesn't announce selected when focus lands on days which is already selected via keyboard. Users will face difficulty to know the selected date if screen reader doesn't announce as selected on already selected date.

### Please provide a reproduction of the issue in a codepen:

This reproduces on demo site and looks like it is not supported currently

#### Actual behavior:

Screen reader is not announcing as selected when focus lands on already selected date inside the DatePicker component.

#### Expected behavior:

Screen reader should announce as selected when focus lands on already selected date inside the DatePicker component.

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-1.1/#aria-selected

**Comment by lorejoh12** [comment]
In FluentUi v7, there were 2 DatePicker controls. The first (older) was in the office-ui-fabric-react package, and had numerous bugs with it, including this one.

The updated version is in @uifabric/date-time, and this works as expected there for me (Narrator, Edge browser, arrow to the selected date and Narrator announces "Feburary 19th, 2021, selected"). You can upgrade to the newer version by importing from @uifabric/date-time instead of from office-ui-fabric-react package. As of FluentUi v8, the new version has been officially merged, and is accessible from both locations (I think date-time has actually been renamed react-date-time in v8).

**Comment by lorejoh12** [comment]
Closing for now. If you were reporting this on the upgraded version of @uifabric/date-time control, please reopen and we can investigate what specific issue you're seeing. In that case, a https://codesandbox.io/ would help, since we have several demo sites floating around and it's not always obvious which demo site is using which version of each control.
