### ISSUE TITLE
Dropdown Component Focus + Dropped placement issue

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/fluentui#16989]
### Environment Information

- **Package version(s)**: 8.0.0-beta.54
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/LeSchmoo/pen/RwopRjK

#### Actual behavior:

Focus Issue:
![image](https://user-images.githubusercontent.com/966863/107933201-56eb0900-6f76-11eb-817a-cd7fc1da40a5.png)

Dropped placement issue:
![image](https://user-images.githubusercontent.com/966863/107933262-69654280-6f76-11eb-8464-2debc79a341e.png)

#### Expected behavior:
Expect Focus to match a regular TextField:
![image](https://user-images.githubusercontent.com/966863/107933347-8ac62e80-6f76-11eb-8710-941858c46db4.png)
Expect Dropped placement to be below the component:
![image](https://user-images.githubusercontent.com/966863/107933509-bcd79080-6f76-11eb-8a22-0ff489154a5c.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: NA

**Comment by joschect** [comment]
@GordonSmith Thanks for the submission! I'm not positive but I believe that this is due to your use of "Float". It looks like that is causing the width of the dropdown to not match it's actual length. You can see in this [version of your codepen where I don't use float](https://codepen.io/slimemold/pen/KKNyBrz?editors=1010) that everything appears fine. Let me know if that helps!

**Comment by GordonSmith** [comment]
@joschect - I agree float is highlighting the issue, but my expectation is that no matter how the DropDown gets positioned, that the "Dropped" portion would match the width and position of the "Non-Dropped" position.
