### ISSUE TITLE
Component icons are not being loaded using SPFx isolated domain:true

### ISSUE THREAD

**Issue by kfircs** [microsoft/fluentui#17030]
### Environment Information

- **Package version(s)**: 6.189.2

### Describe the issue:

While using the SPFx isolated domain the icons that are built in the components for example the Combobox have an arrow on the button that opens up the options are not appearing.
If I'm disabling the isolated domain it does work.

#### Actual behavior:
the arrow is not loaded
![image](https://user-images.githubusercontent.com/26444218/108194448-504bc580-711f-11eb-9a50-ab556756bbea.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/26444218/108200488-37dfa900-7127-11eb-9bb9-fdec88885332.png)

**Comment by joschect** [comment]
@kfircs Thanks for the feedback. This might be a difficult for us to look into because it needs to be hosted within an spfx. But if you could point us to a live codepen that would be super helpful.

One suggestion to try in the meantime is to add a call to initializeIcons() before rendering your UI. The isolated domain might not be initializing the icons for you.

Let us know if you can provide a codepen or try out that suggestion.
