### ISSUE TITLE
DetailsList: can customize "shouldEnterInnerZone" property of list's FocusZone

### ISSUE THREAD

**Issue by kidokidozh** [microsoft/fluentui#17047]
#### Describe the feature that you would like added

Current behavior of DetailsList is, pressing "Right Arrow" key will enter inner FocusZone.
https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/DetailsList/DetailsList.base.tsx#L515
But in some scenarios, we want to customize this "shouldEnterInnerZone" value.

For example, an input table list as below.  Arrow key is used to move cursor inside the input box, it's not convenient to jump to next input box.
![image](https://user-images.githubusercontent.com/58833558/108322603-a04e8900-7200-11eb-8378-6770baa0cac6.png)

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

**Comment by joschect** [comment]
@kidokidozh Thanks for the question! This seems like a reasonable feature to add. We welcome any assistance with community submitted prs as that might speed things up. Otherwise we'll get this added to our backlog.

**Comment by zubinchopra** [comment]
Hey @joschect, first time contributor here. Would like to help out. Any tips that might help me with this feature? I looked at the code for `DetailsList.base.tsx` and it seems that the current mapping for entering inner zone is to the right arrow click.

`shouldEnterInnerZone: isRightArrow,`

Would the expected behavior achieved by checking whether the cursor is an input element or a new mapping is suggested for moving to another input box?

Any steps to repro the issue will be greatly appreciated as well!

**Comment by kidokidozh** [comment]
Hi @zubinchopra  For the expected behavior, I suggest to let user define optional properties to the `FocusZone`.

Here is an example in another component `GroupedList` with the property `focusZoneProps`.  It's more flexible since user can define customized `shouldEnterInnerZone` and choose the behavior they like.
https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/GroupedList/GroupedList.base.tsx#L162

@joschect What do you think? Any other suggestions?

**Comment by richard-einfinity** [comment]
Hi @zubinchopra,

Were you able to progress this any further?

Thank you
