### ISSUE TITLE
The DetailsList - Basic example on the Fluent UI website is not working

### ISSUE THREAD

**Issue by SvampK** [microsoft/fluentui#17210]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:

on the website when I clicke on show code on example, it shows the following error message
"There is an error preventing the code from being rendered:
Error while rendering component: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pen/?editors=1111
see console

#### Actual behavior:

can not see the detaillist example on the FLuent UI website

#### Expected behavior:

When click on the show code button, the UI element still can show, and can still editing the code on Fluent UI website.

**Comment by gouttierre** [comment]
@SvampK - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen. The CodePen you provided is empty. 
![image](https://user-images.githubusercontent.com/78806055/111158183-062bf780-8598-11eb-9328-6a585de2de80.png)

**Comment by schemburkar** [comment]
I think I can help here.

The issue is that on the Fluent UI docs site for DetailsList, there is a live example along with code snippet. The live example works, however when we open the code snippet, the example stops working (without any edits).

This is applicable on following pages of Details List
* https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist
* https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/basic
* https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/compact

Repro GIF
![DetailsListDocs](https://user-images.githubusercontent.com/3159347/111867977-6efedf80-899d-11eb-90c4-868fe16f0d2e.gif)


I found this issue and wanted to dig deeper. Post the deep dive found out that the `<Fabric>` tag causes the issue.
```
<Fabric>
    <DetailList />
</Fabric>
```

On observing the other pages for DetailList, this `<Fabric>` tag does not exist for them.

I have fixed this bug in my [fork](https://github.com/schemburkar/fluentui) with [commit](https://github.com/schemburkar/fluentui/commit/770933821364cf32bddeedb172a0c7b02ef6dce8). 

I'm also opening a PR to fix this...

**Comment by schemburkar** [comment]
PR is open! @khmakoto Anything I can do to help?

**Comment by khmakoto** [comment]
@schemburkar thanks for the PR! I've approved it with a small comment!
