### ISSUE TITLE
ISemanticColors / ISemanticTextColors not updated with latest neutral colors palette

### ISSUE THREAD

**Issue by eszychli** [microsoft/fluentui#17215]
### Describe the issue:

For example, theme.semanticColors.bodyDivider = '#EAEAEA' instead of '#EDEBE9'.
Should be aligned with [color conversion table](https://static2.sharepointonline.com/files/fabric/fabric-website/files/fabric-neutrals-web-color-conversion.pdf).

**Comment by gouttierre** [comment]
@eszychli - thank you for filing this with us.

@khmakoto - Would you be able to confirm if our fabric neutral web colors are up to date?

**Comment by khmakoto** [comment]
@betrue-final-final should we update the values as described above?

**Comment by khmakoto** [comment]
@eszychli I've asked @betrue-final-final offline and it seems that what you are posting is based on old information. I would suggest contacting him if you need more insights on this. Because of that I'll be resolving this as `Not an issue` and `By design`.

Let me know if there's anything else we can do to help.

**Comment by eszychli** [comment]
Thank you, agree the issue was solved

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
