### ISSUE TITLE
NPM Releases missing files?

### ISSUE THREAD

**Issue by GordonSmith** [microsoft/fluentui#17213]
### Environment Information

- **Package version(s)**:  v8.1.1
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

Compare contents of:
* https://cdn.jsdelivr.net/npm/@fluentui/react@8.1.1/dist/ 
* https://cdn.jsdelivr.net/npm/@fluentui/react@7.162.0/dist/ 

#### Actual behavior:

fluentui-react.min.js is missing

#### Expected behavior:

fluentui-react.min.js to exist

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected:

**Comment by ecraig12345** [comment]
Thanks for reporting this, and I'll work on a fix ASAP. The problem here is that most of the stuff that's supposed to be under the package's `dist` folder, including the UMD bundle file, is not getting generated. Still need to investigate why, but I'm wondering if it has something to do with @dzearing's webpack 5 upgrade work.

**Comment by ecraig12345** [comment]
Based on @JustSlone's comment https://github.com/microsoft/fluentui/issues/17208#issuecomment-787622496 I checked unpkg links for 8.0.0-beta.43 vs 8.0.0-beta.44 and that's also when the bundle went missing. 
works: https://unpkg.com/@fluentui/react@8.0.0-beta.43/dist/fluentui-react.js
missing: https://unpkg.com/@fluentui/react@8.0.0-beta.44/dist/fluentui-react.js

beta.44 is when the webpack 5 change #16447 went in, so that's definitely what caused this issue.
