### ISSUE TITLE
How to integrate this library in react-native application?

### ISSUE THREAD

**Issue by shoebtv123** [microsoft/fluentui#17275]
Great library, but How to integrate this library in **react-native** mobile application?

**Comment by MichielDeMey** [comment]
Check out the cross-platform Getting Started: https://developer.microsoft.com/en-us/fluentui#/get-started/crossplatform.
The actual GitHub repo with more setup instructions can be found here: https://github.com/microsoft/fluentui-react-native

**Comment by shoebtv123** [comment]
Hi @MichielDeMey ,

Thanks for your prompt reply but I wanted to use the icons from https://github.com/microsoft/fluentui-system-icons

Please let me know the further steps to integrate the fluentui icons in **react-native**.

Thanks in advance!
Suggestions appreciated.

**Comment by MichielDeMey** [comment]
Since it’s just an icon font, you should be able to download the font file and use https://github.com/oblador/react-native-vector-icons. 🙂

**Comment by gouttierre** [comment]
@shoebtv123 - thanks for filling this question originally. I see you have been assisted since then - if you have any issues with the guidance provided, please, add a CodePen repro with your further questions. You can start from one of the COMPONENT examples (click “Export to CodePen”) or https://aka.ms/fluentpen.
