### ISSUE TITLE
Toolbar visual defects around overflow button and menu

### ISSUE THREAD

**Issue by dwise85** [microsoft/fluentui#17280]
### Environment Information

- **Package version(s)**: 0.52.1
- **Browser and OS versions**: Chrome and Windows

### Please provide a reproduction of the bug in a codepen:

The issue is decently straightforward to reproduce in the current internal version (R0) of Microsoft Teams. What is shown below are the easiest ways to reproduce this issue I have found but may not be all of the potential reproductions.

Case 1:
By resizing the window in small increments you can eventually see the ellipsis fly right out of the toolbar container. This is likely related to its absolute positioning and not pulling out the icon just to its left into overflow.
![image](https://user-images.githubusercontent.com/2475800/110029151-f6372c80-7ce8-11eb-8032-6a0191ac630c.png)

Case 2: By repositioning the window some that compose is around 500 px, then click the ellipsis overflow button to open the overflow menu. Observe that the container shrinks, the ellipsis flies right out of there and aligns to the rightmost edge of the menu that opened:
![image](https://user-images.githubusercontent.com/2475800/110030071-1ca99780-7cea-11eb-97b6-0bef4211b43b.png)

#### Actual behavior:

Ellipsis overflow button is capable of rendering outside of its parent Toolbar container

#### Expected behavior:

Ellipsis should always be contained inside of its' parent container (visually).

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if needed.

Requested priority: Blocking

Products/sites affected: Microsoft Teams feature rollout.

**Comment by ling1726** [comment]
A minimal repro of the problem: https://codesandbox.io/s/fluent-ui-example-forked-y3x4s?file=/example.js:463-464

It seems that during implementation of `Toolbar`'s overflow the scenario where it would be used in `ChatMessage` was never considered.

* chat item sets `float: 'right'` for the message element
* the overflow button in `Toolbar` uses `position: absolute`
* The chat item has no `width` or `minWidth` set
* When the overflow button has menu open the overflow items are removed from the DOM
* The overflow button therefore is not considered in the width calculation of the floated chat item

It seems reasonable that this behaviour should work even if the chat item does not set an explicit width, and therefore should be adressed on Fluent's side.

Two options are obvious for me:

1. Allow a prop to set `position: relative` on the `Toolbar` overflow button once the popup menu is open. This could have an impact on the chat message for different viewports. The change of position should also be done before the popup alignment, or the popup position should be updated. This will need to be tested in TMP-like conditions (possibly with a canary ?). This could be set with a prop so that it is 'opt-in' to avoid potential regressions.

2. When overflow menu is open and the overflow buttons have disappeared, insert a sentinel div with an appropriate width and `visibility: hidden`. This sentinel could also always exist as soon as overflow buttons exist. This feels less intrusive since it just keeps the same behaviour as the other overflow buttons with visibility
