### ISSUE TITLE
Fluent UI GroupedList Selection

### ISSUE THREAD

**Issue by mariache** [microsoft/fluentui#17308]
Playing with FluentUI and trying to make GroupedList working, but I'm stuck and have so many questions about Selection: This is my example: https://codesandbox.io/s/hopeful-chebyshev-n4enr?file=/src/GroupedList.Basic.Example.tsx

What I'm trying to achieve is:

- I need to display the name of selected item;
- In a list of items I'd like to be able to select any (currently, only the last one can be selected)
- I would like to have the first item automatically selected after it's been added;

Priorities and help requested:
Are you willing to submit a PR to fix? No

**Requested priority: High**

**Comment by gouttierre** [comment]
@mariache - Thanks for reach out to us. I will mark this item for the engineering team to review and help you out - but since this not a bug per say - we’re likely not going to get to this request immediately but our team will get back to you. 

@khmakoto - Would you be able to assist with above functionality questions?

**Comment by mariache** [comment]
@gouttierre yes, sure
