### ISSUE TITLE
Tooltip content should be wrapped in <div> instead of <p>

### ISSUE THREAD

**Issue by zhigzhen** [microsoft/fluentui#17344]
### Environment Information

- **Package version(s)**: 7.155.1
- **Browser and OS versions**: N/A

#### Actual behavior:

If a JSX object with a `<div>` other than a `string` is passed into the `content` field of a TooltipHost / Tooltip, the browser will complain with the following error: 

> Warning: validateDOMnesting(...): `<div>` cannot appear as a descendant of `<p>`...

#### Expected behavior:

The browser should not complain because the `content` should be wrapped inside of `<div>` instead of `<p>`. This change can be made on line 71 here: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Tooltip/Tooltip.base.tsx

Another reason for this change, is that `content` field accepts either `string` or `JSX.Element` so it should account for nested objects within a `<div>` when a `JSX.Element` is provided.

source: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Tooltip/Tooltip.types.ts line 33

### Priorities and help requested:

Are you willing to submit a PR to fix? **Yes**

**Comment by gouttierre** [comment]
@zhigzhen - Thanks for reaching out and submitting this issue. I see you are willing to submit a PR for this request - that is great - Would you mind sharing it with us? 

@khmakoto  - can you review the suggestion posted where the `content `should be wrapped inside of `<div>` instead of `<p>`  on line 71 here: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Tooltip/Tooltip.base.tsx
