### ISSUE TITLE
Hover doesn't display actionMenu for chatMessage 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#17352]
I figure out the issue during working on the prototype:
https://github.com/microsoft/fluentui/pull/17329/files

How to reproduce issue:
1. Open prototype in production:
https://fluentsite.z22.web.core.windows.net/0.52.1/prototype-chat-messages
2. Hover over the message in first example: "Chat message with popover and reactions"
![image](https://user-images.githubusercontent.com/22620150/110624874-0e9ebf80-819f-11eb-8381-466435d095a9.png)
Expected: popover is displayed on mouse hover 
Actual: nothing is displayed

Root cause:
Figure out that issue is in chatMessageStyles.ts 

High probably functionality of popover was affected by this commit:
https://github.com/kolaps33/fluentui/commit/061498cbd3f31d83afa7ff6c3515a59ba1071113#diff-28be717ff7f2f2dec34f65ecd408bf248a8374dba016bd971afdfeb23a10c807L89

on line: 89 displaying actionMenu with mouseHover when  variable "showActionMenu" is used.

When I tried change it locally back to 
`zIndex: v.overlayZIndex,`
then it start working - popover starts displaying on mouse hover.

**Comment by gouttierre** [comment]
@kolaps33 - thank you for the information on shared and repro steps. 

 @tomi-msft - can you review this issue and check the [commit](https://github.com/kolaps33/fluentui/commit/061498cbd3f31d83afa7ff6c3515a59ba1071113#diff-28be717ff7f2f2dec34f65ecd408bf248a8374dba016bd971afdfeb23a10c807L89) if it is a possible root cause?
