### ISSUE TITLE
Dropdown - Aria-label doesn't apply on proper element

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#17436]
We got contacted by consumer of dropdown. 

Issue is following:

1. https://codesandbox.io/s/fluent-ui-example-forked-h7vyl?file=/example.js
2. Navigate to the dropdown and verify aria-label is narrated
Actual: aria-label is not narrated, because it doesn't apply on proper(button) element 
Expected: aria-label should apply on button element 

More consideration:
User can do following:
`triggerButton={{"aria-label": "I am drop down"}}`
and will get aria-label to the button. 
Is this enough or do we should support aria-label on the Dropdown?

**Comment by gouttierre** [comment]
@kolaps33 - Thanks for filing this issue with the repro steps + codePen. 

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue with aria-label?
cc @smhigley

**Comment by abmis-mi** [comment]
It seems combobox requries the `label` property to be set in order to emit the `aria-label`. As we use a separate label to show the label and combo side-by-side, we noticed this issue. Fixed this by assigning the label property and hiding using custom styles as in `styles={{ label: {display: 'none' } }}`
