### ISSUE TITLE
SSR issue when DelayedRender is used internally

### ISSUE THREAD

**Issue by fildahui** [microsoft/fluentui#17445]
After one the latest bump to fluentui I noticed all the MessageBars rendered on the server (using the `renderStatic` utility) where flashing on the client and specifically their text content. I had a look at the source code and there is a `DelayedRender` component that wraps the children of the MessageBar: so basically what I guess it's happening now is that the markup returned by the server has no text content cause the content is going to be rendered through a `window.setTimeout` in the `componentDidMount` (of the DelayedRender component) which happens when the app is hydrated.

Is there any way to disable it maybe? because basically I cannot server side render the component since it has to wait for the client (window object) to be actually rendered.

### Environment Information

- **Package version(s)**: 7.155.3

#### Actual behavior:

Component is rendered on the server but due to the presence of a `window.setTimeout` its content it's actually rendered on the client.

#### Expected behavior:

Component should be fully rendered on the server.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low): High

**Comment by gouttierre** [comment]
@fildahui - Thanks for filing this, but you’ll need to add a CodePen repro before we can help. You can start from one of the [MessageBar ](https://developer.microsoft.com/en-us/fluentui#/controls/web/MessageBar )examples (click “Export to CodePen”) or https://aka.ms/fluentpen.

**Comment by fildahui** [comment]
@gouttierre you can have a look here [https://codesandbox.io/s/ssr-issue-with-messagebar-90rqk](https://codesandbox.io/s/ssr-issue-with-messagebar-90rqk)

if you inspect the responses from the server you will see that the first request's response (the page) has the output of the SSR fo the MessageBar but its content is not present (as I said above).

![image](https://user-images.githubusercontent.com/17295499/113752226-a0e5a500-9704-11eb-8b0e-ea4298c5eefb.png)
![image](https://user-images.githubusercontent.com/17295499/113752249-a5aa5900-9704-11eb-8806-94ee60e701b6.png)

And I believe this is somehow similar to this one [https://github.com/microsoft/fluentui/issues/15491](https://github.com/microsoft/fluentui/issues/15491) as there is no window available on the server

**Comment by zdenek-biberle** [comment]
Just came across this when writing some tests with Jest. We're not doing SSR, but having to wait for the contents of the `MessageBar` to appear threw us off a bit.

Does anyone know if there is a reason for the `DelayedRender`? It's got the default delay of zero right now, so I'm not entirely sure that it's doing anything useful, just causing another rerender.

**Comment by fildahui** [comment]
any updates on this?

**Comment by ecraig12345** [comment]
The reason for using the delayed render is to help ensure that the contents of the MessageBar are announced by screen readers. The text announcement works more reliably if the live region (the element wrapping the MessageBar content) is present in the DOM before text is added. 

However, I agree that it could be helpful sometimes to disable the delayed rendering by default, so I made a PR #18443 adding a new prop `delayedRender` which can be used to turn delayed rendering off. If you do this, be sure to follow the suggestions in the new prop comments (demonstrated in a new example) for how to still ensure the message is read for screen reader users.

(Background notes: Delayed rendering of MessageBar children was introduced in #867 and doesn't appear to have changed substantially since then. The only recent change is that #12192 changed the `setTimeout` line in DelayedRender to use `window.setTimeout`, and I'd be surprised if that caused any behavior changes.)

### Testing with delay rendering

To get around the delayed rendering in tests, you'll need to use fake timers. (I noticed this was actually not being done correctly in our own tests, so the PR fixes that too.)

Here's an example using jest and enzyme:
https://github.com/microsoft/fluentui/blob/82e76a7bd475d91cd7c1062ad29eb9e4e24d5714/packages/react/src/components/MessageBar/MessageBar.test.tsx#L158-L176

It's also good to have this cleanup code:
https://github.com/microsoft/fluentui/blob/82e76a7bd475d91cd7c1062ad29eb9e4e24d5714/packages/react/src/components/MessageBar/MessageBar.test.tsx#L14-L18
