### ISSUE TITLE
Links are not clickable in ChoiceGroup with custom option rendering

### ISSUE THREAD

**Issue by lisaharrylock** [microsoft/fluentui#17688]
### Environment Information

- **Package version(s)**: 7.148.1
- **Browser and OS versions**: Edge and Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/brandonthomas/pen/BappwvO

#### Actual behavior:

Link renders but does not respond to clicks, in this case it does not log to console.

#### Expected behavior:

Link should render and respond to clicks.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Low

Products/sites affected: (if applicable)

We have a workaround which is to set the z-Index on the Link element:
https://codepen.io/brandonthomas/pen/bGggYey

**Comment by gouttierre** [comment]
@lisaharrylock - thanks for reaching out and sharing the repo steps.

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by miroslavstastny** [comment]
Not a regression, I see the same behavior in OUIFR 7.155.3 (from Dec 2020).

The reason is the `ChoiceGroupOption` renders a `label` with the content and a `input type=radio` which is absolutely positioned to cover the whole label and capture the clicks.

After setting the `zIndex`, the link is clickable but not sure accessibility is correct - the whole choice group is a single tab stop with up/down keys navigation between the options, the link is the next tab stop after the choice group.
