### ISSUE TITLE
Add fix column function on DetailsList component

### ISSUE THREAD

**Issue by Lijiaoa** [microsoft/fluentui#17789]
#### Describe the feature that you would like added
Add the function `fix column` on `DetailsList` component.

#### What component or utility would this be added to
DetailsList

#### Have you discussed this feature with our team, and if so, who
no

#### Additional context/screenshots
Look like this picture, the column `Full Name` and `Age` is fixed. I think it's a popular usage. Please consider whether to do it.
![image](https://user-images.githubusercontent.com/61399850/114486572-bb59da00-9c40-11eb-87f8-f447f3aa676f.png)

**Comment by Lijiaoa** [comment]
emmm... Is there any progress on this matter? Thanks.

**Comment by tomi-msft** [comment]
Hi @Lijiaoa, thanks for submitting this feature request.

We our focusing most of our engineering efforts on vNext components, won't have the bandwidth at the moment to implement new feature requests since it would require a significant reworking of the structure of DetailsList to support fixed columns that are performant while still supporting the semantics required to make them accessible to screen reader users.

However, if you have any ideas on how to implement this feature we would welcome any contributions to our repo!

**Comment by Lijiaoa** [comment]
Thanks for your feedback!
