### ISSUE TITLE
[Details List] Adding described-by for items in a row

### ISSUE THREAD

**Issue by somoo88** [microsoft/fluentui#17912]
#### Describe the feature that you would like added

A way for screen readers to announce which columns the item is in when announcing the row. For example, if we had a table like this:

Name | Role | Status
Andy Engineer Away

When reading the 2nd row, it should say something along the lines of 'Name Andy, Role Engineer, Status Away.' Please let me know if there is already a functionality for this.

This would be good for accessibility purposes as well.

#### What component or utility would this be added to

This would be indicated by a prop in DetailsList

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

N/A

**Comment by gouttierre** [comment]
@somoo88 - Thanks for reaching out. At the moment our detailsList API has a getRowAriaDescribedBy which does not seem to answer your needs. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
