### ISSUE TITLE
Controlled dropdown cannot reset value

### ISSUE THREAD

**Issue by PatoBeltran** [microsoft/fluentui#17927]
### Environment Information

- **Package version(s)**: latest v8 

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/PatoBeltran/pen/dyNwMzd?editors=0010

#### Actual behavior:

When passing onChange and selectedKey(s) to a dropdown, in theory you should be able to send `null` to clear the value, but doing that make's it so that the users are not able to select a new option anymore.

#### Expected behavior:

If `null` is passed, the dropdown should clear the value and allow for the user to interact with the dropdown as if it was the default state of the dropdown

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @PatoBeltran, it seems like the issue is that you're not passing your defined `onChange` function to the component itself in your codepen, which makes the component start behaving as an uncontrolled component, but on clicking on the `Clear` button it receives `null` as the selected state for the first time and becomes a controlled one.

Actually passing `onChange` fixes the issue as can be seen in [here](https://codepen.io/khmakoto/pen/NWdedpR?editors=0010). Let us know if there's anything else we can do to help!
