### ISSUE TITLE
Range Slider, make central active region draggable to move both value and lowervalue of range

### ISSUE THREAD

**Issue by bmckilligan** [microsoft/fluentui#17975]
#### Describe the feature that you would like added

Make the central span  between the Range Slider thumbs,  (marked with the class activeSection) , draggable to create a moving window for the range selection
 
Sliders (Ranged Slider, vertical and horizontal)

https://github.com/microsoft/fluentui/issues/9264#issuecomment-588487332

**Comment by bmckilligan** [comment]
+1 on having this component. I would also like this new range slider to have the ability to "grab" the bar between the thumbs, and move both thumbs simultaneously while maintaining the distance between them.

_Originally posted by @danmarshall in https://github.com/microsoft/fluentui/issues/9264#issuecomment-588487332_

**Comment by gouttierre** [comment]
@bmckilligan - thank you for reaching out to use and suggesting this feature request.  I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. But if you are willing to submit a PR for this feature request we would love to see it!
