### ISSUE TITLE
Upgrade prettier

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#18008]
This "blocks" #17996. Adding *.mdx to .prettierignore.

prettier 1.19.1 reports errors on valid MDX files:

```sh
> yarn prettier --version
1.19.1

> yarn prettier -c packages/react-examples/src/react-components/FluentUIComponents/Introduction.stories.mdx
...
Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.

> npx --ignore-existing prettier@2.2.1 -c packages/react-examples/src/react-components/FluentUIComponents/Introduction.stories.mdx
All matched files use Prettier code style!
```

The first version of prettier which seems to work is 2.1.0.

**Comment by ecraig12345** [comment]
Whoever upgrades prettier should also run it on the whole repo to avoid extra formatting noise on individual PRs. If we want the change to be less noisy it would help to enable `arrowParens: 'avoid'` since [the default in v2 changed to `always`](https://prettier.io/docs/en/options.html#arrow-function-parentheses). (I don't have a strong opinion about what the value of this setting ought to be; the suggestion of preserving the old setting is only to reduce noise.)
