### ISSUE TITLE
Components based on toggle visibility hides on scroll.

### ISSUE THREAD

**Issue by vamshi9666** [microsoft/fluentui#18080]
Note: Not sure if this is a bug or its part of the design.

Actual behavior:
Most components that are toggled (pickers, dropdown, combobox, etc.) hides/dismiss on scroll. I often found it a bad user experience when i accidentally scroll, or wants to scroll to look for more details.

Expected behavior:
The toggled components will retain its visibility state on scroll.

Priorities and help requested:
Are you willing to submit a PR to fix? No

Requested priority: Normal

copy from #13730

**Comment by khmakoto** [comment]
Hi @vamshi9666, this behavior is our default by design, but we do provide a way to disable this behavior in our components via the `preventDismissOnScroll` prop that's part of `calloutProps`. You can take a look at [this codepen](https://codepen.io/khmakoto/pen/jOBEKgq?editors=0010) to see this implemented in the `Dropdown` component.
