### ISSUE TITLE
There are some css properties which can be added into the `IRawStyleBase`

### ISSUE THREAD

**Issue by yifanwww** [microsoft/fluentui#18111]
#### Describe the feature that you would like added

There are some css properties which can be added into the `IRawStyleBase`, such as:
- `justify-items`
- `place-content`
- `place-items`
- `place-self`

**Comment by gouttierre** [comment]
@YF1999 - thanks for reaching out.  I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. Unless you wish to submit a PR for this request - we always encourage contributions.

**Comment by YF1999** [comment]
Thanks for your reply, I will try to submit a PR.
