### ISSUE TITLE
FluentUI react inputs in Dialog is not trigging the JSLL mousedown events.

### ISSUE THREAD

**Issue by RichardSunPersonal** [microsoft/fluentui#18112]
### Environment Information

- **Package version(s)**: 7.155.3
- **Browser and OS versions**: Windows Enterprise 10 / Edge  90.0.818.56

### Describe the issue:

The JSLL hooked mouse down events in buttons/inputs on Dialog are not triggered at all, looks prevented by Fluent UI built-in events. 
Please check the default page of Fluent: https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog

#### Actual behavior:

There isn't any JSLL events sending out when clicking the buttons in Dialog, e.g.  https://web.vortex.data.microsoft.com/collect/v1?$mscomCookies=false&ext-javascript-msfpc=%27GUID%3D3f97bf8c2662462094a452ec38fa15b7%26HASH%3D3f97%26LV%3D201904%26V%3D4%26LU%3D1556614209868%27

#### Expected behavior:

There should be events triggered and sending the requests out.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected:

**Comment by TristanWatanabe** [comment]
@RichardSunPersonal: can you please provide us with an isolated repro starting from https://aka.ms/fluentsandbox or https://aka.ms/fluentpen? There's currently not enough information for us to troubleshoot.

**Comment by RichardSunMS** [comment]
@TristanWatanabe , I don't have isolated repo now, and I don't think it is needed because this can be repro on FluentUI controls official website: https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog.
If you go to this url (F12 with developer tools opened) and click the show dialog on the page, then click the buttons on the popup dialog. Please pay attention to the F12 networks, you can see the buttons to show the dialog is sending the JSLL requests, but the buttons in the popup dialog is not. 

Please let me know if you need more information. 

Thanks.
Richard.

**Comment by RichardSunMS** [comment]
@TristanWatanabe , not quite sure whether you still need more information or not. please let me know.
