### ISSUE TITLE
TextField: Cannot set property value of #<TextFieldBase2> which has only a getter

### ISSUE THREAD

**Issue by tianyu94** [microsoft/fluentui#18126]
### Environment Information

- **Package version(s)**: 8.14.4
- **Browser and OS versions**: latest Chrome, Windows 10

### Please provide a reproduction of the bug in a codepen:

```tsx
const { control, handleSubmit } = useForm<any>({
  defaultValues: {
    version: 0,
  },
});

// ...

<InputText name="version" label="Version" control={control} />
```

```tsx
type InputProps = ITextFieldProps & UseControllerProps<any, any>

const InputText: React.FunctionComponent<InputProps> = (props) => {
  const { field, fieldState } = useController(props);

  return (
    // eslint-disable-next-line react/prop-types
    <TextField {...field} label={props.label} errorMessage={fieldState.error?.message} />
  );
};

export default InputText;
```

#### Actual behavior:

```text
Uncaught TypeError: Cannot set property value of #<TextFieldBase2> which has only a getter
    at useForm.ts:287
    at updateValidAndValue (useForm.ts:543)
    at registerFieldRef (useForm.ts:951)
    at ref (useForm.ts:994)
    at ref (useController.ts:98)
    at commitAttachRef (react-dom.development.js:20875)
    at commitLayoutEffects (react-dom.development.js:23431)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
```

#### Expected behavior:

set default value by react-hook-form's `useForm({defaultValues: {...}})`. Can successfully set the default value.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
Thanks for filing an issue, but especially for interactions with 3rd-party libraries, it's helpful to have a full live repro rather than just code snippets to make it easier for us to investigate and to ensure we're looking at the exact same scenario as you are. Can you please a live repro starting from https://aka.ms/fluentsandbox or https://aka.ms/fluentpen?

**Comment by ecraig12345** [comment]
Thanks for the repro and sorry for the delayed response! Unfortunately I think this is by design at the moment; TextField only supports updating its value via `props.value`, not by setting the value directly on the field. You could potentially make a wrapper like this to support setting the value: https://codesandbox.io/s/18126-textfield-with-value-setter-s5v49

**Comment by tianyu94** [comment]
Thx :)
