### ISSUE TITLE
Add shimmer when image is being loaded from URL

### ISSUE THREAD

**Issue by hoale-mscom** [microsoft/fluentui#18176]
#### Describe the feature that you would like added

When Image component get a URL it might take a while for the image to fully loaded from the internet. During the loading time we should show the shimmer to avoid empty space experience.

#### What component or utility would this be added to

Image

#### Have you discussed this feature with our team, and if so, who

No 

#### Additional context/screenshots

Something like this : 

![imageShimmerSafe](https://user-images.githubusercontent.com/84152488/118178055-5aacf100-b3e8-11eb-9c75-fda407cad467.gif)

**Comment by hoale-mscom** [comment]
@TristanWatanabe @ecraig12345 is this one considered approved and will be schedule ?

**Comment by gouttierre** [comment]
@hoale-mscom - thank you for reaching out and suggesting this change.  I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. However, if you have an idea on the implementation and wish to submit a PR for this to help speed up the process - we would love for you to share it with us?
