### ISSUE TITLE
[Icons] React-Icons-Northstar - Add support for FilesTxtIcon outline / filled mode

### ISSUE THREAD

**Issue by felixSchober** [microsoft/fluentui#18219]
#### Describe the feature that you would like added

Most icons in react-icons-northstar can be used with filled or outline mode. FilesTxtIcon and FilesTextColoredIcon do not support this.
Furthermore, both icons use a hardcoded white background color which makes theming harder (see below) and on light background harder to read. 

#### What component or utility would this be added to

Either update the existing icons and make them work the same way the other icons work (e.g. [CloseIcon.tsx](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-icons-northstar/src/components/CloseIcon.tsx) or add a styleable version as a new icon.

#### Additional context/screenshots

[FilesTxtIcon.tsx](https://github.com/microsoft/fluentui/blob/master/packages/fluentui/react-icons-northstar/src/components/FilesTxtIcon.tsx)

Light Mode - Dark Mode Comparison with styleable icon.

![image](https://user-images.githubusercontent.com/10966969/118526894-9e7d5e80-b738-11eb-9271-8e5d8b8a2153.png)

**Comment by gouttierre** [comment]
@felixSchober - Thanks for filing this item and the suggestion. I’ve added this to our fluent backlog for review but it’s lower on our priority list so we’re likely not going to get to it right away due to the fact we’re currently focused on larger coherence controls. Would you be willing to submit a PR for this enhancement? 

@jurokapsiar / @kolaps33 - Would you know if there are immediate plans for North-star to support filled or outline mode for `FilesTxtIcon `and `FilesTextColoredIcon`?
