### ISSUE TITLE
GroupHeader with no expand/collapse functionality

### ISSUE THREAD

**Issue by molinger** [microsoft/fluentui#18228]
#### Describe the feature that you would like added

We would like to hide the expand/collapse button on a GroupHeader for groups that have no children.

#### What component or utility would this be added to

GroupHeader

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

We currently implement this in our feature by overriding onRenderHeader. It renders a GroupHeader but we pass it a dynamically generated styles prop that lets us make various changes based on the group that we are rendering the header for. This lets us hide the expand/collapse button but the group header still has the aria-expanded attribute set to either true or false. Ideally, it would be undefined in this case since the header does not support expand/collapse.

There is no way to override the aria-expanded attribute and this is a blocker for our implementation. It would be great if we had native support for disabling expand/collapse or at the very least, if we could override this attribute.

For clarity, we need the header to not allow expand/collapse but still have a spacer so it lines up with other headers that do support expand/collapse on the same level.

**Comment by gouttierre** [comment]
@molinger - thanks for reaching out and suggesting this request. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. However, if you got an idea on the implementation - please feel free to share it with us.
