### ISSUE TITLE
JAWS isn't reading onText and offText for Toggle

### ISSUE THREAD

**Issue by raharri** [microsoft/fluentui#18346]
### Environment Information

- **Package version(s)**: 8.15.0
- **Browser and OS versions**: Chrome 90.0.4430.212 for Windows 10

### Describe the issue:

When using Narrator, if a Toggle has onText and offText those are read when the Toggle state is changed, but for JAWS the only acknowledgement of the changed state is "on" or "off"

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/raharri/pen/yLMoOGd

#### Actual behavior:

When toggling the control, JAWS only reads out "on" and "off"

#### Expected behavior:

JAWS should read out the onText and offText as they get updated (note: this can be achieved by adding an aria-live="polite" property to the label of the toggle, which will then read out the new label text as it gets updated, I'm just not sure if this could also have any potential negative side effects)

### Documentation describing expected behavior

https://microsoft.sharepoint.com/:w:/s/accessibility/Eb176e6QmaBIiwNup3VYGqgBsCOGQmSqjdTXmFAAMm75Mw?e=ZP6hWt

**Comment by gouttierre** [comment]
@raharri - thank you for filing this issue with us and sharing the codepen repro details.
@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by smhigley** [comment]
@raharri thanks for filing the issue! I think this is a good example of where we could improve our documentation to include better accessibility guidance -- currently our docs have some recommendations for the on/off text, but not accessibility-specific information.

What we *should* say in the guidance is this: while the on/off text can be made more specific, it should always be redundant to the label of the switch + the current state. It's essentially intended to be extra helper text for sighted users to be confident that the switch is actually in the correct state (beyond guessing based on color and left/right position).

If the on/off text is modified to include unique information that isn't conveyed through the label and state, it would be a separate accessibility issue because then the name or description of the control would be changing based on user interaction, which is not a good practice. We absolutely should not make the label or descriptive text into a live region, since that would conflict with the native state change announcement, create unwanted extra verbosity, and play havoc with braille displays.

It looks like the best solution would be to update the docs to essentially summarize constraints for on/off text usage in an accessibility best practices section, similar to ones I've been adding in other components (e.g. https://developer.microsoft.com/en-us/fluentui#/controls/web/pickers).

**Comment by pizzaz93** [comment]
Would the fix be localized to the [toggle](https://developer.microsoft.com/en-us/fluentui#/controls/web/toggle) or for all the controls across all contexts (Android, iOS, cross platform etc.)?
