### ISSUE TITLE
ProgressIndicator: ARIA progressbar nodes must have an accessible name

### ISSUE THREAD

**Issue by ghassane23** [microsoft/fluentui#18351]
### Environment Information

- **Package version(s)**: 8.14.5
- **Browser and OS versions**: Edge, Windows

### Describe the issue:

Accessibility insights for Web returns an error when rendering the ProgressIndicator without a Label or Description even though we provide an AriaValueText.

### Please provide a reproduction of the issue in a codepen:

Codepen link: 
https://codepen.io/gadnani/pen/xxqLdLb
<ProgressIndicator ariaValueText="Hello world" />

#### Actual behavior:

ARIA progressbar nodes don't have an accessible name

#### Expected behavior:

ariaValueText is used to give the progress indicator an aria-label

### Documentation describing expected behavior

![image](https://user-images.githubusercontent.com/12913386/119755520-0299d400-be57-11eb-8fe0-9889dacae598.png)

**Comment by gouttierre** [comment]
@ghassane23 - Thanks for filing this issue with us and sharing the details into the problem.

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @smhigley

**Comment by smhigley** [comment]
@ghassane23 the `ariaValueText` component prop will set the `aria-valuetext` DOM attribute, which is unrelated to the accessible name. The `aria-valuetext` attribute provides a custom text alternative to the current *value* of the progressbar, similar to the value of any other form field.

To give the progressbar an accessible name, you can use the `label` prop. If needed, you could style it to be visually hidden.

@miroslavstastny another thing we could look into is adding an `ariaLabel` prop to the ProgressIndicator component, since it looks like we don't currently have one.

**Comment by rachelgshaffer** [comment]
Adding my two cents: I like the idea of adding `ariaLabel` prop
