### ISSUE TITLE
 Narrator announces incorrect name  in fabric control datepicker for “year 2021” instead it announces only “2021” 

### ISSUE THREAD

**Issue by Renuka8796** [microsoft/fluentui#18385]
**Environment Information**
Package version(s): "@fluentui/react": "^7.126.0",
Browser and OS versions: chrome and Windows 10
Describe the issue:
Narrator announces incorrect name for “year 2021” instead it announces only “2021” 

Please provide a reproduction of the issue in a codepen:   https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker
**Actual behavior:**

Narrator announces incorrect name for “year 2021” instead it announces only “2021”

Similar issue is observed with Chrome +NVDA.
**Expected:**
The narrator should announce the year as "year 2021" instead of "2021"

**Comment by gouttierre** [comment]
@Renuka8796  - thanks for filing this issue with us and the details into the problem.
 
@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?
cc @miroslavstastny

**Comment by smhigley** [comment]
@Renuka8796 we need some more information to investigate this, specifically:
- Which control do you think should be named "year 2021" instead of "2021"?
- Why do you believe the accessible name should include the word "year"?

thanks!

**Comment by Renuka8796** [comment]
Hi smhigley,
The issue is with the date picker control, when the calendar was opened and while changing the year in the calendar, the narrator should announce the year as "year 2021" instead of "2021".

**Comment by smhigley** [comment]
@Renuka8796 the current behavior is intentional -- the year changes after a user has explicitly interacted with a control for changing the year. Including the word "year" in there is redundant, and only adds extra verbosity in something that debatably doesn't need a live announcement at all.

We would need evidence that actual screen reader users prefer the more verbose announcement before we consider this change, especially since it would go against the best guidance we current have available.

Could you provide more background on why you have the expectation that the announcement should include the word "year"?
