### ISSUE TITLE
Ability to configure Tooltip-specific Callout styles in theme

### ISSUE THREAD

**Issue by jtbandes** [microsoft/fluentui#18408]
#### Describe the feature that you would like added

Tooltip uses a Callout to render the popup, but `ITooltipStyles` doesn't seem to contain a `subComponentStyles` that allows you to set styles for its callout.

Specifically I want to configure the background color for the tooltip's beak/beakCurtain, and padding etc. (Not **all** Callouts...just the ones used for Tooltips.)

#### What component or utility would this be added to

Tooltip

#### Additional context/screenshots

Currently it seems like I have to do:

```ts
// In my Theme...
  components: {
    Tooltip: {
      styles: ({ theme }: ITooltipStyleProps): Partial<ITooltipStyles> => ({
        root: { background: theme.palette.neutralDark },
        content: { background: theme.palette.neutralDark },
      }),
    },
  }

// And wherever I want to use a tooltip...
    <TooltipHost
      calloutProps={{
        styles: {
          beak: { background: theme.palette.neutralDark },
          beakCurtain: { background: theme.palette.neutralDark },
          calloutMain: { background: theme.palette.neutralDark },
        },
      }}
     ...
    />
```

Here's a real world example where we had to make a wrapper component to apply appropriate styles to Tooltips: https://github.com/foxglove/studio/blob/a44955ab3444821904ff6c732f7631e97311533a/app/components/Tooltip.tsx#L57-L85

_Originally posted by @jtbandes in https://github.com/microsoft/fluentui/discussions/17772_

**Comment by gouttierre** [comment]
@jtbandes - thanks for filing this request. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. However, in the interim if you have an idea on the implementation and would like to contribute - please fee free to submit a PR for this feature request.
