### ISSUE TITLE
Dropdown not work with TeachingBubble

### ISSUE THREAD

**Issue by EYHN** [microsoft/fluentui#18418]
### Environment Information

- **Package version(s)**: 8.16.0
- **Browser and OS versions**: firefox macos

### Please provide a reproduction of the bug in a codepen:

demo: https://codepen.io/huaji/pen/BaWYpBQ

#### Actual behavior:

Unable to open drop-down box when TeachingBubble is visible.

#### Expected behavior:

The drop-down selection box should work fine.

### Priorities and help requested:

> Are you willing to submit a PR to fix?

I don't know what's happening. If I figure out why, I'll be glad to submit pr.

**Comment by gouttierre** [comment]
@EYHN - thank you for filing this issue and great to see that you are willing to submit a PR for the fix!

@miroslavstastny - Would you be able to confirm if this is a regression, or if this behavior is an issue? 
If confirmed, would be able to guide @EYHN on the implementations for a fix? Thank you

**Comment by ling1726** [comment]
@EYHN this issue is caused by the `TeachingBubble` having a `FocusTrapZone` nested inside it. Even when there are no buttons declared in props, empty focusable buttons are rendered. This could be an a11y bug @smhigley. The focus trap will blur the dropdown callout and cause it to dismiss

In your case since you don't use any buttons in your example you might not need to trap focus, here is an example where you can work around this by configuring the `FocusTrapZone` in `TeachingBubble`: https://codesandbox.io/s/hidden-meadow-0ids8?file=/src/App.js

**Comment by EYHN** [comment]
@ling1726  Thank you for your answer, this solved my problem perfectly.

If you don't think this needs to be fixed, please close this issue.
