### ISSUE TITLE
Master branch (8.0) azure-theme no longer being applied to storybook package

### ISSUE THREAD

**Issue by Jacqueline-ms** [microsoft/fluentui#18448]
### Environment Information

- **Package version(s)**: Master branch 

#### Actual behavior:
None of the Azure style sheets are being applied to the controls in story book, nor are any new changes being seen. I expect this has to do with the vNext updates. 

To reproduce: 
> yarn start (master branch)
> fluentUI/azure-themes
In story book, you can see the azure-themes are not being pulled in. 
<img src="https://user-images.githubusercontent.com/30805892/120723303-57a49e00-c486-11eb-87e2-b205bf168fd8.png" width="300" />
<img src="https://user-images.githubusercontent.com/30805892/120723433-93d7fe80-c486-11eb-8ae2-8ab64b23a9b1.png" width="300" />

#### Expected behavior:

<img src="https://user-images.githubusercontent.com/30805892/120724399-9a677580-c488-11eb-8303-943a57ca7430.png" width="300"/>
<img src="https://user-images.githubusercontent.com/30805892/120724451-b2d79000-c488-11eb-95d9-9af5e7e5d9d6.png" width="300"/>

### Priorities and help requested:
Are you willing to submit a PR to fix? Happy to if I could be pointed in the right direction. 

Requested priority: Blocking. 

Products/sites affected: Azure theme 8.0 cherry picking.

**Comment by gouttierre** [comment]
@Jacqueline-ms - thank you for filing this issue and showing willingness to contribute to the solution.

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue? Depending on the outcome of your investigations could guide @Jacqueline-ms on the PR? Thanks in advance. 

cc @miroslavstastny -- (storybook)

**Comment by ecraig12345** [comment]
I'm wondering if this is a bad interaction between Customizer and ThemeProvider, since in version 8 both are being used in the azure-theme stories. (Unfortunately I'm not familiar enough with either one to say for sure.) 
https://github.com/microsoft/fluentui/blob/874be4906a0177df3316e2a15a88dc699836bca9/packages/react-examples/src/azure-themes/stories/Themes/Themes.stories.tsx#L153-L157

I tried switching it to use only the ThemeProvider, and it seemed to work. @Jacqueline-ms Can you try that out, and if it seems correct to you too, make a PR?
```tsx
  <ThemeProvider theme={AzureThemeLight} applyTo="body">
    <Example />
  </ThemeProvider>
```
