### ISSUE TITLE
fluent ui add icon text below icon of button 

### ISSUE THREAD

**Issue by UmamaheshwariGolla** [microsoft/fluentui#18523]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric][fluentui-react] [fluentui](https://stackoverflow.com/questions/tagged/office-ui-fabric).

If you are a Microsoft employee you can also join the "Fluent UI Community" Teams channel.

**Comment by gouttierre** [comment]
@UmamaheshwariGolla - thanks for reaching out with your request of adding icon text below icon of button. 
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
