### ISSUE TITLE
INavStyle Group not updating text color

### ISSUE THREAD

**Issue by ademkikaj** [microsoft/fluentui#18532]
I have this particular style that I am adding to a Nav element.
```
const navStyle: Partial<INavStyles> = {
  groupContent: { marginBottom: 0 },
  group: { marginBottom: 80, color: "red" },
};
```
This piece of code does indeed adds a margin-bottom between groups but it does not update the color of the Group Header. My current workaround is:

```
const _onRenderGroup = (group) => {
  return <span style={{ color: "red" }}>{group.name}</span>;
};
```
Edit: When I edit the `INavStyleProps.groupHeader` with the current workaround it loses all the functionality such as Chevron Icon and its nested links. I get plain `<span>` in red.

**Comment by ecraig12345** [comment]
I think it would be reasonable to add `INavStyleProps.groupHeader` (with no styling by default) to allow style overrides of the group headers. This isn't something our team is likely to get to any time soon due to other priorities, but if anyone is interested in contributing it, I'd be happy to provide more detailed guidance if needed and review a PR.

**Comment by tanisha2710** [comment]
@CheerfulSatchel  is it something you are looking at? I was looking to contribute to OSS, let me know about its status

**Comment by bytrangle** [comment]
Hello @CheerfulSatchel , are you working on this issue? I'm interested in it, so please let me know about its status.
