### ISSUE TITLE
Disable a HoverCard

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#18568]
#### Describe the feature that you would like added

In some situations, such as I want to make a HoverCard disabled until I've got the data in this HoverCard, this feature should be useful, but as I know, the HoverCard seems haven't implemented this feature yet.

#### What component or utility would this be added to

HoverCard in web.

#### Have you discussed this feature with our team, and if so, who

No, I haven't.

#### Additional context/screenshots

None.

**Comment by AkiraVoid** [comment]
I tried to set the styles of HoverCard, like: `visibility: hidden`, but the shadow will be left.

**Comment by gouttierre** [comment]
@AkiraVoid - thanks for filing this request. I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. But if you manage to come up with a solution in the interim - please feel free to submit a PR for the request and our team will review it.
