### ISSUE TITLE
Fluent UI V8 - Checkbox\Toggle component checked state cannot be set if initial checked value is undefined

### ISSUE THREAD

**Issue by mirestom** [microsoft/fluentui#18575]
I have a scenario that broke when updating from Fabric v7 (7.165.1) to Fluent UI v8 (8.14.7).

 

 In Fluent UI v8, in the Checkbox component, if you start with an “undefined” value for the “checked” prop and then you try to set its value to “true”, the Checkbox component never changes its UI rendering to be in a checked state. This is breaking some of our scenarios where our developers assumed that “false” was equivalent to “undefined” for the initial state.

 

Is this a known issue? I assume that other people could've made the same assumption (as it was working before) and therefore this would break their usage of the Checkbox\Toggle components when upgrading to Fluent UI v8.

 

https://codepen.io/miguelresto/pen/XWModWV

@ecraig12345

**Comment by ecraig12345** [comment]
The issue here is that in version 8, we switched some components to use the `useControllableValue` hook, which currently determines whether the component is controlled or uncontrolled on first render and doesn't allow that to change. If the initial value is `undefined`, the component is assumed to be uncontrolled (React makes this assumption as well), so changing it to be controlled is an error.
https://github.com/microsoft/fluentui/blob/3fccf5c8a8ea30529b736b9189e294969242f886/packages/react-hooks/src/useControllableValue.ts#L46

It's generally recommended not to use undefined as an equivalent for an initial value of false; React's built-in input element would allow the change but warn about it [as shown here](https://codepen.io/ecraig12345/pen/OJprowG?editors=0011). The fact that the component was previously encouraging bad practices isn't great, but we also didn't intend to break this behavior without warning.

This actually came up in a conversation with @ling1726 about how controlled stuff should work in converged, and he ended up adding logic similar to what React does to allow the change with a warning [as seen here](https://github.com/microsoft/fluentui/blob/3fccf5c8a8ea30529b736b9189e294969242f886/packages/react-utilities/src/hooks/useControllableValue.ts#L49). So it's possible that we could do something similar in version 8, but I'd want to think a bit more about the implications.

**Comment by gouttierre** [comment]
@mirestom - thanks for filing this issue. 

@ling1726 -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by ling1726** [comment]
This is a bug in v8, and is being fixed in converged with a new hook in #18881 which forces consumers to declare an explicit initial state.

@gouttierre  feel free to assign someone in the v8 team to port that implementation to v8 as a fix
