### ISSUE TITLE
DetailsList: when selectionMode == none, remove focusability from row

### ISSUE THREAD

**Issue by lifwan** [microsoft/fluentui#18611]
### Environment Information
- **Package version(s)**:@fluentui/react 8.17.1
- **Browser and OS versions**: Edge 91.0.864.41 (64-bit), Win 10 Enterprise Version 21H1 OS build 19043.985

### Describe the issue:

When rendering DetailsList with `selectionMode` is none, the list rows are still focusable.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/lifwan/pen/WNpmxgM

#### Actual behavior:

When SelectionMode.none is used on the details list, focus moves to non-interactive table. However this is confusing as the list should not allow selection.

#### Expected behavior:

When SelectionMode.none is used with the details list, the focus should not move to non-interactive table data.

### Documentation describing expected behavior

https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html

**Comment by hetanthakkar1** [comment]
@lifwan I am on it

**Comment by ThomasMichon** [comment]
Just because items in a `DetailsList` aren't selectable, it doesn't mean they aren't actionable. `DetailsList` and `SelectionZone` also accept an `onItemInvoked` callback, so that if the user's keyboard focus is on a row and they hit the enter key, an action will be taken.

A `DetailsList` should only become completely non-focusable if there is not an `onItemInvoked` callback set up for its rows.

Also, keep in mind that rows may be rendered containing focusable sub-widgets, again even if the items are not selectable. Currently the only way to navigate to the focusable widgets within rows is by first using the arrow keys to navigate to the rows themselves. Thus, the focusability of rows provides a crucial navigabilty to sub-content.

Disabling focus in a `DetailsList` thus likely needs to be an explicit option on its own, such as
```
<DetailsList
  focusZoneProps={ {
    disabled: true
  } }
  ...
/>
```

**Comment by ecraig12345** [comment]
In response to the PR, I made [this codesandbox](https://codesandbox.io/s/18611-detailslist-without-hover-styles-9ceox?file=/src/index.tsx) demonstrating how to disable the hover styles (since that's what the PR covered). I'm leaving the sandbox link here in case it's useful to anyone, but on reading through the issue, the real problem is *focusability* not just styling.

The fundamental issue here is that although we do provide a `SelectionMode.none` option, DetailsList wasn't really designed for use with non-interactive content. However, since Fluent UI doesn't currently provide a good non-interactive alternative for rendering tabular data with all the appropriate styling, it might make sense to add either `focusZoneProps` like @ThomasMichon suggested (and possibly do some styling modifications if `focusZoneProps.disabled` is set), or an explicit flag which disables *all* focus-related behavior. @ThomasMichon or @smhigley any thoughts?
