### ISSUE TITLE
Slider bar is moving even after moving mouse cursor outside the slider.

### ISSUE THREAD

**Issue by srinidhiprabhu96** [microsoft/fluentui#18644]
### Environment Information

- **Package version(s)**: 7.164.0(fill this out)

### Describe the issue:
Click the mouse on the slider. Without releasing the mouse click, moving the mouse changes the value in the slider even if the mouse is outside the slider.

#### Expected behavior:
Slider value should change only if the mouse is over the slider. This was raised as an accessibility bug by an accessibility SME. Slider bar should not move when the mouse cursor moves out of slider bar pop up.

### If applicable, please provide a codepen repro:
This can be reproed on the fluent UI slider [page](https://developer.microsoft.com/en-us/fluentui#/controls/web/slider)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) Any site that uses the slider component.

**Comment by ecraig12345** [comment]
This is the intended behavior. This matches the native behavior in browsers as seen [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range). And it's actually better for accessibility, because requiring that the user's mouse stay positioned over the slider (a very narrow area) would require higher dexterity.
