### ISSUE TITLE
Documentation / TypeScript checking for Overlay's onClick prop

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#18643]
[Official documentation site](https://developer.microsoft.com/en-us/fluentui#/controls/web/overlay)

Documentation says onClick has type `()=>void`. However the onClick event does generate an event object, and documentation should reflect `(e)=>void`. This MouseEvent, wrapped up in a React SyntheticBaseEvent can be useful in determining if a user clicked on the empty overlay, or onto a component within the Overlay div.

I'm using this event to check if the overlay should be dismissed.

**Comment by gouttierre** [comment]
@imdavidmin - Thanks for filing this issue with us. This issue will be prioritized and scheduled with the team for a review.

**Comment by smhigley** [comment]
It seems odd, or even an oversight, to me that it's typed at all instead of relying on the `React.HTMLAttributes<HTMLElement>` typing. There's no docs with it, it's treated like a DOM attribute, and no other event handler has specific typings included. I think we should just remove it from `Overlay.types`.
