### ISSUE TITLE
Overlay componentRef / ref should return the DOM element, not React Component

### ISSUE THREAD

**Issue by imdavidmin** [microsoft/fluentui#18654]
#### Describe the feature that you would like added

`<Overlay ref={r => overlayRef = r} />` will give a React virtual component to the variable `overlayRef`, as opposed to the `div` element that the Overlay is represented as in the DOM. This is inconsistent with other components, such as SearchBox, where the `div` is returned.

Returning the DOM element will make it easier to work with when passing the reference to animation libraries (e.g. GSAP). Otherwise, a workaround might be to give a `className` to Overlay and then finding it in the DOM. 

#### What component or utility would this be added to

Overlay

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/48481563/122899167-7ee2e280-d343-11eb-9067-be8ca6820a93.png)

**Comment by ecraig12345** [comment]
This is by design at the moment because Overlay is still a class component, so `ref` is expected to return a class instance. (`componentRef` is always intended to return a class instance or imperative API, regardless of component type.) 

If you need access to the element itself, in some scenario where assigning an `id` or `className` to the Overlay wouldn't work, we can consider temporarily adding an `elementRef` prop similar to what we've done in other components.

**Comment by imdavidmin** [comment]
Thanks - I can use the `className` method for now as it works for me in my use case, will just need to make sure the name is unique. I'm happy to wait until this is moved to a functional component at a future stage.
