### ISSUE TITLE
Textfield's maxLength property doesn't work when the type is 'number'

### ISSUE THREAD

**Issue by sandeepvootoori** [microsoft/fluentui#18718]
### Environment Information

- **Package version(s)**: 8.14.14
- **Browser and OS versions**: Chrome

#### Actual behavior:

Textfield's maxLength property doesn't work when the type is 'number'

#### Expected behavior:

maxLength property should work independent of the type of field

**Comment by ecraig12345** [comment]
This must be a built-in browser behavior, because both `type="number"` and `maxLength` are built-in `<input>` properties that TextField just passes through. So we're not going to add special handling for this case.

The best workaround would be to use a TextField with the `value` and `onChange` props, and in the change handler, only update the value if it's below the length you wanted. https://codepen.io/ecraig12345/pen/dyWPgGw?editors=0010

**Comment by sandeepvootoori** [comment]
> This must be a built-in browser behavior, because both `type="number"` and `maxLength` are built-in `<input>` properties that TextField just passes through. So we're not going to add special handling for this case.
> 
> 
> 
> The best workaround would be to use a TextField with the `value` and `onChange` props, and in the change handler, only update the value if it's below the length you wanted. https://codepen.io/ecraig12345/pen/dyWPgGw?editors=0010

This is what I ended up doing, Thanks for the suggestion.
