### ISSUE TITLE
DetailsList does not apply CSS class onDragEnter

### ISSUE THREAD

**Issue by tsinghammer** [microsoft/fluentui#18750]
### Environment Information

- **Package version(s)**: 8.20.2

### Please provide a reproduction of the bug in a codepen:

This is a duplicate of [#14413](https://github.com/microsoft/fluentui/issues/14413) which has been closed 5 days ago. Unfortunately I'd now need this feature.

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/draganddrop

Actual behavior:
Styles provided in onDragEnter are not applied in the example on the above page.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, but would have to check the Fluent UI code first

Requested priority: Normal

**Comment by gouttierre** [comment]
@tsinghammer - thanks for filing this issue and showing the willingness to help submit a PR for the fix.  The other issue #14413 was closed due to the inactivity over a long period. Our team will guide you on a fix once it has been reviewed internally.

@smhigley - Would you be able to confirm if this is a regression, or if this behavior is an issue?
