### ISSUE TITLE
SpinButton's onChange prop fires differently than in v7

### ISSUE THREAD

**Issue by makopch-ms** [microsoft/fluentui#18782]
v7: https://codepen.io/makopch/pen/xxdbyKW 
v8: https://codepen.io/makopch/pen/bGWNmGd
(See console for output difference)

#### Actual behavior:
In v8, onChange only fires when the user presses KeyDown or moves focus away (blur)

#### Expected behavior:
In v7, onChange fires for every keystroke of the user.

Is this a design change in v8, that onChange was too chatty?  

In our user scenario, as soon as the user starts typing an invalid number outside the accepted range, the border color of the spinbutton will update and there will be a callout indicating the acceptable values.  With the v8 change in behavior, only keydown/blur seem to fire the event and the value will just snap to the most acceptable min/max value.

**Comment by ecraig12345** [comment]
Thanks for the codepens! In the (long) discussion on the feature request for `onChange` (#5326), it was decided that `onChange` should only be called when the value is "committed": on blur, enter, or spin. This was partly because validation only runs on "commit." We didn't think about the fact that `onChange` could already be applied to the root `div` through native props spreading (or that it would do anything when applied that way). 

Tentatively I'd like to leave the behavior in version 8 as it is for now, but open to input from you or others on that decision. If you still want to be notified on every keystroke, a workaround is to use `onInput` (on the root, not `inputProps`) as shown in the links below. I'll also add this to the migration guide.
v8 https://codepen.io/ecraig12345/pen/KKmwJpN
also works in v7 https://codepen.io/ecraig12345/pen/XWRJObz
