### ISSUE TITLE
NVDA is unnecessarily announcing clickable when focus goes on non actionable column headers of the DetailsList.

### ISSUE THREAD

**Issue by ImranAlliKhan** [microsoft/fluentui#18795]
Environment Information
Package version(s): "@fluentui/react": "^8.18.0",
Browser and OS versions: Chrome Version: 89.0.4389.90 (Official Build) (64-bit) and Windows 10
Screen Reader: NVDA(2020.4)

Describe the issue:
In DetailsList fabric control, unnecessarily announcing "**clickable**" when focus goes on non actionable column headers.
![image](https://user-images.githubusercontent.com/27187973/124094683-a25e0980-da76-11eb-8d0d-e72dfc61940f.png)

Actual behavior:
NVDA unnecessarily announces "clickable" when focus goes on non actionable column headers of the DetailsList

Expected behavior:
NVDA should not unnecessarily announce "**clickable**" when focus goes on non actionable column headers of the DetailsList

**Comment by gouttierre** [comment]
@ImranAlliKhan - thanks for filing this issue with us.

@smhigley -  Would you be able to confirm if this is a regression, or if this behavior is an issue with NVDA and DetailsList?
cc @ling1726

**Comment by smhigley** [comment]
NVDA announces "clickable" on quite a lot of things, based on internal heuristics. One of the things that can make it say "clickable" is attaching a click handler to any given element, which we have on the column header's child `<span>`.

Unfortunately we can't feasibly remove the click handler, but since this is really common behavior for NVDA, I doubt anyone would be thrown off by it.

Feel free to re-open if you have any additional concerns or details to add.
