### ISSUE TITLE
(Callout) - Does not revaluate position after width and height modifications

### ISSUE THREAD

**Issue by czearing** [microsoft/fluentui#18839]
### Environment Information
- **Package version(s)**: V8 and V7

### Please provide a reproduction of the bug:
Example: https://codesandbox.io/s/withered-shadow-kxgmj?file=/src/App.js

When the component is initially rendered it correctly adjusts its position to best fit the screen.
![image](https://user-images.githubusercontent.com/7192338/124684568-4d5e3100-de84-11eb-8109-14b48245f1fb.png)

However, upon changing width or height, its position does not update creating various visual bugs. 
![image](https://user-images.githubusercontent.com/7192338/124684572-50592180-de84-11eb-99e5-73c6ec2c110f.png)

#### Actual behavior:
When `Callout` is resized the position is initially detected but then becomes clipped by the screen edge upon size modification.

#### Expected behavior:
When `Callout` is resized:
1. The position should detect whether it is being clipped by the screen edge.
2. It should change its position the same as it does upon initial render.

**Comment by dkozar** [comment]
That's right. From my experience the position seems to be fine, however the popup might be clipped by the screen edge.

So, it would be ideal if the callout could listen for it's content size changes, and place itself accordingly.

It's worth to add that I tried to solve this thing by using [ResizeObserver](https://web.dev/resize-observer/) (in order to react on child resize), but this introduces a "flicker", i.e. a 1-rendering-cycle offset between resizing and re-positioning of the popup.

**Comment by dkozar** [comment]
Great to see this fixed!

Just wondering - does this work with repositioning the popup when close to the screen edge (in order to avoid being clipped by the edge)? Like in my demo: https://codesandbox.io/s/silly-http-oebdv?file=/src/App.js:0-763

**Comment by dkozar** [comment]
Unfortunately, the fix doesn't seem to work for me. The position is not re-evaluated the way I would expect it to be, i.e. the top-right corner of the popup never changes the position. This leads to the callout being clipped by the left screen edge.

Demo (`@fluentui/react@v8.26.2`): https://kdgf5.csb.app/

More info: https://github.com/microsoft/fluentui/pull/18887#issuecomment-891748483

**Comment by KevinLobo** [comment]
I work in OWA and we're also experiencing this issue. We are using @fluentui/react@v8.27.0.

As a workaround, instead of using a boolean in the Callout hidden property, we use it to determine whether to show the component or not, for example:

{boolean && <Callout>...</Callout>}

Please reach out if you need additional info.

**Comment by dkozar** [comment]
> I work in OWA and we're also experiencing this issue. We are using @fluentui/react@v8.27.0.
> 
> As a workaround, instead of using a boolean in the Callout hidden property, we use it to determine whether to show the component or not, for example:
> 
> `{boolean && <Callout>...</Callout>}`
> 
> Please reach out if you need additional info.

Thanks for info, but this solution doesn't work for us, because: our inner component has different _views_, and changing the view resizes the content. The component knows nothing about the "outer world". We wouldn't like to "climb up" to the callout in order to hide it and show again. It's doable, but against the _separation of concerns_.

Btw if you show/remove the popup this way, you disrupt the potential fade in / fade out of the callout. Instead, the callout is abruptly removed. That's why it's desirable to use the `hidden` property.

**Comment by dkozar** [comment]
@czearing any updates? Thanks!

**Comment by KevinLobo** [comment]
@czearing any updates? I am still facing problems with this issue? Maybe removing the fixed status can provide more attention to this?

Thank you.

**Comment by dkozar** [comment]
Any updates to this issue?

Thanks,

**Comment by KevinLobo** [comment]
Another way to repro this is to use CSS transform property with scale. If a certain scale is applied, the callout position will not be recalculated properly and will be away from the element of reference (if that makes sense).

**Comment by dkozar** [comment]
Hi!

Any updates to this issue?

Thanks,
