### ISSUE TITLE
Using the theme to store typographic variations

### ISSUE THREAD

**Issue by 2metres** [microsoft/fluentui#18872]
I am creating an application that features a code block and would like to have something like `monospaceFontStyles` that I can store CSS properties on the theme.

I saw that @micahgodbolt mentioned something like this in #7385 but that issue has subsequently been closed by the issue bot.

Are there any best practices/reccomendations for adding new variants to the theme outside of the xs - mega sizes that are currently present?

**Comment by ling1726** [comment]
@JustSlone  can you see that this is discussed with the core v8 team ? There are more details in the previous closed issue: #7385

**Comment by ecraig12345** [comment]
Adding more typography properties to the theme was discussed in the past but I don't think we ever landed on whether it was something we wanted to support (and if so, how). At this point we're very unlikely to add this to the theme in `@fluentui/react` version 8, since our primary development efforts are focused on converged components (`@fluentui/react-components`). 

Since there's no place in the theme where users can add arbitrary values, probably the best way to share monospace styles for now would be via a constant (which various files can import) or React context if the style needs to vary contextually.
