### ISSUE TITLE
CircleHalfFull icon is smaller than others

### ISSUE THREAD

**Issue by chintanupadhayay** [microsoft/fluentui#18901]
**Environment Information**
Package version(s) : Office UI Fabric React 6.189.2 *(edit: also repros in v8, `@fluentui/font-icons-mdl2` 8.1.8)*
Browser: Chrome

**Describe the issue:**

We are using office fabric icons for our SPFx React app. We have used **CircleHalfFull** but it showing a small size in our app if we compare it with other icons. Seems something wrong with the font family.

Is possible to get the same font family for **CircleHalfFull** as we have CircleRing,CircleFill.

#### Actual behavior:
See the below screenshot of the inconsistent size of **CircleHalfFull**.

![CircleHalfFill_Icon](https://user-images.githubusercontent.com/29138303/125283937-83912a00-e336-11eb-95bc-beed4b4e9f1b.PNG)

### Priorities and help requested:

Are you willing to submit a PR to fix? : No

Requested priority: High

Products/sites affected: Yes

**Comment by ling1726** [comment]
@tomi-msft  could you please take a look at this or direct this to someone who can investigate the svg ?

**Comment by ecraig12345** [comment]
This is using font-based icons, not SVG icons, and a very old version of the library (6). @chintanupadhayay Can you please provide an isolated repro of the issue? Otherwise it's not really possible for us to debug. You can start from https://aka.ms/fluentpen to see if this repros in the current version of Fluent UI. If it doesn't repro in the current version, this won't be a very high priority for us to fix.

**Comment by chintanupadhayay** [comment]
@ecraig12345, Let me check. I will get back to you early next week with a repo.

**Comment by chintanupadhayay** [comment]
Hi @erichdev, I have created a repro with the Fabric icon. What I found the font-family is different for **CircleHalfFull**, let me know your view.
https://codepen.io/chntn/pen/jOmLbqm

**Comment by chintanupadhayay** [comment]
Hi @ecraig12345 Is there any update?

**Comment by ecraig12345** [comment]
I don't think the different font-family is the issue; that's just because the icon font is broken up into subsets to load faster. 

@tomi-msft Can you get someone from design to take a look at this and see if the `CircleHalfFull` icon is supposed to be smaller than the others (and fix it if not)? This is for the old font icons, not the SVG icons.

@chintanupadhayay Just to set expectations: even if the smaller size is determined to be wrong and gets fixed, we wouldn't port the fix back to version 6 at this point, so you'd need to upgrade to `@fluentui/react` version 8 to get the fix. A workaround in the meantime is to change the font size of that icon to be a bit larger.

**Comment by chintanupadhayay** [comment]
@ecraig12345 We have already used the font size workaround, for now, will upgrade to v8 when fluentui team fixed.
