### ISSUE TITLE
Using FluentUI/react in server rendered environment with Nextjs throws useLayoutEffect warning

### ISSUE THREAD

**Issue by thekeviv** [microsoft/fluentui#18916]
### Environment Information

- **Package version(s)**: 

fluentui/react 8.22.3
nextjs 11.0.1

#### Actual behavior:

Using fluentui/react components in server rendered environment in Nextjs 10 throws a useLayoutEffect warning. I first reported it [here](https://github.com/microsoft/fluentui/issues/17893#issuecomment-878762647) and was asked to create a separate issue for this. 

Can you please also let me know how I can suppress the warning while this gets worked on and if there's any things I need to be careful about related to this in my apps

#### Expected behavior:

No warning gets thrown

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe (Not sure rn) 

Requested priority: Normal

Products/sites affected: Client products

**Comment by ling1726** [comment]
Looking at v8 code, it seems there is some usage of `useLayoutEffect` in the library. I think the correct way forward is to remove them and introduce `useIsomorphicLayoutEffect` similar to v0 and vNext. 

FYI @ecraig12345 do you think this makes sense as a proposed fix ?

**Comment by thekeviv** [comment]
@ling1726 Our app is still under heavy development but I don't believe there have been any behavioural issues so far.

I was looking for some guidance from the team on that regard if there can be behavioural issues and how they can be avoided.

**Comment by ecraig12345** [comment]
> Looking at v8 code, it seems there is some usage of `useLayoutEffect` in the library. I think the correct way forward is to remove them and introduce `useIsomorphicLayoutEffect` similar to v0 and vNext.
> 
> FYI @ecraig12345 do you think this makes sense as a proposed fix ?

It depends on the specific usage. IIRC there are a handful of cases that are highly sensitive to timing where `useLayoutEffect` may be necessary. (But there's no way to force React to disable the warning for those cases...)

### Definitely wrong

I think the second `useLayoutEffect` here will prevent keytips from being registered in SSR. Since keytips only display after a keyboard trigger and it's unlikely that props would be updated after they're displayed, I seriously doubt the slight timing difference matters, so these should definitely be updated to `useEffect`.
https://github.com/microsoft/fluentui/blob/83a5b3125734430dd6b341487cbdf3950a4bbe06/packages/react/src/components/KeytipData/useKeytipData.ts#L28-L53

### May be critical (needs confirmation)

See comment inline. This actually is **entirely safe** in SSR since the logic only matters on updates, but unfortunately will trigger warnings.
https://github.com/microsoft/fluentui/blob/83a5b3125734430dd6b341487cbdf3950a4bbe06/packages/react/src/components/TextField/MaskedTextField/MaskedTextField.tsx#L346-L353

This effect has most of the overflow logic, which seems like it *might* be timing-critical but needs input from someone more familiar with the code. And even if it's critical it runs on every render (open the file and observe there's no deps list), so it might be fine in SSR. *This issue also exists in converged react-tabs, cc @behowell.*
https://github.com/microsoft/fluentui/blob/83a5b3125734430dd6b341487cbdf3950a4bbe06/packages/react/src/utilities/useOverflow.ts#L79

### Unclear (needs further investigation)
https://github.com/microsoft/fluentui/blob/83a5b3125734430dd6b341487cbdf3950a4bbe06/packages/react/src/components/Image/Image.base.tsx#L28-L32
https://github.com/microsoft/fluentui/blob/83a5b3125734430dd6b341487cbdf3950a4bbe06/packages/react/src/components/Layer/Layer.base.tsx#L97-L112

**Comment by ling1726** [comment]
All of those issues can be solved by introducing a [useIsomorphicLayoutEffect](https://github.com/microsoft/fluentui/blob/master/packages/react-utilities/src/hooks/useIsomorphicLayoutEffect.ts) that already exists in v0/9, it's just a simple hook that toggles between `useEffect` and `useLayoutEffect` depending on server/browser render:

**Comment by ecraig12345** [comment]
@ling1726 That doesn't fix cases where `useLayoutEffect` is actually required for timing reasons.

**Comment by ling1726** [comment]
@ecraig12345 the only issue is that `useLayoutEffect` will throw a warning in server render, just replace it with `useEffect` during server render, effects aren't even run on the server. By the time the app is in the browser `useLayoutEffect` will still be used, that's the whole point of `useIsomorphicLayoutEffect`

**Comment by thekeviv** [comment]
@ling1726 @ecraig12345 I noticed this warning today in our app which I think is related to this issue:

Warning: Prop `className` did not match. Server: "server-stickyAbove-5" Client: "stickyAbove-58"
at div
at div
at ScrollablePaneBase.

The top level component looks like this:

<ScrollablePane>
      <Sticky stickyPosition={StickyPositionType.Header}>
        <Stack>
            header goes here
        </Stack>
        body goes here
     </Sticky>
<ScrollablePane/>

**Comment by ecraig12345** [comment]
@thekeviv That's an unrelated issue, #3692.
