### ISSUE TITLE
[Dropdown item Bug]Can't overwrite style of dropdown component when browser is too small

### ISSUE THREAD

**Issue by acblacktea** [microsoft/fluentui#18993]
I want to use callout to modify dropdonw item's style like ` { '.ms-Dropdown-item': { color: 'red' } }` (this is just a simple example, style in callout is more complicated in our production code)

```
const { IStackTokens, Stack, Dropdown, DropdownMenuItemType, IDropdownStyles, IDropdownOption, ThemeProvider, initializeIcons } = window.FluentUIReact;

const dropdownStyles: Partial<IDropdownStyles> = {
  dropdown: { width: 300 },
  callout: { '.ms-Dropdown-item': { color: 'red' } }
};

const options: IDropdownOption[] = [
  { key: 'apple', text: 'Apple' },
  { key: 'banana', text: 'Banana' },
  { key: 'grape', text: 'Grape' }
];

const stackTokens: IStackTokens = { childrenGap: 20 };

const DropdownBasicExample: React.FunctionComponent = () => {
  return (
    <Stack tokens={stackTokens}>
      <Dropdown
        placeholder="Select an option"
        label="Basic uncontrolled example"
        options={options}
        styles={dropdownStyles}
      />
    </Stack>
  );
};

const DropdownBasicExampleWrapper = () => <ThemeProvider><DropdownBasicExample /></ThemeProvider>;
ReactDOM.render(<DropdownBasicExampleWrapper />, document.getElementById('content'))
```
if browser size is normal, it work fine
![image](https://user-images.githubusercontent.com/17824206/126137126-ec432927-801c-4ab7-8afe-294431c6c8f1.png)

but if I resize browser to small, callout doesn't work
![image](https://user-images.githubusercontent.com/17824206/126137335-f9d5b89a-5b41-464a-aaaf-8025a7e7dba9.png)

I 100% sure this is a bug, please help fix it.

**Comment by ling1726** [comment]
This is by design, since in smaller viewports the `Callout` is no longer rendered and is replaced by the `Panel` component.

Firstly I would recommend you not to style by targeting class if possible, you can simply use `dropdownItem` styles. Here is an example: https://codepen.io/ling1726/pen/wvdemMz

If you really need to target class, then here is how you can do it with both `Panel` and `Callout`: https://codepen.io/ling1726/pen/gOWRePa
