### ISSUE TITLE
screen reader: tip text present inside Callout is read twice. 

### ISSUE THREAD

**Issue by Renuka8796** [microsoft/fluentui#19018]
Screen Reader: Narrator

Repro Link : https://codepen.io/kusudh/pen/pojMayJ?editors=0010

Browser Details: ​
OS: Windows 10 
Microsoft Edge Dev 

Repro Steps: ​

Start Narrator and navigate to https://codepen.io/kusudh/pen/pojMayJ?editors=0010
Tab till "Show FocusTrapCallout" button and then press Enter.
Wait until narrator finishes to read the information.
Actual Result: ​
Narrator is reading tool-tip details twice.

Expected Result: ​
Narrator should reading tool-tip details once.

Please note :

This issue is not repro with NVDA - chrome.
If the tip-text is less( which contain less than 2 points/sentences, then narrator reads the tip text info only once.

This issue already raised https://github.com/microsoft/fluentui/issues/13413 but it was closed due to  house-keeping purposes as there was no action.

**Comment by smhigley** [comment]
Narrator is reading the tooltip details twice because you have the same content in the callout twice. It looks like you've duplicated the visible text in a visually hidden element, which is *extremely* bad practice. It will be entirely inaccessibly via touch exploration and mouse + SR usage, and cause other side effects like the one you logged in this bug.

The reason the `aria-hidden` on your visible text isn't working is because Edge is using heuristics to try to (correctly, IMO) repair the author error of putting `aria-hidden` on visible text. Remove the `aria-hidden`, and remove the visually hidden duplicated content, and you should be good.
