### ISSUE TITLE
Review react-theme shape

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluentui#19114]
- shallow vs deep
- readable vs hashed CSS variable names

RFC #19752

**Comment by ecraig12345** [comment]
One thing I noticed while implementing styles for Input is that we're relying heavily on deeply nested variable access, which isn't minifiable at all. Here's an example from Button (not to say Button is doing anything wrong, it just demonstrates the overall problem well):
https://github.com/microsoft/fluentui/blob/cea329180db8efad2a71140282752d11f358648a/packages/react-button/src/components/Button/useButtonStyles.ts#L31-L68

**Comment by ecraig12345** [comment]
Also it might be too late to change this since it's coming from design, but @smhigley and I found the numeric names for font size tokens *incredibly* confusing. When I see numbers like that, it makes me think of font weights, which is unrelated to font sizes. I'm guessing this was done instead of names like `small`/`medium`/`large` to avoid names like `smallPlus` or `mediumAndThreeQuarters` if we need to add more intermediate sizes in the future, but I wonder if we can come up with something better.
https://github.com/microsoft/fluentui/blob/cea329180db8efad2a71140282752d11f358648a/packages/react-theme/src/global/fonts.ts#L3-L18
