### ISSUE TITLE
[Announced][Narrator] Doesn't seem to work in Chrome, it only announces 'group'

### ISSUE THREAD

**Issue by lucas-stanford** [microsoft/fluentui#19121]
### Environment Information
- **Package version(s)**: 8.23.8
- **Browser and OS versions**: Chrome, Windows Version	10.0.19043 Build 19043

### Describe the issue:
When testing this sample in chrome/narrator : https://developer.microsoft.com/en-us/fluentui#/controls/web/announced/bulkoperations

It reads 'group', instead of the number of selected items deleted.

#### Actual behavior:
Expected to read 'x' items deleted

#### Expected behavior:
Reads 'group'

---------
Note this works correctly in Edge.

**Comment by ling1726** [comment]
@lucas-stanford  can you please provide more information for a repro ? Do you focus on the items in the example ? are you using Narrator in scan mode ?

**Comment by lucas-stanford** [comment]
It doesn't work at all in any scenario/mode in chrome. But here are some more explicit repro steps:

1. https://developer.microsoft.com/en-us/fluentui#/controls/web/announced/bulkoperations.
1. click the select all button of the grid, 
![image](https://user-images.githubusercontent.com/3011776/127241905-5f92e6c1-874f-4fb1-959e-8d31c18af600.png)
1. use your keyboard to navigate to the delete all button and activate.

**Comment by ling1726** [comment]
@smhigley  could you lend a hand with your screen reader expertise ?

**Comment by smhigley** [comment]
@lucas-stanford Narrator doesn't have first-party support with Chrome -- it consumes a different accessibility API than the one Chrome (or Firefox) outputs, and only sort-of works because of a cross-API bridge built into Windows. It's not surprising that live regions fail in that combination.

There isn't really anything we can do. I also wouldn't suggest testing Narrator with Chrome, in the same way I wouldn't suggest testing Narrator with Firefox, or VoiceOver with anything but Safari :). Not all screen readers work with all browsers.

**Comment by lucas-stanford** [comment]
Thanks for replying, that makes sense! Note could probably get it working, I was eschewing using the announced component b/c setting it up manually was working correctly.

I set up a simple code pen with that shows a live region working with narrator/chrome. https://codepen.io/fordfordford/pen/XWRPeNN
