### ISSUE TITLE
Chart - In Browse mode, NVDA reads the callout content of first focus section multiple times

### ISSUE THREAD

**Issue by LucyLiYY** [microsoft/fluentui#19174]
### Environment Information

The issue repros on Fluent UI example site
https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/charting/dist/index.html#/examples/Donutchart

### Describe the issue:

In browser mode, NVDA announces the hidden call out dialog content for each sections. All the callout dialog content are the same as the first section when they are hidden.

#### Actual behavior:

In Browse mode, NVDA reads the callout content of first focus section multiple times
![image](https://user-images.githubusercontent.com/17995942/127441616-d95bafb9-7ae5-4c1c-93df-c101029a9a21.png)

#### Expected behavior:

In Browse mode,, NVDA should read the callout content for each section for only one time

**Comment by gouttierre** [comment]
@LucyLiYY - thanks for filing this issue with us.

@Raghurk -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by smhigley** [comment]
Looks like the callout shouldn't be used as the label for any of the sections, since its content is dynamic. Either the content for each section would need to persist somewhere else in the DOM to be referenced by `aria-labelledby`, or the text needs to be duplicated in `aria-label`.

As a side note, it also looks like those paths need roles on them, right now they're just graphics that are focusable.
