### ISSUE TITLE
Focus does not move to the first context menu item when button is activated while using a screen reader (NVDA/Narrator)

### ISSUE THREAD

**Issue by Ridrisco** [microsoft/fluentui#19302]
### Environment Information

- **Package version(s)**: Fluent 7.174.0 & 8.27.0
- **Browser and OS versions**: Microsoft Edge v91.0.864.71 (Official build) (64-bit), Windows 10 Enterprise build 19043.1110
- Screen Readers Used: NVDA 2020.4, Narrator 2020

### Describe the issue: 
When using a screen reader to activate a button with a context menu, the focus does not go to the first item in the context menu. However, when not using a screen reader the focus does go to the first item.

### Please provide a reproduction of the issue in a codepen:
Repro can be done directly from the fluent site:
[Fluent Button](https://fabricweb.z5.web.core.windows.net/oufr/8.27.0/#/examples/button)
1. Open up NVDA or Narrator.
2. Navigate focus to the button with a context menu using tab.
3. Press enter or space to active the button.
4. The context menu should open.

#### Actual behavior:
The focus does not move to the first item of the menu when using a screen reader. It goes to the menu as a whole rather than the regular behavior of going to the first item.

#### Expected behavior:
On activating the button, focus should move to the first menu item.

### Documentation describing expected behavior
[WCAG Reference](https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence.html)

**Comment by gouttierre** [comment]
@Ridrisco - Thank you for filing this issue with us and providing the required repro steps.

@smhigley - would you be able to confirm if this is a regression, or if this behavior is an issue where the focus does not move to the first menu item?

**Comment by smhigley** [comment]
It appears that Fluent is setting focus to the first item when the button is activated with the keyboard (as happens if you're using a screen reader in forms/app mode), but setting focus to the menu root when opened with a click (which is what happens when using a screen reader in virtual cursor). That's what's causing the observed issue with NVDA/Narrator which only reproduces in scan mode.

The resulting behavior isn't actually bad IMO, though it could potentially be better if we always set focus to the first item.
