### ISSUE TITLE
LightningBoltSolid icon not included in @fluentui/font-icons-mdl2

### ISSUE THREAD

**Issue by gggjtgxing** [microsoft/fluentui#19300]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:
The icon "lightningboltsolid" was not registered
https://uifabricicons.azurewebsites.net/
![image](https://user-images.githubusercontent.com/17696563/128555880-d9420a35-da78-4f7b-8673-90a8e0b8843b.png)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/17696563/128556789-a8a7052b-b0e8-47e2-984f-b7d41d0aa026.png)

### If applicable, please provide a codepen repro:
https://codepen.io/xingwa/pen/gOWBQVr

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes if you could provide instructions
Requested priority: (Blocking, High, Normal, Low)
Normal
Products/sites affected: (if applicable)
SharePoint

**Comment by ecraig12345** [comment]
This is happening because our default icon set in `@fluentui/font-icons-mdl2` is a bit out of date and doesn't include that icon. 

You can work around the issue for now by using the tool to create a custom icon subset and registering it. More info here: https://github.com/microsoft/fluentui/wiki/Using-icons#creating-an-icon-subset

**Comment by gouttierre** [comment]
@gggjtgxing - Thanks for reaching out to us. I’ve added this to our backlog for review but it’s low on our priority list - especially since you can currently work around the issue for now by using the tool to create a custom icon subset and registering it. More info here: https://github.com/microsoft/fluentui/wiki/Using-icons#creating-an-icon-subset
