### ISSUE TITLE
Dialog: enable resizing/fullscreen

### ISSUE THREAD

**Issue by yangjocy** [microsoft/fluentui#19331]
#### Describe the feature that you would like added
Enable Dialog resizing and fullscreen mode further.

#### What component or utility would this be added to
Dialog

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots
For complex dialog contents, we need to enable users to resize dialogs through dragging & dropping. Fullscreen mode in one-click is also preferable.

**Comment by yangjocy** [comment]
I am trying to implement resizing by myself. To do that I need to add mouse event listender to dialog html elements. However, it seems like I cannot get ref of the dialog/dialogcontent HTMLElement? the only `componentRef` property returns a reference to this react element.

**Comment by gouttierre** [comment]
@yangjocy - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!
