### ISSUE TITLE
Checkbox is getting focused in details List row when added through onRenderCheckbox event

### ISSUE THREAD

**Issue by GayatriDeviP** [microsoft/fluentui#19357]
### Environment Information 
- **Package version(s)**: Fluent UI React 8.27.1 
- **Browser and OS versions**:  All browsers(Chrome, edge) , Windows 10 and Android 10 

### Describe the issue: 
Checkbox is added in details list through onRenderCheckbox event.
while navigating using keyboard tab, once the details row got focus, on right key press checkbox is getting focused which is not expected. 

### Please provide a reproduction of the issue in a codepen: 
 https://codepen.io/GayatriDeviP/pen/PomVzEX 

Repro steps: 
1. Go to the codepen, Navigate to the detail list rendered in codepen. 
2. Navigate using keyboard tab  on any row. 
3. Now the focus is on row, press right arrow key and verify if checkbox got focus. 

#### Actual behavior: 
 Checkbox is getting focused in details List row when right arrow key is pressed. 

#### Expected behavior: 
 Checkbox should not get focused in details List row when right arrow key is pressed. 
  
### Documentation describing expected behavior 
If we consider default details list, radio button is not getting focused with right arrow. It is happening only when checkbox is added through onRenderCheckbox.

**Comment by gouttierre** [comment]
@GayatriDeviP - thanks for filing this issue and providing the required repro steps.

@smhigley  -  Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by smhigley** [comment]
@GayatriDeviP you can add `data-is-focusable': false` to the Checkbox's `inputProps` to have it not be managed by the FocusZone.

That said, passing a `<Checkbox>` component or input in to the `onRenderCheckbox` prop will break accessibility for screen reader users. Since `onRenderCheckbox` lets you customize the _children_ of the DetailsList checkbox, rendering an actual checkbox input will result in nested checkboxes. If you want to customize the checkbox display. I suggest passing in a custom check icon.

Hope that helps!

**Comment by GayatriDeviP** [comment]
@smhigley , Thanks you for your inputs.
we tried adding '**data-is-focusable': false** to the checkbox **inputProps**, It is working for web browser but issue is still persists for android device with talkback.

Do you have any suggestions?
