### ISSUE TITLE
React SpinButton defaultValue issue 

### ISSUE THREAD

**Issue by maryamhdr** [microsoft/fluentui#19373]
Hey, I was checking the SpinButton component in https://developer.microsoft.com/en-us/fluentui#/controls/web/spinbutton and I came across some issues.
I set the defaultValue of SpinButton equal to "a":
![freesnippingtool com_capture_20210811233606](https://user-images.githubusercontent.com/48528003/129088678-850779a5-abd4-4e19-8545-bd208253d671.png)

When I clicked increase button, the result I got was "NaN":
![freesnippingtool com_capture_20210811233630](https://user-images.githubusercontent.com/48528003/129088807-144cdd89-d91d-474a-9b28-836d7a887e19.png)

I think there should be a solution to this issue.

**Comment by gouttierre** [comment]
@maryamhdr  - Thanks for filing this issue with us. To set expectation our team will have a look at the issue but only once capacity allows.
  
@GeoffCoxMSFT -  Would you be able to confirm if this is a regression, or if this behavior is an issue where we show NaN - "Not A Numeric" for none numeric values?

**Comment by bsunderhus** [comment]
This is an edge case that should no be treated by the component. Since this component expects to receive only numbers, there's no validation that you're providing a number as a `defaultValue`.

If you're providing a custom spinner ("a" to "b", to "c", etc,.) you should also provide a custom `onIncrement` and `onDecrement` methods to provide next and previous values.  here's an example on [codesandbox](https://codesandbox.io/s/react-spinbutton-defaultvalue-issue-y1jv7)
