### ISSUE TITLE
Calendar missing 'disabled' prop

### ISSUE THREAD

**Issue by dkozar** [microsoft/fluentui#19453]
#### Describe the feature that you would like added

Adding the `disabled` prop to Calendar component.

#### What component or utility would this be added to

Calendar.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

Sometimes one needs to show the calendar with selected date(s), however these dates should not be changeable, the "month" arrows on top should be disabled etc.

Other Fluent UI components all have the `disabled` flag, so possibly should also the Calendar.

Sure, there are [hacks](https://github.com/microsoft/fluentui/issues/4210) to change button styles etc., but possibly we could do better.

As an example, I've built the datetime selector component, which has the `disabled` prop. The component is passing the `disabled` prop to its children, however only the time selectors could get disabled:

![image](https://user-images.githubusercontent.com/1078403/130078126-ced1acd8-f5cd-4bf1-88f4-1407c0ee154d.png)

We'd like the same to happen with Calendar.

**Comment by gouttierre** [comment]
@dkozar - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!
