### ISSUE TITLE
Positive tabindex support on DetailsList

### ISSUE THREAD

**Issue by scottdurow** [microsoft/fluentui#19506]
#### Describe the feature that you would like added

The ability to assign a positive tabindex to the DetailsList control so that when used inside Power Apps, the resulting tab order is correct. 
Power Apps (canvas apps) currently assigns positive tabindexes, even if a zero tabindex is assigned by the app maker.

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

@smhigley

**Comment by gouttierre** [comment]
@scottdurow  - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.

However, if this becomes a blocker for PowerApps please reach out to @paulgildea and we can discuss it further.

**Comment by scottdurow** [comment]
Thanks @gouttierre.
@paulgildea Without this update, until Power Apps is changed to allow zero tab indexes, you cannot use the DetailsList in Power Apps Canvas Pages in an accessible way. It is also a challenge with other components that use the FocusZone such as the Command Bar and Pivot Controls.
