### ISSUE TITLE
swatchColorPicker color cell rendering issue

### ISSUE THREAD

**Issue by agrawalnikhil100** [microsoft/fluentui#19533]
Fluent UI version: 8.29.2

https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker
In the above component I faced some issues:
1) there's no way to access IColorPickerGridCellProps. I wanted to add my custom ID to the color cell. 
2) ISwatchColorPickerProps onChange prop function has event undefined. (i.e. event value comes as undefined in my function passed in onChange prop) 
3) the index in IColorCellProps is nowhere used.

**Comment by ecraig12345** [comment]
Thanks for filing this, but in the future we'd appreciate if you would make a separate issue for each problem, follow the issue template, and provide a repro (start from "Export to CodePen" on the example).

Here's a demo I made of the first two issues: https://codepen.io/ecraig12345/pen/ExXyZEz?editors=0011

1. `IColorCellProps.id` is misleadingly named--it's just being used as a unique identifier/key, not as the `id` DOM attribute. Changing this behavior (making it use the provided `id` in the DOM) could cause problems for people who were not already providing globally-unique IDs for the swatches. Depending on specifically why you wanted to set the `id`, there might be a workaround.

2. This is a bug which we should fix if time allows (or I'd be happy to provide more detailed guidance and review a PR if someone else is willing to help). This line should be passing an event as the second argument to `setSelectedId`. 
https://github.com/microsoft/fluentui/blob/ecc79efaeaf9bf8b3164d64eaf3610918c4e8624/packages/react/src/components/SwatchColorPicker/SwatchColorPicker.base.tsx#L244
Since the event isn't currently provided on `IColorPickerGridCellProps.onClick` or `IButtonGridCellProps.onClick`, it would also need to be added to those types and passed through here.
https://github.com/microsoft/fluentui/blob/ecc79efaeaf9bf8b3164d64eaf3610918c4e8624/packages/react/src/utilities/ButtonGrid/ButtonGridCell.tsx#L32

3. You're not intended to use `IColorPickerGridCellProps` directly. `index` is for internal use by `SwatchColorPicker`.
