### ISSUE TITLE
TagPicker:Track remove tag event

### ISSUE THREAD

**Issue by patilravikiran** [microsoft/fluentui#19546]
Not able to see property to track remove tag action. We would like to take confirmation from users before removing tag from parents record.

**Comment by gouttierre** [comment]
@patilravikiran - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!
