### ISSUE TITLE
`selection` property type of `IMarqueeSelectionProps` and `IDetailsListProps` should be generic

### ISSUE THREAD

**Issue by kidlj** [microsoft/fluentui#19657]
### Environment Information

- **Package version(s)**: "@fluentui/react": "^8.30.4"
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

with `_selection` defined as generic:
```typescript

export interface Word extends IObjectWithKey {
	id: number,
	name: string,
	verified: boolean,
	uk_phonetic: string,
	us_phonetic: string,
	def_zh: string[],
	def_net: string[],
}

	// selection
	const _selection: ISelection<Word> = new Selection({
		items: words ? words as Word[] : undefined,
		getKey: (item) => item.id,
		selectionMode: SelectionMode.multiple,
		onSelectionChanged: () => {
			const ids = _selection.getItems().map((item) => item.id)
			setSelectedIDs(ids)
			console.log(ids)
		},
	})
```

`MarqueeSelection` and `DetailsList` complain type incompatibility:
```typescript
				<MarqueeSelection selection={_selection}>
							<DetailsList
								onItemInvoked={_onItemInvoked}
								items={words}
								columns={columns}
								isHeaderVisible={true}
								selection={_selection}
							/>
						</MarqueeSelection>
```

I guess this is an incomplete fix of #11538

#### Actual behavior:

Compiler complains:
```
Type 'ISelection<Word>' is not assignable to type 'ISelection<IObjectWithKey>'.
  Types of property 'canSelectItem' are incompatible.
    Type '(item: Word, index?: number | undefined) => boolean' is not assignable to type '(item: IObjectWithKey, index?: number | undefined) => boolean'.
      Types of parameters 'item' and 'item' are incompatible.
        Type 'IObjectWithKey' is not assignable to type 'Word'.ts(2322)
```

#### Expected behavior:

No compiler complains.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by AkiraVoid** [comment]
Totally agree. I just do not know why they design it like this. The `Selection` utility is actually designed generic, but when we trying to use it in a certain component, the `selection` property is just set to only accept parameter which's type is `Selection<IObjectWithKey>`, and this even cannot be fixed by implementing `IObjectWithKey` or add `key` property in the class or interface we truly want to use. This not just happen in `MarqueeSelection` but also `DetailsList`. They have already offered a way to define the `key` in our own class which is not contain the `key` property, we can do this easily by define `getKey` option when we first instantiate a `Selection` object, so I don't know truly is there any technical difficulty stop them from doing so.

**Comment by AkiraVoid** [comment]
Why this issue doesn't have assignees? @GeoffCoxMSFT @ecraig12345 @jurokapsiar

**Comment by QuillFancyson** [comment]
A hacky workaround for anyone who comes across this: set your selection to be an `ISelection<IObjectWithKey | IDataType>` where `IDataType` is your custom type. Then just do some casting everywhere.

```typescript
const _selection: ISelection<IObjectWithKey | IDataType> = new Selection<IObjectWithKey | IDataType>({
    onSelectionChanged: () => {
        setSelectedItems((_selection as ISelection<IDataType>).getItems());
    },
    getKey: (item: IDataType) => { return (item.Id); },
});
```

In your render:

```html
<MarqueeSelection selection={ _selection as ISelection<IObjectWithKey> }>
    <DetailsList
        selection={ _selection as ISelection<IObjectWithKey> }
        // other props...
    />
</MarqueeSelection>
```

**Comment by gouttierre** [comment]
@AkiraVoid - Thanks for filing this issue with us. Our team will have a look but to set expectations, we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items.

@bsunderhus -  Would you be able to confirm the findings ? 
cc @smhigley , @GeoffCoxMSFT

**Comment by GeoffCoxMSFT** [comment]
@AkiraVoid  @QuillFancyson I'm still investigating if the selection property in DetailsList should be ISelection<any> as the DetailsList items are any[] and it doesn't have a generic TItem type specified as part of its signature in the props.

There is an easier workaround than specifying union types of interfaces though.

Instead of:
`_selection: ISelection<Word> = new Selection({`

use type inference and specify the generic on the constructor:
`_selection = new Selection<Word>({`

If _selection is a private member variable and you want to put a type on it, try `private _selection : Selection`

Why does this work? I think the type defaulting occurs on the Selection<TItem> and this extends ISelection<TItem> where the TItem has been resolved against the clas before TItem is resolved against the interface.  This allows the _selection to be an ISelection and can be assigned to the selection property.
