### ISSUE TITLE
After entering content search in the search box, click the clear button to clear the content of the search box, undefined appears in the search box

### ISSUE THREAD

**Issue by Supermariozmx** [microsoft/fluentui#19675]
### Environment Information

- **Package version(s)**: 8.29.2
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
Click x button to clear the content of the search box, undefined appears in the search box

#### Expected behavior:

Click the X button to clear the content of the search box, and the content in the search box will be cleared

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by GeoffCoxMSFT** [comment]
@Supermariozmx I was unable to reproduce this one the [Fluent UI site](https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox).  I tried in both Chrome and Edge.  

Could you kindly provide some example code of how you are using SearchBox?  Preferably a CodePen that reproduces the behavior.  I'm wondering if maybe the placeholder attribute is being bound to a variable and that is getting set to undefined.

**Comment by gouttierre** [comment]
@Supermariozmx - Could you kindly provide some example code of how you are using SearchBox? Preferably a CodePen that reproduces the behavior.

**Comment by ecraig12345** [comment]
We encountered this issue with the icon search on the Fluent doc site too. It happens when you have a controlled SearchBox that updates the value from `onChange`. https://codepen.io/ecraig12345/pen/eYGQbOK?editors=0010

The issue is that the `onChange` callback is missing a `newValue` parameter, and instead is taking the value from the event, which won't work for clear events.
https://github.com/microsoft/fluentui/blob/dfb5538a2494b48cbb61702c4c2c9aaf8de37a6f/packages/react/src/components/SearchBox/SearchBox.base.tsx#L68-L71
