### ISSUE TITLE
[DatePicker] Ability to hide/never trigger the pop up calendar when focusing/clicking.

### ISSUE THREAD

**Issue by Lego6245** [microsoft/fluentui#19713]
#### Describe the feature that you would like added

In the scenario we are building, we want to utilize the validation, formatting and other aspects of the DatePicker, but use a calendar we are mounting in the surface, as opposed to the one that pops up when you focus the element.

We can achieve this by utilizing `calloutProps` and setting `hidden: true`, but this still causes the callout to mount (there are DOM changes). This isn't ideal, as there's a performance cost to doing so.

I've investigated other props such as `showOnClick` but those don't behave exactly right, and not every way of opening the callout with the calendar is covered.

An ideal state would be either a prop to never mount the callout at all, saving the mounting step and improving performance for this scenario, or an override for the whole callout mounting process that we can no-op.

#### What component or utility would this be added to

DatePicker

**Comment by gouttierre** [comment]
@Lego6245 - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!
