### ISSUE TITLE
Fluent Dialog not behaving correctly for RTL direction

### ISSUE THREAD

**Issue by Dazmurphy** [microsoft/fluentui#19766]
### Environment Information

- **Package version(s)**: Latest consumed on https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog
- **Browser and OS versions**: All browsers

### Describe the issue:

Upon visiting https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog if you change the text direction to RTL the Dialog component does not handle it properly. There are a few issues visible in the screenshot below. Firstly the dot that fills the options is overlapping the text. I believe the header should be right aligned, and also the buttons should move to the left side of the dialog. The body text should also align to the right.

#### Actual behavior:

The Dialog content does not display appropriately in RTL mode.

#### Expected behavior:

The Dialog displays some elements overlapping each other, while not correctly aligning the text and buttons.

![image](https://user-images.githubusercontent.com/10632384/133087441-dcf52a37-bf5b-47f8-81b8-91f386217474.png)

**Comment by gouttierre** [comment]
@Dazmurphy - Thanks for filing this issue with us. Our team will have a look but to set expectations, we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items.

@bsunderhus - Would you be able to confirm if this is a regression, or if this behavior is an issue with RTL mode?
cc @smhigley

**Comment by tronguye** [comment]
I'm also seeing this issue with the teaching bubble when using the `dir` attribute. Tried on forked codepen from fluent docs
