### ISSUE TITLE
Details List: support hidden property for list items to support filtering

### ISSUE THREAD

**Issue by yangjocy** [microsoft/fluentui#19762]
#### Describe the feature that you would like added

Support `hidden` property for list items so that filtering is feasible.
Currently, we have to provide a filtered `items` to implement filtering, but that brings problems with user selection -- filtered out items will be removed from `selection`.

#### What component or utility would this be added to

Details List

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

Related issue: https://github.com/microsoft/fluentui/issues/14084 (closed)
Raise this issue because I think adding a property is feasible despite the complexity and dependencies of List components.
![image](https://user-images.githubusercontent.com/11807272/146896717-cf9239eb-c338-4e5e-aafc-87582d3b22de.png)

**Comment by GeoffCoxMSFT** [comment]
@yangjocy Thanks for the good feature request.  I’ll mark this as a feature request and add it to our backlog, but we’re likely not going to get to it for a while as we’re currently focused on larger convergence work, vNext, and enhancements to our performance.

I think there are some more details about this feature to resolve before it could be added to DetailsList.  I don't think this is an exhaustive list, but here are my thoughts:

- If a selected item is hidden by the filter rather than removed, it will still be in the list of selected items.  This would cause the selection count and the visualization of selection to not match.  Users would not be able to unselect those items unless they cleared the filter.
- The list controls re-render when the items array changes (or any other props), but not when state inside the items change.  You can read more about this under [My List is not re-rendering when I mutate its items. What should I do?](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist). The items are specified to be general purpose and the rendering of items to be overridden.  This makes it difficult to enforce a hidden property for items and to decide who is responsible for not rendering hidden items. Should the item render even be called for hidden items?
- The lists are virtualized, so it would have to be sure to handle excluding hidden items from measurements, etc.  Because the column widths are measured to try and fit the items, it is unclear if they should include hidden items or not.
- Lists can have select all actions.  Does this apply to hidden items?
- Server side rendering and server side data retrieval gets the benefit of not sending down filtered out items to the client.  With the hidden approach, the control would have to receive all of the data.

**Comment by yangjocy** [comment]
> @GeoffCoxMSFT
> 
> * I think user could understand that some of the selection will be unseen, or cannot be unselected, or cannot match the selection count, if they are filtered out -- that's how filtering works, right? It hides the items rather than removes them. Plus it is more confusing (and risky) to let user selection gets magically unselected after filtering.
> * I'm thinking a similar behavior as `checkboxVisibility`, which is not rendering the item if it's set to `hidden`. If visibility of the `Checkbox` could be controlled, then I assume it could do the same for items. And if the items array needs to be recreated to get re-rendered, then recreate it. That's acceptable as it is just follows what Details List does now.
> * As I see in the code, the width is determined by `column` and `cellStyleProps`, and doesn't seems to be impacted by a hidden item. Please correct me if my understanding is wrong.
> 
> ```js
>         const width: string | number =
>           typeof column.calculatedWidth === 'undefined'
>             ? 'auto'
>             : column.calculatedWidth +
>               cellStyleProps.cellLeftPadding +
>               cellStyleProps.cellRightPadding +
>               (column.isPadded ? cellStyleProps.cellExtraRightPadding : 0);
> ```
> 
> * Yes. The filtered out items doesn't have to be rendered, but needs to be added in `selection` object.
> * For SSR I think consumer could decide whether they want to send hidden items to client. `hidden` won't impact html file anyway (if we agree not to render hidden items). But I agree it seems more reasonable to send out all the data including the filtered data, because if consumer doesn't want the filtered data, s/he could simply remove it from `items` rather than hide it.
>   
>   * BTW, doesn't fluent ui handle SSR now? I understand it supports SSR but don't know whether it has special handling for SSR.

@GeoffCoxMSFT How do you think?
