### ISSUE TITLE
Add description to ComboBox

### ISSUE THREAD

**Issue by AkiraVoid** [microsoft/fluentui#19879]
#### Describe the feature that you would like added

The `TextField` component has property `description` which can render a line of text under the input box. As `ComboBox` is a combination of `TextField` and `Dropdown`, it should support this feature.

#### What component or utility would this be added to

ComboBox

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

None.

**Comment by gouttierre** [comment]
@AkiraVoid - I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance.
However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!
