### ISSUE TITLE
Add readonly state to Checkbox

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/fluentui#20010]
#### Describe the feature that you would like added

Checkbox should support readonly state. In this state, the control is still focusable and meets a11y requirements for contrast. Data would still be sent to the server if used in FormData. But the user is clearly informed that they can't interact with it. Pointer does not change on hover, and clicking does nothing.

#### What component or utility would this be added to

Checkbox

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

N/A

**Comment by gouttierre** [comment]
@mark-wiemer -I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. However, If you come up with a solution in the interim and would like to submit a PR for this request - our team will gladly review it!
