### ISSUE TITLE
DetailList Issue with scroll when multiple groups added and one large group

### ISSUE THREAD

**Issue by nimeickl** [microsoft/fluentui#20037]
### Environment Information

- **Package version(s)**: 7.170.2
- **Browser and OS versions**: Edge

### Describe the issue:

When multiple groups are added to the DetailList and one group is ~200 items or more, the scrollbar jumps once you get near the bottom of the page. Seems like there is an issue calculating the page height causing a jump.

#### Actual behavior:

When nearing the bottom of the DetailList, the scrollbar jumps to a different position instead of going to the bottom of the page successfully. This means some items can't be seen. 

#### Expected behavior:

Can scroll to the bottom of the page without issue and see all items in each grouped list.

### If applicable, please provide a codepen repro:
https://codepen.io/nicolemeickle/pen/jOwdomj

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking / High

Products/sites affected: yes

**Comment by shrevek** [comment]
We are experiencing this problem as well. The number of items curerntly shown does seem to cause it to happen and I have noticed the problem most often when I pull the scroll bar down rather than scrolling with the mouse wheel.

Even on the example from the documentation page this occurs:
https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlis

As shown in this screen capture
https://user-images.githubusercontent.com/1272428/142836919-d50f17b9-e7c9-47ca-9a0d-abfb97c0dd39.mp4

**Comment by spmonahan** [comment]
I think this is due to how row and page heights are calculated for layout virtualization.

Probably related Github issues:

- #20825
- #20978
