### ISSUE TITLE
Checkbox checkmark should have opacity 0 in indeterminate state

### ISSUE THREAD

**Issue by MPor80** [microsoft/fluentui#20043]
### Environment Information

- **Package version(s)**: fluentui/react": 8.29.2

The chekmark inside checkboxes is set to opacity 0 on hover when the checkbox is in indeterminate state. However, it is still visible in indeterminate state without hover, as can be seen here:

![indeterminate dark](https://user-images.githubusercontent.com/91671706/135452294-52f3c73f-6108-4edd-bea5-f165373a8d74.png)

Usually that is not an issue, unless you change the checkmark color like we did here in dark theme. Then the white checkmark is still visible in the indeterminate checkbox.

#### Actual behavior:

Checkmark is visible in indeterminate state without hover.

#### Expected behavior:

Checkmark shouldn't be visible (opacity 0) in indeterminate state, regardless of hover.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Power Query for Mac

Thanks in advance!

**Comment by GeoffCoxMSFT** [comment]
@MPor80 - Do you have a codepen or codesandbox that replicates this?  I am having trouble reproducing using the fluent site with the dark theme applied.

**Comment by GeoffCoxMSFT** [comment]
Investigated with @smhigley, who figured out that the issue is when the checkbox is controlled, in the checked state, and gets set back to indeterminate.  This causes the opacity to be set back to 1 by a style rule on the checkmark that is not accounting for indeterminate state.  

I will get a PR out today to fix this issue in v8.
