### ISSUE TITLE
Modal's keep in bounds unexpected behaviour

### ISSUE THREAD

**Issue by martinowren** [microsoft/fluentui#20122]
### Environment Information

- **Package version(s)**: 8.2.2
- **Browser and OS versions**: Edge, Chrome, Firefox, MacOS, Windows. Tested on various versions of all OS'es and browsers. 
- 

### Please provide a reproduction of the bug in a codepen:

I am not able to reproduce the bug in codepen. I will instead provide some code used to render the modal. 

```JSX
const getModalStyles = (
  data: PinnableTooltipData,
  hide: boolean
) => ({
  root: {
    display: hide ? "none" : "flex",
    alignItems: "start",
    justifyContent: "left",
  },
  main: {
    minHeight: 0,
    minWidth: 0,
    overflowY: "initial",
    top: data.tooltipAttributes.top,
    left: data.tooltipAttributes.left,
  },
});
<Modal
  isOpen={true}
  dragOptions={{
	    moveMenuItemText: "Move",
	    closeMenuItemText: "Close",
	    menu: ContextualMenu,
	    keepInBounds: true,
  }}
  isModeless={true}
  styles={getModalStyles(data, hide)}
>
	CONTENT
</>
```

#### Actual behavior:

The modal bounding is a lot smaller than the viewport. 

https://user-images.githubusercontent.com/22822433/136192295-6f59cf19-162b-42e0-b9cb-51e28c0aac49.mov

#### Expected behavior:

The modal bounding box should fill the whole viewport. 

### Priorities and help requested:

Requested priority: Normal

Any help/advice in debugging would be greatly appreciated.

**Comment by martinowren** [comment]
Looks like the video was not uploaded in the original post, here is the video of the bug. 

https://user-images.githubusercontent.com/22822433/136192295-6f59cf19-162b-42e0-b9cb-51e28c0aac49.mov

**Comment by mgamis-msft** [comment]
This unexpected bound behavior seems to be triggered when Modal styles prop `main.top` is assigned to a non-zero value.

**Comment by JamesBurnside** [comment]
Here's a pen for repro: https://codepen.io/jaburnsi/pen/ExoWgNK

Looking into the fluent modal code, this is because of how the min and max values for the clamping are calculated:

https://github.com/microsoft/fluentui/blob/b7f17e976f9e058f39c9fce4f0f9bb6eb4dfa577/packages/react/src/components/Modal/Modal.base.tsx#L212-L216

Fluent assumes the modal is positioned in the center of the screen. Because of this the calculation of the minPosition and max position being +-top and +-left do not work when `.top` is changed.
Similarly the keepInBounds will show failures if any of `.bottom`, `.left` or `.right` is set (likely coupled with `position: absolute` to allow placement anywhere).

One fix could be for Fluent to use the bounds of the parent component that typically fills the draggable zone:
https://github.com/microsoft/fluentui/blob/b7f17e976f9e058f39c9fce4f0f9bb6eb4dfa577/packages/react/src/components/Modal/Modal.base.tsx#L472

However I do not have good insight to say this would work in all scenarios.

A less risky fix would be to extend the API to allow a developer using the modal to pass in the minPosition and maxPosition and use that as the internal state position if passed in:
```ts
internalState.minPosition = props.dragBounds?.keepInBoundProps?.minPosition ?? { x: -modalRectangle.left, y: -modalRectangle.top };
internalState.maxPosition = props.dragBounds?.keepInBoundProps?.minPosition ?? { x: modalRectangle.left, y: modalRectangle.top };
```

However this issue only appears to result when a developer wants to position the modal somewhere other than the center of the screen. Perhaps there is a way to position the modal such that the keepInBounds check does not fail? (i.e. position by not using .top/.bottom/.left/.right on the `main` element in the modal) -- Fluent do you know if this would be possible?
