### ISSUE TITLE
vNext Avatar color assignment leans heavily towards pink/purple/red

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluentui#20176]
Current
![image](https://user-images.githubusercontent.com/48726002/136630917-b418102c-a2d5-48a4-b254-a7619581f59c.png)
Current color assignment seems to result predominantly in the pink, purples, and reds. Is there a way for the yellow/greens/blues to be picked up more? 

Environment: https://fluentuipr.z22.web.core.windows.net/heads/master/react-components/storybook/index.html?path=/story/components-avatar--colors

**Comment by behowell** [comment]
The colors are assigned based on a string hash of the person's name. I checked the hash function against 200,000 names (combined the top 200 first names and 1000 last names), and the distribution of colors looks even.

Here's a demo of 2000 random avatars, plus the breakdown of colors for the 200,000 names:
https://behowell.github.io/csb-nmp9z/

@daisygeng I'm going to close this as not repro since the code doesn't seem to be biasing one color over another. If you're still seeing a bias towards pink/purple/red, then it's possible it could be because there are more pinks/purples/reds in the list of possible Avatar colors. If that's the case, then the fix would be to change the list of colors for Avatar; let me know if you'd like to do that.
