### ISSUE TITLE
DetailsList - Custom Item Columns

### ISSUE THREAD

**Issue by mikaelnilsson77** [microsoft/fluentui#20213]
refers to non visible code:
**import { createListItems, IExampleItem } from '@fluentui/example-data';**

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. 

@khmakoto  - Would you be able to look at the code documentation to ensure we not mentioning non visible code.

**Comment by ecraig12345** [comment]
`@fluentui/example-data` is a package which is [available on npm](https://www.npmjs.com/package/@fluentui/example-data), and you can see the source code [in our repo](https://github.com/microsoft/fluentui/tree/master/packages/example-data). It's just used so that we don't have to repeat the code for item creation helpers across all the examples. The code isn't particularly relevant for real usage because in that case, you would define your own item type with the appropriate fields.
