### ISSUE TITLE
FocusZone in DetailList component doesn't fully support multiline TextField

### ISSUE THREAD

**Issue by halerankin** [microsoft/fluentui#20301]
### Important note

This bug references a previous bug [#12177](https://github.com/microsoft/fluentui/issues/12177) which has since been closed but was never resolved. Environment information and reproduction steps are available within.

Before reviving this bug I re-tested to make sure this was still an issue. 

### Environment Information

- **Package version(s)**: Fluent UI React 8.37.1
- **OS version**: Mac OS 11.6
- **Browser versions**: Chrome 95.0.4638.54, Firefox 93.0, Edge 95.0.1020.30

This bug is a blocker to creating an editable grid control for the ADUX Control Library React. The following is a [Teams conversation](https://teams.microsoft.com/l/message/19:7a3948b85c34414299156f678a1fbf2e@thread.tacv2/1632643231454?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=65b0a80d-5edc-4728-a7d2-676ebbaa28b1&amp;parentMessageId=1632431903633&amp;teamName=ADUX%20Control%20Library&amp;channelName=Discussions%20-%20Engineering&amp;createdTime=1632643231454) about the issue.

**From Philip Liu:**
When a textbox/textarea is embedded in a grid cell, in edit mode, and having the keyboard input focus, an arrow key is expected to change the cursor position in the textbox/textarea.  The actual behavior is an arrow key always selects an adjacent grid cell and never changes the cursor position within the current embedded textbox/textarea, i.e. similar to how arrow keys work in Excel.  You can try asset details > schema tab > edit to see for yourself.

**Questions:**
- What gesture and key chord should set the keyboard input focus to an embedded textbox/textarea in a grid so that arrow keys change the cursor position within the textbox/textarea?
- What gesture and key chord should set the keyboard input focus to the grid so that an arrow key selects an adjacent grid cell?

**Comment by kidokidozh** [comment]
@smhigley The root cause of this issue is that `FocusZone` does not handle `textarea` element in the below method `_shouldInputLoseFocus`. It only considers the situation of `input` element.
https://github.com/microsoft/fluentui/blob/906d31cfa368c25d75f23e47821299575eda1eb1/packages/react-focus/src/components/FocusZone/FocusZone.tsx#L1324

We can fix the bug by adding a `onKeyDown` handler to textarea, and stop event propagation if cursor is moving inside it. But I think it's better that you can fix this problem in component side.
