### ISSUE TITLE
fix: Wrong z-axis order for `fluent-accordion` in `@fluentui/webcomponents`

### ISSUE THREAD

**Issue by davidxuang** [microsoft/fluentui#20376]
# 🐛 Bug Report

Wrong z-axis order for overlaying controls (e.g. `fluent-select`) inside `fluent-accordion`.

## 💻 Repro or Code Sample

``` html
<fluent-accordion>
  <fluent-accordion-item expanded>
  <label slot="heading">Encryption</label>
  <!-- ... -->
  <div class="flex-column">
    <label id="cipher">Cipher</label>
    <fluent-select aria-labelledby="encryption">
        <fluent-option value="0">None</fluent-option>
        <fluent-option value="1" disabled>AES-128-GCM</fluent-option>
        <fluent-option value="2" disabled>AES-256-GCM</fluent-option>
        <fluent-option value="3" disabled>ChaCha20-Poly1305</fluent-option>
    </fluent-select>
  </div>
  <!-- ... -->
  </fluent-accordion-item>
  <fluent-accordion-item>
  <label slot="heading">Security</label>
  <!-- ... -->
  </fluent-accordion-item>
</fluent-accordion>
```

## 🤔 Expected Behavior

ListBox of Select should be over the accordion heading stuffs.

## 😯 Current Behavior

![图片](https://user-images.githubusercontent.com/24728204/138886595-e4ab890b-090d-448f-8a4a-d3c9ced3cef3.png)

## 💁 Possible Solution

Currently, Accordion heading has a `z-index` of `2` while that of ListBox of Select is `1`, so this may be fixed by just modifying CSS.

## 🔦 Context

Building a form dialog with classified options with Blazor.

## 🌍 Your Environment

* OS & Device: Windows 11
* Browser Microsoft Edge 95.0.1020.30, Mozilla Firefox 93.0
* Version 2.0.0

**Comment by robarbms** [comment]
I did some digging and found the problem in fast-accordion-item. The actuator for expanding and collapsing each accordion item is a button that is between start, end and the icon elements. It doesn't span the full width but is trying to capture clicks  for the entire header. They used a clever trick of adding a ::before pseudo element positioned absolute to span the entire width of the header. This was however covering the start, end and icon and swallowing clicks for this. To prevent this, `z-index: 1` was applied to the pseudo element and `z-index: 2` on start, end and icon elements. This forced them on top but caused header elements to appear above other elements unexpectedly.

The accordion item was built that z-index isn't really needed. Button comes before start, end and icon in the DOM and using grid, start is positioned left of the button. It was just the position: absolute on the button::before pseudo element that forced it above everything. Adding to `position: relative` to start, end and icon removes the need for z-index. This pops those elements above the pseudo element since they come after it in the DOM order.
