### ISSUE TITLE
feat: add persona component

### ISSUE THREAD

**Issue by Ciwo-K** [microsoft/fluentui#20377]
# 🙋 Feature Request

I'd like to use the persona component from Fluent UI.
I would appreciate a automatic initials to picture option. I'd like to use it to show userinformation about the active user.
![image](https://user-images.githubusercontent.com/62892625/138276379-0a609633-113f-4cff-bb50-ccb97b0478a7.png)

**Comment by AndrewCraswell** [comment]
Kinda. The Avatar is a part of the Persona component. The Persona brings together the Avatar, and [Presence Badge](https://6002298f95a00c00213f4d55-cchhefncfe.chromatic.com/?path=/docs/components-presence-badge--default) with profile information (full name, secondary text, etc) to give a basic representation of a user with details. But since Fluent v9 already includes an Avatar and the Presence Badge, seems like building a Persona feature would be more relevant there for now.
