### ISSUE TITLE
`Stack` should expose `componentRef`

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fluentui#20410]
#### Describe the feature that you would like added

As far as I can tell the [Stack](https://developer.microsoft.com/en-us/fluentui#/controls/web/stack) element does not expose any way to access the ref property of its underlying html elements. e.g. for use in [useResponsiveMode](https://github.com/microsoft/fluentui/blob/1817a5e193448ab6f456e3bd9445e537fd64348c/packages/react/src/utilities/hooks/useResponsiveMode.tsx#L12).

Components such as [Button](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) do expose a componentRef.

#### What component or utility would this be added to

Stack

#### Additional context/screenshots

See related stackoverflow post: https://stackoverflow.com/questions/68029261/how-to-obtain-ref-of-stack

**Comment by khmakoto** [comment]
Hi @JamesBurnside, thanks for filing this issue. While it is true that `Stack` does not have an exported `componentRef` it does have a `ref` property taht should be enough for use in `useResponsiveMode`. Have you tried that approach?

**Comment by JamesBurnside** [comment]
As far as I can tell `Stack` does not expose a `ref` property either:
![image](https://user-images.githubusercontent.com/2684369/141496787-d5380df6-3534-4490-9f57-748089878370.png)

Can you give an example of how to use it?

I am using fluent version: `"@fluentui/react": "8.17.4",`

**Comment by pineaulo** [comment]
I have the same issue, using office-ui-fabric-react 7.174.1

**Comment by FeodorFitsner** [comment]
Found a nice workaround:

```javascript
const stackId = "<generate-random-id>";

React.useEffect(() => {
  const div = document.getElementById(stackId); // this is Stack's div element
})

return <Stack id={stackId}> ... </Stack>
```

**Comment by khmakoto** [comment]
> > Because this issue has not had activity for over 180 days, we're automatically closing it for house-keeping purposes.
> > _Still require assistance? Please, create a new issue with up-to date details._
> 
> ☹️

Reopening

**Comment by gouttierre** [comment]
This issue has been queued for upcoming investigations. To set expectations the developers will review this issue once capacity allows and all updates will be posted on the issue accordingly.

**Comment by Hotell** [comment]
> While it is true that Stack does not have an exported componentRef it does have a ref property that should be enough 

Stack is implemented as Functional Component via `createComponent` api from foundation legacy package. That means it does not support `ref`. To make it support `ref` we would need to wrap it within `forwardRef`, which might not be trivial/wanted as it would affect all packages that use this API. 

To provide more context: this inconsistency between v8 components is caused by using various React/Fluent API to create React component ( Button, Label use Class API which support `ref` default, other components some use `styled` and others(Stack) `createComponent` ).

I'm not 100% familiar with the reasonings behind this, but from my POV if we want support `ref` the easiest approach would be to transform `Stack` to class component. If agreed by author @khmakoto anyone from community is more than welcome to send a PR.
