### ISSUE TITLE
FocusZone inside a Callout doesn't handle PageDown key correctly

### ISSUE THREAD

**Issue by dotnetjunky** [microsoft/fluentui#20526]
### Environment Information

- **Package version(s)**: 8.41.1
- **Browser and OS versions**: Edge on Mac or Windows

### Please provide a reproduction of the bug in a codepen:

1. Place a `FocusZone` inside a `Callout` component. Set the `setInitialFocus` prop of the `Callout` to `true`.
2. Add lots of focusable controls inside the `FocusZone` so that they span multiple pages. 
3. When focus is inside the `Callout`, pressing DownArrow key repeatedly to move focus to an element near the bottom of the current page.
4. Now press Page Down and observe the element at the top of the new page. The page is scrolled down way more than it should.

Here's the codepen to repro the bug: https://codepen.io/dotnetjunky/pen/XWaZvqN 

#### Actual behavior:

The element at the top of the new page is far below the element at the bottom of the previous page. 

#### Expected behavior:

The element at the top of the new page is at most only one place below the element at the bottom of the previous page.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Office Online

**Comment by khmakoto** [comment]
Hi @dotnetjunky, I don't think this is a bug but by design. You can take a look at how many elements the focus jumps from time to time. In your example it consistently jumps 23 elements (from 0 to 23, from 23 to 46, etc. when doing `PageDown`). I think this is by design in how focus is handled in the `FocusZone`.

**Comment by dotnetjunky** [comment]
@khmakoto You're correct that it jumps over the right number of elements; but the real problem here is that the focused element is shifted within the viewport of the current page. 

If I place focus on an element near the bottom of the viewport, when I page down, I expect the new focused element to be placed near the bottom too. 

Here's how it behaves currently. I'm on Element 14 near the bottom and I Page down:

![image](https://user-images.githubusercontent.com/7623075/140738817-1bac4f87-c7b0-493c-a645-e537ec905354.png)

Element 30 gets the focus, but it's in the middle of the viewport: 

![image](https://user-images.githubusercontent.com/7623075/140738976-80c1524b-039f-4b2d-b711-54e07c47986b.png)

Notice that Element 22 is at the top of the new viewport. As a result, users never see elements 16 to 21.

**Comment by petewu100** [comment]
The design criteria we should meet is that if the user press Page Down repeatedly, each item in the list should be rendered at least once during the scrolling so that the user can visually scan for the item they are looking for. Right now, we do not meet this criteria since some items get skipped and that impacts the usability of keyboard navigation.
