### ISSUE TITLE
ContextualMenu as Submenu in Callout doesn't position or scroll correctly when finalHeight provided

### ISSUE THREAD

**Issue by CampbellOwen** [microsoft/fluentui#20619]
### Environment Information

- **Package version(s)**: 8.42.0

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/campbellowen/pen/JjyeMgz

#### Actual behavior:

When the contents of a ContextualMenu used as a submenu for a Callout have dynamic height and I provide a value of `finalHeight` in `calloutProps`, the submenu callout no longer repositions itself properly or allows scrolling

#### Expected behavior:
In the codepen, when you click the button to expand the submenu note that there's no scrollbar and the submenu does not move up to fit on the screen.
If you delete the line of code where I commented that sets `finalHeight`, it'll work correctly.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Office Online

**Comment by CampbellOwen** [comment]
@smhigley fyi

**Comment by smhigley** [comment]
This led me to an interesting and undocumented behavior 🤔. In Callout, there's a `hideOverflow` prop, and it turns out that its value defaults to `!!finalHeight`: https://github.com/microsoft/fluentui/blame/f8113b88c86cccedd5f232640ef70c4e6282bca8/packages/react/src/components/Callout/CalloutContent.base.tsx#L404

So if you set `finalHeight` and want the overflow to have a scrollbar, setting both explicitly works for me in the codepen:
```js
finalHeight: 36*100,
hideOverflow: false
```

@CampbellOwen does that resolve your issue?

**Comment by CampbellOwen** [comment]
Unfortunately this only fixes one of the issues, which is the lack of scrolling. The other issue is that prior to this the submenu callout would position itself to fit on screen if possible. (in this case it'd be the height of the viewport and anchor to the top of the screen). 

The behaviour now seems to be forcing the callout to stick to its target, even if that means it won't fit

**Comment by smhigley** [comment]
Fixed in #20639
