### ISSUE TITLE
Hovercard using eventListenerTarget to trigger card open not working

### ISSUE THREAD

**Issue by schidella** [microsoft/fluentui#20646]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

In the example provided for Hovercard using eventListenerTarget to trigger card open on the official Fluent UI documentation on the following link https://developer.microsoft.com/en-us/fluentui#/controls/web/hovercard

#### Actual behavior:

![image](https://user-images.githubusercontent.com/94564911/142351331-20a1fbf4-da2b-433f-a79b-0fa833f0b211.png)
Hover not working on the 'Hover Zone' text

#### Expected behavior:

Hover should work just like the other examples

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: (if applicable)

**Comment by gouttierre** [comment]
@schidella -Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows. I see the repro on the website and code pen where the Hover doesn't work over the text as the other examples. 

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by spmonahan** [comment]
This is happening because the `.current` properties of the refs on the example are `null` on the first render and updating a ref does not trigger a render so `HoverCard` is effectively never passed the refs. I've forked the Codepen from the example to force a re-render when clicking the emoji `IconButton`. With the console open you can see the refs get updated after the first render and the example then works as expected. I think this is a bug.

[Forked Codepen](https://codepen.io/seanms/pen/KKXrEJv?editors=0011)

**Comment by spmonahan** [comment]
Hey @schidella , as part of working on a separate feature I spent some time reading about refs in React and I can offer a workaround for your issue: [callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs).

Essentially, you use a callback to set a ref which allows you to encapsulate some functionality to trigger a re-render when the ref is set, thus ensuring the hovercard works as expected. The downside to this is that you are triggering an extra render.

I've created a [Codepend demonstrating how to use callback refs with `HoverCard`](https://codepen.io/seanms/pen/oNowEML). Lines 23-36 are the bulk of the example.
