### ISSUE TITLE
Duplicate ID attribute value on Contextual Menu with Sub Menus

### ISSUE THREAD

**Issue by sivapalaniappan** [microsoft/fluentui#20682]
### Environment Information

- **Package version(s)**: 8:42:1
- **Browser and OS versions**: Win - Edge & Chrome

### Describe the issue:

Duplicate ID Attribute Values on ContextualMenu container element when using SubMenus

### Please provide a reproduction of the issue in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/8.42.1/#/examples/contextualmenu

![image](https://user-images.githubusercontent.com/25989832/142706922-548c0f93-16cf-4adf-90ef-24e5e182831c.png)

#### Actual behavior:

Duplicate ID Attribute Values

#### Expected behavior:

No duplicate ID Attribute values

### Documentation describing expected behavior

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. However, If you want to submit a PR for this in the mean time, please, feel free to do so and our team will review it.
