### ISSUE TITLE
Badge: informative color tokens do not work in outline/ghost in HC mode

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#20714]
Outline:
![image](https://user-images.githubusercontent.com/20744592/143014515-d0e55c50-1066-4682-aa1d-ff13bf57178b.png)

Ghost:
![image](https://user-images.githubusercontent.com/20744592/143014540-5da9ae92-9e6a-4cba-af03-311e8ffa98af.png)

The color token used here is `color neutral background 5` as in the design spec. However, this color provides no contrast with the canvas background in HC mode;

expected design

Outline:
![image](https://user-images.githubusercontent.com/20744592/143014673-7504a504-3013-408c-b797-e141d5296d4a.png)

Ghost:
![image](https://user-images.githubusercontent.com/20744592/143014699-a5ff2fb9-8731-4091-81f6-95f3057aca7f.png)

**Comment by daisygeng** [comment]
Fixed in the design spec:
https://www.figma.com/file/e0zRO2jOws26kqpJKvOgQS/Badge?node-id=0%3A1

For outline:
![image](https://user-images.githubusercontent.com/48726002/144303517-5103da38-8f2c-443f-a136-f09a584f6065.png)


For ghost:
![image](https://user-images.githubusercontent.com/48726002/144303465-d2ac9c80-78af-44fa-b8dc-d810ca5cbaf3.png)

**Comment by ling1726** [comment]
@daisygeng is the `informative ghost` variant supposed to be on brand background ? This is what I get with `neutral foreground 3`

![image](https://user-images.githubusercontent.com/20744592/145089283-a15b979e-54a6-478b-a037-7f3a9727662f.png)
