### ISSUE TITLE
migrate-converged-pkg: generator erases custom config `.storybook/preview.js`

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#20750]
I ran generator for `@fluentui/react-components` and it completely erased all changes in `packages/react-components/.storybook/preview.js`.

![image](https://user-images.githubusercontent.com/14183168/143233152-6a7af678-6591-48d3-8f5f-8a00c4287489.png)

**Comment by Hotell** [comment]
thanks for reporting issue!

That's expected behaviour - there is no AST parsing in place and for 1 use-case which is `react-components` it would be need extended  effort. Expectation is that owner of this package should be aware what was custom and needs to stay there - thus undoing particular changes within git.

I'm gonna keep this open for future reference , but this wont be fixed ATM for reasons mentioned. thanks for understanding.
