### ISSUE TITLE
Support `a` element as root for `MenuItem`

### ISSUE THREAD

**Issue by bsunderhus** [microsoft/fluentui#20777]
#### Describe the feature that you would like added

Anchor element should be supported by `MenuItem` by default as it's a normal use case to have a list of anchors on `Menu`

#### What component or utility would this be added to

MenuItem

#### Have you discussed this feature with our team, and if so, who

@ling1726 

#### Additional context/screenshots

This is an example of  overriding `MenuItem` for the lack of support for `a`

![image](https://user-images.githubusercontent.com/5483269/143426969-4e357056-125e-4a38-a3c5-042209651aac.png)

**Comment by ling1726** [comment]
Th big debate is whether we should support this through the `as` prop or create a new `MenuItemLink` component similar to what we have done for `MenuItemCheckbox`

Personally I like the `MenuItemLink` idea since it simplifies typings and usage for users and does not mean that props structure suddenly changes when someone uses a different value for `as`

**Comment by tudorpopams** [comment]
Hello, do we still want this implemented / discuss it with the broader team?

**Comment by ling1726** [comment]
We **must** create the `MenuItemLink` to support this ticket since we can't update the root slot type to accept other elements

See #25887
