### ISSUE TITLE
ContextualMenu componentRef is null

### ISSUE THREAD

**Issue by toml0006** [microsoft/fluentui#20908]
### Environment Information

- **Package version(s)**: 8.46.0
- **Browser and OS versions**: Chrome 96.0.4664.55, macOS 12.0.1

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/toml0006/pen/rNGVrOP

#### Actual behavior:

Setting the `componentRef` on `<ContextualMenu/>` results in a null ref every time.

#### Expected behavior:

`componentRef` should be defined

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: internal for now

**Comment by layershifter** [comment]
I modified CodePens to show the problem:
- v7 https://codepen.io/layershifter/pen/abLNJLO
- v8 https://codepen.io/layershifter/pen/dyVMNPa

In v7 it returns an instance of `ContextualMenuBase` (👇), in v8 it's just `null`.

![image](https://user-images.githubusercontent.com/14183168/145063637-5d023f70-f079-48a1-8b80-1c8d8c65db46.png)

---

However, according to typings it should be just an empty object:

https://github.com/microsoft/fluentui/blob/91c9bbd9f3f78912671c1a431bf6020a6485e693/packages/react/src/components/ContextualMenu/ContextualMenu.types.ts#L37-L51

@toml0006 can you please clarify what is expected behavior? Do you expect to have an object as `componentRef`?
