### ISSUE TITLE
Disabled CommandBar buttons are accessible throught focus.

### ISSUE THREAD

**Issue by ilanbd** [microsoft/fluentui#20928]
Actual behavior:
Disabled CommandBar buttons are accessible throught focus.

Expected behavior:
A disabled button should not get the focus

**Comment by layershifter** [comment]
Can you please fill the whole issue template? It's not clear to what version of Fluent UI it's related.

**Comment by ilanbd** [comment]
![chrome-capture](https://user-images.githubusercontent.com/19327745/145002063-9064d1a0-940a-4d06-aa44-e5158a3f27e6.gif)

Personnaly I am using version 8 but I don't think that this issue is related to a specific version.
I have added a screenshot from the FluentUI website where you can see the bug

**Comment by layershifter** [comment]
@ilanbd thanks for details. It's by design:

https://github.com/microsoft/fluentui/blob/6ca0355f6740f836ff4df009687718a380085247/packages/react/src/components/CommandBar/CommandBar.base.tsx#L170-L173

However, you can still pass `allowDisabledFocus: false` to `items`:

```tsx
const _items: ICommandBarItemProps[] = [
  {
    key: "share",
    text: "Share",
    allowDisabledFocus: false,
    iconProps: { iconName: "Share" },
    disabled: true
  },
]
```

I made a Codesandbox with an example: https://codesandbox.io/s/awesome-https-hj66u?file=/src/App.tsx.
