### ISSUE TITLE
SearchBox component: a cursor can't be placed after the first letter

### ISSUE THREAD

**Issue by argrygor** [microsoft/fluentui#20938]
To reproduce:
https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox
Type anything in the search box component.
Try to place cursor after the 1st letter 

#### Actual behavior:

The cursor is placed before the 1st letter. All other letters work properly.

#### Expected behavior:

Should be possible to place cursor at any position

### Priorities and help requested:

Requested priority: High

Products/sites affected: all products

**Comment by raj-pat** [comment]
![CursorNot Working](https://user-images.githubusercontent.com/43891519/144937192-52e3764e-8942-482a-9ff0-db585e373f99.gif)

**Comment by layershifter** [comment]
I checked and the problem is present in both v7 & v8.

A codepen for v8: https://codepen.io/layershifter/pen/VwMaayB

---

The problem is caused by `onClickFocus` handler for `icon`:

![image](https://user-images.githubusercontent.com/14183168/145033870-430c3048-830e-4934-9847-8f178f44f285.png)

Matching place in code:

https://github.com/microsoft/fluentui/blob/7cb2a5d8db1b6a1ddb638aa82d5815ab5ae84e69/packages/react/src/components/SearchBox/SearchBox.base.tsx#L131-L136

This happens because icon only changes `opacity`, but still handles events. A fix is to set in this case `pointer-events: none`:

```css
.ms-SearchBox.is-active .ms-SearchBox-icon {
  pointer-events: none;
}
```

https://codepen.io/layershifter/pen/eYGZZQR

---

I will submit a PR to fix it.

**Comment by argrygor** [comment]
@layershifter thank you for a prompt response!
Unfortunately, the fix doesn't solve all cases. It works if a cursor is already in the search box. However, during the first placement, it still doesn't work properly. Here is the gif:
![fix1](https://user-images.githubusercontent.com/95659191/145064906-a541c46c-2161-4259-94a3-7f65cd3f9141.gif)

**Comment by layershifter** [comment]
> @layershifter thank you for a prompt response! Unfortunately, the fix doesn't solve all cases. It works if a cursor is already in the search box. However, during the first placement, it still doesn't work properly. Steps to reproduce:
> 
> * type something
> * click outside of the search
> * try to place cursor after 1st letter
> 
> Here is the gif: ![fix1](https://user-images.githubusercontent.com/95659191/145064906-a541c46c-2161-4259-94a3-7f65cd3f9141.gif)

Hmm... Good catch 👍 One more override solves that problem:

```css
.ms-SearchBox:hover .ms-SearchBox-icon {
  pointer-events: none;
}
```

https://codepen.io/layershifter/pen/oNGxZrw
