### ISSUE TITLE
Upgrade to Typescript 4.4+

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/fluentui#20942]
According to TS team, 4.4 has "some big perf wins." 4.5 is current as of writing, but we should probably try 4.4 first.

**Comment by chrisdholt** [comment]
We won't be able to move the Web Components to Typescript v4.4 as part of this due to an issue where lib-dom ARIAMixin value typings changed from `string | null` to `string`, essentially making these "non-nullable", which is problematic. This problem was initially raised here: https://github.com/microsoft/TypeScript/issues/45047 and can be seen in the table denoting that a trivial fix is not available for this. 

On the heels of this, the Typescript team quickly has provided a feature as of v4.5.0 which allows teams to pin lib-dom versions, which would enable stability between minor versions and allow us to move ahead. Without that, we'll hit build errors due to the typing incompatibilities noted above.

**Comment by chrisdholt** [comment]
> We won't be able to move the Web Components to Typescript v4.4 as part of this due to an issue where lib-dom ARIAMixin value typings changed from `string | null` to `string`, essentially making these "non-nullable", which is problematic. This problem was initially raised here: [microsoft/TypeScript#45047](https://github.com/microsoft/TypeScript/issues/45047) and can be seen in the table denoting that a trivial fix is not available for this.
> 
> On the heels of this, the Typescript team quickly has provided a feature as of v4.5.0 which allows teams to pin lib-dom versions, which would enable stability between minor versions and allow us to move ahead. Without that, we'll hit build errors due to the typing incompatibilities noted above.

We’ve resolved this - FYI, so we can upgrade any time!
