### ISSUE TITLE
Some Calendar elements have no color set which makes them unreadable in dark theme

### ISSUE THREAD

**Issue by johannes-z** [microsoft/fluentui#21018]
### Environment Information

- **Package version(s)**: latest/src
- **Browser and OS versions**: Edge, Win 10

### Describe the issue:

Some Calendar elements don't set the theme color, so they remain dark.

One occurence is the CalendarPicker's currentItemButton: https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Calendar/CalendarPicker/CalendarPicker.styles.ts#L51

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/johannes-z/pen/oNGBqQE

#### Actual behavior:

Calendar elements are unreadable in dark theme.

#### Expected behavior:

Calendar elements should be readable in dark theme.

### Documentation describing expected behavior

??

**Comment by gouttierre** [comment]
@johannes-z - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm the colors used in the dark theme are correct to a11y standards? Thank you

**Comment by smhigley** [comment]
Fixed in this PR: #21896

@johannes-z it looks like there's one remaining issue in your codepen, where the "Go to today" button has dark text because `pallette.neutralTertiaryAlt` is being passed in a dark hex value in your custom theme. I verified that changing the value passed to `createTheme` did fix the issue. Feel free to re-open if you're still running into problems with Calendar buttons not picking up dark theme values.
