### ISSUE TITLE
Sorting is not working as expected in Chinese language

### ISSUE THREAD

**Issue by v-pasha2** [microsoft/fluentui#21097]
Sorting is not working as expected for detail list component.

https://codepen.io/v-pasha2/pen/WNZOmNO 

We are using following strings to sort.

const itemList=['任务','权限','反馈','测试','表权限'];

Expected Ascending Order should be - 
<img width="89" alt="image" src="https://user-images.githubusercontent.com/88125031/146770981-5aeac226-bbb6-410b-9a6f-c5fafe619996.png">

However in current implementation we are getting below order.
<img width="318" alt="image" src="https://user-images.githubusercontent.com/88125031/146771181-fe69b2dd-f475-410e-b226-590871442b8f.png">

**this issue is happening only for Chinese based OS.**

**Comment by gouttierre** [comment]
@v-pasha2 - Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue with the Chinese based OS? Thanks

**Comment by spmonahan** [comment]
Without having access to a Chinese-based OS nor the ability to read Chinese I'll have to speculate a bit :)

In the linked example sorting is handled by the `_copyAndSort()` function:

```ts
function _copyAndSort<T>(items: T[], columnKey: string, isSortedDescending?: boolean): T[] {
  const key = columnKey as keyof T;
  return items.slice(0).sort((a: T, b: T) => ((isSortedDescending ? a[key] < b[key] : a[key] > b[key]) ? 1 : -1));
}
```

I suspect the issue is that the comparisons used for sorting don't work correctly for Chinese. The [`String.prototype.localeCompare`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) method should allow Chinese to be correctly sorted and in [my testing `localeCompare` seems to resolve the issue](https://codepen.io/seanms/pen/QWmKqzg) (check lines 310-319 for my changes).

For reference I changed the `_copyAndSort()` function to this:

```ts
function _copyAndSort<T>(items: T[], columnKey: string, isSortedDescending?: boolean): T[] {
  const key = columnKey as keyof T;
  return items.slice(0).sort((a: T, b: T) => {
    const order = a[key].localeCompare(b[key], 'zh-CN');
    if (isSortedDescending) {
        return order;
    }
    return -1 * order;
   });
}
```

In a real application this function would need to be made a bit more robust. For example, here I know that `a[key]` is a `string` so I can safely call `localeCompare()` but that's not necessarily guaranteed.
