### ISSUE TITLE
TagPicker: CreateGenericItem doesn't work correctly when itemLimit is set

### ISSUE THREAD

**Issue by vorobievik** [microsoft/fluentui#21156]
### Environmental Information

- ** Package version (s) **: 8.44.0
- ** Browser and OS Versions **: Chrome

### Please provide a reproduction of the error in the code-behind:
https://codepen.io/vorobievik/pen/eYGrKwX?editors=1111

#### Actual Behavior:
if we set a custom tag with itemLimit and press Enter - the last item was added and then removed (I think the reason is in the  bubbling event - because after addItem onRemoveItem is called)

#### Expected Behavior:
a custom tag can be added using itemLimit

Requested priority: (high)

**Comment by Trish92** [comment]
Following this issue

**Comment by Trish92** [comment]
There is a race condition, if you add a debugger you will see that this works as expected. 
```
  BasePicker.prototype.canAddItems = function () {
        var items = this.state.items;
        var itemLimit = this.props.itemLimit;
        return itemLimit === undefined || items.length < itemLimit;
    };

```
This function is being called in multiple places in the base picker. The last condition determines whether the item should be added to the selected items list and this.props.itemLimit is not correct because of the race condition. The function call that is causing this has to be isolated.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thanks
