### ISSUE TITLE
Datepicker not showing scrollbar if datepicker size is more than viewport.

### ISSUE THREAD

**Issue by AjayKumar84** [microsoft/fluentui#21208]
### Environment Information

- **Package version(s)**: 0.59.0 
- **Browser and OS versions**:  All browser and OS

#### Actual behavior:

We are using DatePicker inside Dialog but in low resolution screen or if user try to zoom-in in browser, Datepicker not showing scroll if we don't have enough space to render.

You can notice, few date in bottom of Datepicker not visible and user don't have any option to scroll.
![image](https://user-images.githubusercontent.com/44785092/148501472-92cb4583-70f9-4d6b-8b61-20736c810684.png)

#### Expected behavior:

We should have scrollbar in Datepicker

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

Products/sites affected: (if applicable)

**Comment by AjayKumar84** [comment]
@spmonahan, is this is triaged ?. Any update on this issue ?

**Comment by spmonahan** [comment]
@microsoft/teams-prg Can you please take a look at this issue?

**Comment by annabratseiko** [comment]
@AjayKumar84 this issue was fixed earlier in https://github.com/microsoft/fluentui/pull/17159.

All you need to do is to add property `popup={{ autoSize: true }}` to your `Datepicker` component as in this example: https://codesandbox.io/s/fluent-ui-example-forked-x9jh0b?file=/example.js.

As a result Datepicker perfectly fit in the viewport and scrollbar appears automatically:
![image](https://user-images.githubusercontent.com/20684334/154519944-b8b8e346-f01c-444b-96fb-0fe07f9a8221.png)
