### ISSUE TITLE
Link and Dropdown crash app when undefined is passed as theme property

### ISSUE THREAD

**Issue by max-zheng** [microsoft/fluentui#21281]
### Environment Information
- **Package version(s)**: "@fluentui/react": "8.49.5"
- **Browser and OS versions**: Chrome 97.0.4692.71

### Describe the issue:
When you pass undefined to the theme prop of any component, it crashes the app. If the theme prop allows undefined as a valid value, passing it should not crash the app. This issue is present in at least Link and Dropdown components.

#### Actual behavior:
Passing undefined to the [theme](https://docs.microsoft.com/en-us/javascript/api/react-internal/ilinkprops?view=office-ui-fabric-react-latest#theme) prop of a Link caused our app to crash with the following error in the console:
![image](https://user-images.githubusercontent.com/26679351/149408115-090e3308-e99d-43d1-b95a-b0a2dfe75c34.png)

#### Expected behavior:
Passing undefined to the theme prop of any component should have no effect. The component should still adopt the app wide theme. One scenario where I would want to pass undefined to the theme prop is the following:

```
interface IAppTheme {
  base: ITheme;
  link?: ITheme;
}
```

the link prop is sometimes set depending on host context then it is passed to the <Link> component

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Microsoft Gateway Admin Portal: https://admin.powerplatform.microsoft.com/ext/DataGateways

**Comment by max-zheng** [comment]
Any updates?

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. To set expectations, the developers will review this issue once capacity allows as we’re currently focused on larger coherence work items. Also, I see there is no repro added to the issue filled, meaning when the time comes our dev team will need access to the code in order to debug the problem. 

@tomi-msft - Would you be able to confirm if this is a regression, or if this behavior is an issue?
