### ISSUE TITLE
CommandBar button supports tooltip

### ISSUE THREAD

**Issue by c-s-huang** [microsoft/fluentui#21396]
#### Describe the feature that you would like added

Need the feature to display tooltip for CommandBar button for iconOnly = false mode

#### What component or utility would this be added to

CommandBar button

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you come up with a solution and would like to contribute - please, do so and our team will review the PR.
