### ISSUE TITLE
we need a search button to click to search

### ISSUE THREAD

**Issue by LinglingZhangMicrosoft** [microsoft/fluentui#21485]
#### Describe the feature that you would like added

currently only enter key could trigger searching, but some users don't know this, they were trying to find the search button
show a search button, user can click it to trigger searching

#### What component or utility would this be added to

SearchBox

#### Have you discussed this feature with our team, and if so, who

no

**Comment by DevYak** [comment]
Seconded.

The desired behaviour already exists for the search bar within a SharePoint site (located on the tenant bar), for instance. When you start typing your search term, a button appears on the right. 

When an additional action is required by the user to trigger search, IMO it's better UX to have a button trigger. Not everyone knows to hit Enter, and some search inputs automatically display search results without hitting Enter. Having a button reinforces for the user an additional step is required (as with search within SharePoint).

**Comment by paulgildea** [comment]
@LinglingZhangMicrosoft, @DevYak  Thanks for the feedback. 

This is mostly by design as the `SearchBox` component is pretty minimal in functionality allowing authors to extend it to meet their needs.

I can imagine listening to the `onChange` handler and toggling the visibility of a `Button` that's adjacent to the `SearchBox` could be a reasonable work around and give authors the flexibility to control the look and feel that UI element fully.

**Comment by LinglingZhangMicrosoft** [comment]
thanks for your advice, i will try it. but i don't think this kind of design can meet microsoft's accessibility bar. it doesn't have any hint to tell user to click enter. i also didn't find any other places using this kind of design, why we accept this kind of design? we should change it even it is difficult and needs more time. but we should go towards a right direction.
