### ISSUE TITLE
DetailsList row width auto increases

### ISSUE THREAD

**Issue by teriyaki-89** [microsoft/fluentui#21611]
### Environment Information

- **Package version(s)**: 
- "@fluentui/react": "^8.45.0",
    "@fluentui/react-hooks": "^8.3.7",
    "@fluentui/react-icons": "^1.1.145"
- **Browser and OS versions**: Browser Google Chrome Version 97.0.4692.99 (Official Build) (64-bit) and OS windows 11

### Please provide a reproduction of the bug in a codepen:

 I have a DetailsList with rows and columns and certain rows render another inner Detailist, which is shown when an icon gets clicked on a row on the main DetailsList.
Everything works fine but when the second DetailsList is open I get the row of that inner DetailList constantly increasing it's **width**, that ruins the whole UI, below is part of HTML that is being increased

![image](https://user-images.githubusercontent.com/3207983/152544902-7bc744b1-1a50-4711-a966-7e92528b883c.png)

Unfortunately code is complex to put it to codepen ((

Requested priority: (Blocking)

Products/sites affected: Internal

**Just asking if there is anything to stop autoincreasing its width?**

**Comment by gouttierre** [comment]
Thank you for filing this item with us. I’ll mark this as a high priority request and add it to our queue. The team will investigate this issue but to set expectations the developers will only review this issue once personal capacity allows.
@GeoffCoxMSFT - is there a way / or work around you know of to stop auto increasing the inner DetailList width? Also, could you confirm this issues priority (HP/LP) as well based on your findings? Thanks

**Comment by teriyaki-89** [comment]
I am still facing the same problem

**Comment by murattishkul** [comment]
Hi, I am taking over @teriyaki-89 's work with this component. are there any updates on this? @TristanWatanabe @gouttierre

**Comment by murattishkul** [comment]
seems like [#14284
 14284](https://github.com/microsoft/fluentui/issues/14284) is kinda similar

**Comment by yangjocy** [comment]
Came across exactly the same issue. The second list which is displayed on a button click increases its width automatically.

**Comment by tudorpopams** [comment]
_Just asking if there is anything to stop autoincreasing its width?_

@spmonahan can you help out with this question?

**Comment by etheodoridou** [comment]
Hi there, I am also experiencing this issue in Microsoft portal code, when using DetailsList with flexbox. It specifically appeared after I started messing with the onRenderRow function. 

@murattishkul @TristanWatanabe @gouttierre, any updates on this?

**Comment by spmonahan** [comment]
@murattishkul Without a simplified repro case it is challenging to provide a solution here as I cannot see how the two `DetailsList`s are configured.

That said, I can speculate that the justified column resizing logic may be the root of the issue here. The first thing that comes to mind is to use a [fixed columns layout mode](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist#DetailsListLayoutMode) so that `DetailsList` will not attempt to resize columns.

You can set this with:

```tsx
<DetailsList
  layoutMode={DetailsListLayoutMode.fixedColumns}
  // ... your other props here
/>
```

I know your actual implementation is a bit too complex for a Codepen example but could you make a simplified version that repros the example so I can take a more in-depth look?

**Comment by powergeoff** [comment]
This is happening when layoutMode=DetailsListLayoutMode.justified and I am setting a right or left border inside of my function that is wired to onRenderRow. If I don't set a right or left border, the render function is called once per row. Otherwise, it calls it infinitely and the entire table expands infinitely.

**Comment by WhiteAdy** [comment]
We're here exactly 1 year later and this issue has not been fixed. In my case this appears when I have a fixed max-height set on the list, with overflow-y: auto.

Whenever the number of items in the list exceeds the max-height of it, the scrollbar appears, and the infinite table expansion starts.

**Comment by spmonahan** [comment]
@WhiteAdy Can you provide a code example that reproduces the issue? It's very difficult for us to debug without an example of the issue.
