### ISSUE TITLE
Using back button not working correctly

### ISSUE THREAD

**Issue by TankDoor** [microsoft/fluentui#21747]
### Environment Information

Fluent UI latest
Windows Chrome and Edge latest

### Please provide a reproduction of the bug in a codepen:

N/A

#### Actual behavior:

When entering text in a Combo box using the back delete button to amend an entry does not work as expected and also occasionally causes a freeze that requires the ComboBox to be closed and reopened to fix.
Also, When a match with too many characters has been found hitting the back delete button does not remove the end characters and find a smaller string it just causes a hang

#### Expected behavior:

Hitting the back delete button should remove text from the filter so different text can be added or shorter matches can be found

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) N/A

**Comment by micahgodbolt** [comment]
Can you define the steps needed to reproduce this error? I went to the [ComboBox](https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox) page and typed, and used back space/delete key without issue.

Which demo should I use? What steps should I do to repro the issue.

**Comment by TankDoor** [comment]
I can see the behaviour on the first combo in the demo on the page https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox
When I start typing, text appears as expected. However, when I use the backspace button text is not removed.
As I type Option only the first two letters are shown as recognised by removing the blue background.

**Comment by micahgodbolt** [comment]
@TankDoor this is expected behavior. For non freeform combo boxes (which the 1st demo is), typing doesn't allow you to freeform type anything into the input. But if you type letters matching one of the items, it will switch to that item. In this case you aren't typing text into an input, so you can't delete it.

You'll see the same behavior on an HTML select https://developer.mozilla.org/en-US/docs/web/html/element/select

If you type.....then pause, and type again, you'll be able to select a new item.
