### ISSUE TITLE
Please introduce onRenderFoo for DropDown component when rendering button beside of drop down element

### ISSUE THREAD

**Issue by xinguo98052** [microsoft/fluentui#21816]
#### Describe the feature that you would like added

At DropDown "Set focus" example, https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown
If the DropDown component need to show error message, the "Set focus" button will be out of align. See Bug 21801:
https://github.com/microsoft/fluentui/issues/21801

I suggest to introduce onRenderFoo for DropDown component, so customers can do their own implementation for the button, and the button has right align.
 
#### What component or utility would this be added to

DropDown
#### Have you discussed this feature with our team, and if so, who

Had email discussion with Micah Godbolt, and Fluent UI React Engineering team.

**Comment by gouttierre** [comment]
I’ve added this to our backlog for review but it’s low on our priority list as we’re likely not going to get to it immediately due to the fact we’re currently focused on larger coherence work items and enhancements to our performance. In the meantime, if you want to submit a PR for this feature request, please do so and our dev team will review it.
