### ISSUE TITLE
TalkBack focus moves out of the dialog box while the dialog remains expanded.

### ISSUE THREAD

**Issue by sbatikeri** [microsoft/fluentui#21859]
### Environment Information

- **Package version(s)**: 8.14.13
- **Browser and OS versions**: Android - TalkBack

### Describe the issue:

Focus moves out of dialog box while the dialog remains expanded. Focus moves to parent control/button which is not the correct behavior.

### Please provide a reproduction of the issue in a codepen:
We can repo this on Fluent UI demo site. 
https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog
1. Open chrome browser in Android device
2. Redirect to https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog
3. Scroll to "Dialog with large header and ChoiceGroup"
4. Turn on TalkBack (Press up+down volume buttons)
5. Swipe right to navigate next item
6. Double tap on "Open Dialog"
7. Navigate all elements in side dialog.  (Make sure adress bar is visible. Scroll up/down little bit to enable address bar)
8.  Observe that Focus will be moved out of dialog if address bar enabled if not focus tracped inside dialog. 

#### Actual behavior:
TalkBack focus moves out of the dialog box while the dialog remains open

#### Expected behavior:
TalkBack focus should not move out of the dialog box until and unless users close the dialog box through 'Cancel' button.

### Documentation describing expected behavior
[

https://user-images.githubusercontent.com/62160090/155580764-3206989d-75c3-481d-8f9f-d079b648baac.mp4

](url)

**Comment by smhigley** [comment]
It looks like this bug was auto-closed, but on looking into it, this is also not a valid bug -- we would never want to prevent a screen reader user from accessing the browser chrome (i.e. the browser's own UI, including the address bar).

It would be a bug if Talkback were entering into the background page behind the modal, but entering the browser UI is desired behavior.

**Comment by sbatikeri** [comment]
Thanks Sarah Higley, for updating the info. Can we say this bug is designed?

**Comment by smhigley** [comment]
Yup, or even more than that -- there's no mechanism for a webpage to block screen reader access to browser controls. Doing so would be a major accessibility problem itself 😅

**Comment by sbatikeri** [comment]
I have a small question. We are trapping focus in the Windows Edge browser while the dialog is open and the narrator is running. Is it not the same as this bug? The accessibility team may raise this question.
Fluent UI Dialog ref video: 
https://user-images.githubusercontent.com/62160090/185716194-b33b992b-225f-421e-bef4-e7c70e1def31.mp4

**Comment by smhigley** [comment]
Good question! Trapping tabs is fairly different than trapping a touch-based screen reader cursor – there are multiple options to access the browser chrome with a full keyboard. Ctrl + L or Ctrl + E are common ways to access the address bar from a web page, and will work from within a modal that traps tabs. Tab and focus control is also very different from manipulating the screen reader cursor – even if tabs are trapped, screen reader users can still explore the page, the browser, and the OS by directly moving their cursor without necessarily moving focus.

Touch screen readers are very different, and their users aren’t generally tabbing through UI (leaving out bluetooth keyboards here for simplicity). Navigating by swiping needs to allow access to browser UI because there are no other alternatives available.

**Comment by sbatikeri** [comment]
I was flattered by the answer. That was my thought. Thanks for the quick response. I will close this bug as designed.

**Comment by fabianderson** [comment]
Thank you so much @smhigley for your fast response! :) really appreciate you taking the time!! Will let my team know about this. 👍
