### ISSUE TITLE
Styles are no longer exported due to explicit exports

### ISSUE THREAD

**Issue by MichielDeMey** [microsoft/fluentui#22126]
Due to switching to explicit exports (see https://github.com/microsoft/fluentui/pull/21508) it is no longer possible to import component styles.

We've developed custom components that use FluentUI's style by importing those specific styles and applying them to our own components.

The `getStyles` function IS exported (See https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Slider/Slider.styles.ts#L28), but the new explicit exports prevent Webpack 5 from accessing the styles.

Unfortunately, the styles do not seem to be exported in the `index.js` either.

Is this intended to stay this way? If so, what would a migration look like?
Or is it possible that this is an oversight in the exports definitions?

### Environment Information

- **Package version(s)**: @fluentui/react@8.61.2
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:

```ts
import { getStyles } from '@fluentui/react/lib/components/Slider/Slider.styles';
```

#### Actual behavior:

The following error is reported by Webpack (v5.65.0):

```
Creating an optimized production build...
Failed to compile.

Module not found: Error: Package path ./lib/components/Slider/Slider.styles is not exported from package /Users/xxx/Documents/yyy/repos/zzz/node_modules/@fluentui/react (see exports field in /Users/xxx/Documents/yyy/repos/zzz/node_modules/@fluentui/react/package.json)
```

#### Expected behavior:

The import should succeed.

### Priorities and help requested:

Are you willing to submit a PR to fix? Not yet

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by bittola** [comment]
same for *.styles.ts files

**Comment by MichielDeMey** [comment]
As a workaround, we temporarily import the styles through a relative URL which seems to circumvent the exports definitions.

e.g.
```ts
import { getStyles } from '../../../../node_modules/@fluentui/react/lib/components/Slider/Slider.styles';
```

**Comment by MichielDeMey** [comment]
@dzearing Any opinions on exporting styles?

**Comment by dzearing** [comment]
Well that's messy. Sorry about that. Trying to understand the best path forward here.

It's not ideal to deep import like this - it just takes a rename of a folder to break.

Really the styles function should be exported from the Slider barrel file - then it becomes part of the explicit contract. However that won't work because there are 40 other getStyles functions. We could export them as purposeful names, (e.g. `getSliderStyles`) but that would also mean a code change on your side.) What do you think of that idea? (It's a little churn for you, but it's a guaranteed contract rather than an implied one.)

@bittola Which sass imports are you referencing?

**Comment by dzearing** [comment]
cc @GeoffCox, @khmakoto, @spmonahan

**Comment by dzearing** [comment]
We internally discussed these options and will add the styles exports to unbreak you. @khmakoto will have a PR shortly.

**Comment by mrmeku** [comment]
I think you missed exporting `SearchBox.styles`
