### ISSUE TITLE
Support button on the end for TextField

### ISSUE THREAD

**Issue by zepei-sun** [microsoft/fluentui#22158]
#### Describe the feature that you would like added

Currently the input field only support image and password hide/show button on the end. We will like to have some extra button support, like delete, lock, etc... So the input could be a button? Or maybe just onClick or whatever.

#### What component or utility would this be added to

TextField

#### Have you discussed this feature with our team, and if so, who

Not yet.

#### Additional context/screenshots

We are expecting something like this:
![image](https://user-images.githubusercontent.com/101152963/159069966-36c66e04-7dd0-4af2-a427-97144cf98459.png)

**Comment by paulgildea** [comment]
Thanks for the feedback @zepei-sun. 

While not directly supported via a prop to add an extra button, you can use the `onRenderSuffix` prop to return custom JSX and some style overrides to achieve what you are looking for as a workaround.

We've taken this feedback and in the next version of the library applied it to the `Input` component that allows you to compose in whatever JSX you want in the `contentAfter` slot to achieve this type of scenario. 

I'm marking this one as by design for now - knowing that we've addressed it in the next version of the library and there's a possible workaround.
