### ISSUE TITLE
storybook does not allow switching to canvas when toolbar enabled on published docs site

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#22441]
### Environment Information

- **Package version(s)**: aka.ms/fluentui-storybook (4/8/2022)
https://6002298f95a00c00213f4d55-qpafvorpoj.chromatic.com/?path=/story/components-button--default

### Repro

Go to published vNext storybook site
Click the ... button in the nav and enable the toolbar
Click the canvas button

#### Actual behavior:

View remains on docs

#### Expected behavior:

View should show canvas

### Screenshots

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/28762486/162550491-ed1b9c88-4516-4d5f-b02e-2adaef30e725.png">

**Comment by micahgodbolt** [comment]
This appears to be fixed in master. @levithomason probably just needs to update his branch or the aka link

https://61b7c406fa7cd4003a8a07ec-kxbhyuikpy.chromatic.com/?path=/docs/components-button--default

**Comment by micahgodbolt** [comment]
Is there a desire to have the canvas on the docs site? I believe it was hidden intentionally to have more of a website appearance, rather than a storybook look. I honestly didn't know you could enable the toolbar, which is why we moved theming into it's own dropdown.

**Comment by micahgodbolt** [comment]
Looked at this again. It appears to load properly when going directly to the URL, but the switching does not work.
I'm curious though if for the public site, we should just turn off that menu button, and even disable the keyboard shortcut. Opening up the canvas is pretty broken due to not being able to access any of the stories (left nav sub items are hidden, and right rail is only in docs template).

**Comment by GeoffCoxMSFT** [comment]
Context ... menu is removed from published doc site so no longer an issue. Fixed!
