### ISSUE TITLE
[Bug]: Dropdown: onRenderOption affecting rendering of Header options

### ISSUE THREAD

**Issue by nipope** [microsoft/fluentui#22454]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 12.89 GB / 31.59 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codepen.io/nipope1/pen/JjMBWVb

## Actual Behavior
Providing a function to Dropdown onRenderOption applies that render logic to both normal options and header options.

## Expected Behavior
onRenderOption should only affect the rendering of normal options, the header option should remain unchanged.

### Requested priority

Normal

### Products/sites affected

Azure Lab Services

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The option object passed in contains information about the option and what "type" it is (header is type 2)

![image](https://user-images.githubusercontent.com/1434956/163031104-fc6154ef-2cb5-491e-ac0d-990f0e4f2079.png)

While it might be nice to not have to worry about filtering those out, we won't change it in the current release due to it being a major breaking change.
