### ISSUE TITLE
[Release]: Issue with versions bump

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluentui#22559]
### Library

React Components / v9 (@fluentui/react-components)

### Bug Description

[The latest release](https://github.com/microsoft/fluentui/commit/579c28e26a93cad92aa5998d4bf1c513c8b5f884) bumped `@fluentui/react-components` to `rc.7`:

https://github.com/microsoft/fluentui/blob/d1ac3a2a447caff9c48724a964cf736d4b2678ce/packages/react-components/package.json#L2-L3

But versions in `@fluentui/ts-minbar-test-react-components` & `@fluentui/upgrade-examples-v8-v9` were not bumped:

https://github.com/microsoft/fluentui/blob/d1ac3a2a447caff9c48724a964cf736d4b2678ce/apps/ts-minbar-test-react-components/package.json#L8

https://github.com/microsoft/fluentui/blob/d1ac3a2a447caff9c48724a964cf736d4b2678ce/apps/upgrade-examples-v8-v9/package.json#L23

## Actual Behavior

Versions in `@fluentui/ts-minbar-test-react-components` & `@fluentui/upgrade-examples-v8-v9` are not bumped.

## Expected Behavior

Versions are not bumped.

![image](https://user-images.githubusercontent.com/14183168/164182898-2893aaf7-2bc7-4967-8672-20940f3530d4.png)

### Requested priority

High

**Comment by Hotell** [comment]
1. `@fluentui/ts-minbar-test-react-components` is fixed by this PR https://github.com/microsoft/fluentui/pull/22561

2. `@fluentui/upgrade-examples-v8-v9`

Not 100% sure if there can be anything done as tool that we use for releasing (beachball) is not allowing this and adding a completely new feature would require non trivial effort form our side.

**Unrelated to this issue but important to note:** 

this app also introduces **major Pipeline time penalty** as any change in `v8` or `v9` dependancy tree will trigger a build for both v8 and v9, which is what we have been trying to avoid for some time. This also relates to how our orchestration tool lage works. 

In ideal scenario, it should not happen, as described on the image generated via `nx affected:graph`

![image](https://user-images.githubusercontent.com/1223799/164229953-13410ee0-b6f6-402c-a80a-21465777e9cd.png)

**How to mitigate this?**

Because this app is basically only a storybook shell that resolves dependencies via TS path aliases:
- we can remove `react-components` and `react` from dependencies and leverage aliases only for storybook builds
- remove `build` task completely to ignore `lage` orchestration


This would resolve issues with beachball and CI penalty times. To make this happen additional build scripting will be needed as currently it uses v8 just logic which doesn't work as expected for v9.
