### ISSUE TITLE
[Bug]: Checkboxes with the same id only acts on the first instance

### ISSUE THREAD

**Issue by jspurlin** [microsoft/fluentui#22609]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
latest v8
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/jspurlin/pen/jOYeOVW

### Bug Description

We have scenarios where the same checkbox can be rendered twice in the DOM (responsive rendering and preload overflow menu scenarios). In this case, the non-visible checkbox is first in the DOM. When the second checkbox is executed, the events fire against the first checkbox in the DOM.

For our specific scenario, this was related to a checkbox that was in a menu and when executing the checkbox the dismissOnFocusLost callback runs and the event is coming from the first checkbox instance (which is not in the menu) and hence causes the menu to dismiss unexpectedly.

## Repro steps
1. navigate to this [codepen](https://codepen.io/jspurlin/pen/jOYeOVW) (it contains 4 checkboxes, the first two with the same id)
2.  Click on the second checkbox

## Actual Behavior
The first instance of the checkbox is updated and not the second (and note that the first checkbox fires the same events that the second checkbox does)

## Expected Behavior
Only the second checkbox to be checked (and events to only first for the second checkbox)

We were able to get around this by ensuring that our checkboxes have unique ids (even if it's the same control where one is rendering in a hidden context), but this shouldn't be required

### Requested priority

Normal

### Products/sites affected

Office Online

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
Thanks for filing this issue with us. I see your stated issue being reproduced. To set expectations the developers will review this issue once capacity allows. In the meantime, if you want to contribute towards this request, please share your PR and our dev team will review it.

@smhigley  - Would you be able to confirm if this is a regression, or if this behavior is an issue?

**Comment by khmakoto** [comment]
Hi @jspurlin, elements within a page should have unique ids, if they do not have unique ids unexpected behavior will occur. In this case, this is happening because our `Checkbox` input is hidden and the label spans the whole area. You can see in [this modification of your codepen](https://codepen.io/khmakoto/pen/gOvZBdQ) how clicking on the label for the second native `<input type="checkbox" >` triggers the first one because that's how the `<label for="" >` works.

While this _could_ be fixable in v8, it would require restructuring of the DOM, which might be breaking for some people to fix what essentially should be an unsupported scenario either way, so I don't see us fixing this anytime soon.
