### ISSUE TITLE
Button: Left-align for action/command (maybe others?)

### ISSUE THREAD

**Issue by mbest** [microsoft/fluentui#22614]
### Environment Information

- **Package version(s)**: 8.21.1
- **Browser and OS versions**: Chrome/Windows

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/mbest098/pen/bGRzJqY

#### Actual behavior:

Text content is centered

![image](https://user-images.githubusercontent.com/1230364/135341443-6a9484c2-2862-4012-a100-a258e32998ba.png)

#### Expected behavior:

Text content is left aligned

![image](https://user-images.githubusercontent.com/1230364/135357665-057fb79a-3bc3-419f-899b-d511a570d9b6.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

Reopening #20034

**Comment by micahgodbolt** [comment]
You can add `styles={{textContainer: {textAlign: 'left'}}}` and have the text align to the left. We typically don't add props for things that can easily be done via styling.

**Comment by mbest** [comment]
@micahgodbolt So you think the default centering style is correct?

**Comment by micahgodbolt** [comment]
Buttons are centered text by default, that certainly isn't going to change. We could left align text when an icon is present, but that could break end users just as easily as fix them. Considering the risk of making this change, vs the ease of correcting for it (if you don't want it), I don't feel it's a necessary change in v8.

**Comment by mbest** [comment]
None of the [document examples](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) show a button with anything but auto width or in a constrained space, where the text might wrap and alignment would make a difference. I also checked the [figma](https://www.figma.com/file/F5BN2yodUyHlOfpL4KJCFK/Fluent-Web?node-id=1%3A923) with the same result.

There is one button type where alignment is important and it's using left alignment:

![image](https://user-images.githubusercontent.com/1230364/165369331-786a0e8b-4b63-4d5e-a610-eec2e0898dec.png)

**Comment by khmakoto** [comment]
Hi @mbest, while I understand the concern and agree to a point that it might make sense to have `ActionButton`/`CommandButton` be left-aligned since they are styled closer to links than to buttons there are 2 things that prevent us from making the change right now.

The first thing preventing us from making the change is that, like you said, there really is no design guidance on what to do in this type of scenarios. We first need to check with design if this is the correct change to do and how to approach it.

The second, and in my opinion most pressing, thing that is keeping us from making such a change is that this could effectively be a breaking change for a bunch of consumers of the library that have built on top of it expecting the styles that are there right now. As such, we'd have to make such a change in a major version revision of the library.

Given all of the above, I don't think we'd get to this anytime soon, especially since the workaround @micahgodbolt provided works fine right now. If you don't like this because you have to replicate it for every `ActionButton`/`CommandButton`, remember that you can pass specific styles to be applied wholesale via our theme:

```
const newTheme = createTheme({
  components: {
    ActionButton: {
      styles: {
        textContainer: {
          textAlign: 'left'
        }
      }
    }
  }
});
```
