### ISSUE TITLE
[Bug]: fluentui demo page for Image has blank images in the examples

### ISSUE THREAD

**Issue by NinthDesertDude** [microsoft/fluentui#22837]
### Library

React Northstar / v8 (@fluentui/react)
(library not important here)

### System Info

```shell
Windows 10 64-bit Home running latest stable Edge
```

### Are you reporting Accessibility issue?

No

### Reproduction

see https://developer.microsoft.com/en-us/fluentui#/controls/web/image#feedback

## Actual Behavior
The placeholders from via.placeholder.com used in the examples on the page aren't loading. I can go to the urls in another tab and see the image, though.

## Expected Behavior
The placeholders would ideally load so the examples make more sense.

### Requested priority

Low

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui#/controls/web/image#feedback

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by JustSlone** [comment]
@NinthDesertDude Can you elaborate on the issue here? The images on the page linked are just placeholders and appear to be loading correctly for me. (e.g. https://fabricweb.azureedge.net/fabric-website/placeholders/350x150.png) 

![image](https://user-images.githubusercontent.com/40304143/197419113-af469a48-6b62-496d-b1aa-b78920ce4fac.png)

**Comment by NinthDesertDude** [comment]
This no longer repros for me either. Thanks for following up. Closing.
