### ISSUE TITLE
Fluent Ui hover card is not getting expanded properly if limited space is there

### ISSUE THREAD

**Issue by AnjaliAgarwal123** [microsoft/fluentui#22910]
Hover card is not getting adjusted with the available space. If there is limited space at bottom or top, then card is not getting displayed properly. 
Curren Behavior:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/104159144/167541883-2efe390c-c435-45ce-bc77-b2801ac4a230.png">

Expected Behavior:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/104159144/167542052-ab9eda8f-4c45-473c-b414-a4910cca7128.png">
Expected behavior is that the card should pushed to top when hovering at last list item. So how can we achieve this ?

**Comment by GeoffCoxMSFT** [comment]
@AnjaliAgarwal123 It turns out that the HoverCard's design is not accessible.  After talking over with the team at length, it appears that it would take a full rewrite of the component make it work, but it still would not be a good experience for users.  We recommend you not use this component and instead use a panel or modal dialog instead.

**Comment by gouttierre** [comment]
@AnjaliAgarwal123 - Thanks for reaching out to us. I’ve added this to our backlog for later review but it’s low on our priority list - especially since you can currently use a panel or modal dialog instead.
