### ISSUE TITLE
[Bug]: Beachball tries to bump a package from a caret peerDependency

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#23147]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
This happened in the Azure Pipeline release build.
```

### Are you reporting Accessibility issue?

no

### Reproduction

N/A

## Actual Behavior

When attempting to release a package that has a caret dependency the release pipeline will "bump" to the same, already released version of a package, causing the release to fail.

## Expected Behavior

A caret dependency change for a package should not cause a release to fail. Either the package should be bumped to a new release version or it should be skipped.

## Notes

This happened in the `react-conformance-griffel` package where the peerDep was set to `^0.13.0` while the devDep was set to `*`.

[Link to package.json for the commit](https://github.com/microsoft/fluentui/blob/a569864246be0184a5a51421b3da4450deafb854/packages/react-components/react-conformance-griffel/package.json)

### Logs

```shell
The issue first appeared in a release build but is reproducible locally.
Build: https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=250403&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=fb65810a-a7a9-58a0-61f9-7163cb0bcc0b&l=187
```

### Requested priority

High

### Products/sites affected

@fluentui/react-components, possible @fluentui/react and northstar as well

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Related issue: https://github.com/marwan38/fluentui/commit/ada38f440b819f53d19a3bf96bb8ed3e99be3b81

**Comment by ling1726** [comment]
This happens because @fluentui/react-conformance-griffel depends on @fluentui/react-conformance. They are released on different cycles.

react-conformance is released during the v8 cycle (daily) which does not bump react-conformance-griffel.

1. react-conformance is 1.0.0, react-conformance-griffel depends on 1.0.0
2. release react-conformance to 1.1.0
3. release react-conformance-griffel
4. ERROR: beachball generates a change for react-conformance-griffel because react-conformance version changed
5. release failed

**Comment by Hotell** [comment]
we haven't run into this for quite some time. closing
