### ISSUE TITLE
[Bug]: Slider doesn't remove hover effect on smaller screen size

### ISSUE THREAD

**Issue by rachitkumar13** [microsoft/fluentui#23211]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 91.21 GB / 127.86 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.39)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/xachit/pen/yLvNoyY

## Actual Behavior
Scale down the UI shared in below link to a mobile ui in chrome dev tools.
Drag any slider and observe the hover effect (blue color) of the slider doesn't vanish when the mouse moves away from the slider.

## Expected Behavior
The color of the slider should turn back to black when not hovering.

https://user-images.githubusercontent.com/6224197/170189972-a8481e9d-a5cd-40de-8697-1ce0c6d6d431.mp4

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@rachitkumar13 - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@khmakoto - Would you be able to confirm if this is a regression, or if this behavior is an issue? Then flag the priority level on the issue accordingly from your findings. Thanks

**Comment by layershifter** [comment]
I was able to repro it also on a mobile device (iPad iOS 15.6), the problem comes from this style:

![image](https://user-images.githubusercontent.com/14183168/184357199-53326f47-8f58-4be6-b60e-5136821f0ecc.png)

So it's not about `:hover` as an element remains active after a pointer leaves the area.

---

@gouttierre I am not experienced in this area, so it's hard for me to say if it's a bug or not.

**Comment by JustSlone** [comment]
Yep, looking at the code this seems intentional. As I see it, touch makes the slider "active", and `const restActiveSectionColor = palette.neutralPrimary;` means that active sections at rest will have neutral Primary or that blue color.  

https://github.com/microsoft/fluentui/blob/85639d1b51422690a1cb92d3f9ec8526672c2c22/packages/react/src/components/Slider/Slider.styles.ts#L33-L47

@rachitkumar13 is there a reason this behavior is problematic? It seems like this is there to show the last touched slider, but I could be wrong.

**Comment by micahgodbolt** [comment]
Yeah, this is an effect of how touch inputs are handled in the browser. It has nothing to do with screen size or media queries.
