### ISSUE TITLE
[Bug]: Can't click on Checkbox/ChoiceGroup inside scrolled FocusTrapZone

### ISSUE THREAD

**Issue by brettc-microsoft** [microsoft/fluentui#23314]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (32) x64 AMD Ryzen Threadripper PRO 3955WX 16-Cores
    Memory: 86.84 GB / 127.86 GB
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/brettcockerill/pen/gOvoJvj?editors=0010

## Repro Steps
1. Open the [codepen](https://codepen.io/brettcockerill/pen/gOvoJvj?editors=0010)
2. Scroll the Callout to the bottom
3. Try to click on the Checkbox (or ChoiceGroup options)

## Actual Behavior
You can't click on the Checkbox. Instead you are scrolled back to the top of the Callout

## Expected Behavior
You can click on the Checkbox and nothing is scrolled.

## Notes
You can click on the Checkbox or ChoiceGroup options before you scroll the Callout to the bottom.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I've confirmed the issue in Firefox 102.0.1 and Chrome 103.0.5060.114.

After investigating this appears to be a bug when [`FocusTrapZone`](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx#L95) is used inside a Callout (and in `FocusTrapCallout` which is a helper for Callouts and FocusTrapZone). A scrolling FocusTrapZone outside of a Callout seems to function correctly.

I don't have a fix in mind but I'll drop my investigation notes here for future reference.

Here are my debugging repro steps:

1. Copy the [Codepen example](https://codepen.io/brettcockerill/pen/gOvoJvj?editors=0010) into a place where it can be changed locally. I used the [Callout FocusTrap Example](https://github.com/microsoft/fluentui/blob/master/packages/react-examples/src/react/Callout/Callout.FocusTrap.Example.tsx).
2. Load up the example in a browser. I used Edge.
3. In DevTools, place a breakpoint on [onFocusRootCapture](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx#L201).
4. Open the Callout, scroll the content to the bottom checkbox, click the last checkbox in the Callout.
5. Breakpoint from above should be triggered
6. Examine `ev.target`. It's a reference to the first checkbox in the Callout, not the last checkbox that was clicked.

If you update the height of the Callout such that it does not scroll you can observe the same `ev.target` in DevTools _but_ the last checkbox is correctly selected. This leads me to believe that the issue is related to behavior in Callout and not necessarily scrolling.
