### ISSUE TITLE
Clicking on the group selects all members

### ISSUE THREAD

**Issue by jbzdarkid** [microsoft/fluentui#23380]
### Environment Information

- **Package version(s)**: 7.185.6

### Describe the issue:

Clicking on the group's text selects all sub-elements, rather than expanding/collapsing the group.
![selects all](https://user-images.githubusercontent.com/5459085/171747175-37a9778a-ed7c-472f-bfa6-6d336e33a3d7.png)

#### Actual behavior:

All sub-elements are selected (akin to clicking on the checkbox)

#### Expected behavior:

All sub-elements are hidden/shown (akin to clicking on the arrow)

### If applicable, please provide a codepen repro:

I am not familiar enough with Fluent to build a minimal repro. This is affecting a feature that's currently in development -- once it reaches public preview I can put in screenshots with more information. If you contact me through teams, I can demonstrate this at PPE.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Azure Portal

CC @brfabian-msft

**Comment by gouttierre** [comment]
@jbzdarkid - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity permits. Once queued and bandwidth allows the developer will need to work with you in order to access the code.

@bsunderhus - Here is another reported bug by our partner. Could this be investigated together with the other issue reported https://github.com/microsoft/fluentui/issues/23381?

**Comment by spmonahan** [comment]
This issue was fixed in v8 but that change was never cherry-picked to v7. I have a PR open to add the fix to v7.
