### ISSUE TITLE
[Bug]: unable to reset the ChoiceGroup selection using selectedKey in  "8.58.0"

### ISSUE THREAD

**Issue by vinuthakaranth** [microsoft/fluentui#23466]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 7.12 GB / 31.78 GB
  Browsers:
    Chrome: 102.0.5005.63
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codesandbox.io/s/pedantic-platform-kk90kv?file=/src/CohortEditor.tsx:1626-1659

## Actual Behavior
I am hitting this issue where selectedKey of ChoiceGroup set to undefined isn't reflected in the UI on re-render. This issue is caught while migrating to "@fluentui/react": "8.58.0".

## Expected Behavior
ChoiceGroup should have no keys selected on selectedKey set to undefined

In repro link - >

Open console log
Click on equal
click on addFilter
We can see this.state.selectedFilterCategory is set to undefined but ChoiceGroup still has Equal selected.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@vinuthakaranth  - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.
@ling1726 - Would you be able to investigate the issue and confirm if this is a regression, or if this behavior is an issue?

**Comment by vinuthakaranth** [comment]
issue persists with latest version "8.72.3"

**Comment by ling1726** [comment]
Hi @vinuthakaranth, this is fixed by setting the default value of the selected choice to `null`. You can see that in the following sandbox https://codesandbox.io/s/hardcore-khayyam-f0y6nh?file=/src/CohortEditor.tsx

v8 has a hook `useControllableValue`, which never lets you control the component again if the initial state is `undefined`. Therefore in your example you were never actually controlling the value of the `ChoiceGroup`. I have no idea why it was ever implemented like this. As to why this decision was made for v8 (v9 does not behave this way) I have no idea

https://github.com/microsoft/fluentui/blob/7b6300bec0ab6b1412817fe687dd438de3bcd8de/packages/react-hooks/src/useControllableValue.ts#L46

**Comment by vinuthakaranth** [comment]
I don't think this is an appropriate approach. As (property) is IChoiceGroupProps.selectedKey?: string | number | undefined
 and null not always common in typescript.

**Comment by vinuthakaranth** [comment]
Please don't close the issue without confirming if solution is working or not.
