### ISSUE TITLE
[Bug]: Reveal Password is showing regardless of browser reveal password button

### ISSUE THREAD

**Issue by TheMikeL** [microsoft/fluentui#23482]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 3.89 GB / 15.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.39)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

staging2.takelessons.com

## Actual Behavior
Shows the reveal password button on Edge even if there is a built-in reveal password button.

## Expected Behavior
Should not show the reveal password button on the edge.

Reproduction:
Access link on Edge browser
Type into the password field, a in-browser reveal password will appear.

### Requested priority

High

### Products/sites affected

takelessons.com

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chilidoggca** [comment]
We encountered this same issue. I believe this issue is related but was soft closed: https://github.com/microsoft/fluentui/issues/19295

We also found that the bug is reproducible on Fluent UI's documentation example: https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

Ultimately we were able to fix the bug by applying pseudo-element styling in project's root index.css: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#remove-the-password-reveal-control
`::-ms-reveal {
    display: none;
}`

**Comment by gouttierre** [comment]
@TheMikeL - Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? Thank you

**Comment by chilidoggca** [comment]
This bug affects both fluentui v8 and v9 on Edge browser. It is reproducible using codepen from v9 docs: https://codesandbox.io/s/3jzmvj?file=/example.tsx

When you start typing into the password input field, the eye icon appears. However, if you blur, it disappears. When you focus on it again, it remains hidden. It only reappears if you clear the input field and start typing again.

**Comment by spmonahan** [comment]
I see why this issue is raised as a bug but I don't really think it is one. This is the default behavior of an HTML `input` in Edge and in v9 in particular we've tried to stick as closely as possible to web platform defaults. 

> When you start typing into the password input field, the eye icon appears. However, if you blur, it disappears. When you focus on it again, it remains hidden. It only reappears if you clear the input field and start typing again.

This is essentially how the behavior is described in the [Edge web platform documentation for password reveal](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#visibility-of-the-control). As such my feeling is that v9 `Input` and v8 `TextField` are both behaving correctly.

The password reveal button can be hidden with custom styling in both v8 and v9. I've written up examples for each:

- [Hide Edge's password reveal button in Fluent v8](https://codepen.io/seanms/pen/NWYRgOB)
- [Hide Edge's password reveal button in Fluent v9](https://codesandbox.io/s/custom-password-styles-for-fluent-v9-rvi638)

---

I'm closing this as I don't think there's anything to fix here. I think we're open to considering a feature request along the lines of "add a prop to hide browser built-in input controls" ([`input type="search"` has a feature similar to password fields](https://codepen.io/seanms/pen/NWYRvdJ)). If that's something you'd like [please open a feature request](https://github.com/microsoft/fluentui/issues/new?assignees=&labels=Type%3A+Feature%2CNeeds%3A+Triage+%F0%9F%94%8D&template=feature-request.yml&title=%5BFeature%5D%3A+).
