### ISSUE TITLE
[Bug]: Rendering issue with CommandBar with delayed farItems

### ISSUE THREAD

**Issue by brwatt** [microsoft/fluentui#23502]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
browser/system independent
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/brwatt/pen/MWQzrJL

### Bug Description

`CommandBar` currently only uses the primary commands when it computes its cache key for caching the measure for a given configuration. This means that if `farItems` changes without `items` or the window size changing, the CommandBar will give `ResizeGroup` an incorrect cached size which will likely result in a rendering issue.

The linked codepen shows the broken scenario compared to the working scenario. In the broken scenario, the `farItems` prop is changed after a short time.

I believe the cache key should include the far command keys as well to fix the issue.

### Requested priority

Normal

### Products/sites affected

OneDrive Consumer Web

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by jumpmanjay** [comment]
The issue is even a little deeper, I believe. I have an app using react/redux and if the items are modified very quickly from the initial render, they become stale. For example:

`const disabled = useSelector(isDisabled);`
`const items = useMemo(() => {`
`  return [{`
`    key: "key",`
`    name: "name",`
`    disabled,`
`  }];`
`}, [disabled]);`
`return <CommandBar items={items}/>;`

This results in the item being disabled, even though I have verified that what is being passed to CommandBar.items is 1) a new array and 2) items[0].disabled === false. I have had to resort to putting a useEffect with a timeout and a force render to work around this bug.
