### ISSUE TITLE
[Bug]: Incorrect role of column header is defined as button despite having no functionality.

### ISSUE THREAD

**Issue by adarshljj** [microsoft/fluentui#23586]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 752.65 MB / 15.76 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41), ChromiumDev (104.0.1278.2)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction

https://admin-ignite.microsoft.com/Adminportal/Home

## Actual Behavior
Despite having no functionality, column header is defined as 'button'.

## Expected Behavior
Column header should not be defined as 'button' if it does not have any functionality.

![role=button](https://user-images.githubusercontent.com/35987839/174139164-9e9944c8-d754-4942-8fea-a3da30673102.PNG)

### Requested priority

Normal

### Products/sites affected

Microsoft 365 AdminUX

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by gouttierre** [comment]
@adarshljj -  Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows. I was unable to view your repro of the issue due to access rights.  
![image](https://user-images.githubusercontent.com/78806055/179504300-41b80dfc-aeb5-43b1-bd5f-fb965a6ec215.png)

@spmonahan - Would you be able to confirm if this is a regression, or if this behavior is an issue? You might need to confirm that you have access rights to the repro.
