### ISSUE TITLE
[Bug]: StrictMode breaks v9 theming

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#23625]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
react 18.0.0
@fluentui/react-component 9.0.0-rc.15
```

### Reproduction

https://codesandbox.io/s/nice-villani-7vgw53?file=/src/index.tsx

## Actual Behavior
Ugly buttons

![image](https://user-images.githubusercontent.com/1110944/174862041-34c66669-5f39-43d1-aa2a-f4d32e5975c8.png)

## Expected Behavior
Pretty buttons (remove the `StrictMode` to see)

![image](https://user-images.githubusercontent.com/1110944/174862095-64a9f93a-a4c7-4b50-8500-ac99602a8ce1.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
probably ID related. i repro'ed it with a base react 18 repro

**Comment by micahgodbolt** [comment]
Issue comes down to how we inject styles into the DOM at render, but clean up on useEffect return. This approach is necessary because useEffect/useLayoutEffect is too slow to be injecting styles into the DOM without a ton of style recalculation. React 18 provides a useInsertionEffect that is tailor made to support CSS in JS libraries inserting styles into the document. 

The solution will be forking behavior and using the new hook when it is available. I have a prototype branch working now, and currently gathering feedback on the solution.

**Comment by layershifter** [comment]
@micahgodbolt current code should be simply refactored to use `useInsertionEffect` always and fallback to `useLayoutEffect` when it's not present like in Emotion:
https://github.com/emotion-js/emotion/blob/ff3cb16419b44578c7bab275dce7b5845b61db84/packages/react/src/global.js#L16-L18

This allows reduce amount of conditions & branches. Refactor should also remove need of `usePrevious()` as it will be handled in the effect. Having two separate hooks will allow to handle dependencies cleaner IMO: we don't want to recreate style element if `theme` changes for example.

```ts
const useInsertionEffect = React['useInsertion' + 'Effect']
  ? React['useInsertion' + 'Effect']
  : React.useLayoutEffect

// ---

const styleTag = React.useRef<HTMLStyleElement>();

useInsertionEffect(() => {
  styleTag.current = createStyleTag(targetDocument, styleTagId)

  return () => {
      if (styleTag.current) {
        styleTag.current.remove();
      }
  }
}, [styleTagId, targetDocument])

useInsertionEffect(() => {
  const sheet = styleTag.current.sheet;

  if (sheet) {
    sheet.insertRule(cssRule, 0);

    return () => {
      if (sheet.cssRules.length > 0) {
        sheet.deleteRule(0);
      }
    }
  } else if (process.env.NODE_ENV !== 'production') {
    // eslint-disable-next-line no-console
    console.error('FluentProvider: No sheet available on styleTag, styles will not be inserted into DOM.');
  }
}, [cssRule])
```

**Comment by layershifter** [comment]
@micahgodbolt current code can be simply refactored to use `useInsertionEffect` always and fallback to `useLayoutEffect` when it's not present [like in Emotion](https://github.com/emotion-js/emotion/blob/ff3cb16419b44578c7bab275dce7b5845b61db84/packages/react/src/global.js#L16-L18) 🐱 This is safe for older React versions as:

> useInsertionEffect is new in React 18. It works roughly like useLayoutEffect except you don't have access to refs to DOM nodes at this time.
> https://github.com/reactwg/react-18/discussions/110

This allows reduce amount of conditions & branches. Refactor should also remove need of `usePrevious()` as it will be handled in the effect 💪 

~We can keep creating an element during render as it has clear dependencies (`styleTagId` & `targetDocument`) then `useInsertionEffect` will also have clear dependencies ⬇️~

_Edit_: 👆 we can't as it's the actual source of the problem: rendering happens twice (we create `element1` and `element2` due different ids) and then an effect will run with `element2` that will be deleted while `element1` remains in DOM 💥

---

I made some adjustments to the original code:

```ts
const useInsertionEffect = React["useInsertion" + "Effect"]
  ? React["useInsertion" + "Effect"]
  : React.useLayoutEffect;

// ---

useInsertionEffect(() => {
  styleTag.current = createStyleTag(targetDocument, styleTagId);

  if (styleTag.current) {
    insertSheet(styleTag.current, cssRule);

    return () => {
      styleTag.current.remove();
    };
  }
}, [cssRule, targetDocument, styleTagId]);
```

---

**Note**, the usage of Emotion's hack is required otherwise we will get a problem on consumer's side:
![image](https://user-images.githubusercontent.com/14183168/180662017-518f36c4-0151-4d75-9871-fcd45c53720b.png)

P.S. Tested with React 17 & React 18 in `StrictMode` & without - works like a charm 💎
