### ISSUE TITLE
[Feature]: Provide 100% Themeless Components

### ISSUE THREAD

**Issue by tebinraouf** [microsoft/fluentui#23781]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Hi, 

React v9 CSS-in-JS provides a great way to apply theming to components through FluentProvider. While to use a component, it is my understanding that FluentProvider is not needed. 

Issue: currently there is tight coupling between FluentProvider, `makeStyles` and the components. When a component is used, the markup is rendered with `makeStyles`'s generated classes. For instance, 

```js
import {Button} from '@fluentui/react-components'
...
<Button>Sample Button</Button>
```

renders to 

```html
<button type="button" class="fui-Button ___22bxoo0_1dffs6j f122n59 ftuwxu6 f4d9j23 fmrv4ls f1hu3pq6 f11qmguv f19f4twv f1tyq0we f1n52uh2 f1p9o1ba f1sil6mw f1cmbuwj fz5stix fxugw4r f19n0e5 f192inf7 f5tn483 f1vxd6vx f1ojsxk5 fzkkow9 fcdblym fg706s2 fjik90z fj3muxo f1akhkt f1aperda f1lxtadh fk6fouc f1s6fcnf f1knas48 fvcxoqz f1ub3y4t f1xlaoq0 f1m52nbi feu1g3u f8491dx ft1hn21 fuxngvv f141de4g f11v6sdu f9yn8i4 f1uwu36w f1ajwf28 f9olfzr fiu5zv5 f1dfjoow f1j98vj9 f8rnyb3 fhb3ry5 f16e7g02 f11223yd ff1wgvm fiob0tu f1j6scgf f1x4h75k f4xjyn1 f9ddjv3 fztplxc fw5db7e f9g1xly f1uw59to f1d2rq10 f14es27b f1aa9q02 f16jpd5f f1jar5jt fyu767a fkhj508 fl43uef f1i3iumi ftqa4ok flfsvnh f1781m5e f50u1b5 flvaaa9 f19j8a82 fgeg2qa fhcq1yo f9ycirn fpt6wn7 f1ezw2km f18buiid f1hat8c3 f10ee3ek">Sample Button</button>
```

I propose (if possible) to have a cleaner markup. This makes Fluent components purely 'skinless/themeless' and allows developers to use their preferred styling approach that isn't only CSS-in-JS.
```html
<button type="button">Sample Button</button>
```

This could be implemented in multiple ways. One approach is to have a new `isThemeless` interface on the component state that is `false` by default.

For example:
```js
export type ButtonState = ComponentState<ButtonSlots> &
  Required<Pick<ButtonProps, 'appearance' | 'disabledFocusable' | 'disabled' | 'iconPosition' | 'shape' | 'size'>> & {
    ...
    /**
     * A button can be themeless
     *
     * @default false
     */
    isThemeless: boolean;
  };
```

Usage:
```js
import {Button} from '@fluentui/react-components'
...
<Button isThemeless>Sample Button</Button>
```

With this new feature, any styling approach (CSS, SCSS, CSS-in-JS) can be used to style the component without forcing an opinionated approach to theming/styling. 

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by joneff** [comment]
I am not part of the Fluent theme, but I have a couple of questions:
* how would this particular button (with no classes) differ from an ordinary button? Surely you don't need an entire package to return a button
* how would this button, when rendered with `a` instead of `button` be different and distinguishable from the rest of the links on the page?

In short, **how would one guess who to style anything related to any component if there are no class names**?

**Comment by JustSlone** [comment]
@tebinraouf, thank you for suggestion and request. This is something we considered but aren't able to tackle just yet. There are ergonomics and as I recall performance benefits from the more tight coupling we have today. That being said, this does not preclude style-less components in the future. We have considered actually doing this at build time and releasing a second set of components that have all the griffel dependencies and styling stripped out. 

Today, you should be able to accomplish this with a little bit of effort if you recompose our components via the hooks. Removing or replacing the styles hook here will allow you to change the styling dependencies of the component.
https://github.com/microsoft/fluentui/blob/e255da7cf629534ebaaac05af3b5bb9a2f7def71/packages/react-components/react-button/src/components/Button/Button.tsx#L11-L18

Note our composition model is not final and that's why these hooks are marked unstable, meaning the surface may change completely in the future, so I understand if this blocks extensive usage. 

CC: @levithomason, @layershifter, @miroslavstastny, @behowell
