### ISSUE TITLE
[Feature]: IIconProps should extend React.HTMLAttributes<HTMLElement>

### ISSUE THREAD

**Issue by sydsutton** [microsoft/fluentui#24189]
### Library

React / v8 (@fluentui/react)

## Actual Behavior
According to https://developer.microsoft.com/en-us/fluentui#/controls/web/icon `IIconProps` extends `IBaseProps` as well as `React.HTMLAttributes<HTMLElement>`, but in the docs on https://docs.microsoft.com/en-us/javascript/api/office-ui-fabric-react/iiconprops?view=office-ui-fabric-react-latest `IIconProps` only extends `IBaseProps`.

## Expected Behavior
IIconProps should extend both IBaseProps and React.HTMLAttributes<HTMLElement>.

### Additional context

![image](https://user-images.githubusercontent.com/83406605/182442059-d7f90083-4171-4306-af88-6053171799aa.png)
![image](https://user-images.githubusercontent.com/83406605/182442130-4b698122-33b2-4985-9cce-119d12dbc811.png)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gouttierre** [comment]
@sydsutton -  Thanks for filing this issue with us. To set expectations the developers will review this issue once capacity allows.

@tomi-msft - I remember you did work on the icons, would you be able to review the documentation to ensure its completeness? Thank you

cc @layershifter

**Comment by layershifter** [comment]
`IIconProps` extends both `IBaseProps` and `React.HTMLAttributes`:

https://github.com/microsoft/fluentui/blob/958f4e2469b779d6e394fd6885ebd2532c7c229e/packages/react/src/components/Icon/Icon.types.ts#L34-L37

So documentation in https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/icon is correct. This is true for both `@fluentui/react@v7` & `@fluentui/react@v8`.

---

The problem is that `React.HTMLAttributes` is not visible in https://docs.microsoft.com/en-us/javascript/api/office-ui-fabric-react/iiconprops?view=office-ui-fabric-react-latest:

![image](https://user-images.githubusercontent.com/14183168/184604293-0cc14100-db53-41d2-8d96-703cd4eb2bca.png)

**Comment by sydsutton** [comment]
Hey, @layershifter. Thanks for your response. Yes, that is correct.
