### ISSUE TITLE
`weight` attribute does not work with predefined styled text components

### ISSUE THREAD

**Issue by blueset** [microsoft/fluentui#24341]
### Environment Information

- **Package version(s)**: `@fluent/react-components`==9.2.0
- **Browser and OS versions**: _(irrelevant)_

### Describe the issue:

`weight` attribute does not work with predefined styled text components (`<Body1 />`, `<Caption1 />`, `<Caption2 />`, etc.)

#### Actual behavior:

```tsx
import { Text, Body1 } from "@fluentui/react-components";
import * as React from "react";
export const Weight = () => (
  <div
    style={{
      display: "flex",
      gap: 20
    }}
  >
    <Text weight="semibold">Semibold weight 1</Text>
    <Body1 weight="semibold">Semibold weight 2</Body1>
  </div>
);
```

"Semibold weight 2" is rendered in regular weight.

#### Expected behavior:

Both texts should be in semibold weight.

### If applicable, please provide a codepen repro:

https://codesandbox.io/s/mystifying-gwen-yyr4h1?file=/example.tsx:0-307

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: MS internal-only product

**Comment by JustSlone** [comment]
Thanks @blueset for filling this. 

This is intentional, though maybe non-obvious. The documentation should explain this but it does not. I filed #25548 to track  the documentation issue. 

The `Text` component offers full customization of the text. While the wrappers `Body1`, `Title1`, etc. have fixed un-customizable styles. The intention with the wrappers is to allow applications to help ensure that when `Body1` or `Title1` are used that there is consistency in the styling and that the styling is always the same. 

That being said, we'd love feedback if this isn't a good experience for customers, so please given this context let us know what you would expect the behavior to be here. Others please also add your thoughts to this issue! we may change this behavior if enough folks hit this, even after we updated the documentation to explain this.

**Comment by blueset** [comment]
We are having some scenarios that we want to have some ad-hoc styles variants based on existing predefined styles, e.g., using monospaced fonts in some code-like text labels, or using italics to represent missing values. Currently, we are having an inner `<span />` to wrap the text content in order to achieve these styles.

If it is an intended behavior, would it be better to remove these properties in TypeScript from the wrapper components?

**Comment by marcosmoura** [comment]
@blueset Currently, the Text presets like `Body1` and `Caption1` will preserve the styles to keep style consistency. We've updated the documentation to match this. We are exploring good ways to allow such customization.  

In the meantime, a consistent way to achieve what you need without wrapping a `span` tag, would be using the `Text` component together with typography tokens:

``` typescript
import * as React from 'react';
import { makeStyles, Text, typographyStyles } from '@fluentui/react-components';

const useCustomCaptionStyles = makeStyles({
  customCaption: {
    ...typographyStyles.caption1, // This will generate the same styles as a `Caption1`
    fontStyle: 'italic', // Full customization allowed in here
	fontWeight: 600
  },
})

export const CustomCaption = ({ children }: React.PropsWithChildren<{}>) => {
  const styles = useCustomCaptionStyles();

  return <Text italic className={styles.customCaption}>{children}</Text>;
};
```
