### ISSUE TITLE
[Bug]: react-file-type-icons SVG icons size 64 are 32x32px

### ISSUE THREAD

**Issue by ilbrando** [microsoft/fluentui#24445]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A
```

### Reproduction

N/A

### Bug Description

It appears that the SVG served by the CDN is wrong for icons size 64.

## Actual Behavior
Example: `https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220803.001/assets/item-types/64/docx.svg`
Responds with: `<svg width="32" height="32" fill="none" xmlns="http:/...`

As far as I can see, this is the case for all (several) of the icons.

In comparison the size 96 responds with: `<svg width="96" height="96" fill="none" xmlns="http:/...`

## Expected Behavior
`<svg width="64" height="64" fill="none" xmlns="http:/...`

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
SVGs scale much better than JPG/gifs. I believe this was intentional to serve the same SVG for both 32px and 64px use. This is the case for other 64x sizes as well. 

https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220803.001/assets/item-types/64/xlsx.svg
https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20220803.001/assets/item-types/64/pptx.svg
