### ISSUE TITLE
[Bug]: Modeless dialog is not opening up in Excel Online

### ISSUE THREAD

**Issue by liyatilahun** [microsoft/fluentui#24529]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Excel Online - Mode: Edit view
Fastfood and MSIT

Browser: Edge, Chrome
```

## Actual Behavior
Modeless dialogs in Excel online is not opening up. 

After further investigation, we have found out that it's because of a change made on the Modal infra here: https://github.com/microsoft/fluentui/commit/ad8661e299d2528a2d191469f52b2000a293dd72

![image](https://user-images.githubusercontent.com/92185632/186718659-7ef75492-7867-4376-a023-0b4f5ff7a8ef.png)

![image](https://user-images.githubusercontent.com/92185632/186718756-e878266f-f45a-429b-9d35-225905eeecdd.png)

The position property change from "absolute" to "fixed" is causing the problem to modeless dialogs. 

This issue is currently showing in MSIT for Excel. It's not affecting PPT yet because the change hasn't made it there yet. 

## Expected Behavior
Modeless dialogs should open correctly.

### Requested priority

Blocking

### Products/sites affected

Excel Online, and if not fixed soon will be affecting PPT online too

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
The changes to Modeless dialog were intention because a recent change to improve layer performance had broken the layout of modeless dialogs. The fixes were done in this PR

https://github.com/microsoft/fluentui/pull/24074

We are unable to revert these changes without breaking other partners, so you'd need to look at the excel modals to see what customizations you are doing that might not work with the new layout approach. 

If you can identify a bug in the current modeless modal, please create a repro and post it here.

**Comment by micahgodbolt** [comment]
This bug is being fixed elsewhere.
