### ISSUE TITLE
[Bug]: [DatePicker] Go to Today link is not enable when user pick any other date for same month.

### ISSUE THREAD

**Issue by vinfol** [microsoft/fluentui#24581]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 17.00 GB / 31.72 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
```

### Reproduction

https://codepen.io/vinfol/pen/xxWvXJw

### Bug Description

**`DatePicker`** Go to Today link is not enabled when the user picks any other date for the same month.

## Expected Behavior

**`DatePicker`** Go to Today link should be enabled when the user picks any other date for the same month.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
@vinfol your codepen example is of a commandbar, not datepicker

**Comment by vinfol** [comment]
@micahgodbolt  Sorry about that. Updated

**Comment by micahgodbolt** [comment]
I believe this is expected behavior, as this is also the behavior on the current outlook web app. 

![image](https://user-images.githubusercontent.com/1434956/189152574-4b377709-a33c-41a2-8b50-925de70f19d7.png)

As the date picker component is primarily driven by the outlook team and their requirements, we don't intent to change this behavior until their team wants the change made and defines the new behavior.
