### ISSUE TITLE
Remove usage of EventTarget constructor in tabster

### ISSUE THREAD

**Issue by TristanWatanabe** [microsoft/fluentui#24721]
### Issue:
- `tabster` uses the `EventTarget` constructor which isn't supported until Safari 14 which exceeds our intended partial support matrix proposed in #24283.
- The usage of this breaks partners who are still supporting Safari 13.

**Comment by JustSlone** [comment]
@microsoft/teams-prg can you work with tabster folks to address this issue?

**Comment by layershifter** [comment]
@JustSlone @TristanWatanabe I would like to better understand the scope of work. The mentioned PR #24283 contains:

> FluentUI provides partial support for the browsers below which will have limitations that will require consumers to transpile down and/or use polyfills to cover the support gaps.

There is a polyfill (https://github.com/benlesh/event-target-polyfill) for `EventTarget` that customers could use. I would suggest to use the polyfill on partner side and close the issue.

**Comment by TristanWatanabe** [comment]
@layershifter I chatted about this with @ling1726 and basically the idea behind the partial support browser matrix is that it's essentially our **internal** browser matrix that we develop against. With our partial/internal browser support for Safari about to be set at 13.1, our components should not break/crash consumer apps who need to support Safari 13 which `tabster` does at the moment. So the scope of the work is basically removing usage of the `EventTarget` constructor from `tabster` and replacing it a `MyEventTarget` (something along these lines) which does the exact same thing as the native `EventTarget`.

**Comment by ling1726** [comment]
@TristanWatanabe, it seems that the description of the partial support matrix in #24283 is not quite clear what we should act on here. Our partial support matrix actually suggests customers to use polyfills for browsers under partial support 🤔.

Could you please clarify this task with respect to the statement about polyfills ?

**Comment by JustSlone** [comment]
thanks for looking at this

So, here we should weight the cost/impact of changing our library vs asking all partners to install a polyfill. There is ongoing work on standardizing browser matrix more broadly, I suspect that work will find Safari 13 within the browser support matrix due to the number of customers on that browser. 

I agree that elaborating on #24283 is a good idea, it's not particular clear from that short text. @TristanWatanabe can you work on that? feel free to pull me in for feedback on text

The intention there is that we support Safari 13.1 for browser APIs and CSS features, except in exceptional cases. Things like flex gap are there because it provides a lot of value to component development, and the impact of not supporting it is minor. With EventTarget I believe the impact of not supporting it is an exception thrown, which is a pretty huge impact. That is mitigated by the fact that there is a well-known polyfil, but I'd like to keep the # of polyfills we require down, so if we can resolve this ourselves for now let's do it. We can remove our solution when we drop support for Safari 13.1.

**Comment by layershifter** [comment]
@JustSlone let's continue the discussion in the PR, https://github.com/microsoft/fluentui/pull/24283#discussion_r969837736.
