### ISSUE TITLE
[Feature]: DetailsList and GroupedList in Fluent UI React Components v9

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#24774]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Are you planning on implementing [DetailsList](https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist) and [GroupedList](https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist) components in Fluent UI React Components v9?
Mainly I mean a GroupedList, more like a tree view pattern. 
Just need to know whether you gonna implement it in V9 or not.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AkiraVoid** [comment]
Discussed in [#24751](https://github.com/microsoft/fluentui/discussions/24751#discussioncomment-3633174)

The author wants to know if there is any components will be implements which have similar behavior like Table, but rows in it can be grouped like GroupedList in v8.

**Comment by gouttierre** [comment]
Yes, we do have a table component in works for v9. You are welcome to view all v9 controls on our [Fluent v9 React Storybook](https://react.fluentui.dev/?path=/docs/preview-components-table--default). To see what else we have planned for v9, please, check out our wiki for monthly updates to our [Fluent v9 Roadmap](https://github.com/microsoft/fluentui/wiki/Fluent-UI-React-v9-Component-Roadmap)

@paulgildea and @JustSlone could either of you confirm if there is plan in FY23 for DetailsList and GroupedList for v9?

**Comment by ling1726** [comment]
Thanks for the feedback and input @AkiraVoid  @kroudams. We understand that the DetailsList is very heavy in features and can do a lot of very cool and powerful things. 

In the case of grouping specifically, one of the biggest problems that we are still thinking about is how to make this accessible. Table layouts in HTML do not naturally support any kind of collapsible sections, and generally it's quite hard to narrate them to screenreaders, and breaks the structured narration of tables and grids. In terms of pure accessibility, it's quite obvious to say that a tree or treegrid would be the natural component for this scenario.

Then again, we do know that the library needs to be flexible. Currently we've only made significant progress with the primitives of the `Table` component so that users can use those components with their own logic and meet the design requirements of Microsoft products. We do intend to release headless hooks to manage states for more complicated features that one might find in the `DetailsList` but are still in exploration on how to provide the best API for developers.

We understand the need for powerful features that the `DetailsList` provides in v9 and we appreciate the feedback. We have heard you and are simply making sure we do not end up in the same destination as the `DetailsList` where most feature requests are rejected or can take months to even release as preview because nobody knows anything about the codebase anymore. Please bear with us 🙏

**Comment by ling1726** [comment]
Closing this issue until more concrete work items come out of #24226 Please use the discussion feature to discuss the features 🙏
