### ISSUE TITLE
[Bug]: TextField icon button for the password to be revealed is gone from all environments. Even your demo site 

### ISSUE THREAD

**Issue by NathanC15** [microsoft/fluentui#24997]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 1.65 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield

## Actual Behavior
There is no icon inside of the password text field for a user to reveal/hide the password. Now a user only sees a password with dots
![Screenshot 2022-09-28 105902](https://user-images.githubusercontent.com/49923682/192855189-22513c86-0761-416e-8998-1ccb4c39044d.png)

## Expected Behavior
Have the eye icon inside of the password text field for a user to reveal/hide the password.
![image](https://user-images.githubusercontent.com/49923682/192855871-53b253d7-2c6f-44d6-8e53-540d4e5293fd.png)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by NathanC15** [comment]
This is causing issues in our production version of our app which is currently impacting multiple customers at the moment because they can't reveal passwords that they need to access. What our prod version looks like:
![image](https://user-images.githubusercontent.com/49923682/192857678-7b68d066-4f7d-4877-b202-ba082a2701a4.png)

**Comment by micahgodbolt** [comment]
This is expected behavior in Edge which has built in reveal password functionality. Not sure why you were getting the non edge behavior in the past.

Solution discussed offline was to create a 'show password' button outside of the input that switches the input from type="password" to type="text". This is how it's done internally in the textfield.

I believe that the behavior in edge (where clicking into a password field does not show reveal password button) is actually the correct, secure behavior. So moving this button outside of the input, and ensuring that the user has permission to see this password, is probably the best move anyway.
