### ISSUE TITLE
`Accessibilty` should really be `Accessibility`

### ISSUE THREAD

**Issue by jsoref** [microsoft/fluentui#25039]
### Environment Information

- **Package version(s)**: https://github.com/microsoft/fluentui/search?q=Accessibilty default (`master`) branch
- **Browser and OS versions**: 

### Describe the issue:

`Accessibilty` is a typo for `Accessibility`.

If it's possible to switch to the correct spelling and leave a compatibility shim for the old spelling, that'd be great

#### Actual behavior:

`Accessibilty`

#### Expected behavior:

`Accessibility`

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: All? microsoft/charticulator

**Comment by miroslavstastny** [comment]
The public API is `AccessibiltyChecker` icon `font-icons-mdl2` and `AccessibiltyCheckerIcon` in `react-icons-mdl2`.

We cannot change break the public API, the only way forward would be to add a new icon with a correct name and deprecate the current one.

Considering the icon has been there for more than two years now I don't think the fix is worth the effort.
