### ISSUE TITLE
[Bug]: Panel content overlays header and footer if panel is opened from start

### ISSUE THREAD

**Issue by yhladki** [microsoft/fluentui#25089]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 44.17 GB / 63.73 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/chaoticgoodyury/pen/mdLjwMV

## Actual Behavior
Big and scrollable panel content overflows header and footer if Panel is opened from start.
![image](https://user-images.githubusercontent.com/27007621/194040886-efbb8cd0-6cf2-43be-8604-532701ecbe1a.png)
The problem is resolved when window is resized or panel reopened, so I assume that there is some minimal state mismatch for the Panel component.

## Expected Behavior
Panel's header and footer are not overlayed by content when scrolling.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
### Workaround
Apply style overrides to the `Panel` component:
```jsx
<Panel
  ...
  styles={({ theme }) => ({
    commands: {
      backgroundColor: theme?.semanticColors.bodyBackground,
    },
    footer: {
      backgroundColor: theme?.semanticColors.bodyBackground,
      borderTopColor: theme?.semanticColors.variantBorder,
    },
  })}
>
```

### Details

Based on `isFooterSticky` state in the `Panel` prop, the styles showed above are applied to the component.
The problem is that the `isFooterSticky` state is set only **after the transition** (animation) to the open/closed state.
If the `Panel` is initially rendered as `open`, the transition does not happen, the `isFooterSticky` state is not set and the component is not rendered with the corresponding styles.

nit: Also the state actually does not reflect whether the footer is sticky but rather whether the content is scrollable. The sticky attribute is controlled by a CSS breakpoint - if the height of the window is small, the footer is not sticky, but the styles are applied.
