### ISSUE TITLE
[Bug]: Custom styling ComboBox does not wrap around 

### ISSUE THREAD

**Issue by wangsanfeng1998** [microsoft/fluentui#25152]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 782.21 MB / 15.75 GB
  Browsers:
    Chrome: 106.0.5249.103
    Edge: Spartan (44.22621.521.0), Chromium (106.0.1370.37)
    Internet Explorer: 11.0.22621.1
```

### Reproduction

https://codepen.io/sanwang/pen/abGQGZR

## Actual Behavior
The custom styled Combox does not have text that wraps around
![image](https://user-images.githubusercontent.com/19734646/194933407-2241eee2-32bd-4cf5-9524-f5ff8ddd204c.png)

## Expected Behavior
In a custom styled ComboBox, we should be able to wrap text around.
![image](https://user-images.githubusercontent.com/19734646/194933312-ff043fa8-da9b-42f2-8a19-489e269e84ca.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
I am sorry but I do not follow. Could you please explain which example you are referring to and what exactly does not work?

What I see in the `ComboBoxCustomStyledExample` the items are not wrapped in the second combobox because there is no `maxWidth` applied to `optionsContainerWrapper` and there are no styles added to the `span` in `onRenderOption`. Once I add the styles there:
```jsx
return (
  <span
    style={{
      fontFamily: fontFamily,
      overflow: 'visible',
      whiteSpace: 'normal',
      textOverflow: 'ellipsis',
      minWidth: '0px',
      maxWidth: '100%',
      overflowWrap: 'break-word',
      display: 'inline-block',
    }}
  >
    {item.text}
  </span>
);
```

Both examples wrap the items in the combobox:
![image](https://user-images.githubusercontent.com/9615899/195912287-d5996cda-ddfb-4a5b-89e4-762f5f319f4e.png)
