### ISSUE TITLE
[Bug]: Details list leaves blank spots

### ISSUE THREAD

**Issue by TonyTroeff** [microsoft/fluentui#25186]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 6.70 GB / 31.77 GB
  Browsers:
    Edge: Spartan (44.22621.521.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

I cannot reproduce it in CodePen.

### Bug Description
I am using version 8.98.0 of the fluentui package

## Actual Behavior
Only by resizing the window, I can make the hidden rows appear.
https://user-images.githubusercontent.com/33567383/195366346-9e792e5a-8053-4a87-a918-04e1ea7647cb.mp4

## Expected Behavior
I expect that all rows should be successfully visualized.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by KirianCaumes** [comment]
I think I have the same problem with the last version 8.98.3.

I still use the version 8.77.1 where is perfectly working.

As the 8.77.1 was released 24 Jun 2022 and according to [component history](https://github.com/microsoft/fluentui/commits/master/packages/react/src/components/List/List.tsx), the problem might be from either: https://github.com/microsoft/fluentui/pull/23813, https://github.com/microsoft/fluentui/pull/24353 or https://github.com/microsoft/fluentui/pull/24460

**Comment by AdrianSchmidt91** [comment]
Same for me using v8.99.2

**Comment by TristanWatanabe** [comment]
Unfortunately, without a proper repo, this is incredibly difficult to debug. I checked our existing examples to try and reproduce the issue to no avail. Please provide some form of repro example so we may look into this further. Also tagging @spmonahan whose worked on `DetailsList` recently in case he has an idea on what's going on.

**Comment by spmonahan** [comment]
Hey @TonyTroeff , @KirianCaumes , @AdrianSchmidt91 -- are you using the `groups` prop on `DetailsList`? I see you're unable to repro the issue in Codepen but a code example of how you're using `DetailsList` will still be very helpful in diagnosing your issue.

**Comment by KirianCaumes** [comment]
Hi @spmonahan @TristanWatanabe,
I just created a simple repo with two projects : one working (@fluentui/react v8.77.1) and another not properly working (@fluentui/react v8.104.8). You can find it here: https://github.com/KirianCaumes/fluentui-list-bug
I have also put two video showing the problem (see Readme.md).
Hope that will help 😁

**Comment by spmonahan** [comment]
> Hi @spmonahan @TristanWatanabe, I just created a simple repo with two projects : one working (@fluentui/react v8.77.1) and another not properly working (@fluentui/react v8.104.8). You can find it here: https://github.com/KirianCaumes/fluentui-list-bug I have also put two video showing the problem (see Readme.md). Hope that will help 😁

Thanks for this! I wasn't able to get your "working" example running as there are conflicts with React 18. It's probable that 8.77.1 was before we enabled React 18 support in Fluent UI v8. Anyway, I was able to review your videos and I suspect the issue you demonstrate is different from the original issue.

In your example you've set `renderedWindowsAhead/Behind` to `0`. These props control how many offscreen elements are rendered so while not ideal it's not surprising to see some gaps while rendering catches up to scrolling. We can certainly do better here but the elements all do render and while it's certainly not ideal to render gaps even for short periods like in your example, I don't see the issue as high priority, particularly when compared with the original issue where large chunks of the list are essentially never rendered.

List rendering is complex so your issue could be related to the original bug but I won't be focusing on it as I investigate this bug. I'm happy to help you get setup to contribute to Fluent if it's something you want to get fixed faster.

I've seen the original issue before when there are nested groups which is why there is a [new, opt-in, `GroupedListV2`](https://github.com/microsoft/fluentui/pull/24460) for rendering grouped lists. From the original video it doesn't look like there is any grouping in the `DetailsList` but it does appear to be in a `Dialog`.

I've created a [Codepen with `DetailsList` in `Dialog`](https://codepen.io/seanms/pen/dygPGBX) but that still doesn't repro the issue.

Without a repro case I won't be able to work on a fix.

**Comment by spmonahan** [comment]
Thanks for following up and providing some context on your examples.

> Or maybe we can even wait for the equivalent of this component to be available on FluentUi v9, and see if the problem will still be relevant.

You should check out Fluent v9's [DataGrid](https://react.fluentui.dev/?path=/docs/components-datagrid--default)
