### ISSUE TITLE
[Docs]: Split buttons primary action must also be in overflow menu (docs/examples update)

### ISSUE THREAD

**Issue by dmceachernmsft** [microsoft/fluentui#25323]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
iPad
iOS 15.5
Safari 15.5
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/dmceachernmsft/pen/wvjLOyJ

## Actual Behavior
Split button when actioned on iPad activates the secondary action when trying to activate the primary action

## Expected Behavior
Primary action is triggered and alert is shown

https://user-images.githubusercontent.com/94866715/197017441-f66acfb3-d845-45ba-a579-b708f8c9cfba.mp4

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
reprod on current ipad and android phone. Also repros in touch mode of inspector device emulation

**Comment by micahgodbolt** [comment]
It looks like this is an expected behavior in v8 (with the button being a single tabstop and the 2nd button not being a large enough target). The advice is to always have the primary action also available in the menu.

![image](https://user-images.githubusercontent.com/1434956/214906422-e5973ee6-ef7e-47cc-b256-28b486413575.png)

Button is a shortcut for highlighting yellow, but the overflow still contains the highlight yellow option.

Or even more close to home

![image](https://user-images.githubusercontent.com/1434956/214906571-8a242ed3-b42c-4668-a356-672a9126158c.png)

You can still close with comment in the overflow menu.

**Comment by micahgodbolt** [comment]
We will update our button guidance to note that the primary action should also be available in the overflow.
