### ISSUE TITLE
Review v8 DatePicker and plan options for v9 DatePicker

### ISSUE THREAD

**Issue by spmonahan** [microsoft/fluentui#25375]
## Problem

We need a `DatePicker` that integrates cleanly with Fluent UI v9. As Fluent v9 introduces a different approach to building components compared with Fluent v8 we will need to examine the [Fluent v8 DatePicker]() to understand how to best integrate it into Fluent v9 applications without rewriting the entire control.

## Appetite

1-2 weeks

## Solution

Review the existing implementation to make notes about what it would take to

1. Update DatePicker to use v9's styling and theming solutions
2. Add v9 slots to DatePicker
3. Use v9's hooks composition model with DatePicker

## Risks (Rabbit holes)

DatePickers are complicated controls. We don't need to solve every single case or issue but build an idea of the overall problem scope.

## Out of scope (No-gos)

This issue will not provide any concrete implementations. It's only a review of the existing v8 DatePicker implementation with notes about how it might be ported into v9.

**Comment by khmakoto** [comment]
We have a working v9ified `DatePicker` (with some issues that need to be ironed out) in https://github.com/khmakoto/fluentui/tree/v9ifiedDatePicker10.

Some of the things that we did during this investigation on v9ifying the v8 `DatePicker` are:
- Swapping out `mergeStyles` for `makeStyles` in `DatePicker` and all `Calendar` components
- Replacing some of the v8 components used within `DatePicker` for their v9 equivalents
  - v8 `TextField` for v9 `Input`
  - v8 `Callout` for v9 `Popover`
  - v8 `Icon` for individual icons in `@fluentui/react-icons`
- Moving `DatePicker` to the slots + hooks approach
- Replacing some imports from v8 dependencies with inlined, scaffolded or v9 equivalents
  - `@fluentui/date-time-utilities`
  - `@fluentui/react-focus`
  - `@fluentui/react-hooks`
  - `@fluentui/utilities`

I have not yet tested render performance on our v9ified `DatePicker`, but I did test bundle size performance, and found out that our v9ified `DatePicker` has a much bigger bundle size (~230KB) than our v8 `DatePicker` (~170KB). I originally attributed this to the fact that we were using v8 and v9 dependencies in tandem. However, after running the code through a bundle size analyzer, I realized that the main culprit of this bundle size increase is `@fluentui/react-icons`, which seems to not be tree-shaking correctly. In fact, without the hit from this package, our v9ified `DatePicker` already has a smaller bundle size than our v8 one.

![image](https://user-images.githubusercontent.com/7798177/204355840-aff2bf25-19ef-4d3f-a94e-35276843f00a.png)

We need to fix this going forward to be able to have better bundle size on v9, as I suspect most of our components using `@fluentui/react-icons` probably have a larger (or at least an equivalent) bundle size than their v8 equivalents even after all of our improvements.

On a more general sense, I think the realization from this investigation is that it is feasible to move a big v8 component and v9ify it. However, more testing needs to be done in order to ensure that doing so will bring tangible benefits over using the v8 version other than just updating the tech stack.
