### ISSUE TITLE
Text Inputs Validation Error - NVDA reads out error twice

### ISSUE THREAD

**Issue by glemis** [microsoft/fluentui#25444]
### Describe the issue:

When using the `<TextField errorMessage="A message" />`
The message is read out twice. 

This took place on our site using version 8.76.0 but also takes place on the fluent UI dev site https://developer.microsoft.com/en-us/fluentui#/controls/web/textfield 

Took place on both chrome and Edge. 

I believe this is due to because it is decorated with `role="alert"`
So it first alerts then reads the text also. 

#### Actual behavior:

Error message reads out twice.

#### Expected behavior:

Error message only reads out once.

**Comment by smhigley** [comment]
@glemis could you provide a codepen of the issue and specify the screen reader this is happening with?

The reason I ask is that generally the `role="alert"` will cause the error message to be read when it is created, and only then. Since this usually happens on blur, the text will be read once after focus moves away from the input. When focus moves back into the input, the text will be read as part of the input's description, again only once. The specific event callback and implementation of the error message matters in how it is presented.

When the error message is added while the user is still editing (so focus is in the field), it may be read twice in some screen readers -- once for the alert, and once because it is the description for the field. It wouldn't be good to change either behavior, even in this case -- not all screen readers will read changes to a description, so the alert is still necessary. Additionally, the description is necessary so users will still be advised of the error if they leave and return to the input. Reading an error twice is not in itself a bug here, and is preferable to the message not being read at all.

Hope that helps!
