### ISSUE TITLE
[Bug]: Jaws announces dropdown option twice when text is equal lengths as prior

### ISSUE THREAD

**Issue by dacheson** [microsoft/fluentui#25445]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Environment Details:
OS build Version: 21H2 (OS Build 22000.795)

Chromium Edge Dev: Version 105.0.1329.1 (Official build) dev (64-bit)
App name: Project_Web (PWD-AT)


Repro Steps:
Launch the URL: - https://aka.ms/projDaily and login with appropriate credentials.
Open a project 
Add some tasks 
Open task details
Actual Result:
The selected option name announced only once.
Expected Result:
The selected option name should be announced only once.
User Impact:
screen reader users may find the announcement redundant."

MAS References:

MAS 1.3.1 – Info and Relationships
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/dacheson66/pen/dyKGPze

## Actual Behavior
Narrator reads each option twice on initial focus

## Expected Behavior
Narrator reads each option once

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by dacheson** [comment]
This reproduces on any Dropdown example on your example sites. Repro is turn on narrator and go through the dropdown options. You should hear each option once, any you hear twice is the bug.

**Comment by micahgodbolt** [comment]
I can't repro this at all. I hear "Brocolli, 5 of 7". Thats it.

**Comment by KeiraYang** [comment]
@micahgodbolt I also can reproduce it in the fluent example page:
https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

Using Narrator + Edge Chromium, when focus on the dropdown, it read out the option twice. Checked fluent Combobox component which has similar UI but no this issue.

**Comment by gfisher-vmsft** [comment]
I was also able to reproduce this. On closer investigation, the bug seems to be triggered when consecutive combobox options have the same text length.

## Pre-Requisites
### Browsers:
- Chrome version 110.0.5481.104
- Edge version 110.0.1587.46

### Combobox Options
- consecutive options must be the same text length (Most examples have this)

### Screen Reader
- JAWS version 2023.2210.29 ILM

## Repro Steps:
1. Navigate to page with a combobox
1. Focus the combobox, but do NOT expand the options list
1. Arrow key down

**Expected result:** Combobox is expanded and screen reader reads the option aloud
**Actual results:** Combobox is not expanded, and screen reader does not read the new option aloud

## Other notes
- At some point, JAWS will start reading all options. At this point, it will double read any options that have a different text length than the previously read options

## Bug does not exist for
- JAWS on Firefox
- NVDA with Firefox, Chrome, Edge
