### ISSUE TITLE
Checkbox and Radio styles nested selector usage might not be scalable

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25483]
Currently the `Checkbox` and `Radio` components use nested selectors to style states, some examples below:

```ts
[`:not(:checked) ~ .${radioClassNames.indicator} > *`]
':enabled'
':enabled:not(:checked)'
```

These kinds of styles have two important consequences that will impact partners when using these components

### Override specificity

It is not obvious how to override slot styles without using `important`: https://codesandbox.io/s/funny-monad-xhjzj1?file=/example.tsx

```ts
const useStyles = makeStyles({
  checkedIndicator: {
    backgroundColor: "red"
  },
  checkedIndicatorImportant: {
    backgroundColor: "red !important"
  },
  checkedNestedIndicator: {
    ":enabled:checked:not(:indeterminate)": {
      [`& ~ .${checkboxClassNames.indicator}`]: {
        backgroundColor: "red"
      }
    }
  }
});
```

Since our components are liable to be used in our libraries that are shared and reused, these kinds of overrides are not scaleable in an app or cross app.

### CSS classes bloat

Each control will contain more >100 CSS classes at any time. The use of nested selectors means that the classes are never applied conditionally and will always be there. This has a negative impact on performance since atomic css performance can decrease linearly with respect to the number of classes.

Checkbox

![image](https://user-images.githubusercontent.com/20744592/199451755-5ebed230-072f-4aef-b7b9-87a2ca799971.png)

Radio

![image](https://user-images.githubusercontent.com/20744592/199451990-87891ad3-6b9b-4ff8-b878-15a9aef185c6.png)

**Comment by naostranMS** [comment]
I think this is the same issue I just encountered with Tabs.

Tabs use this selector to set the color of the content: [`'& .fui-Tab__content'`](https://github.com/microsoft/fluentui/blob/5ed22515a7542b432ed694f22606ac3718d501cb/packages/react-components/react-tabs/src/components/Tab/useTabStyles.ts#L106)

I tried to override using something like this:
```
const useStyles = makeStyles({
    tabContent: {
        color: "magenta",
    },
});

...

<Tab value={item.id} content={{ className: styles.tabContent }}>
```
but since the result is a selector with a single class it has lower specificity and the default color still wins.
Adding `!important` works, and might be fine for my use case.
And as with your third example, I can also add a nested selector with the same specificity:
```
[`& ${tabClassNames.content}`]
```

**Comment by behowell** [comment]
I think the solution here needs to be more comprehensive than refactoring the Checkbox styles to reduce the use of selectors:
* This affects most of our components to some extent (as naostranMS mentioned for Tabs), although Checkbox is an extreme example of the use of selectors. 
* Doing a large refactoring of Checkbox's styles at this point would almost certainly break anyone who's already written CSS to override the default styles.
* It's also not feasible to refactor the CSS for all of our components to be entirely predictable for people who want to override any aspect of them.
  * Some implementation details and optimizations might require using CSS props or selectors that users wouldn't expect without knowing about the implementation details.
  * There's no real way to know if CSS styles are "predictable enough" to easily override, since different people overriding them may have different ideas about how it would work.
  * We might need to make future changes to the CSS to fix bugs, which could break these overrides.

For those reasons, we're investigating other ways to override styles of our components. There is no final proposal yet, but there is a draft RFC with some of the working ideas here:
* #25333

We're going to hold off making changes to Checkbox's styles while we work on the RFC.

**Comment by behowell** [comment]
My comment above addresses the first half of the bug ("Override Specificity"). As for the second half ("CSS classes bloat"): some of that will be addressed by the use of Griffel's reset styles, to combine all of the base styles into a single CSS class, as well as other Griffel optimizations (like merging shorthand styles into fewer classes). There may be opportunity to do some more targeted refactoring as well, but it may be worthwhile to wait until we have a plan for the Custom Styling RFC before working on that.

**Comment by behowell** [comment]
I've opened this PR to address the CSS class bloat issue by making use of Griffel reset styles:
* #25984

It reduces the number of CSS classes by 85%, and improves styling performance by roughly 12% for Checkbox.
