### ISSUE TITLE
[Feature]: make accessible labelling a required prop for image buttons

### ISSUE THREAD

**Issue by aubreyquinn** [microsoft/fluentui#25574]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

An image button not having an aria label or other type of accessible labelling is a common accessibility violation.

<Button icon={<CalendarMonth />} />

Right now, it is not a required prop in React. Can we make it required for image buttons?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by smhigley** [comment]
@aubreyquinn thanks for the suggestion! Part of the issue here is that there are quite a few ways to provide an icon-only or image-only button with an accessible name:

```jsx
// using visually hidden button text
<Button icon={<CalendarMonthRegular />}><span class="visuallyHidden">Month</span></Button>

// using aria-label on the Button
<Button icon={<CalendarMonthRegular />} aria-label="Month" />

// using aria-labelledby on the Button
<span id="month-text">Choose a Month</span>
<Button icon={<CalendarMonthRegular />} aria-labelledby="month-text" />

// using aria-label on the icon
<Button icon={<CalendarMonthRegular aria-label="Month" />} />

// using aria-labelledby on the icon
<span id="month-text">Choose a Month</span>
<Button icon={<CalendarMonthRegular aria-labelledby="month-text" />} />
```

Part of the issue is that these are spread across the `<Button>` component and the icon component, and the parent Button has no way to know whether the icon itself has an accessible name. The only real way to test whether the Button has an accessible name is after the JSX has been rendered, which we would like to aid teams in doing. It just isn't really possible in the types themselves.

Hope that helps, and let us know if you have any other suggestions!

**Comment by smhigley** [comment]
@aubreyquinn you're probably right that most developers will do that, but I'd still be hesitant to use typings to generate errors for valid ways to approach labelling that are just less common. I wouldn't be surprised if someone repackaged our icons with localized label strings, for instance.

Re: the icon `aria-hidden` thing -- it's only hidden if you don't provide an accessible name :)

We are looking at developing a set of accessibility tests for Fluent components to catch things like this, or mis-uses of ARIA specific to our components that we can determine from props and component type.
