### ISSUE TITLE
Calendar with month picker and no day picker

### ISSUE THREAD

**Issue by Leif-Frederiksen** [microsoft/fluentui#25585]
When using the Calendar  set up as month picker, and with the day picker not showing, selecting a date does not return the date range - only a selected date, which is the current date of the selected month.

This can be tried out in the example called "Calendar with month picker and no day picker" on the https://developer.microsoft.com/en-us/fluentui#/controls/web/calendar page.

#### Actual behavior:
Only a single date is returned.

#### Expected behavior:
The range of the entire month clicked should be returned - like in the "Calendar with month selection" example.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Low)

**Comment by smhigley** [comment]
@Leif-Frederiksen thanks for the feedback! I'm not actually sure that the Calendar as a month-only picker should return a range of dates vs. a single date, since the user is still selecting a single choice vs. a range (e.g. Feb-April). I could see arguments both ways -- a full month is always a span of dates, but if we always return a range, then there's no differentiation between picking a single month vs. picking a range.

For now, does it work for your use case that when you use a month-only picker, you process the date in `onSelectDate` to get all days within the month?

**Comment by Leif-Frederiksen** [comment]
@smhigley - Actually in the "Month picker" example the user is not selecting a single date, but can only click on a month:
![image](https://user-images.githubusercontent.com/25172917/201597779-54306fcf-b598-4e1c-86e3-9af82af81b20.png)

In the "Calendar with month" example, the user IS clicking on a date, and in this example both the selected date, and the corresponding month interval is returned correctly:
![image](https://user-images.githubusercontent.com/25172917/201598045-6c77048f-61d9-48d1-af6d-717d7c84d63d.png)

Of course I can just calculate the start and end of month myself - which I do. So this is not critical at all - just an inconsistency in the component.

**Comment by Leif-Frederiksen** [comment]
Wrong to close - I provided feedback as author and then nothing further happened.

**Comment by khmakoto** [comment]
@Leif-Frederiksen reopening given your feedback

**Comment by Leif-Frederiksen** [comment]
What author feedback are you still requiring?
