### ISSUE TITLE
[Bug]:  Selection is not maintaining the order in which items are selected and selection is not getting preserved when filtering .

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/fluentui#25707]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
React:18
@fluentui/react:8.96.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/muddy-leaf-zkv3pn?file=/src/App.tsx

## Actual Behavior
fill this out
Selection is maintaining the order in which items are there but not as per selection order.
Example: If i have selected last item at first and then selected first item, getSelection() is returning in order [firstItem, lastItem]  but not in the order [lastItem, firstItem].

If item is selected at first and then Onfiltering if items are becoming empty onSelectionChanged() method getting triggered automatically .

In onSelectionChanged() I am getting selectiondetails and setting to state. When items are becoming empty after filtering onSelectionChnaged is getting triggered and selectedItems state is getting lost. onSelectionChnaged should not be triggered untill and unless we manually change the selection. 

Selection is not getting preserved after filtering.

## Expected Behavior
fill this out
Selection should maintain the order in which items are selected.

There should be some way to preserve selection even aftering items. onSelectionChanged shouldnot be triggered if items become empty .

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@bhanu345-cmd  so it seems that there are two problems here:

* The `Selection` instance always keeps items in render order instead of order they are selected
* `onSelectionChange` is called during filtering so selections don't persist during filter by default without work on the userland side

Both of these have been the default behaviour since the last major version. Unfortunately this means that they will need to be logged as feature requests for the `DetailsList`. If you work in Mircrosoft, you can reach out to our PMs to prioritize these features higher on our backlog.
