### ISSUE TITLE
[Bug]: Insufficient contrast for Alert with inverted appearance

### ISSUE THREAD

**Issue by behowell** [microsoft/fluentui#25722]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.24 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42), ChromiumDev (109.0.1495.2)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/preview-components-alert--default#appearance

## Actual Behavior
The link text and icons for inverted Alerts don't meet contrast requirements.

<img alt="image" src="https://user-images.githubusercontent.com/48106640/202780873-92f453b9-1ebf-4ce6-8cc6-5d97cc5b883a.png">

## Expected Behavior
The text should meet the minimum contrast requirements.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
There are currently following problems with the `<Alert appearance="inverted" />`:
- Action button is hard to see
![image](https://user-images.githubusercontent.com/9615899/203548929-e906bfe0-4d04-4c98-bd50-31e998720b9b.png)

- Icons are hard to see 
![image](https://user-images.githubusercontent.com/9615899/203548862-0864c558-ca8e-455c-8f10-0e5a9db2a3c3.png)

- Focus ring hardly visible
![image](https://user-images.githubusercontent.com/9615899/203548763-7415f51c-730a-4b06-b324-e8ed33e0c14a.png)

- Text is not visible in High contrast mode
![image](https://user-images.githubusercontent.com/9615899/203548580-4ca5fa2b-7e84-40bf-bd5a-62f444dcc309.png)

**Comment by miroslavstastny** [comment]
This is a prototype showing potential fixes (which can be applied temporarily on application side): https://codesandbox.io/s/damp-morning-bvnd5i?file=/example.tsx

## Action button is hard to see
- Update `colorBrandForegroundInverted`, `colorBrandForegroundInvertedHover` and `colorBrandForegroundInvertedPressed` tokens in `teamsDarkTheme` - #25721
- Use these tokens for the `action` color

**Problem** - this changes the button to be white (hcCanvasText) instead of yellow (hcHyperlink) in Teams High Contrast.

## Icons hard to see
- Use `colorNeutralForegroundInverted2` for `info`, add tokens for `success`, `error` and `warning` intents - #25721.

**Problem** - the issue currently does not specify the color palette tokens to be added.

## Focus ring hardly visible
- The ring currenty uses `colorStrokeFocus2`, I tried to change it to `colorStrokeFocus1` - that fixes the issue in light and dark theme.

**Problem** - In Teams High Contrast the outline is black (hcCanvas) and not visible instead of cyan (hcHighlight):
![image](https://user-images.githubusercontent.com/9615899/203551599-532c7940-5616-42ec-acc2-85e6f5f76855.png)
_(the white line is a button border, not the focus ring)_
