### ISSUE TITLE
[Bug]: `useControllableState` is not able to sync internal state with incoming state

### ISSUE THREAD

**Issue by YuanboXue-Amber** [microsoft/fluentui#25748]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-utilities 9.2.2
Edge/chrome browser
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/determined-kilby-fc1re0?file=/example.tsx

### Bug Description

`useControllableState` maintains its `internalState`. When user changes the state input, `useControllableState` is not updating its internalState to be in sync with user state. Please see the codesandbox for more details.

_This is a screenshot from codesandbox_:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/28751745/203295269-5438d98e-cba4-4b7c-8c7c-dafe2a66f80c.png">

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment]
Note that v0 @fluentui/react-bindings `useAutoControlled` has the same issue

**Comment by ling1726** [comment]
The most important negative impact here is that the callback setter of `useControllableState` is unreliable

```ts`
const [state, setState] = useControllableState({ defaultState: true, state: userState, initialState: false });

// ⚠️⚠️ `prevState` can desync from the actual user state
setState(prevState => getNextState(prevState));
```

**Comment by miroslavstastny** [comment]
Either remove the callback or fix it (might not be doble at all).

**Comment by bsunderhus** [comment]
The way I see the name being given to the `setState` hook is being misinterpreted here.

We're assuming the hook has the ability of actually change `state` value, whereas it should probably be name `requestSetState`?! as this hook will only **try** to set the state, since there's no way to actually do that if it's controlled by the user. So on those cases that the update doesn't happen is because there's no way to update (that's why the callback in this matter is not being invoked)!

On the given example https://codesandbox.io/s/determined-kilby-fc1re0?file=/example.tsx :

```ts
const setOpen = (id: string, shouldOpen: boolean) => {
  setOpenState(prevOpen => {
    console.log('setOpenState', 'prevOpen', prevOpen, 'shouldOpen', shouldOpen);
    if (prevOpen !== shouldOpen) {
      props.onOpenChange?.(id, { open: shouldOpen });
    }

    return shouldOpen;
  });
};
```

You have the external listener that has the job to propagate modification to it's controller (the parent component) inside of the callback of the internal state modification. That internal state modification callback will never be invoked, since there's no internal state, internal state is just a reflection of the external one!
So in this case making that ` props.onOpenChange` invocation outside of the internal state modification callback solves the problem:

```ts
const setOpen = (id: string, shouldOpen: boolean) => {
  if (open !== shouldOpen) {
    props.onOpenChange?.(id, { open: shouldOpen });
  }
  setOpenState(prevOpen => {
    console.log('setOpenState', 'prevOpen', prevOpen, 'shouldOpen', shouldOpen);

    return shouldOpen;
  });
};
```

I would see this more of an implementation bug then a problem on the `useControllableHook`

**Comment by YuanboXue-Amber** [comment]
Chat with @bsunderhus and I realize when the state is controlled externally, `setOpenState` is noop. I like this change and it makes sense to me. Going to close this issue.
