### ISSUE TITLE
[Bug]: Coachmark mouseover gets triggered behind a modal

### ISSUE THREAD

**Issue by kehindeoni** [microsoft/fluentui#25791]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 65.38 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.49), ChromiumDev (105.0.1336.2)
    Internet Explorer: 11.0.22000.120
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/kehindeoni/pen/rNKvRWe?editors=0010

## Actual Behavior
When coachmark is displayed and you open a modal on top of it, hovering on modal causes the mouseover event on the coachmark to be triggered. Even when coachmark is not visible (hidden behind the modal), hovering on it expands the coachmark. 

https://user-images.githubusercontent.com/69808477/204055736-b104d56a-0e7b-439c-847e-ec8befb21fc6.mp4

## Expected Behavior
Modal mouseover should not bubble to coachmark.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
@kehindeoni this is a regression, more details https://github.com/microsoft/fluentui/issues/23074#issuecomment-1215070201. That's why I am going to close this as a duplicate.

BTW, you can contribute a fix for that issue 😉 

---

As a workaround I see following options:

- Hide `Coachmark` when a `Modal` will be opened, i.e.
  ```tsx
  <DefaultButton
    onClick={() => {
      showModal();
      hideCoachmark();
    }}
  />
  ```
  https://codesandbox.io/s/upbeat-keller-zfdqfg?file=/src/App.tsx
- Use `onDismiss` + `preventDismissOnLostFocus` on `Coachmark`. This option has a downside as once #23074 will be fixed you will need to remove/flip `preventDismissOnLostFocus`
  https://codesandbox.io/s/amazing-greider-svtwvt?file=/src/App.tsx
