### ISSUE TITLE
[Bug]: FocusTrapZone flow not correct if last element is iframe

### ISSUE THREAD

**Issue by dosomder** [microsoft/fluentui#25840]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
OS: Linux 6.0 Arch Linux
CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Memory: 14.19 GB / 31.04 GB
Container: Yes
Shell: 3.5.1 - /usr/bin/fish
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/nothanksmate/pen/BaVOQOW

## Actual Behavior
When tabbing through the reproduction, after the last element inside the iframe, the focus jumps back to the element before the iframe (i.e. the input inside trap zone). The focus flow stays between the input and the iframe's elements afterwards. Only with a shift+tab, the toggle can be reached.

Important: This bug only exists if the last element of the FocusTrapZone is the iframe.

## Expected Behavior
When tabbing through the reproduction, after the last element inside the iframe, the focus should jump back to the first element of the FocusTrapZone (i.e. the toggle).

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by Sentri** [comment]
Adding to this, it also happens if the *first* element is an iframe.

We are running into this accessibility issue in Power Query. I have also created a repro pen for our issue:
https://codepen.io/sentri/pen/LYgjpbb
You cannot tab to cycle through everything, but shift-tab works.

We tried to solve this by adding "data-is-focusable=true" onto the iframe itself, but it just leads to a different weird behavior:
https://codepen.io/sentri/pen/LYgLdLL
This makes cycling inside the iframe work, but now you cannot access the button outside the frame at all.

Note that this is being raised as a Sev1 accessibility issue for us, so please prioritize accordingly.
