### ISSUE TITLE
[Feature]: Add icon to v9 Link component

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#25879]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

To match visual parity with our Button control, the Link (which can render AS a button) should also have an Icon slot to add an icon before or after the text.

The alternative is that users will take an Icon Button and style it as a link (which we've seen happen)

Example
![image](https://user-images.githubusercontent.com/1434956/205363346-08223747-4c0e-4149-a4d9-16a6f07620f3.png)

### Have you discussed this feature with our team

coastal/red

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by khmakoto** [comment]
Spoke with other members of the team and, specifically, with @micahgodbolt about this. There is very little effort required to achieve this by passing the icon as children to the `Link` component + some small extra styles (3 lines of CSS). An example of this is done in [the following codesandbox](https://codesandbox.io/s/link-with-an-icons-before-and-after-s28t0b?file=/src/App.tsx).

Parity with the `Button` component is not expected since we made that effort in `Button` components because of some extra logic that exists for switching between the regular and filled version of the icons on hover. This requirement does not exist for the `Link` component, so we prefer to not expose additional API for the benefit of not writing these 3 lines of CSS.

Ultimately, if additional feedback or requirements come in we can revisit adding the slot in the future.

All this being said, I'll be closing the issue for now.
