### ISSUE TITLE
Breaking change in `MenuItemProps`

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#25887]
Change was introduced in https://github.com/microsoft/fluentui/pull/24738, After that PR it's no longer possible to reuse the prop type using `Partial<MenuItemProps>` because of the typed event handler. 

In the below repro, simply remove the `onClick` handler to remove the TS error

https://codesandbox.io/s/still-https-kjlbz5?file=/example.tsx

**Comment by bsunderhus** [comment]
## The problem

Just to give my two cents on this topic:

This is not a direct problem on our side, technically the changes provided by #24738 are not breaking changes as they support the same surface API. The problem here is that since we adopted `ARIAButton` types from that PR and forward, we've introduced an `union` of type on the root of the component.

It is a known problem to properly break an union in TS. And using `Partial` (as is the case of the mentioned example) is basically breaking down an union. [Here's an example of this problem in a smaller scale](https://www.typescriptlang.org/play?#code/C4TwDgpgBAGlC8UBQUA+BvAhgfgFxQEYAaKAMwDs8AKTfAZ2ACcBLcgcwEoEA+KANwD2zACYBfFBlpQATCQrUp5AK4BbAEYRGXeL0EjxSQwGMB5BlBC4ACpkbBmmADYAeGLwRR04k2eBQAXrhwHl6GSKRK5Eb2plDAEAxUAB74MFzoSAYA9FlQaowQmADWdFAA7szAABZQNnYOjkjxiSAcTQnAVP4cQA)


## Proposed solutions

1. Let's simply not break unions! And in this case in particular there's absolutely no reason to break `MenuItemProps` with `Partial`, as all it's properties are already optional.
2. Let's not use a union on root (stop using `ARIAButton` type)
