### ISSUE TITLE
[Feature]: Add a Password Field to the Web Componets

### ISSUE THREAD

**Issue by CodeZhangBorui** [microsoft/fluentui#26019]
### Library

Web Components (@fluentui/web-components)

### Describe the feature that you would like added

Add a Text Field that user can input password. The characters inside this field are invisible in default but user can make them visible by keeping pressing down a button.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by eljefe223** [comment]
@CodeZhangBorui to clarify the `fluent-text-field` already supports `type = TextFieldType.Password` you are specifically asking for the added functionality to view the characters inputed to be visible? Because this is already supported.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/37851214/224386009-f5404e8d-d7d3-4ed4-8799-0f9dad8c7b13.png">

https://fluent-components.azurewebsites.net/?path=/docs/components-text-field--text-field
