### ISSUE TITLE
[Bug]: multi-select ComboBox - when some option has focus and component loses focus the option gets selected

### ISSUE THREAD

**Issue by croraf** [microsoft/fluentui#26010]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
@fluentui/react: "~8.103.8"
Browser: Chrome 108, Edge 108
OS: Windows 10, Linux Ubuntu
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox#usage "Controlled multi-select ComboBox"

## Actual Behavior
Check documentation's example "Controlled multi-select ComboBox" (https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox#usage) with "Allow freeform" ON.

1. put focus on an option, for example "option C" (click or tab to the input field, press enter, navigate to "Option C" with arrow keys)
2. press TAB (or alternatively mouse-click away from the ComboBox)
3. observe that the focused option has been toggled (if selected gets unselected, if unselected gets selected)

## Expected Behavior
The option that has focus **must not**  be selected/unselected (that is `onChange` on the `ComboBox` should not trigger) when `ComboBox` loses focus (either because of tab or because of mouse click away)

### Requested priority

Blocking

### Products/sites affected

Microsoft Power BI

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This is caused by the interaction of freeform with the active option and selection. The following behaviors are all present:

- The active option's text is reflected in the Combobox input, so as you arrow down, the text in the input changes.
- With freeform on, the user may enter any text in the input as a valid selection.
- User-typed text is preserved when the Combobox is closed. You can test this by arrowing to e.g. "Option C" and deleting "C", and you will get a new selected option with the text "Option ".
- A user-typed freeform text string is not differentiated from a text string inserted in the input by arrowing to an option.

Based on the above, without drastically changing v8 Combobox behavior, I can't currently think of a way to support freeform entry without also allowing arrowed-to option text to be preserved on blur. In general, I wouldn't recommend using a freeform multiselect Combobox at all, since they've tested very poorly in user studies as an interaction pattern. The Picker component works much better as a multiselect combobox -- I'd recommend switching to that for the multiselect+freeform use case. The v9 Combobox also gets around this problem by not inserting the option text into the input when you arrow.

**Comment by croraf** [comment]
What we basically need is just "Multiselect combobox, without freeform, with automatic dropdown filtering". But that doesn't work OK in neither v8 nor v9. 

Something like this: https://mui.com/material-ui/react-autocomplete/#customized-hook

**Comment by croraf** [comment]
Regarding v9, even though the focused option is not toggled when the user clicks away to close the dropdown it gets toggled when the user tabs away after focusing an option.


https://user-images.githubusercontent.com/19698636/208630207-4d09205d-b718-45e5-b160-ba1fc519fcd5.mp4
