### ISSUE TITLE
[Bug]: Screen Reader faulty working in Rating Component

### ISSUE THREAD

**Issue by akravindran** [microsoft/fluentui#26020]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 11.95 GB / 31.68 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/pen

### Bug Description

The Screen Reader on the star component reads out individual letters when trying to navigate among the different options.

Please provide an isolated reproduction of the issue in a codepen or url:

[Fabric Example Pen (codepen.io)](https://codepen.io/pen)
The issue is reproducible in the default implementation

**Actual behavior:**
When navigating through the stars in the rating component while screen reader is on it reads out incorrectly

**Expected behavior:**
When navigatingthrough the stars, the navigation works appropriately and the screen reader reads appropriate text

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@akravindran the codepen link in the issue is to a blank codepen, it looks like you may have pasted the wrong link into the issue. Could you provide a codepen demonstrating the bug, as well as details on the specific screen reader (e.g. JAWS, NVDA, etc.) and version you're using?

A quick test on our docs site with NVDA, JAWS, and Narrator on Edge shows the v8 Rating control working exactly as I'd expect -- tested on the rating controls under "Usage > Rating" on this page: https://developer.microsoft.com/en-us/fluentui#/controls/web/rating

Just to check, are you sure you're not using Narrator in scan mode and navigating letter-by-letter?

**Comment by akravindran** [comment]
@smhigley I was using the narrator in Scan mode. Thankyou for pointing this out.
