### ISSUE TITLE
[Bug]: PresenceBadge having wrong glyph for Away + OOO

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#26036]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://react.fluentui.dev/?path=/docs/components-badge-presencebadge--default
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-badge-presencebadge--default

## Actual Behavior
OOO takes precedence in determining whether the badge is filled or outlined. In case of status away and OutOfOffice being true, currently the badge is showing badge for away (from color perspective) offline (from icon perspective) OOO (from fill perspective)

<img width="974" alt="image" src="https://user-images.githubusercontent.com/13742664/208470159-90015383-b004-4619-8330-3343b21ec798.png">

## Expected Behavior
OOF icon for Away has the same shape as the default, with only outline

### Requested priority

Blocking

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
I thought this would be an easy fix since it seems like we are just referencing the wrong thing. Actually, what happens is that the correct icons to be used do not exist in `@fluentui/react-icons` yet. I have made a request to create those icons and include them in that package, as well as a request to make this a priority since it is blocking Teams integration.
