### ISSUE TITLE
[Bug]: Selector list argument in `:not()` and `:is()`, CSS pseudo-classes, is not supported

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#26058]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
none
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox

## Actual Behavior
Selector list argument in `:not` and `:is` CSS pseudo-class is not supported.

Example: 

const myStyle= {
      root: {
        border: `1px solid blue`,
        '&:not(:hover, :focus)': {
          borderWidth: '10px'
        }
    },
}

export const SearchBoxExample = () => {
  return (
      <SearchBox
        styles={myStyle}
      />
  );
};

The code above should set a large border on the element when it is neither hovered nor focused.

This doesn't happen.

To achieve this one needs to use multiple pseudo-classes `&:not(:hover):not(:focus)`

## Expected Behavior
'&:not(:hover, :focus)': should work

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Stepping through the code a `:not(.a, .b)` selector will end up in [this branch because of the comma](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/src/styleToClassName.ts#L92). Since this is [not a `:global` selector no further parsing is done](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/src/styleToClassName.ts#L40) and the [selector gets split along its commas](https://github.com/microsoft/fluentui/blob/master/packages/merge-styles/src/styleToClassName.ts#L93-L97) which means we end up with selectors like `:not(.a` and `.b)` which are not valid.

Selector lists are a relatively new feature ([at least for `:not`](https://caniuse.com/css-not-sel-list)) that predate the initial creation of `mergeStyles` which is presumably why there is no support (`mergeStyles` was written before my time on Fluent). That said, I don't see any reason this feature cannot be added.

You indicated you're willing to submit a PR and I'm happy to help you with that process. My email is in my profile so you can reach out directly and I can help you with anything you need.

**Comment by kroudams** [comment]
I assume we could create a function similar to `expandCommaSeparatedGlobals`, from what it seems, as the logic should mostly be the same. 
But I'm afraid I'm not the one to make the decision. 
There are other CSS pseudo-class functions (e.g. `:is()`, `:where()`, :has()`) which also accept a list of values, by the by. They are also should be supported. 
Moreover, there is also a difference between a regular `<selector-list>` and the `<forgiving-selector-list>` which also needs to be considered.
