### ISSUE TITLE
[Bug]: Overflow Tooltip in documentation not focusable

### ISSUE THREAD

**Issue by dinoilic** [microsoft/fluentui#26159]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
Reproducible on FluentUI docs + CodePen
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip

### Bug Description

This is an issue with the current version of Fluent UI documentation pages. It can easily be reproduced if you click "Export to CodePen" on the Tooltip page within the Overflow section

## Actual Behavior
In the documentation tab navigation is not supported within the section on "Overflow tooltip".

## Expected Behavior
The element that the Tooltip is on should be focuseable via keyboard.

Here's the example used in the documentation:

```tsx
{
  /* Example of TooltipOverflowMode.Self */
}
<div className={classNames.example}>
  <Label>Show tooltip when TooltipHost's content overflows</Label>

  <TooltipHost
    overflowMode={TooltipOverflowMode.Self}
    // The TooltipHost itself will overflow
    hostClassName={css(shouldOverflow && classNames.overflow)}
    content={contentSelf}
    onTooltipToggle={setIsParentTooltipVisible}
    styles={hostStyles}
    // In this mode, aria-describedby is automatically added/removed based on tooltip visibility
  >
    This is the TooltipHost area. {contentSelf}
  </TooltipHost>
</div>;
```

However, the example starts working if we wrap the contents in a span and add a `tabindex` of 0 like this:

```tsx
<span tabindex="0">This is the TooltipHost area. {contentSelf}</span>
```

I can of course create a PR to do the fix, but I'm unsure if this is the best way of doing it. This is not super urgent, but it is kind of an accessibility bug as well on the documentation pages.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@dinoilic this is a good description and issue and in the right place, thanks for filing it!

The main problem here is that we should not have made a docs example of a Tooltip on a non-interactive/non-focusable element, since those are de facto inaccessible, and there's no real way to make them accessible. Simply adding `tabindex="0"` to the overflowing region in that example wouldn't work, since it doesn't have the correct semantics or behavior to be a tabbable item.

It is, at its core, an inaccessible design, and my recommendation to a team trying to create something like this would be to generate an actual expand/collapse button on overflow that would show the full text when clicked instead of hiding it in a tooltip.

Maybe a good approach for us and the docs page would be to remove that example, and create one that shows a button with overflowing text + a tooltip. Even that isn't super accessible, but it is at least passable 😅.

Do you have a bug in a product that you would like a11y help with related to this issue?

**Comment by smhigley** [comment]
Also if you're interested in doing a PR to switch from the text region overflow to a button + overflowing content, that would be wonderful!

**Comment by dinoilic** [comment]
Thanks! I understand what you pointed out with `tabindex` and it makes perfect sense. I was just checking if the element not being focusable was the problem 😄

For us in the product, we actually have a link inside the Tooltip component, and we have no problems locally, but as I was helping a teammate debug, I wanted to read up on the docs and saw that the tabbing did not work there.

I can try and do the change myself, could you just point me to any docs on working with the repo/docs? Is it as easy as cloning the repo and starting documentation build/server?

Thanks!

**Comment by dinoilic** [comment]
Hey @smhigley - we do actually think there's a bug with something we found today. You said:

> The main problem here is that we should not have made a docs example of a Tooltip on a non-interactive/non-focusable element

I'm assuming a link would be an interactive element that's focusable here? In that case, if you change the whole line of text in CodePen to be:

```tsx
<a href="https://www.microsoft.com">This is the TooltipHost area. {contentSelf}</a>
```

Instead of just pure text:

```tsx
This is the TooltipHost area. {contentSelf}
```

Then tabbing works, however the focus outline is missing its right border. Likely because it's trying to focus the entire text, some of which is hidden, hence the hidden right border.

Without overflow:
![image](https://user-images.githubusercontent.com/4788533/210809190-0f0bd739-7774-4836-b4f6-c9e6268f4721.png)

With overflow:
![image](https://user-images.githubusercontent.com/4788533/210809241-a489ab03-72ac-4cfc-8a8e-37389f82f4c7.png)

Two questions:
1. I'm assuming a link is a valid, tabbable, interactive element that can be a child of `TooltipHost`
2. Is the behavior from screenshots expected?

The reason why I'm mentioning a link is because we are encountering the same problem in our product, where a link is within `TooltipHost` causing accessibility issues.

Thanks for the help!

**Comment by spmonahan** [comment]
> I can try and do the change myself, could you just point me to any docs on working with the repo/docs? Is it as easy as cloning the repo and starting documentation build/server?

The getting started docs are here: https://github.com/microsoft/fluentui/wiki/Setup

My email is in my profile. If you need any help please ping me.

**Comment by dinoilic** [comment]
Hey @smhigley, let me know if you have any comments on the bug above!

**Comment by smhigley** [comment]
@dinoilic when I wrap the contents of the TooltipHost in a link or button, the tooltip does appear when I focus the link or button, which resolves the initial issue (or at least my understanding of it).

On the weird link focus outline -- that's unrelated to TooltipHost, and just caused by the link being an inline element that is clipped by the overflow styles of its parent. The bounding box of the link is extending past its parent, and clipped by it. That'll be true with or without the tooltip. So, to your questions:
1. Yup! A link is a valid interactive child of TooltipHost, and should give you a keyboard-accessible tooltip
2. That behavior is "expected" in the sense that it's just what happens when a focused interactive item is clipped by its parent's overflow, independent of Tooltip/TooltipHost

**Comment by dinoilic** [comment]
Right thanks @smhigley, then for the first one we can replace it with a link to keep it minimal :)

For the second one - even if this is intended behavior it still looks broken accessibility wise on the docs, perhaps that's something that can be fixed easily as well?

But also, is it clipped by its parent's overflow? In my screenshot it happens in the second example which is "Show tooltip when TooltipHost's content overflows" - or did you mean parent as in the blue box?
