### ISSUE TITLE
[Bug]: Combobox - Multiselect With Value String - User Experience - Screen reader user is not aware of selected items

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluentui#26320]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 12.51 GB / 31.74 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/dnh0tb?file=/example.tsx

### Bug Description

Steps:
1. Screen reader is on (tested with Chrome/NVDA)
2. Navigate to combobox
3. Do selection for couple of items
4. Shift+TAB from combobox
5. TAB again into combobox
6. observe narration

## Actual Behavior
Narration:
Best pets  combo box  collapsed  editable  Select one or more animals  blank

## Expected Behavior
This is more about user experience. 
When user navigate back to the compobox they doesn't know what is already selected.
Of course user can navigate through the list and listen for each item, which is selected or not, but it is not the best experience. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Yup, I agree this example isn't ideal, which is why we took this behavior out of the control by default. The reason this example was included is because this was the behavior in Fluent v8, and I was aiming to demonstrate possible migration paths with minimal initial change.

I can add a text warning to the example itself to say that we strongly recommend using tags, rather than the value string with multiselect combobox.
