### ISSUE TITLE
[Bug]: fluent-horizontal-scroll displays no flippers when combined with @container CSS property

### ISSUE THREAD

**Issue by sarahstandish** [microsoft/fluentui#26389]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/coldwintryday/pen/wvxrjvv

## Actual Behavior
When combining fluent-horizontal-scroll with the @container CSS property, there are no flippers and no way to scroll to the left to see the next card.

## Expected Behavior
In RTL mode, a flipper should appear on the left and allow one to scroll to the left to see the next card.

### Requested priority

High

### Products/sites affected

Edge

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by eljefe223** [comment]
I think we can close this issue. It seems to work fine in the latest fluent package (noticed here you are locked to 2.0.0). Here is a pen showing it working.

https://codepen.io/eljefe223/pen/oNPoMBM

There may be a bug around using calculated units ( `fr`, `vw`, `cqi` ) These seems to work fine when you initially load but if you resize the window the last flipper does not always disappear or the items does not perfectly scroll into view.

I've created an issue tracking that here: #27145 

At any rate this at least proves that much of the issues you are seeing are because of outdated code.
