### ISSUE TITLE
[Bug]: Popover layering overrides v8 Modal layer

### ISSUE THREAD

**Issue by jobutle** [microsoft/fluentui#26386]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (32) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 50.16 GB / 62.81 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/cool-cherry-ufq2og?file=/example.tsx

### Bug Description

When opening a Modal from a v9 Popover, the Modal layer is rendered underneath the the Popover. I would expect the Modal layer to take priority over the Popover. 

Note: this only happens the second time and onward when launching the modal from the popover (in the codesandbox). The first launch works as expected.

## Actual Behavior
v9 Popover component layers over v8 Modal

## Expected Behavior
v8 Modal layer should be over v9 popover

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Both items have the same z-index. The v8 modals use the same fluent-layer-host each time they are loaded (and the layer host stays in the DOM even if empty). 
![image](https://user-images.githubusercontent.com/1434956/214877787-7b555a29-9426-422c-ab4e-8838dcedd9ec.png)


In v9 a fluent provider is the host of the layer, and it is added and removed each time that the layer is removed.

![image](https://user-images.githubusercontent.com/1434956/214878042-e7e96c2a-3c36-44f5-a0c1-c187eb695db0.png)


You can fix this by changing the layerhost of your modal to be the body rather than the fluent-layer-host. We aren't going to change the default behaviors of either of these components as they were not designed to work together.
