### ISSUE TITLE
[Bug]: version.js no longer updated in v8 packages.

### ISSUE THREAD

**Issue by brandonthomas** [microsoft/fluentui#26526]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
N/A not a browser issue
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://unpkg.com/@fluentui/style-utilities@8.8.5/lib-commonjs/version.js

## Actual Behavior
Version is set to 0.0.0 in recent FluentUIReact v8 packages.

## Expected Behavior
Version reflects the actual version of the package and is returned correctly when running __packages__ in console.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
The problem is indeed there, looks like an issue is intermittent:
- 8.8.5 https://cdn.jsdelivr.net/npm/@fluentui/style-utilities@8.8.5/lib-commonjs/version.js ❌ 
- 8.6.0 https://cdn.jsdelivr.net/npm/@fluentui/style-utilities@8.6.0/lib-commonjs/version.js ✅
- 8.7.7 https://cdn.jsdelivr.net/npm/@fluentui/style-utilities@8.7.7/lib-commonjs/version.js ✅ 
- 8.7.12 https://cdn.jsdelivr.net/npm/@fluentui/style-utilities@8.7.12/lib-commonjs/version.js ✅ 
- 8.9.0 https://cdn.jsdelivr.net/npm/@fluentui/style-utilities@8.9.0/lib-commonjs/version.js ❌

**Comment by Hotell** [comment]
with next release of any v8 package, `setVersion` will work correctly again. cheers
