### ISSUE TITLE
Build should detect and report failures in storybook publishing

### ISSUE THREAD

**Issue by GeoffCoxMSFT** [microsoft/fluentui#26568]
Recently, the chromatic publishing to aka.ms/fluentui-storybook and react.fluentui.dev have been silently failing. The latter is on 9.11.1 while npm shows react-components at 9.12.0.  

The build should error or warn when chromatic publishing fails so that build shield can respond.

**Comment by GeoffCoxMSFT** [comment]
@Hotell - Assigning to you for v-build team planning.

**Comment by Hotell** [comment]
Regarding docsite publish:

1. It will happen automatically on merged PR from master if `packages/react-components/react-components/package.json` is changed. The pipeline can be tracked in the [Actions panel](https://github.com/microsoft/fluentui/actions/workflows/docsite-publish-ghpages.yml)

With that there is no mechanism to report that pipeline and block, because it's on master (default branch)

2. We can block it on PR though!

The thing is that with our current task orchestration we don't run storybook builds on PR if affected. 

We run only `build` npm scripts within affected dependency tree. In case of public-docsite-v9, that runs only naively `just-scripts` that compiles typescript files within the app ( which has very little to do with actual making sure that docsite will work).

**The solution:** revamp scripts definition within our `apps/` so it catches appropriate issues.

**Comment by Hotell** [comment]
hmm so we actually run `build-storybook` with every PR, thus if `public-docsite-v9` is affected we execute `build-storybook` and if there are any failures you won't be able to merge.

Of course the known problem is if your branch is very old and not up to date, it might happen that your PR will end up creating race condition which will be exposed on master when deploy will be triggered. ATM we don't have anything to mitigate this beyond github merge queues that are not an option for us ATM.

Based on provided reasoning I'm gonna close.
