### ISSUE TITLE
[Bug]: The initial value of Combobox / Dropdown is not rendered

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#26759]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components v9.14.0

Using Code Sandbox
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/combobox-and-dropdown-empty-value-edition-ztww3y?file=/example.tsx

## Actual Behavior
Open the Code Sandbox sample and do nothing else.
![image](https://user-images.githubusercontent.com/50703224/217540174-f0c16155-ae13-4d75-bbda-7f7e1783a434.png)

## Expected Behavior
Downgrade @fluentui/react-components to v9.13.0
![image](https://user-images.githubusercontent.com/50703224/217540028-ca09fb0a-2a38-48f1-bb5f-c68fd6a9f5da.png)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
The core issue here is that Options are not rendered when the combobox is collapsed, so there is no way to know that an Option with the value e.g. "Workspace-GUID-3" actually has the text "Workspace 3" until the combobox opens.

The reason this appeared to work before is because we had a bug where we directly displayed the value text in `selectedOptions` as the Combobox display value (so would have shown "Workspace-GUID-3" instead of "Workspace 3", even when open).

Because of this, when using `defaultSelectedOptions` or `selectedOptions`, `defaultValue` and `value` should also be used to set the display value independent of the rendered options.

**Comment by chenxinyanc** [comment]
> when using `defaultSelectedOptions` or `selectedOptions`, `defaultValue` and `value` should also be used to set the display value independent of the rendered options

So it seems I should use `value` instead of `selectedOptions` if I want to show user a single-selection dropdown box. `selectedOptions` only affects which items are "checked"; is that correct? I think I must have got it wrong...

**Comment by dankocrnkovic** [comment]
Its a mess with dropdown and Value vs Text... 
There is a ticket that is marked as fixed. but nothing was resolved
#24937 
I dont understand how it can be usable in this state.

**Comment by chenxinyanc** [comment]
Frankly speaking I'd suggest to make the `Dropdown` API more intuitive. As I've mentioned it already in https://github.com/microsoft/fluentui/issues/24937#issuecomment-1298322203

> It's unusual for users to see a dropdown option that has different appearances when in dropdown list and in dropdown field (as selected item)

Currently we are forced to set both `value` (controls what displays in the dropdown) and `selectedOptions` (controls what items are "checked" in the dropdown list). This is rather inconvenient.

**Comment by kidlj** [comment]
Why do you need to set `value` when `selectedOptions` is set? This is anti-pattern.
