### ISSUE TITLE
[Bug]: Focus escapes from Dialog

### ISSUE THREAD

**Issue by zjhch123** [microsoft/fluentui#26822]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
    Memory: 5.24 GB / 31.72 GB
  Browsers:
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/upbeat-bohr-2krd8q?file=/example.tsx

### Bug Description

Related to #26771 

Hi @micahgodbolt, we are thinking it should not be "By design" since the document said：

<img width="807" alt="image" src="https://user-images.githubusercontent.com/12215513/218426935-73c83aa4-7ca7-42ba-8794-c3d757c6348d.png">

And also the a11y document:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/12215513/218427012-9fba1294-0a05-48a3-a314-9dd1eab34301.png">

Any suggestion?

## Actual Behavior

When I use the keyboard (`Tab`) to control the focus, I find that the focus can escape from the Dialog.

See the gif here:

![focus](https://user-images.githubusercontent.com/12215513/217760725-5a6c1be0-91e6-4bda-ad1f-f7f071dbdb56.gif)

(I'm not sure if it is an a11y bug)

## Expected Behavior

The focus should be restricted to the Dialog and could not escape from Dialog, just like the behavior in v8.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by micahgodbolt** [comment]
Alright. We need to figure out our messaging here. I was told this was intentional, but our docs are conflicting. I'll get a final answer.

**Comment by bsunderhus** [comment]
So. This is not an issue per se, it's expected behaviour @zjhch123.

You can notice that when you tab after the last focusable element the focus goes to outside of the current page and back to the browser navigation interface. This is to ensure navigability from the users perspective as trapping the user inside of a Dialog forever is considered a bad behaviour! You can notice that the native `<dialog>` component does the same! https://codesandbox.io/s/competent-tristan-puukey?file=/src/App.tsx


We implemented this way to raise awareness and try to force our way out of the API provided on v8, since this is a more user friendly experience. That being said since we do want to support v8 API somehow I'll see to open an issue to add a property to opt-out of this behaviour to the classic focus trapping!
