### ISSUE TITLE
Components that use `react-positioning` should have vertical overflow set to auto

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#26875]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
any
```

### Are you reporting Accessibility issue?

None

### Reproduction

v9 storybook

## Actual Behavior
Even with autoSize, Menu items overflow from MenuPopover

## Expected Behavior
By default or when autosize is used popover should have vertical overflow set to auto

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This problem is not isolated to `Menu` but rather all positioned components that use autosize

**Comment by ling1726** [comment]
Either we:
1. apply overflow inline for all positioned elements like in #26868
2. apply overflow for each component that supports positioning like in #26922

Option 1 is better except for when users want to use autoSize but _**don't want overflow**_. It's a bit of a strange use case, but IMO acceptable since parsing positioning options and maintaining styles for every component that needs it can be super awkward and would depend on the component architecture how to even propagate the configuration.
