### ISSUE TITLE
[Bug]: Accessibility Issue -Split button 

### ISSUE THREAD

**Issue by ChithiraMG** [microsoft/fluentui#26883]
### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 3.55 GB / 15.78 GB
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

Run fastpass in Acceessibility Insights for web (chrome extension) for split button in fluent ui

## Actual Behavior
Fluent ui image
![image](https://user-images.githubusercontent.com/101738825/219538971-1019a133-96ea-4210-b07d-dd2d4bb80fdc.png)

AT: Accessibility Insights for web -->Fastpass
![image](https://user-images.githubusercontent.com/101738825/219542167-68d211fc-7923-4071-a7e4-f09c61a68b82.png)

Not able to remove negative tab index from split button menuProps items
### Requested priority

Blocking

### Products/sites affected

Fluent ui - buttons

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This is an intentional design decision that stems from the original decision to make a "splitbutton" a single tab stop. Because there is no "splitbutton" control on the web, it is effectively a button pretending to be two buttons, and that creates some hard-to-resolve accessibility issues.

Since we can't really change this to be two tab stops without it being a breaking change, the best workaround we have found is the current one. We've tested it in all common screen readers (NVDA, JAWS, Narrator, VoiceOver, Talkback) and done our best to mitigate any practical issues. The automated Accessibility Insights error is a side effect of all of this. It's not a good idea to try to hack the control to "fix" the automated error, because that is likely to degrade the real-world accessibility.

More specific info in: https://github.com/microsoft/fluentui/pull/18697#discussion_r662652772 and https://github.com/microsoft/fluentui/issues/18484#issuecomment-861723118

This is fully fixed in the Fluent v9 splitbutton, where we do actually make it have two separate tab/arrow stops.
