### ISSUE TITLE
[Bug]: Popover onOpenChange not triggered for controlled popover trigger

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/fluentui#26953]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz  
    Memory: 16.33 GB / 31.90 GB
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.50)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/competent-danilo-h1i2r8?file=/example.tsx

## Actual Behavior
`onOpenChange` callback in not triggered when using custom trigger outside of `Popover` and when Popover `open` state is `true`.
Steps to repro:
1. Add a button to control the open state of a popover
2. Add console.log(data.open) in the `OnOpenChange`
3. Click on the button multiple times
4. Observe that only `false` statements are printed out in console.

## Expected Behavior
`OnOpenChange` should be triggered regardless the `open` state is true or false.

### Requested priority

Blocking

### Products/sites affected

Microsoft Viva

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Thanks for reporting the issue and providing a sandbox.

Since you do not use a `PopoverTrigger` there is nothing within the popover that would ever invoke `onOpenChange`. However, there are still events where you might want to close the popover like clicking outside. When you click on your trigger button in the repro `onOpenChange` is invoked because the button is outside of the popover.
