### ISSUE TITLE
[Bug]: Cannot tab list when columnActionsMode is disabled and selectionMode is none

### ISSUE THREAD

**Issue by jcksonhe** [microsoft/fluentui#27026]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 29.79 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/jcksonhe/pen/XWPMRBO

## Actual Behavior
As of @fluentui/react@8.105.10, DetailsList with `columnActionsMode` set to disabled and `selectionMode` set as none cannot have its rows tabbed by keyboard. In the codepen, if we change to @fluentui/react@8.105.9, the rows can be tabbed again. On investigation, I found that the first row does not have `tabIndex: 0` set on the first row anymore.

## Expected Behavior
DetailList rows should be tabable like in @fluentui/react@8.105.9 with a tabIndex of 0 on the first row.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
We had to revert this change that enabled this behavior in #26896

It is reimplemented by #27002 but that requires you use 8.107.4 or later. I have a Codepen example that demonstrates how to opt in to the behavior here: https://codepen.io/seanms/pen/NWERvjq?editors=0010

---

You can see this behavior first appears in 8.99.2 when the early `List` render was added. It works up until 8.105.10 when the behavior was reverted because it was breaking downstream users of `List` and we could not see a way to fix the broken components and maintain the early render behavior. The early render behavior was re-implemented in 8.107.4 but behind a flag so users that need it can opt in to the new (and arguably better) behavior when needed.
