### ISSUE TITLE
[Feature]: Add contentBefore and contentAfter to Textarea

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#27039]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

To match the Input component, we need to add contentBefore and contentAfter to Textarea

### Additional context

In Input, the before/after are placed horizontally. We need to decide if we'd do the same for Textarea, or do them above/below since the component is more of a vertical component.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ling1726** [comment]
Are these slots really necessary? what is wrong with

```tsx
<div>
  <Toolbar />
  <TextArea />
  <Toolbar />
</div>
```

The addition of these slots don't really add any a11y or functional support and is just some extra styles that aren't very complicated.
 
Using Teams as an example since it has that exact layout in the screenshot of #27104... it would not be useful, because a toolbar like that would use a WYSIWYG editor that isn't a semantic `textarea` element

**Comment by micahgodbolt** [comment]
the primary difference was the buttons above the focus line (not below). This is doable with children render function, so I don't think we need this right now.
