### ISSUE TITLE
Custom style hooks adds object with properties that can't be minified by Terser

### ISSUE THREAD

**Issue by ling1726** [microsoft/fluentui#27139]
Currently custom style hooks adds ~3KB bundle size to each component that uses it, **and will only increase with each added component**

The bundle size increase comes from the single object in context that can't be minified https://github.com/microsoft/fluentui/blob/67a8ba872ba6244c9d64722e909e74949adc4e78/packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts#L95-L176

The PRs to introduce this feature to components will confirm the bundle size increase:
 * https://github.com/microsoft/fluentui/pull/27080#issuecomment-1454837779
 * https://github.com/microsoft/fluentui/pull/27075#issuecomment-1454833177
 * https://github.com/microsoft/fluentui/pull/27076#issuecomment-1454834118
 * https://github.com/microsoft/fluentui/pull/27077#issue-1609885944

**Comment by ling1726** [comment]
We could potentially use a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy?retiredLocale=de) to mitigate this

**Comment by layershifter** [comment]
Note, this happens because of this default value:

https://github.com/microsoft/fluentui/blob/67a8ba872ba6244c9d64722e909e74949adc4e78/packages/react-components/react-shared-contexts/src/CustomStyleHooksContext/CustomStyleHooksContext.ts#L95-L176

It has zero value for customers as it just returns a noop function. Usage of a Proxy or some other patterns can decrease footprint caused by that hook.
