### ISSUE TITLE
[Bug]: Disabled button frozen tooltip 

### ISSUE THREAD

**Issue by niagrawal-microsoft** [microsoft/fluentui#27211]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
npx: installed 1 in 9.222s

  System:
    OS: Windows 10 10.0.22621
    CPU: (40) x64 Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz
    Memory: 45.19 GB / 63.71 GB
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (109.0.1518.78)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/niagrawal-microsoft/details/ExeLamb

## Actual Behavior

We have two buttons adjacently placed and there is scenario where one button is disabled. 

When the user hovers over disabled button and then to enabled button, the tooltip points to wrong button. I have reproduce the issue in sandbox: https://codepen.io/niagrawal-microsoft/details/ExeLamb
 
 In the below screenshot, my mouse was above highlighted area. 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/112335211/225213451-98dc7eda-04e9-43fa-a876-e1918fc8090f.png">

## Expected Behavior
The tooltip position should be correct and should always be present above hovered button. 

### Requested priority

Blocking

### Products/sites affected

power pages/ power portals

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
It looks like this is due to the way that Chrome/Edge handle mouse events for disabled elements. The mouse leave event isn't getting fired on the disabled button, so its tooltip doesn't know it should go away.

It actually looks like this behavior might be getting fixed soon(?) in Chrome/Edge: https://chromestatus.com/feature/6128674512830464

--

Unrelated to the bug itself: adding tooltips to disabled controls is not recommended. It makes it so keyboard users can't see the tooltip text because they can't focus on the disabled element. You could try using a FluentUI button with `allowDisabledFocus` instead. That also works around this issue.
