### ISSUE TITLE
[Bug]: Overflow vertical doesn't work

### ISSUE THREAD

**Issue by maralihart** [microsoft/fluentui#27249]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 14.01 GB / 31.85 GB
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.69)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/pedantic-ride-deccr2?file=/example.tsx

## Actual Behavior
Cell squish to the appropriate height, but no overflow happens

## Expected Behavior
The cells should stay the same height and there should be an overflow menu popping up

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
@maralihart  the reason it's not working for you is because the button items are shrinking which is caused by the flex layout. You can do one of the two:
* use flex-shrink on the overflow items https://codesandbox.io/s/festive-tdd-x0e470?file=/example.tsx
* stop using flex layout: https://codesandbox.io/s/determined-glade-r9jsdt?file=/example.tsx:423-464
