### ISSUE TITLE
[Bug]: DialogTrigger inside a menu on a MenuItem is not showing the Dialog

### ISSUE THREAD

**Issue by Beaker73** [microsoft/fluentui#27252]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22624
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 4.47 GB / 15.92 GB
  Browsers:
    Edge: Spartan (44.22621.1391.0), Chromium (111.0.1661.43)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/sad-cache-znkzwj?file=/index.js

## Actual Behavior
The menu closes and no dialog is shown

## Expected Behavior
The dialog will be shown.

#Possible cause
It think triggering the menu item closes the menu. In effect tearing down the component hosting the dialog.
Would it actual be possible to show a dialog without closing the menu?

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ozluy** [comment]
I think current behavior make sense as `Dialog` is child of `MenuPopover` and when you click Settings  button `MenuPopover` is unmounted as Dialog is child of it, it unmounts along with it.

![Screenshot 2023-03-20 at 23 04 11](https://user-images.githubusercontent.com/2522722/226476030-588573d8-a54b-4273-981c-70cc78aeaf2c.png)

**Comment by ling1726** [comment]
This is caused by the unoumting of the `MenuPopover` when a `MenuItem`  is invoked. This is intentional and you have two options here:

* Use the `persistOnClick` prop so that the menu stays open once the Dialog is opened https://codesandbox.io/s/confident-sunset-xfjpmt?file=/index.js
* Control the Dialog with state if the menu _should_ be closed once the Dialog is opened. The Dialog tries to focus on the trigger once it is closed, but this won't be possible if the menu is closed, so the controlling is also necessary to make sure the scenario is still accessible. https://codesandbox.io/s/quirky-rain-ze0qrz?file=/index.js
