### ISSUE TITLE
[Bug]: VoiceOver - Dropdown component not announcing label of Dropdown when there is a selectedKey.

### ISSUE THREAD

**Issue by UniqueClone** [microsoft/fluentui#27309]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1
    Memory: 56.93 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Firefox: 105.0.1
    Safari: 16.3
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown

## Actual Behavior
Announce Dropdown label and then selected key when using VoiceOver on macOS.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23245211/227239985-f9d2ac44-e618-44dd-b1a0-fd757df7a691.png">

## Expected Behavior
Announcing selected key when using VoiceOver on macOS.

### Requested priority

Low

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @UniqueClone, can you double-check what you wrote for "Actual Behavior" vs. "Expected Behavior" it seems the opposite of the issue title. Is the issue that the Dropdown's label is NOT being read by VoiceOver, but you expect it to be read?

Could you take a look at this @smhigley? I don't have easy access to a Mac to investigate.
