### ISSUE TITLE
[Bug]: Enable legacyTrapFocus to false in Popover behavior differently after 9.16.0

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/fluentui#27447]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 6.63 GB / 15.60 GB
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/wonderful-drake-ektp2v?file=/example.tsx

## Actual Behavior
In [newer version codesandbox](https://codesandbox.io/s/wonderful-drake-ektp2v?file=/example.tsx), note that setting `legacyTrapFocus` to false would not allow users to opt-out legacy trap focus behaviour. This prop is deprecated  since 9.16.0. 

## Expected Behavior
Enabling the `legacyTrapFocus` setting to false provides users with the option to disable the legacy trap focus behavior regarding any minor version update.

Our team is developing a component library with Fluent UI as its peer dependencies, currently ranging from version 9.7.0 to 10.0.0. However, the recent 9.16.0 update introduced a change that necessitates updating our peer dependencies to versions 9.16.0 to 10.0.0. This presents a challenge as some of our consumers are not yet prepared to upgrade from version 9.7.0 to 9.16.0, and resolving this issue is complicated by the fact that `inertTrapFocus` is not available until version 9.16.0.

[Sandbox link for v9.18.6](https://codesandbox.io/s/wonderful-drake-ektp2v?file=/example.tsx)
[Sandbox link for v9.15.6](https://codesandbox.io/s/serene-leaf-lqedrz?file=/example.tsx)

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by miroslavstastny** [comment]
@ling1726 could you please check this one?

**Comment by ling1726** [comment]
yeah I see the problem, completely disabling `legacyTrapFocus` (i.e. the prop does nothing) is technically a breaking change even if we introduced the new `inertTrapFocus` prop.

@bsunderhus  can you take a look at this since you made the original changes to introduce `inertTrapFocus`, the fix should just involve respecting the `legacyTrapFocus` flag again, it should probably lose to `inertTrapFocus` if both are used.

**Comment by bsunderhus** [comment]
I'll be looking into this now @shaohaolin.

> yeah I see the problem, completely disabling legacyTrapFocus (i.e. the prop does nothing) is technically a breaking change even if we introduced the new inertTrapFocus prop.

If this is the case @ling1726, perhaps it would be better for us to rollback the introduction of `inertTrapFocus` and deprecation of `legacyTrapFocus`? And instead just invert the default boolean value of `legacyTrapFocus` from `false` to `true`?

**Comment by shaohaolin** [comment]
@bsunderhus  Thank you.

From a consumer perspective, how does rollback work? Does it imply that versions v9.16.0 - v9.18.6 (the versions affected by the rollback) will no longer be available for installation after the rollback has been implemented?

**Comment by bsunderhus** [comment]
The version affected by this bug will remain be available @shaohaolin.

The idea of the rollback here would be considering future versions. Since the new property `inertTrapFocus` is not widely spread, a changelog clarifying why it should be discontinued could be emitted in favor of keeping `legacyTrapFocus` as the main property for this behaviour, but this should go under discussion as it would, in theory, be a breaking change. I'll keep you posted in the decisions on this through here!

In the meantime a PR to solve this bug of the behaviour of `legacyTrapFocus` has already been created https://github.com/microsoft/fluentui/pull/27574

**Comment by bsunderhus** [comment]
PR has been merged! I'll open up another issue to follow up on the possibility of a rollback @shaohaolin!

**Comment by shaohaolin** [comment]
@bsunderhus Looks like the 9.19.1 releases included the bug fix. Would you mind sharing the issue about the follow up on the possibility of a rollback in case we decide to upgrade to Fluent UI 9.19.1? It would be helpful to have a clear understanding of the rollback process as we plan for the upgrade.

**Comment by bsunderhus** [comment]
We'll end up keeping both properties @shaohaolin, just to avoid any breaking change on this matter. So from 9.19.1 and forward both properties are valid and should work, and the priority goes to `inertTrapFocus`
