### ISSUE TITLE
[Bug]: Classname for DetailsList column applied to the incorrect index

### ISSUE THREAD

**Issue by spellegrino021** [microsoft/fluentui#27535]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
    Memory: 32.60 GB / 63.93 GB
  Browsers:
    Chrome: 112.0.5615.49
    Edge: Spartan (44.22621.1250.0), Chromium (109.0.1518.70), ChromiumDev (114.0.1788.0)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

it is able to be reproduced on https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns -- I tried applying a class to items with index < 10 and it applies it to items with index 1-10 and skips item with index 0

## Actual Behavior
We want to apply classNames to specific columns by index in a DetailsList to show the dirty state/a new item has been added to the list. When we do this however it does not apply to the correct index. It does not apply to index 0 and when provided with a non-zero index it will apply the classname to the index  + 1 (so in the list, the item below the item it should apply to).

This is from testing in Fluent UI only:
I tried to apply the classname to all index < 10 and it applies it to index 1-10.
![image](https://user-images.githubusercontent.com/35281019/231607725-c4d8d117-8e92-4c18-9d35-419667fbaa33.png)

Here it is on the portal being applied to the item below the item it should be applied to:
![image](https://user-images.githubusercontent.com/35281019/231608026-7985d1fd-0bfd-44be-a416-427000cb5f84.png)

## Expected Behavior
This is how it should look:
![image](https://user-images.githubusercontent.com/35281019/231607954-d7f8ad3d-df34-465e-8970-f9ecd2057365.png)

It seems like the indexing is no longer starting at zero or is one off of what it should be. This is confusing for our customers since the dirty state is showing on the wrong items.

Seems like it reproing on rc.portal.azure..com with version 11.153.0.1 but not reproing in portal.azure.com with version 11.143.2.1. Both have the same websites extension version that includes our fluent UI update. This appeared after updating our Fluent UI version to 8.107.1.

### Logs

```shell
I attached screenshots
```

### Requested priority

High

### Products/sites affected

portal.azure.com, ms.portal.azure.com

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spellegrino021** [comment]
Hi! Not sure who is monitoring this but wanted to see if there was an update on timeline for this.

**Comment by spmonahan** [comment]
Sounds like this might be a regression. You said you noticed this when you updated to Fluent 8.97.2. What version were you on prior to that? Knowing the version range can help me pinpoint any PRs that may have introduced the issue.

**Comment by spellegrino021** [comment]
We moved from 8.34.1 to 8.107.1

**Comment by spellegrino021** [comment]
Any more updates on this?

**Comment by spmonahan** [comment]
Hey @spellegrino021, I dug into this yesterday and identified [the commit that change the render order of `DetailsRowFields`](https://github.com/microsoft/fluentui/pull/22081/files#diff-1483d3f3b3783ce7a3f282738637952111be1c399c6d1829efec30328dbfa8af).

The reason this bug appeared is because the column render override was moved to render after the parent, previously it had rendered before the parent. Because your example modifies the parent props by setting the classname on `column` this prop change would not be visible for the first item to which it was applied because the parent in that render pass had already been rendered. The classname change is applied to subsequent renders which is why the classnames appear to be off by one. Subsequent renders will pick up the prop and render correctly.

This can be observed by toggling the first row in [this example](https://codepen.io/seanms/pen/qBJgeyZ). If you toggle the row to selected, then back to unselected you'll trigger a React render which will draw the correct style for the first row.

In finding that and examining your repro example I think you should change your styling approach. I see two issues with your current approach:

1. You're relying on an implementation detail (i.e., the internal rendering order of DetailsList/Row/Fields) that is not specified in the API contract.
2. You're modifying parent component props when rendering the child. This is the bigger issue and why I think you should change your approach.

While modifying parent props, as in your example, is not strictly disallowed in React it is an anti-pattern. Props and state are meant to flow down through the React tree and pushing a change up like in this example can cause issues, particularly if the change happens during the render call. If this prop modification were using a React API an error would be triggered as it has the potential to create an infinite render loop. Obviously an infinite loop is not being created here but I still feel React is being misused and, critically, we can implement your feature in a better way.

Fortunately there is an approach that should address both these issues. By customizing the row rather than the column you can use Fluent v8's `styles` API and directly style the parent component. Based on your repro I put together an example to demonstrate how to do this: https://codepen.io/seanms/pen/ExdrzWZ

Let me know if this approach works for you. Happy to help with any code changes you need to make.

**Comment by spmonahan** [comment]
Alternatively, this can be implemented with `onRenderField`: https://codepen.io/seanms/pen/oNaVvvW
