### ISSUE TITLE
Combobox does not open options with VoiceOver command when allowFreeForm prop is set to true.

### ISSUE THREAD

**Issue by UniqueClone** [microsoft/fluentui#27813]
### Environment Information

- **Package version(s)**: 8.109.3
- **Browser and OS versions**: macOS Ventura, Microsoft Edge 112.0.1722.68

### Describe the issue:

When the allowFreeForm prop is set to true, voiceover won't open the options pressing the ctrl + option + space combination. this is quite misleading because the voice over is telling the user to press that set of keys but it won't open anything.

#### Actual behavior:

When the allowFreeForm prop is set to true, voiceover is not opening the menu if the combination of ctrl + option + space is pressed.

#### Expected behavior:

When the allowFreeForm prop is set to true, voiceover should open the menu if the combination of ctrl + option + space is pressed.

### If applicable, please provide a codepen repro:

https://developer.microsoft.com/en-us/fluentui#/controls/web/combobox

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? 
Yes, but only with support ramping up on codebase.

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)
High because it makes the component unusable in MacOS if the allowFreeform prop is set to true

**Comment by smhigley** [comment]
This is a widespread issue with VoiceOver not fully supporting custom/ARIA widgets, and can be seen on the APG editable combobox examples as well. Web authors have no control over this, since the custom VO commands are not exposed to the page in any way.

VoiceOver users can either use non-VO commands, or use the button immediately following the input to open the combobox.
