### ISSUE TITLE
[Bug]: Loop file icon break in some scale. 

### ISSUE THREAD

**Issue by tiaxu1** [microsoft/fluentui#27839]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz
    Memory: 27.39 GB / 63.80 GB
  Browsers:
    Chrome: 113.0.5672.93
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20221015.001/assets/item-types/64_1.5x/loop.svg

## Actual Behavior
The loop file icon breaks in some scale. Currently we notice for 125% and 150% it may break. The link for loop file icon is 150% is https://spoppe-b.azureedge.net/files/fabric-cdn-prod_20221015.001/assets/item-types/64_1.5x/loop.svg
We think this link fails for some reason.
![image](https://github.com/microsoft/fluentui/assets/133458968/bf95d22f-8beb-4b7e-923b-26755bbe8962)

## Expected Behavior
![image](https://github.com/microsoft/fluentui/assets/133458968/2b9b07fa-c99f-46a5-bbd3-367257292a13)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bigbadcapers** [comment]
This issue is resolved by https://github.com/microsoft/fluentui/pull/27779

Watch for a new package version announcement added at the top of this changelog, which will indicate when you can update to the latest version of the react-file-type-icons package which will render loop icons at 64 svg 2x correctly.
https://github.com/microsoft/fluentui/blob/7.0/packages/file-type-icons/CHANGELOG.md

Please note in the future we will reduce the ramp sizes for file type icons, including removing 64 and 72 where they might still exist. Integrations that need to place a filetype icon in an img frame that is larger than 48x48 are recommended to use the 96 sized asset and scaling it. For lower sizes, we can't scale because of blurriness but at larger sizes it works well.

**Comment by bigbadcapers** [comment]
Note that fluent is now updated, please update the package as seen here and .loop and .fluid files will now render at 64 and use the latest design from the team

https://github.com/microsoft/fluentui/pull/27779#issuecomment-1563946845
