### ISSUE TITLE
[Bug]: useComboboxBaseState doesn't ignore defaultValue changes and uses useMemo for dependency management

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#27853]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 36.38 GB / 62.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Firefox: 104.0
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/exciting-hodgkin-qyl6fj?file=/example.tsx

Steps:

1. Select any option.
2. Press any of the buttons that doesn't match the option you selected.
3. Value from the combobox should have been cleared.

## Actual Behavior
When selecting an option and then clicking one of the buttons that changes the defaultValue clears the value of the combobox.

## Expected Behavior
Changes to defaultValue should be ignored.

## Related
- #27836, specifically https://github.com/microsoft/fluentui/pull/27836#discussion_r1192789249

### Requested priority

High

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Here's a potential update to how the value is tracked in `useComboboxBaseState`. Have it be updated whenever the selection is changed, rather than using useMemo to calculate it on demand.

Based on some offline conversations, this is likely incomplete: for example, you'd also need to have a way to reset to the last selected value when the ComboBox is blurred. Possibly by having another state variable `valueFromSelection`, and updating it in the `onOptionSelect` callback as well. Then when the ComboBox is blurred, you can reset it to valueFromSelection if needed.

This is also completely untested and is meant to show the idea rather than be final code.

```ts
  const onOptionSelect = useEventCallback(
    mergeCallbacks(props.onOptionSelect, (_, data) => {
      const selectedOptionsText = getOptionsMatchingValue(optionValue => {
        return selectedOptions.includes(optionValue);
      }).map(option => option.text);

      if (multiselect) {
        // editable inputs should not display multiple selected options in the input as text
        setValue(editable ? '' : selectedOptionsText.join(', '));
      } else {
        setValue(selectedOptionsText[0]);
      }
    }),
  );

  const selectionState = useSelection({ ...props, onOptionSelect });
  const { selectedOptions } = selectionState;

  const [value, setValue] = useControllableState({
    state: props.value,
    defaultState: props.defaultValue,
    initialState: undefined,
  });

  // ...call to useMemo removed...
```
