### ISSUE TITLE
[Bug]: @fluentui/react-icons is missing Subtract sizes 12, 16 and 20

### ISSUE THREAD

**Issue by elav000** [microsoft/fluentui#27923]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 66.36 MB / 64.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 16.4
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://064xel.csb.app/

## Actual Behavior
Subtract icon does not render. It looks like it is missing in the currently published packages.

![image](https://github.com/microsoft/fluentui/assets/12959403/747600b3-bbeb-4e5e-bf6b-d8ae477cf2b3)

From the sandbox:
![image](https://github.com/microsoft/fluentui/assets/12959403/597463ce-f565-4b84-a46f-6d9771cdb547)

## Expected Behavior
Subtract icons for sizes less than 24 should render.

### Requested priority

High

### Products/sites affected

microsoft365.com

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by layershifter** [comment]
The problem is in place at least for the latest `@fluentui/react-icons@2.0.202`:

- Open https://cdn.jsdelivr.net/npm/@fluentui/react-icons@2.0.202/lib/sizedIcons/chunk-11.js
- Search for `'Substract`
- Notice empty glyphs

<img width="1624" alt="image" src="https://github.com/microsoft/fluentui/assets/14183168/cd96f4f9-9be7-4b0c-a18f-483544cb8705">

**Comment by elav000** [comment]
Thank you!
