### ISSUE TITLE
[Bug]: Accessibility: SearchBox: Narrator announced random text on SearchBox text cleared

### ISSUE THREAD

**Issue by bradhugh** [microsoft/fluentui#27938]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 10.03 GB / 31.73 GB
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50), ChromiumDev (115.0.1851.0)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox

## Actual Behavior
When using Narrator with Edge using the SearchBox control. You can reproduce this with the "Default SearchBox" on the fluent-ui demo app at https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox

1. Run Narrator
2. Enter some text in the search box and hit enter to search
3. Navigate to the "Clear text" button on the SearchBox and execute it
4. Narrator reads: "Search Search Box Code"
The word "Code" here is random and completely unexpected. There doesn't appear to be anything in the markup that refers to "Code".  In my application, Narrator reads "Search Search Box Test" instead of "Code", but whether "Code" or "Test", both of these are unexpected.

## Expected Behavior
Narrator should read: "Search Search Box" and not say the random word "Code" or any other random word.

### Requested priority

Blocking

### Products/sites affected

https://testconnectivity.microsoft.com/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
I'm going to guess that your SearchBox, like the one on the Fluent docs site, does not have a visible label. It appears that Narrator is using its own heuristics to look for the label in the text immediately prior to the input. In our docs site, that is "Show code" (with only "code" getting used), and in your site, it's probably something ending in "test". If you change the text preceding the SearchBox input, the Narrator announcement also changes.

This can be fixed by adding a visually hidden label immediately preceding the input, or doing nothing and just accepting it as a Narrator quirk. I'd actually recommend the latter -- I just tested with NVDA, JAWS, and VoiceOver, and none of them show any bugs with the input. Narrator has very low usage and it's not a severe bug, so I'd lean towards closing the issue vs. implementing a hacky fix that would have other side effects.

**Comment by bradhugh** [comment]
Thank you @smhigley! - This makes sense. I wasn't able to interpret what narrator thought it was doing at all. I'll give this a try and see if it can be reasonably worked around.
