### ISSUE TITLE
[Bug]: Go to today doesn't work for year picker

### ISSUE THREAD

**Issue by danavishnukb** [microsoft/fluentui#27932]
### Library

React v8 (@fluentui/react)

### System Info

```shell
NA
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/Danavishnu_kb/pen/vYVaaQa

## Actual Behavior
Goto Today option is not working for year picker.

Go to year picker, navigate to 1970 and then select goto today. The component gets stuck in year picker.

## Expected Behavior
Goto Today should work on year picker.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
@danavishnukb Having a look at this, we are currently looking at working on a v9 Calendar. This means that we will replace v8's Calendar with the new v9. This is also a long standing bug that doesn't really affect much of the functionality and has been reported until now. Is this a blocking bug? Seems like it's not due to the time it has passed and because that's the default priority in GH. If it's not a blocking bug I'm leaning towards closing it, what do you think?

**Comment by danavishnukb** [comment]
Adding @Sai keerthi ***@***.***>, @Poorvi ***@***.***>
This bug is related to Goto Today not working in Year Picker.

Thanks
Vishnu
