### ISSUE TITLE
Cannot type space in the <Input> component inside the <MenuList> of <Menu> component

### ISSUE THREAD

**Issue by kumarritikms** [microsoft/fluentui#28038]
### Environment Information

- **Package version(s)**:  "@fluentui/react-components": "^9.6.0",
- **Browser and OS versions**: Windows 11 Chrome 

### Describe the issue:

On render of the Input(https://react.fluentui.dev/?path=/docs/components-input--default) component inside the MenuList of Menu(https://react.fluentui.dev/?path=/docs/components-menu-menu--default) component unable to type space in the input field.

#### Actual behavior:

Unable to type space.

#### Expected behavior:

Should be able to type space

### If applicable, please provide a codepen repro:

https://codesandbox.io/s/competent-https-mh5xjm?file=/example.tsx

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking High

Products/sites affected: (if applicable)

**Comment by smhigley** [comment]
@kumarritikms there are a few reasons we do not want to encourage using an Input (or any form field) inside of a Menu:
- the input's role (`textbox`) is not a valid child of a menu or menuitem, so the control will be violating the ARIA spec
- an input within a menuitem will interfere with the screen reader experience in some ways, including incorrect indexing (e.g. "2 of 5" instead of "1 of 5")
- The keyboard interaction you would need for an input in a menu is not exactly the same as a menuitem in a menu

If you want to make this pattern work, there are a few things that would need to happen:

- Focus should always go directly into the input, and never reach the MenuItem parent of the input. Down arrow/up arrow should still move focus to the next/previous menuitem, and escape should still dismiss the menu.
- If the input is the first child, the parent MenuItem should have `role="none"`.
- For spacebar, you'd need to call `ev.stopPropagation()` on keydown:

```jsx
<Input
    placeholder={"Type group name"}
    autoComplete={"off"}
    contentAfter={<Button icon={<CutIcon />} />}
    onKeyDown={(e) => {
      if (e.key === ' ') e.stopPropagation();
    }}
  />
```

Hope that helps!
