### ISSUE TITLE
[Accessibility Issue]: DataGrid selection cell has Accessibility Issue

### ISSUE THREAD

**Issue by iasnijor09** [microsoft/fluentui#28187]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Chrome version 114.0.0.0

"@fluentui/react-components": "^9.14.0"
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/dtwyrb?file=/example.tsx

### Bug Description

Issue :
Accessibility insights is throwing allowed aria attributes and label rules on DataGrid component.

Screenshots :
![image](https://github.com/microsoft/fluentui/assets/136116410/b314dad1-0ab0-4677-8566-e9f1e3335513)
![image](https://github.com/microsoft/fluentui/assets/136116410/9f3cd67b-25b2-4066-8b0d-962f18577282)

![image](https://github.com/microsoft/fluentui/assets/136116410/5f82a0f8-eaa9-4e1a-ba76-b8722a2baad1)
![image](https://github.com/microsoft/fluentui/assets/136116410/c84ac477-87f0-46b6-81ae-a487ed9a828b)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
For the first issue, we don't have an immediate fix since we want to expose the mixed-state checkbox on the cell, which is possible through `aria-checked` but not through `aria-selected`. In addition to that, `aria-checked` is more user-friendly in general for multiple selection scenarios. I've opened an issue on the ARIA spec to consider adding it as a supported attribute on `gridcell`s: https://github.com/w3c/aria/issues/1960

For the second, that will be tracked in #28233

Thanks for filing this issue!
