### ISSUE TITLE
[Bug]: Form submission needs to be performed twice in Field and Input accessibility scenarios

### ISSUE THREAD

**Issue by adamsamec** [microsoft/fluentui#28378]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
N/A
```

### Are you reporting Accessibility issue?

no

### Repro steps

1. Navigate to the [Field](https://fluentuipr.z22.web.core.windows.net/pull/25071/public-docsite-v9/storybook/iframe.html?id=concepts-developer-accessibility-stories--ticket-order-form-fields&viewMode=story) and [Input](https://fluentuipr.z22.web.core.windows.net/pull/25071/public-docsite-v9/storybook/iframe.html?id=concepts-developer-accessibility-stories--registration-form-inputs&viewMode=story) scenarios.
2. Fill in the forms so that they contain no errors.
3. Press the "Order ticket" or "Register" button, respectively.
4. Press the same submit button again.

## Actual Behavior

The submit button needs to be pressed twice to successfully submit a valid form.

## Expected Behavior

The submit button should require only one press to successfully submit a valid form.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @adamsamec, this doesn't appear to be a bug with the controls in question, but rather a bug in the scenario pages in your PR https://github.com/microsoft/fluentui/pull/25071.

Is this issue intended to track a fix in your PR?

Also, I'm not able to repro the issue with the links given:
* The [Field](https://fluentuipr.z22.web.core.windows.net/pull/25071/public-docsite-v9/storybook/iframe.html?id=concepts-developer-accessibility-stories--ticket-order-form-fields&viewMode=story) scenario never submits because the Terms and Conditions checkbox never validates.
* The [Input](https://fluentuipr.z22.web.core.windows.net/pull/25071/public-docsite-v9/storybook/iframe.html?id=concepts-developer-accessibility-stories--registration-form-inputs&viewMode=story) scenario submits successfully on the first attempt.
