### ISSUE TITLE
[Bug]: DetailsList: onRenderRow tabIndex is overwritten which makes custom component inaccessible

### ISSUE THREAD

**Issue by Yash5044** [microsoft/fluentui#28384]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
@fluentui/react: 8.110.6
Browser: Microsoft Edge
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/yash5044/pen/qBQmdOP?editors=0010

## Actual Behavior
Tab focus should go to each row one by one. Still, after using onRenderRow in the custom component, the focus is not on the component, even if tabIndex is explicitly set to 0.
![image](https://github.com/microsoft/fluentui/assets/46025582/84a1de65-f511-4eb2-b414-166556dce1d2)

## Expected Behavior
Tab navigation should go to the custom component using onRenderRow.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @Yash5044, I don't believe `_onRenderRow` supports rendering something other than a `DetailsRow`, which handles arrow key navigation. [Note that the entire DetailsList is a single tab stop, so tabIndex is not the right solution here]. Custom row rendering seems to be more for adding custom styles to the DetailsRow.

Consider following the "Custom Item Columns" example to render custom content inside each cell, rather than replacing the entire row: https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/customitemcolumns

If you need more help, you could try posting in [Discussions](https://github.com/microsoft/fluentui/discussions) with details about what you're trying to accomplish, to see if anyone in the community has suggestions.
