### ISSUE TITLE
[Bug]: Coach mark is always displaying on right side for second flex item with particular width.

### ISSUE THREAD

**Issue by bhanu345-cmd** [microsoft/fluentui#28477]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
fluent ui/react:8^
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/s/vibrant-kirch-gccnqr?file=/src/App.js

## Actual Behavior

Coach mark at end of element if there is a particular width for element.

## Expected Behavior
 should be always at start

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Looking through the code and reading [this comment](https://github.com/microsoft/fluentui/blob/master/packages/react/src/utilities/positioning/positioning.ts#L596-L600) I believe this is the intended behavior as the example is using auto positioning.

I've verified this by orienting the `Stack` vertically so the second item appears on the left-hand side of the screen and the `Coachmark` is at the start of the item: https://codesandbox.io/s/coachmark-vertical-c7ptv8?file=/src/App.js

Since you want to use a horizontal `Stack` you'll need to provide directional hints to the `Coachmark`: https://codesandbox.io/s/coachmark-horizontal-with-directionalhint-n6yc42?file=/src/App.js

The [usage example](https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark#usage) demonstrates all the values of directional hint.

Note, that I'm only rendering a single `Coachmark` at a time as the [docs state](https://developer.microsoft.com/en-us/fluentui#/controls/web/coachmark):

> Only one coach mark and teaching bubble combo should be displayed at a time.
