### ISSUE TITLE
[Bug] Tooltip triggered on disabled elements

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluentui#28524]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
mac / chromium
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/stupefied-night-38389z?file=/index.html

## Actual Behavior
Tooltip shows up for disabled elements as Tooltip relies on pointer events

## Expected Behavior
Tooltip does not show up for disabled elements
If it is deisred for tooltip to still show, we should document this intention and advise users to prevent showing the tooltip. However that way we would also preventing them from attaching aria-label which comes from the tooltip.

### Requested priority

High

### Products/sites affected

Teams

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @jurokapsiar, there are use cases where someone may want to show a tooltip on a disabled control, such as to describe why it's disabled. I don't think it would be desirable to change the default behavior to not show Tooltips for disabled controls.

I'd recommend one of two options in this case:

**Option 1**: Only render the Tooltip if the button is enabled. That will prevent the tooltip from showing, since it's not rendered, but it will also prevent `aria-label` from being added automatically, so you'd need to add it manually if needed:

```jsx
const button = <Button disabled={!buttonEnabled} aria-label={buttonLabel} ... />;
return buttonEnabled
  ? <Tooltip content={buttonLabel} relationship="label">{button}</Tooltip>
  : button;
```

**Option 2**: Use the `visible` attribute to prevent the tooltip from showing when the button is disabled. The Tooltip will still add the `aria-label` attribute in this case. However, you'll need to fully control the `visible` prop, which means adding an `onVisibleChange` listener:

```jsx
const [visible, setVisible] = React.useState(false);
const onVisibleChange = (_, data) => setVisible(buttonEnabled && data.visible);
return (
  <Tooltip content={buttonLabel} relationship="label" visible={visible} onVisibleChange={onVisibleChange}>
    <Button disabled={!buttonEnabled} ... />
  </Tooltip>
);
```

Here's a codesandbox with the two options: https://codesandbox.io/s/gallant-danilo-r5974f?file=/example.tsx

I'd generally recommend option 1, but either one could work depending on what's best for your scenario.
