### ISSUE TITLE
[Bug]: https://uifabricicons.azurewebsites.net/ Tool not loading - 500 server error

### ISSUE THREAD

**Issue by RawkBob** [microsoft/fluentui#28581]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
n/a https://uifabricicons.azurewebsites.net/ is not loading
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://uifabricicons.azurewebsites.net/

## Actual Behavior
https://uifabricicons.azurewebsites.net 500 server error
## Expected Behavior
https://uifabricicons.azurewebsites.net 200 OK server response

### Logs

```shell
n/a
```

### Requested priority

Blocking

### Products/sites affected

https://uifabricicons.azurewebsites.net/

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by dylansuite** [comment]
I am also experiencing the same issue.

**Comment by rejohnson10** [comment]
Site has been down for more than a week.  Receiving HTTP ERROR 500 page isn't working.

**Comment by GeorgiyZhuravlev** [comment]
Same issue!

Can't live without the tool, please fix it.

**Comment by andrewconnell** [comment]
Judging by the domain name, I wonder if this was ever a real thing or taken seriously by the team. Seems like a dev on the team just thew something up on an Azure web app free plan and somehow it made the docs.

This is a reliable resource from the community I started using a while back, before the one in this issue died:

https://www.flicon.io/

**Comment by SiemvandenBerg** [comment]
Please revive https://[uifabricicons.azurewebsites.net](https://uifabricicons.azurewebsites.net/)/ as soon as possible. I rely on this to do my job. Do something or provide an alternative.

**Comment by Jahnp** [comment]
Hey folks, apologies for the disruption. I'm the one who created this tool originally and am working on a resolution. No high-confidence ETA right now but aiming to be resolved by EOW.

I haven't isolated a cause for the failure: there haven't been changes deployed for ~1yr, no configuration changes were made to the app itself, and the typical service health problem areas aren't showing any issues (i.e. service plan quotas).

So, I'm going to try re-deploying the app, but that requires some updates to the pipeline & release definitions as security policies have changed since last year's deployment. I'll update as I make progress.

**Comment by Jahnp** [comment]
Update: This should be resolved now. Sorry again for the disruption.

I unfortunately still don't know what the specific cause of failure was—logs didn't show anything—but I spun up a clean deployment slot to test. It was experiencing memory issues due to an apparently 32-bit node runtime, and changing it to 64-bit did the trick. I made the same change to the existing apps and did a clean deploy for each, and that seems to have resolved it.

**Comment by Jahnp** [comment]
Closing this out since it's resolved now, but let me know if you see any more issues with the site.
