### ISSUE TITLE
[Bug]: When the ComboBox is placed within the Fluent UI Panel, the hovering over the text does not highlight the option, and clicking the text does not select the option.

### ISSUE THREAD

**Issue by Kokila13081999** [microsoft/fluentui#28595]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
(Using StackblitzEditor)

""@fluentui/react": "8.110.7",
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/repro-syncfusion-react-combobox-issue-x3gvx4?file=package.json,index.js

## Actual Behavior
When the ComboBox is placed within the Fluent UI Panel, the hovering over the text does not highlight the option, and clicking the text does not select the option.

## Expected Behavior
When the ComboBox is placed within the Fluent UI Panel, the hovering over the text it should highlight the option, and clicking the text should select the option.

## Video illustration

![chrome_07CKaDIma9](https://github.com/microsoft/fluentui/assets/93525217/da8cb9a5-19e1-4891-aa8f-beab65896627)

## Sample 

By default, we render the popup inside the body section but because of this issue we have tried to move the popup with the panel target event through we facing the same issue. We have prepared samples bellow for your reference :

**Popup with in the body :**

https://stackblitz.com/edit/repro-syncfusion-react-combobox-issue-fjrdus?file=package.json,index.js

**Popup moved to panel target :** 

https://stackblitz.com/edit/repro-syncfusion-react-combobox-issue-x3gvx4?file=package.json,index.js

## Replication Procedure

1. Run the sample
2. Filter any data in the ComboBox
3. Hover over the text in the popup. Now the option does not highlight the option and clicking the text does not select the option.

### Logs

```shell
No
```

### Requested priority

Blocking

### Products/sites affected

No

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Hi @Kokila13081999,

Thanks for filing this issue! I've forked your repro and confirmed that `Panel` works correctly with the Fluent v8 `ComboBox`: https://stackblitz.com/edit/repro-syncfusion-react-combobox-issue-an9wt6?file=index.js

Prior to looking into this issue I was not aware of Syncfusion and, generally, we cannot ensure compatibility with third-party libraries. Given that the Fluent `ComboBox` works correctly I assume that `Panel` is working as intended as well. If you can point to a specific issue in Fluent that prevent's Syncfusion's `ComboBox` from working correctly we're happy to dig in and work on a fix but with the data at hand it's just as likely that the issue is in the Syncfusion code and that's not something we can fix.
