### ISSUE TITLE
[Feature]: Optional Backdrop on (non-modal) Dialog

### ISSUE THREAD

**Issue by ThomasPe** [microsoft/fluentui#28722]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

I'd like to have a Dialog with a backdrop (like modal and alert) but also a close button like the non-modal has. [From the docs](https://react.fluentui.dev/?path=/docs/components-dialog--default#non-modal):

> A non-modal Dialog **by default presents no backdrop**, allowing elements outside of the Dialog to be interacted with (unless DialogSurface noTrapFocus property is provided).

> DialogTitle compound component will present **by default a closeButton**.

Both sound like they can be changed which seems to be not the case. Having backdrop and closeButton as a boolean parameter to pass would be awesome.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by sopranopillow** [comment]
The information on parenthesis is incorrect, but DialogSurface does have an optional backdrop as seen in https://codesandbox.io/s/exciting-sea-ck8gj5?file=/example.tsx. I would not recommend using the backdrop when not trapping focus since visually you'll have a mismatch of behavior, adding the backdrop usually means you can't access the rest of the DOM aside from the dialog.

**Comment by ThomasPe** [comment]
thanks! can this be combined with light dismiss?
