### ISSUE TITLE
[Bug]: CardProps.onClick cannot be activated by keyboard

### ISSUE THREAD

**Issue by ok-AK** [microsoft/fluentui#28763]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 42.15 GB / 63.84 GB
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

yes

### Reproduction

~https://codesandbox.io/s/sparkling-sunset-34r7kv~
Updated CSB that adds a missing dependency (code is the same): https://codesandbox.io/s/serverless-meadow-34xqsc

## Actual Behavior
When adding a focusMode to CardProps, most allow keyboard navigation to the card. Further keyboard interactions involving Tab or Enter mostly result in focus changing to one of the inner components of the card, if they exist.

However, if CardProps contains an onClick prop, none of the focus modes or keyboard presses appear to trigger the onClick prop.

CardProps.onClick can still be trigger via mouse click.

Specific example from the repro link above where focus is on the Card. The user can click the card to activate the onClick prop but cannot activate the onClick prop via the keyboard

![image](https://github.com/microsoft/fluentui/assets/17037706/a99a8834-e9a8-4865-ab69-2d40a70831d6)

## Expected Behavior
CardProps.onClick should be possible to trigger via keyboard press.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I think this behavior is correct since the listener you're adding is for the native `click` event which doesn't not fire for keyboard events. Depending on what you want to achieve I see two options.

The first option is to use `Card`'s `onSelectionChange` handler. This event is fired when the selection state of the `Card` changes regardless if that change was from a click or the keyboard (enter key in this case). [Here's an example using `onSelectionChange`](https://codesandbox.io/s/card-onselectionchange-gsx3jw?file=/example.tsx:1476-1546).

The second option is to add an `onKeyDown` listener. This will bind to the native `keydown` event and you'll be able to respond to the keyboard event however you like. [Here's an example using `onKeyDown`](https://codesandbox.io/s/card-onkeydown-9qgnrs?file=/example.tsx:1381-1431).

**Comment by ok-AK** [comment]
Thanks for the suggestions. `onSelectionChange` seems like a good bet and is handling the keyboard scenario the way I need it to.

For thread context, I am making a collapsible card where the `header` should trigger open/close behavior. By placing the entire Fluent v9 Card as the "header" of the collapsible card, I hide/show the content in a separate div below it.

The benefit of of using the FluentV9 Card as the new header is because it allows button-over-button situations such as the header is a button to open/close this collapsible card but another button for opening a sub menu such as water button or the fire icon button can also trigger a separate action as shown below. Both are reachable from the keyboard.

![image](https://github.com/microsoft/fluentui/assets/17037706/b2643cac-8cbd-42d2-b61a-6e7f9484283e)
![image](https://github.com/microsoft/fluentui/assets/17037706/2d9b9e0c-2d05-49a9-8046-278d4bfb5951)
![image](https://github.com/microsoft/fluentui/assets/17037706/a6899c6b-c9d3-497e-8760-fede24e4e086)

Thanks again, closing the issue.

**Comment by smhigley** [comment]
I know this is closed, but it came up in a separate issue and I just wanted to add some context here -- adding an `onKeyDown` listener to the Card would not be an accessible approach.

A Card is not itself an actionable element by its nature -- it does not have the correct role to support an accessible keyboard activation with enter/space. It also cannot have a role that would support that behavior, since it can have nested buttons, links, and other interactive widgets. It can't be both at once -- actionable and a container for other actionable elements.

To do this behavior accessibly, you can add an onClick to the Card root, but the same functionality must also be available via a button or link within the card that can be activated with the keyboard, a screen reader, and voice control. Adding an `onKeyDown` would only help keyboard users, and it would remain inaccessible to most screen reader users and voice control users.
