### ISSUE TITLE
[Bug]: elementToFocusOnDismiss/disableRestoreFocus not respected in Dialog or Modal

### ISSUE THREAD

**Issue by jcksonhe** [microsoft/fluentui#28782]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
    Memory: 20.07 GB / 63.59 GB
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.43)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/jcksonhe/pen/qBQweZZ

### Bug Description

Some context: We have a save button that opens up a Dialog. When save is complete in the dialog, the save button disables. We'd like another button, call it the "view saves" button, to be focused upon closing the Dialog.

Focus on a button that opens a Dialog/Modal, open it, and close it with `elementToFocusOnDismiss` and/or `disableRestoreFocus` set:

## Actual Behavior
Focus returns back to the button that spawned the Dialog/Modal.

## Expected Behavior
Focus should apply to the div set in `elementToFocusOnDismiss` or should not focus anything with `disableRestoreFocus`.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I see a couple issues with your example and I think if we address those the focus behavior works as it should. And, not that you should have to look at the source code, but if we [take a look there](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx#L217-L233) I think some of the issues will become apparent 🙂

The first issue is that you're trying to restore focus to a `div` which is not focusable by default. One way to address this is to set [`tabIndex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) on the `div` however I do not recommend this as the `div` isn't actionable (i.e., you cannot click it for example). Better to restore focus to the button in question which can be done on `DefaultButton` with the [`elementRef` prop](https://developer.microsoft.com/en-us/fluentui#/controls/web/button#implementation).

The second issue is that you've set `disableRestoreFocus` to `true` which means the [focus behavior will not be invoked](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/FocusTrapZone/FocusTrapZone.tsx#L226). I see why you did this after reading the docs for this prop. I think we can update the docs to be more clear on this point so I've created an [issue to update the docs](https://github.com/microsoft/fluentui/issues/29010).

The final issue is that `modalProps` is memoized but relies on a React ref. Since the ref will be `undefined` on the initial render when `modalProps` is memoized and refs do not trigger re-renders (and the memoized object will never be re-created anyway because of the empty array for the second param), `modalProps` never receives the value of the ref when it is set. There are a couple ways to handle this.

The first is to use a [ref callback function](https://react.dev/reference/react-dom/components/common#ref-callback) which will allow us to trigger a re-render and update the value of `modalProps`. [Here's a fork of your example demonstrating this approach](https://codepen.io/seanms/pen/VwqeqbW?editors=0011).

The second approach is to remove memoization. [Here's another fork of your example demonstrating this](https://codepen.io/seanms/pen/oNJbJEw?editors=0011).

With these changes I think you should be able to achieve your desired behavior.
