### ISSUE TITLE
[Feature]: TimePicker timeRange option should support any time (like 8:30 AM) instead of just hours

### ISSUE THREAD

**Issue by Senorsen** [microsoft/fluentui#28972]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
(failed to run this command)
@fluentui/react 8.110.15
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/Senorsen/pen/eYbNbZZ

## Actual Behavior
The `timeRange.start / end` only accepts number (integer actually), so we couldn't specify the time like '8:30 AM', it only accept 0-23 integer numbers for hours.
![image](https://github.com/microsoft/fluentui/assets/4176091/2df92023-2073-4f50-be43-4a2b808cc10a)
https://developer.microsoft.com/en-us/fluentui#/controls/web/timepicker#ITimeRange
![image](https://github.com/microsoft/fluentui/assets/4176091/4f540ce5-070e-4699-8659-9f5d2b64948d)

## Expected Behavior
The `timeRange.start / end` should be / support `Date` type, or other forms that supports specifying any time (hh:mm:ss) instead of just 0-23 hours.

### Requested priority

Blocking

### Products/sites affected

https://www.bing.com/homes

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I'm going to change this to a feature request as it feels like a new feature that we should add.

@Senorsen, you indicated you're willing to create a PR for this work, is that still the case?

> The timeRange.start / end should be / support Date type, or other forms that supports specifying any time (hh:mm:ss) instead of just 0-23 hours.

We need to maintain `timeRange` exactly as it is to ensure backward compatibility as we cannot introduce any breaking change into 8.x.

My feeling is that we should introduce a new `ITime` interface:

```ts
interface ITime {
  /** Hour value on a 24-hour clock (0-23 where 0 is midnight) **/
  hour: number;
  /** Minute value (0-59). @default 0 **/
  minute?: number;
  /** Second value (0-59) @default 0 **/
  second?: number;
}
```

My reasoning is that `Date` includes days, months, years, time zones, etc. and that information is not relevant here and a potential source of bugs when we're just concerned about hours, minutes and seconds.

One option is to then expand the type of `timeRange` to:

```ts
interface ITimeRange {
  start: number | ITime;
  end: number | ITime;
}
```

or add a new prop called something like `fullTimeRange` (open to names here!):

```ts
interface IFullTimeRange {
  start: ITime;
  end: ITime;
}
```

I find myself leaning toward this second option because it makes the logic simpler:
1. `start` and `end` are guaranteed to be of the same type for both `fullTimeRange` and `timeRange`
2. We can ignore `timeRange` if `fullTimeRange` is set

What do you think?

CC: @sopranopillow as I know you're looking at a compat version of this control for Fluent v9.
