### ISSUE TITLE
[Bug]: People picker: Edge/Chrome/Desktop: The suggestion list is not displaying below input field; instead, it's displaying at the side.

### ISSUE THREAD

**Issue by sahilkumarmaths** [microsoft/fluentui#29019]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.23521
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
    Memory: 14.94 GB / 31.92 GB
  Browsers:
    Chrome: 116.0.5845.111
    Edge: Spartan (44.23521.1000.0), Chromium (116.0.1938.62), ChromiumDev (118.0.2048.1)
    Internet Explorer: 11.0.23521.1000
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/peoplepicker

## Actual Behavior
The suggestion list should is being displayed on the side of the input.

![image](https://github.com/microsoft/fluentui/assets/1578304/8ab2b257-b1be-423d-8be3-1ea0068d076f)

## Expected Behavior
The suggestion list should be displayed at the bottom or top of the input.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I think this is happening because there is not enough vertical space to fit the callout:

https://github.com/microsoft/fluentui/assets/93940821/10190273-8f7c-473e-b749-1cbcf69d4954

`Callout` positioning respect "directional hints" but will re-position based on available space. If you want to disable these overrides and stick with the default directional hint you can set `directionalHintFixed` to `true`. Here's an example of that: https://codepen.io/seanms/pen/mdaPWMq
