### ISSUE TITLE
[Bug]: FluentDropdown's disabled option click event stopped working

### ISSUE THREAD

**Issue by bhargavgaglani07** [microsoft/fluentui#29027]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 12.44 GB / 31.87 GB
  Browsers:
    Chrome: 116.0.5845.112
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.38)
    Internet Explorer: 11.0.19041.1566
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/silent-field-7cvyc4

## Actual Behavior
FluentDropdown having disabled option and customOptionRender to have a click event stopped working. Refer [this ](https://codesandbox.io/s/silent-field-7cvyc4) codesandbox for example. Kindly note that same is working for android edge browser.

## Expected Behavior
FluentDropdown having disabled option and customOptionRender to have a click event should work (click event should get fired).

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
The issue is that [disabled elements cannot be interacted with](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) and therefore will not fire events. This applies to `onRenderOption` because it is the [child of an element that is `disabled`](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Dropdown/Dropdown.base.tsx#L832).

You can instead use the [`onRenderItem` callback to control the rendering higher up](https://github.com/microsoft/fluentui/blob/master/packages/react/src/components/Dropdown/Dropdown.base.tsx#L684). 

Here's an example: https://codesandbox.io/s/onrenderitem-x7fjqm
This approach requires you to recreate all the styling for each option however.

Another approach is to make the options "visually disabled" as opposed to actually `disabled`. In this case the "disabled" options would visually look disabled but would still fire events as you want so users can interact with them.

I will take this opportunity to advise you to strongly consider whether you actually need to do either of these things however 🙂 While there are often exceptions to these types of things, users expect disabled things (or things that look disabled) to actually be disabled and subverting that can surprise users which is generally not a good thing.

**Comment by bhargavgaglani07** [comment]
Hi @spmonahan 

Thank you for suggesting workaround, I'll try this out and see if it can resolve business problem. But technical query is still open as same [code](https://codesandbox.io/s/silent-field-7cvyc4) used to work few days back and still working on mobile edge browser, so want to understand what changes has caused this behavior change.

And I do agree with your thoughts regarding disabled option expectation from the end user side, however, click event firing is important for us considering business use cases. Showing message is just a example here to validate click event firing.

**Comment by bhargavgaglani07** [comment]
Still waiting for response

**Comment by khmakoto** [comment]
Reopening, also fyi @spmonahan.

**Comment by spmonahan** [comment]
> But technical query is still open as same [code](https://codesandbox.io/s/silent-field-7cvyc4) used to work few days back and still working on mobile edge browser, so want to understand what changes has caused this behavior change.

I don't think there are any changes in Fluent that caused this behavior change. In testing I've observed in your example:

1. The click event fires on macOS and iOS
2. The click event does not fire on Windows or Android

The HTML spec for `disabled` is not really crisp on this topic as it turns out ☹️ For form controls it states:

> The user can neither edit nor focus on the control, nor its form control descendants

But it's not really clear if a `disabled` `div`'s (or `button`'s) children should inherit that `disabled`-ness. And in [this example](https://jsfiddle.net/q3eLuvza/) the `span` is always clickable.

So it seems like the issue is platform-dependent which makes me think different platforms handle this case differently. Generally we don't do anything in Fluent to directly handle platform-specific behavior but the linked example makes me think there could be a bug in Fluent (or that we should align the behavior to be consistent across all platforms).

I've created #29135 for us to investigate further.
