### ISSUE TITLE
[Bug]: createFocusOutlineStyle does not work well with tab

### ISSUE THREAD

**Issue by flora8984461** [microsoft/fluentui#29047]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
    Memory: 42.89 GB / 63.57 GB
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/hidden-lake-4vvd3l?file=/example.tsx

## Actual Behavior
Using `createFocusOutlineStyle` with tab list's tabs, if the tab has selected indicator and focus on it, it does not behave correctly, as the screenshot shows: 

<img width="338" alt="image" src="https://github.com/microsoft/fluentui/assets/39588094/bf6de3b9-3f9e-40f4-af6d-105cc52463cf">

## Expected Behavior
Expect it works well with tabs. Or there could be alternative way to work with it. 

In the codesandbox I commented out a workaround. Would there be any other ways for items with `:before` and `:after` to work well together with focus indicator? 

Really appreciate your help!

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by behowell** [comment]
Hi @flora8984461, TabList comes built-in with the recommended focus indicator styling. While it's possible to customize the styling of components through the className prop, there's no official support or expectation that it would work with arbitrary styles, including createFocusOutlineStyle. You'll need to experiment with styles to override the built-in focus indicator if desired. In fact, it sounds like you've already found a workaround using createCustomFocusIndicatorStyle? 

I'm going to close this issue since the requested behavior is not supported, and there's already a workaround. Let us know if you have more questions.
