### ISSUE TITLE
[Bug]: The slider indicator is in the incorrect position when the min, max, and value are all equal.

### ISSUE THREAD

**Issue by vmpham1012** [microsoft/fluentui#29066]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

No

### Reproduction

Set min, max and value to the same number

## Actual Behavior

When min, max, and value are all set to the same value, the indicator remains on the left side of the slider, giving the appearance that the value is 0.

## Expected Behavior
If the value is equal to the max value, the indicator should be positioned on the right side of the slider

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@vmpham1012 This is expected behavior and by design. When you're setting `min`, `max` and `value` to the same number, the slider indicator will expectedly be on the left hand side (in a horizontal slider) because you have set the `min` to be equal to `max`. If you have a use case where the `min` and `max` are equal, using a `Slider` component is probably not ideal.
