### ISSUE TITLE
[Bug]: Popover renders under input when rendered inline

### ISSUE THREAD

**Issue by sopranopillow** [microsoft/fluentui#29185]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 36.49 GB / 62.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
Browsers:
    Edge: 119.0.2109.0 (Official build) canary (32-bit)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/modern-shadow-52yspg?file=/example.tsx

## Actual Behavior
When the Popover is rendered inline it renders under the input.

## Expected Behavior
Popover should render on top of the input.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
This is not a bug, but rather how CSS works. Inline Popovers are positioned using `position: 'absolute'`. The `Input ` is styled with `position: 'relative'` https://github.com/microsoft/fluentui/blob/b3a0fb9ea16298ba5553c7338cb9ec55fd5ef66b/packages/react-components/react-input/src/components/Input/useInputStyles.styles.ts#L26

The `position` style creates a new stacking context, that is higher than the inline popover because the popover is rendered earlier in DOM. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context

I'm not entirely sure why the Input needs that style, but there are two ways to get the inline Popover to render correctly here:

* Apply a zindex https://codesandbox.io/s/vigilant-rhodes-j6f7gc?file=/example.tsx
* Remove `position: 'relative'` from Input https://codesandbox.io/s/vibrant-sun-8vr4dh?file=/example.tsx

**Comment by sopranopillow** [comment]
Closing because it's not really an issue as explained by https://github.com/microsoft/fluentui/issues/29185#issuecomment-1747288722. Since many of our components have `position: relative` in their styles, we should apply a zIndex.

**Comment by spmonahan** [comment]
> I'm not entirely sure why the Input needs that style,

I found this issue while looking into what turns out to be the same issue with `DatePicker`'s `Calendar` popover. The reason `Input` uses that style is to position the focus outline: https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-input/src/components/Input/useInputStyles.styles.ts#L39-L44

This same issue affects all the Fluent controls that have that visual treatment (`Textarea`, `SpinButton`, etc) and, of course, other positioned elements.
