### ISSUE TITLE
[Bug]: Textarea, scrollbar appears before available height is filled with text

### ISSUE THREAD

**Issue by logicaloud** [microsoft/fluentui#29474]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.60)

Fluent UI 9.34.2
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codesandbox.io/s/wizardly-kirch-8jqzdg?file=/example.tsx

## Actual Behavior

When setting the the height of the Textarea to a high value (400, for example), then a scrollbar appears when entering text that utilizes only part of the available height.

![image](https://github.com/microsoft/fluentui/assets/47704763/eb9b6eaa-8c4e-4023-985c-1ee52ee7bd72)

## Expected Behavior

The scrollbar should only appear once the entered text no longer fits into the available height.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @logicaloud, this happens due to the structure of Textarea and the fact that we add a max-height so the Textarea can get a scroll by default when entering text. To give a little more detail, we wrap the native textarea with a span which gives the custom styles and we remove styling from the native textarea's border. This means adding a style to the style prop affects the span rather than the actual textarea. A quick fix to this would be to send that style prop to the textarea through slots: `<Textarea textarea={{style: { height: '100px' }}} />` it would probably be best to use classname instead with makeStyles.

If what you're trying to achieve is hard setting the height, then the fix above should do it. if you want to show the scroll-bar by when you hit a certain height, you probably should use `maxHeight` instead.

For future reference, I'll add a best practices item to mention how to do this.

**Comment by logicaloud** [comment]
Hi @sopranopillow, thank you for looking into it; that helped me solve the problem. I have additionally set the `maxHeight` for the `textarea` to get to the desired height, i.e.:

`textarea={{style: { maxHeight: 320, height: 320 }}}`
