### ISSUE TITLE
[Feature]: Open up the command button of Dropdown options

### ISSUE THREAD

**Issue by engineerrocks** [microsoft/fluentui#29537]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

FluentUI dropdown has a list of options. Each option is rendered as a command button. My ask is to be able to customize the command button using button props. For example, would like to create a submenu in the dropdown for more options the way contextual menu can. 

The onRenderOption can do something similar, except there is a bug that won't allow for the subMenu to stay focused on the page. 

![image](https://github.com/microsoft/fluentui/assets/114700433/03be3874-00c4-4951-9652-2715a35952c8)

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

High

**Comment by behowell** [comment]
Hi @engineerrocks, Dropdowns are intended for picking an item out of a list of options, and they aren't designed to be used as menus. If you want a submenu like in the included screenshot, you should use the Menu component: https://react.fluentui.dev/?path=/docs/components-menu-menu--default

**Comment by engineerrocks** [comment]
Hi @behowell the ask is for picking an item that has multiple subItems. The Menu component does not allow for picking an item out of a list. 
I checked the code for Dropdown and I see each option is listed as a CommandButton. So I just ask that we can use the subMenuProps that comes with each button.

**Comment by behowell** [comment]
@engineerrocks That's not something we can support, because menus aren't allowed to be in a dropdown's listbox according to the ARIA spec. See the MDN documentation on the listbox role: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role

You can consider using a menu with toggleable split buttons to achieve something similar. Based on your reply, it sounds like you're using FluentUI v8? For an example of a toggleable split button in v8, see **ContextualMenu with checkable menu items and toggleable split button** on https://developer.microsoft.com/en-us/fluentui#/controls/web/contextualmenu
