### ISSUE TITLE
[Bug]: page with a lot of FluentButtons becomes slower and slower (web-components

### ISSUE THREAD

**Issue by vnbaaij** [microsoft/fluentui#29738]
### Library

Web Components (@fluentui/web-components)

### System Info

```shell
discoverd when using the Blazor library which uses web-components.min.js v2.5.16
```

### Are you reporting Accessibility issue?

yes

### Reproduction

minimal reproduction is described here: https://github.com/microsoft/fluentui-blazor/issues/871

### Bug Description

**Issue is discussed with Chris Holt and should be assigned to him**

## Actual Behavior
Rendering time increases every time page is shown.

## Expected Behavior
Rendering time is more or less consistent

### Logs

```shell
Output from the stopwatch as used in the reproduction:
Rendering took 384 ms
Rendering took 434 ms
Rendering took 627 ms
Rendering took 662 ms
Rendering took 831 ms
Rendering took 942 ms
Rendering took 1124 ms
Rendering took 1296 ms
Rendering took 1439 ms
Rendering took 1582 ms
```

### Requested priority

Normal

### Products/sites affected

Blazor library package, web-components package

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by chrisdholt** [comment]
@vnbaaij I've got a fix for the form associated portion of this and am going to publish it and get it here into stable. I think we need a very clear, min repro for the MatchMedia behavior suggestion though - those are individually unbound by the controller, so I'm not seeing or able to find how or why different behaviors would affect one another. I'm curious if solving the Form Associated issue addresses this in whole...

**Comment by vnbaaij** [comment]
I'll re-run the test with the library once this PR has landed in the web components script to see what happens and report back here

**Comment by andreisaperski** [comment]
@chrisdholt the fix in FormAssociated is a prerequisite to reproduce MatchMedia behavior issue. I have a [repo](https://github.com/andreisaperski/fluentui-blazor-issues/tree/main/BlazorFluentButtonPerf) (Blazor) with it. Steps are:
1. go to 'Buttons' page;
2. put a breakpoint on line 2297 `behavior.unbind(element);` in web-components-v2.5.16.js;
3. click on 'Counter' page  link.

When the breakpoint is hit for button's controller, 'behaviors' has 9 entries.

![image](https://github.com/microsoft/fluentui/assets/30940385/0c3fbb62-eed0-49ee-9d88-4b2ef0bf621b)

But when PropertyStyleSheetBehavior (propertyName: appearance, value: accent) is unbind, it removes MatchMediaStyleSheetBehavior and doesn't unbind it because of Controller's _isConnected = false.

Before unbind is executed - still 9 entries:

![image](https://github.com/microsoft/fluentui/assets/30940385/a75d7c12-c22a-46ab-9871-0d1ce7a7ad7c)

Right after unbind execution - MatchMediaStyleSheetBehavior is gone, 'behaviors' contains 8 entries:

![image](https://github.com/microsoft/fluentui/assets/30940385/7f7b8a1c-8c71-41c4-ada9-f05fd0816d07)

Replacing 
```js
        const behaviors = this.behaviors;
        if (behaviors !== null) {
            const element = this.element;
            for (const [behavior] of behaviors) {
                behavior.unbind(element);
            }
        }
```
with
```js
        let behaviors = this.behaviors;
        if (behaviors !== null) {
            behaviors = new Map(behaviors);
            const element = this.element;
            for (const [behavior] of behaviors) {
                behavior.unbind(element);
            }
        }
```
 guarantees unbinding of all behaviors, but i'm not sure if it's a right way
