### ISSUE TITLE
[Bug]: accessibility issue on grouped DetailsList, group headers.

### ISSUE THREAD

**Issue by rahul4217583** [microsoft/fluentui#29889]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 3.66 GB / 15.78 GB
  Browsers:
    Edge: Chromium (118.0.2088.76)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/grouped

## Actual Behavior
A11y issue on grouped DetailsList group header when running fast pass. 
![image](https://github.com/microsoft/fluentui/assets/11205817/a960d0e1-5f9b-4c1d-b300-0f4a212c4c86)

![image](https://github.com/microsoft/fluentui/assets/11205817/86de4ba2-6a28-437d-9c20-e2ecc1104214)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
The aria-required-children error is a false positive, and the aria-allowed-attr one is an intentional design decision, detailed in our [known issues wiki](https://dev.azure.com/microsoftdesign/fluent-ui/_wiki/wikis/fluent-ui.wiki/332/Fluent-v8-known-issues) (an internal Microsoft link, let us know if you need the info copied here).
