### ISSUE TITLE
[Bug]:DataGrid select/de-select is slow with 100+ records.

### ISSUE THREAD

**Issue by blendsdk** [microsoft/fluentui#29908]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz
    Memory: 4.15 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 15.6.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/friendly-clarke-ngkdk8?file=/src/example.tsx

### Bug Description

Please see the following discussion for code example and additional description

https://github.com/microsoft/fluentui/discussions/29891

### Requested priority

Normal

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Profiling the example CSB with the React DevTools Profiler it seems the issue is that every cell of every row is re-rendered on selection change. I ran two profiles, one using the "toggle all" in the header and another just toggling single rows. In both cases it appears the entire `DataGrid` is re-rendered on every selection change.

**Comment by blendsdk** [comment]
I think this is because of how the table features are designed. It has some inner loops that eventually change the state forcing the entire DataGrid to re-render. Unfortunately this makes the DataGrid unusable. Looking at the code I could not find a way to fix it without significant refactoring.

**Comment by jumoc-bf** [comment]
Is there a workaround for this?

**Comment by blendsdk** [comment]
I have had a quick look at the code (table features and the DataGrid). The selection mechanism is very different from what DetailsList in v8 was. From what I see it does not look it is easily fixable without having a context-aware selection mechanism. The workaround would be to not use the built-in selection and render a custom checkbox column where you can handle the selection yourself.

**Comment by ling1726** [comment]
Yeah I see the problem - there's a bunch of things that should be memoized that aren't. I managed to get it to the point when you select a row, only that row is re-rendered 

![image](https://github.com/microsoft/fluentui/assets/20744592/38490bbc-3c63-4247-977b-7bb7883f31bd)

However there is still the limtation all cells of that row will be re-rendered. The row itself does need to re-render because it needs to update its own styles (brand background when the row is selected)

The cells re-rendering is constrained by the child render function API. I don't have any way to optimize that unfortunately, which means that when you 'select all rows' all rows and cells will re-render.

**Comment by spmonahan** [comment]
> This can be mitigated by the user memoizing the contents of cells in userland.

Would virtualization help as well?

Should we provide examples in the docs?

**Comment by blendsdk** [comment]
Thank you for the fix. It is very much appreciated.
