### ISSUE TITLE
Focus borders are not showing on fluent docsite for charts

### ISSUE THREAD

**Issue by AtishayMsft** [microsoft/fluentui#29939]
To repro this issue:
Go to - https://developer.microsoft.com/en-us/fluentui#/controls/web/horizontalbarchart
Focus on a bar and press tab to navigate to other bars in the chart.
The black border on the bar chart is not visible.

Expected behavior:
Perform the same steps on the demo site. The focus rings are visible
https://fluentuipr.z22.web.core.windows.net/heads/master/react-charting/demo/index.html#/examples/horizontalbarchart

**Comment by krkshitij** [comment]
@AtishayMsft 
Like @Shubhabrata08 said, the outline style is overridden here: https://github.com/microsoft/fluentui/blob/872548854fe302a49fb60bd479de95949a66a078/apps/public-docsite/src/styles/_base.scss#L47 and the reason for it is also mentioned in the comments. This doesn't happen on the demo site, allowing the browser's default focus style to take effect.
<img src="https://github.com/microsoft/fluentui/assets/110246001/4f817cc4-f316-46f6-bc3a-ee4bbff2c120" alt="image" width="300" />

On inspecting FocusZone examples in the docsite, I observed that the focus indicator still appears for focusable elements because the focus style is explicitly defined for them at the component level.
Example: https://github.com/microsoft/fluentui/blob/872548854fe302a49fb60bd479de95949a66a078/packages/react/src/components/DetailsList/DetailsRow.styles.ts#L296
To resolve this, we need to do the same for all charting components.

**Note**: The `getFocusStyle` utility cannot be used in our charts because pseudo elements (such as ::after, ::before) don't work with SVG elements.
https://github.com/microsoft/fluentui/blob/872548854fe302a49fb60bd479de95949a66a078/packages/style-utilities/src/styles/getFocusStyle.ts#L93

**Comment by AtishayMsft** [comment]
Thanks for the pointers Kshitij. Let me take a look on how we can standardize setting the focus property.
