### ISSUE TITLE
[Bug]: Accessibility Issue in Grouped List Component

### ISSUE THREAD

**Issue by Arpita-Blog** [microsoft/fluentui#29955]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 2.08 GB / 15.78 GB
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

Yes

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/groupedlist

## Actual Behavior
The Grouped List component in Fluent UI is causing accessibility issues when running Fast Pass. Specifically, it throws the following errors:

"Element has children which are not allowed: i[aria-hidden]"
"Element uses aria-busy='true' while showing a loader."

Steps to reproduce - 
Go to the Fluent UI official website
Navigate to the page/component with the Grouped List.
Run Fast Pass.
Observe the accessibility issues mentioned above.

![image](https://github.com/microsoft/fluentui/assets/90197139/10678c68-bb71-4b9e-b474-960b16c14ee5)
![image](https://github.com/microsoft/fluentui/assets/90197139/e0b60f0f-68aa-452a-b025-53f12b5adaad)

## Expected Behavior
Fast Pass should run successfully without throwing any accessibility issues

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This is a false positive that is fixed in axe-core, and will be fixed in Accessibility Insights once the version is updated. We have it documented in our [internal wiki](https://dev.azure.com/microsoftdesign/fluent-ui/_wiki/wikis/fluent-ui.wiki/332/Fluent-v8-known-issues?anchor=%60aria-required-children%60-on-any-element-that-also-has-%60aria-hidden%60), if you are able to access it.

The element in question is the `i[aria-hidden]` mentioned in the error text, which should not be counted as a disallowed child because of the `aria-hidden=true` attribute.
