### ISSUE TITLE
[Feature]: Support for native aria-orientation attribute on Divider component

### ISSUE THREAD

**Issue by jfbrennan** [microsoft/fluentui#29965]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Currently the Divider component defines a custom prop for setting the native orientation attribute internally:
```jsx
<Divider vertical />
// Outputs
<div role="separator" aria-orientation="vertical">...</div>
```
 It would be intuitive for web developers to be able to set that standard ARIA attribute themselves:
```jsx
<Divider aria-orientation="vertical" />
// Outputs
<div role="separator" aria-orientation="vertical">...</div>
```

Bonus points: use the language of the web, i.e. "separator", and add an alias, e.g. `<Separator />`

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by spmonahan** [comment]
I don't think there are any instances of Fluent using `aria-*` attributes in this way and because we aim to be strict about semver we'd have to continue supporting both the `vertical` prop and `aria-orientation`. This expands both the API surface of the component along with the implementation (and bundle size too) for minimal gain, if any.

I'll note that it is possible to pass intrinsic attributes to Fluent components, so you can pass in `aria-orientation` and it will be rendered to HTML. However, in this case, the `vertical` prop is also driving styling so just using `aria-orientation` is not equivalent to `vertical`.

Thank you for bringing up this idea but I don't think it's something we'll implement.
