### ISSUE TITLE
[Bug]: Clicking on dropdown blanks the page

### ISSUE THREAD

**Issue by stevebeauge** [microsoft/fluentui#30040]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.40 GB / 15.89 GB
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636

@fluentuid packages (envinfo command does not works):

    "@fluentui/react-components": "^9.42.0",
    "@fluentui/react-hooks": "^8.6.33",
    "@fluentui/react-icons": "^2.0.224", 
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/fluentui-issue-964zxh?file=%2Fsrc%2FApp.tsx%3A11%2C21

## Actual Behavior
When click on a Dropdown, the page goes blank until I click again anywhere in the page

Dropdown closed:
![image](https://github.com/microsoft/fluentui/assets/184604/1e143a8b-f89f-42e1-b133-5fd99d6aa1ec)

Clicking on the dropdown makes the screen blank and a new div fluentprovider is injected:

![image](https://github.com/microsoft/fluentui/assets/184604/7a803a3c-afa8-4137-b1e5-47a22c63e456)

## Expected Behavior
The dropdown should open

### Logs

```shell
No specific console log is emitted
```

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
I've done this exact thing before too! The issue is that the `Dropdown`'s list is rendered into a layer and, by default, Fluent will essentially clone the `Dropdown`'s `FluentProvider` for this layer. Because you have a `height: 100vh;` style on your `FluentProvider` this means the layer's `FluentProvider` will also have this style, pushing everything off screen. If you examine the Elements tab in DevTools you can see all the DOM elements are present, just pushed off screen.

The solution is to move your styles to a child of the `FluentProvider`, for example: https://codesandbox.io/p/sandbox/fluentui-issue-forked-lvf8vg?file=%2Fsrc%2FApp.tsx

**Comment by stevebeauge** [comment]
It's working as expected using your fix.

Does it mean styling the FluentProvider's generated div is a bad practice?

At first, I wanted to avoid the extra div it generates. 

Maybe some documentation improvement may clarify?

I guess the issue can be closed, since it's not a bug but a misuse of the framework.

**Comment by spmonahan** [comment]
> Does it mean styling the FluentProvider's generated div is a bad practice?

Yes, you should avoid styling it.

> At first, I wanted to avoid the extra div it generates.

You can use [HeadlessProvider](https://github.com/microsoft/fluentui-contrib/blob/main/packages/react-headless-provider/README.md) to achieve this.

> Maybe some documentation improvement may clarify?

I like this idea! Could you file a bug for it?

**Comment by barbalex** [comment]
This got me too. Hard to find out. Thankful to find the solution here.
