### ISSUE TITLE
[Bug]: DataGrid - `as` attribute doesn't work on DataGridRow 

### ISSUE THREAD

**Issue by kroudams** [microsoft/fluentui#30106]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
.
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/condescending-browser-r8gr2y?file=%2Fsrc%2Fexample.tsx%3A9%2C16

## Actual Behavior
When `as="tr"` is set on `<DataGridRow as="tr">` it still renders as `<div role="row">`

## Expected Behavior
When `as="tr"` is set on `<DataGridRow as="tr">` it should be rendered as `<tr>`

![image](https://github.com/microsoft/fluentui/assets/87769044/4607a9d6-5c11-4996-ad2e-f64763855004)

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by ling1726** [comment]
Using native semantic table elements means that all other elements must be semantic table elements. Due to the restrictions there and the fact that DataGrid renders as `role="grid"`, we made the decision to not allow semantic table element toggling in this component.

Is there a reason why rendering DataGrid as semantic table elements would be preferrable? The case you're drescribing now _should not_ be supported since you would be rendering `tr` for rows but `div` for everything else

**Comment by kroudams** [comment]
`tr` was an example. I wanted to use `DataGrid` as it already has all the functionality built-in (e.g. sorting).
