### ISSUE TITLE
[Bug]:  IFacepilePersona image flickers when state changes

### ISSUE THREAD

**Issue by balbyu** [microsoft/fluentui#30152]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
"Unexpected identifier 'envinfo'"
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://codepen.io/russellboone/pen/OJqJNJV

## Actual Behavior
Persona image flickers when the `Fade in` checkbox is selected and then de-selected. This happens with other state changes too, like if you click the `Show code` and `Hide code` in the official documentation: https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile

### Clicking the checkbox

![Demo](https://github.com/microsoft/fluentui/assets/33497321/b782bf56-037a-42e9-a451-a02a9efad319)

### Hiding and showing another component

![Demo2](https://github.com/microsoft/fluentui/assets/33497321/302d9a97-0508-4336-a166-1b0c69bd899e)

## Expected Behavior
Persona image should not flicker

### Requested priority

Normal

### Products/sites affected

https://developer.microsoft.com/en-us/fluentui#/controls/web/facepile

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @balbyu, this is not really an issue based on the repro you've provided. Here's an example that shows it only happens when turning on/off the fade toggle as it's expected since we want to show the animation. For the other example, the personas are rerendered because when opening the code editor, we move from a static example to the actual code in the example getting transpiled + injected. So, this is expected behavior as well. I'll mark it as resolved and will close in a week, but if you need more assistance feel free to ping me or reopen the issue.
