### ISSUE TITLE
[Bug]: This component doesn't pass the accessibility checks

### ISSUE THREAD

**Issue by Rafaelki** [microsoft/fluentui#30305]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
The bug can be reproduced in your documentation
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codepen.io/rafaelki/pen/PoLbWyx

## Actual Behavior
Go to the documentation page: https://developer.microsoft.com/en-us/fluentui#/controls/web/swatchcolorpicker
Run FastPass of "Accessibility Insights for Web"
Check that the component has this error: **ARIA role gridcell is not allowed for given element**

![image](https://github.com/microsoft/fluentui/assets/24438807/c5cd55d4-9c2d-4fa3-b89a-059f7a44fb7e)

## Expected Behavior
I expect to pass the accessibility checks.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This is a false positive that we have [in our wiki](https://dev.azure.com/microsoftdesign/fluent-ui/_wiki/wikis/fluent-ui.wiki/332/Fluent-v8-known-issues?anchor=%60aria-allowed-role%60-error-on-buttons-in-calendar%2C-datepicker%2C-and-swatchcolorpicker). Copying that text here:

This is a false positive that came from a change in the ARIA in HTML spec, which has now [been reverted](https://github.com/w3c/html-aria/issues/298). The gridcell role is now officially allowed on button, and this bug is a false positive that has already been fixed in axe-core and will no longer show in Accessibility Insights once the axe-core version is updated.

**Comment by Rafaelki** [comment]
It seems I don't have access to your wiki

![image](https://github.com/microsoft/fluentui/assets/24438807/806a193d-fc4f-4f39-ab03-ceeeb1bb4922)
