### ISSUE TITLE
[Bug]: Basic List - Background color issue on Theme switch

### ISSUE THREAD

**Issue by jayachandrikagadwal** [microsoft/fluentui#30358]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 13.69 GB / 31.60 GB
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://developer.microsoft.com/en-us/fluentui#/controls/web/list

## Actual Behavior

List control from fluent UI is not changing the background color of its items on hover according to the theme. All of the list attributes are switching according to the theme except the background color for onhover behaviour. The sample given in fluent documentation also shows the same behaviour.
[Fluent List](https://developer.microsoft.com/en-us/fluentui#/controls/web/list)

css used:
![image](https://github.com/microsoft/fluentui/assets/29462031/294d3075-4521-4178-9d24-90d4e41cef72)

initial behaviour with light theme:
![image](https://github.com/microsoft/fluentui/assets/29462031/0fa2d5f6-8220-48c5-83aa-556284956a4e)

behaviour upon theme switch:
![image](https://github.com/microsoft/fluentui/assets/29462031/460b3028-b3e8-4de1-b665-162f72a3fd0c)

## Expected Behavior
If the theme is switched, the hover color should change. 

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mltejera** [comment]
Hi jayachandrikagadwal - thanks for submitting!

The examples for list use a very outdated theme mechanism (getTheme) that gets a global static theme, rather than the live theme that lives in the theme provider. The useTheme hook is our current way of getting the theme. These examples just haven't been updated.

Can you provide a link to a reduction that uses the current standard for theming?

The List component itself doesn't contain any theming or styling opinions, so I really hesitate to investigate further without a verified reproduction using the modern approach to theme.

I'm going to close for now, but please feel free to re-open if you're able to get a reproduction.
