### ISSUE TITLE
[Bug]: textarea with full height sizing issue

### ISSUE THREAD

**Issue by pellea** [microsoft/fluentui#30370]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
"@fluentui/react-components": "^9.42.0",
    "@fluentui/theme": "^2.6.38",
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/festive-haze-k38f8z?file=/src/App.tsx

## Actual Behavior
The "input" of the textarea doesn't grow with the parent (scrollbar, grip, editable surface ...).
And then, the resize grip of the textarea stops at the middle of the height while the whole component stretch correctly.
It seems there are a maximum height set somewhere.

![image](https://github.com/microsoft/fluentui/assets/395982/f8f1fccc-1d1c-4732-874c-d83eb9062308)

## Expected Behavior
The resize grip and the editable area are positioned/stretched at the bottom of the textarea

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by pellea** [comment]
I use TailwindCSS in my production project; so makeStyles/useStyles are not my default styling options. Using `style` directly was only for the demo.

Setting `maxHeight: 'unset'` make the component behavior even worst! Now, if I use the resize grip, it can overflow out of the "blue" area.

![image](https://github.com/microsoft/fluentui/assets/395982/40f4acb2-13e3-4965-96a5-787f74a71f9f)

or go smaller than the blue area ...

![image](https://github.com/microsoft/fluentui/assets/395982/a8eefb1a-941b-4777-8df9-ed246c6801b0)

This is clearly a bug. A component should not behave like this. 
If this is by design, I'll simply use the "usual/normal" textarea.

**Comment by sopranopillow** [comment]
Oh okay, I see what you're trying to do. The way you should think about Textarea is that you have the actual textarea and the wrapper, the wrapper is like a blanket trying to take the form of the inner one. This is a limitation we take due to its design. Usually, you should set height related styles on the textarea slot, but in this case we want to  have that and the wrapper take the available width of your section element. To do this, you need to do the following: https://codesandbox.io/p/sandbox/serene-sunset-w67dg9?file=%2Fsrc%2FApp.tsx%3A29%2C35. Since we only want to allow resizing the vertical direction, there's no need to do anything to the height, except remove the max height limitation coming from our design.

**Comment by aeltorio** [comment]
@sopranopillow 
Your example on codesandobx does not exist anymore. Could you explain how do you solve this issue ?
Ronan

**Comment by sopranopillow** [comment]
@aeltorio you have to apply a classname with makeStyles to the 
```ts
const useStyles = makeStyles({
    textarea: {
        maxHeight: 'unset'
    }
});

const YourComponent = () => {
    const styles = useStyles();
    return <Textarea textarea={{ className: styles.textarea }} />
}
