### ISSUE TITLE
[Bug]: Menu close with Escape do not call `stopPropagation` by default

### ISSUE THREAD

**Issue by marcosmoura** [microsoft/fluentui#30384]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.15 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome Canary: 122.0.6261.3
    Edge: 120.0.2210.144
    Firefox Nightly: 117.0a1
    Safari: 17.2.1
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codesandbox.io/p/sandbox/throbbing-dream-v9p9vh?file=/example.tsx:45,22

## Actual Behavior
When a Menu component is inside another container that also closes on Escape press, closing the Menu will trigger both events. In this case, the parent container will also close, when it shouldn't

## Expected Behavior
The Menu component should call `stopPropagation` to prevent the event to bubble up.

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by bsunderhus** [comment]
We've decided to go with default prevention instead of stopping propagation https://github.com/microsoft/fluentui/pull/29262,.

In a library level you cannot assume much of what the application will be doing with click/keydown events.

To solve this problem you should verify if the `event` is prevented to decide if you can react to it or not, Like in this [example](https://codesandbox.io/p/sandbox/dreamy-kowalevski-94sqxc?file=%2Fexample.tsx)
