### ISSUE TITLE
[Bug]: useArrowNavigationGroup with grid or grid-linear navigation in RadioGroup doesn't update checked option as expected

### ISSUE THREAD

**Issue by marciat** [microsoft/fluentui#30558]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 58.24 GB / 62.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/p/sandbox/intelligent-bird-j5wnhr?file=%2Fsrc%2Fexample.tsx

### Bug Description

Scenario description: We want to have radio buttons displayed in a grid. Since there are 25 items, we want to facilitate keyboard navigation by having bi-dimensional grid navigation. We tried using `useArrowNavigationGroup` with `grid` and `grid-linear` axis. The radio group is not inside a toolbar.

## Actual Behavior
When navigating through the radio buttons with the arrow keys, the selected option is not always the option in focus. Only in some cases does moving the focus also change the selected option. With `grid-linear` axis the selected option only moves with the focus in the following cases:
- when focus is on the first row and the user presses Up arrow, or in the last row when user presses Down arrow;
- when focus is on the first option and the user presses Left/Up arrow, or in the last option when the user presses Right/Down arrow.

With `grid` axis, it also happens when the focus is on the the first column and the user presses Left arrow, or in the last column when the user presses Right arrow.

In all other cases, the focus moves around the options, but the checked option doesn't change. User needs to press Space key to select the focused option.

## Expected Behavior
We expect that the selected option will be the option that is focused. As the focus moves around the options, the selected option would also update. [Radio Group Pattern - Keyboard Interaction](https://www.w3.org/WAI/ARIA/apg/patterns/radio/#:~:text=Right%20Arrow,the%20last%20button.)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
From an accessibility perspective, you have two options here:
1. Do not implement bi-directional arrow key navigation of radio options
2. Use a selectable grid instead of radios

The reason is that radios do not have row/column semantics, and the keyboard behavior in that codesandbox will essentially be entirely random and create a broken experience for a blind or low vision screen reader user.

My personal suggestion would be to go with option 1, and remove the bi-directional keyboard behavior. Even though it seems to give more efficiency at first glance, unless your options are actually meaningfully associated by row/column (e.g. if columns are hue and rows are lightness in a color picker), differentiating left/right and up/down would be obfuscating understanding rather than aiding in it. If your columns and rows are based on meaning rather than layout, then a grid would be a good choice over radio buttons.

The technical reason why the keyboard behavior in the codesandbox is buggy is because the tabster keyboard behavior that handles the custom arrow key navigation is warring with the native HTML arrow key behavior of radio inputs. When tabster doesn't do anything with an arrow key press (e.g. if you hit down arrow at the end of a column), then the native browser behavior takes over, and also moves selection. If you wish to override the native browser behavior of radio inputs, you would need to take over not only the arrow key navigation, but also selection. In this case, I strongly recommend against doing so for the reasons above :).

I hope that addresses your use case & gives a couple possible solutions! Let me know if you have any questions on the accessibility info :)
