### ISSUE TITLE
[Bug]: Fluent UI Spin Button Styling

### ISSUE THREAD

**Issue by lipalath-ms** [microsoft/fluentui#30569]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
npx envinfo --system --npmPackages '{@fluent/*}' --browsers
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/lipalath/pen/yLwwLXW

### Bug Description

I have a [spin button](https://codepen.io/lipalath/pen/yLwwLXW) created using Fluent UI.

      const styles: IStyleFunction<ISpinButtonStyleProps, ISpinButtonStyles> = (props: ISpinButtonStyleProps) => {
      const { theme } = props;
      return {
        spinButtonWrapper: [
          { 
            width: 300,
            borderColor: theme.palette.yellow
          }          
        ],
      };
    };
    
    const SpinButtonCustomStyledExample: React.FunctionComponent = () => {
      return (
        <SpinButton
          styles={styles}     
          defaultValue="0"
          label="Custom styled SpinButton"
          min={0}
          max={100}
          step={1}
        />
      );
    };

I need it's border color to be theme.palette.yellow

And when the screen size changes, I don't see the spin button width getting updated

[![enter image description here][1]][1]

 [1]: https://i.stack.imgur.com/tmUjh.png

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Hi @lipalath-ms! The reason the color isn't changing is because the `border-color` style is applied to an element that does not have a border. The visual border is actually an `:after` pseudo-element, not on the `spinbuttonWrapper` element itself. If you use the following style block, the border color updates to yellow:

```js
spinButtonWrapper: [
    { 
        width: 300,
        
        '&::after': {
            borderColor: theme.palette.yellow
        }
    }          
],
```

The reason the input isn't changing when the screen size changes is because of the `width: 300` that was also added in the same style block. If you remove that, the input reduces in width until it hits the defined `minWidth`.

Let us know if you have any other styling questions! For general (non-bug) questions, we'd generally prefer using the github discussions tab, or our internal Teams channel. Feel free to re-open this if there is a bug you're encountering that I missed, though.
