### ISSUE TITLE
[Feature]: Enable TagPicker to add new Tags

### ISSUE THREAD

**Issue by CrytoxXD** [microsoft/fluentui#30611]
### Library

React / v8 (@fluentui/react)

### Describe the feature that you would like added

As already requst in this Issue #9008 it would be good to have a simple way to add new tags. 

The use-case at hand would be that a customer want to add new tags by pressing enter while using the picker.
Currently there is a workaround using onItemSelected and the keyDown Event with Input Debouncing but that is a rather hacky way of doing it.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

None

**Comment by smhigley** [comment]
We're generally not adding new features to Fluent v8, since we are encouraging teams to migrate to v9. The v9 tagpicker is currently being worked on, and I'll tag @ling1726 for visibility on this feature request for v9.

If you're willing to create a PR for this feature or for a docs example demonstrating how to create it with `onItemSelected`, I'd be happy to review it, though we can't commit to merging new v8 features. My suggestion would be to go with the current workaround, and update to the v9 picker when it's available and when you're able to.

Would those options address your use case?

**Comment by CrytoxXD** [comment]
Hello,

I understand. We were already looking into migrating to v9 for some time. I didn't offer some features we require though, so we decides to go with v8 for the time being. 
I thank you for telling me! 

Once the TagPicker is implemented, we'll migrate.

Thank you for your time!

**Comment by OpenSource03** [comment]
For anyone wandering, it is possible to do so. Here is the code (options should be useState):
  
```tsx
    <TagPickerInput
      aria-label="Select Employees"
      onChange={(e) => {
        const value = e.target.value;
  
        if (value.includes(",")) {
          const newOption = value.replace(",", "");
          addOption(newOption);
          setSelectedOptions([
            ...selectedOptions,
            newOption,
          ]);
          e.target.value = "";
        }
      }}
    />
```
