### ISSUE TITLE
The builds are broken

### ISSUE THREAD

**Issue by mltejera** [microsoft/fluentui#30711]
Noticing two things that look related:

This has repro'd on lastet master on both my, and Mak's machines:

![image](https://github.com/microsoft/fluentui/assets/17346018/6aa1e885-ee72-48a9-8306-42b47c545cca)

All my PR's are broken in the CICD:

![image](https://github.com/microsoft/fluentui/assets/17346018/562bb439-ab9c-4762-8d1d-cee6085efb17)

**Comment by Hotell** [comment]
thanks for report.


> Noticing two things that look related

this has nothing to do with build per say. 

It's bug in the generator - if you provided `--project` flag explicitly it would pass. Also it tells you to pass `--verbose` to get stack-trace which could navigate you to the root cause ;). 

Every generator comes with `--help` flag,  I encourage folks to try that first ( to get better sense about customizations available, which might help you unblock a particular problem ATM). 

@ValentinaKozlova  pinged me about it yesterday evening but didn't manage to create issue for that as it was bit late.  

I fixed it already https://github.com/microsoft/fluentui/pull/30708.


> All my PRs are broken 

wondering if you have clicked on that pipeline, which should tell you which dependencies are mismatched. Also your PR tells you that your branch is "out of date" which is related to your failure.

This is the failure report from your pipeline.

<img width="1018" alt="image" src="https://github.com/microsoft/fluentui/assets/1223799/ed01a4ac-f510-4103-8f8a-3d4f80d95c7b">

I'm wondering what more can be done from DX POV so folks can self service their things ?

**Comment by Hotell** [comment]
I don't see any actionable in terms of "fixing" this issue as there is nothing to be fixed. Feel free to close this or happy to answer further questions. ty

**Comment by behowell** [comment]
@Hotell for context on the PR build syncpack issue. It was caused by the `react-tag-picker-preview` package being merged with an out-of-date package version at the time it was merged to master:
https://github.com/microsoft/fluentui/commit/ebaa4f3a81246de9311b72600e6d5dd98240c383#diff-284d232ca2a788613f1492ec8c9a38a00195a804264f581379ff401f0994587d

The problem was fixed by an automated package update, 2 days later:
https://github.com/microsoft/fluentui/commit/73dd463eb6d3c9dfbaabb4a080b585516b17b31f#diff-284d232ca2a788613f1492ec8c9a38a00195a804264f581379ff401f0994587d

That issue broke all PR builds for the 2 days before it was fixed. It wasn't an error in the PR, nor something that could be fixed by the PR author.

It didn't seem to break the main pipeline build. It might be that -preview package versions aren't checked in the main pipeline?

**Comment by mltejera** [comment]
I'm back up and running, so going to close this. Thanks for the investigation 🍻
