### ISSUE TITLE
[Feature]: makeStyles should accept for function style 

### ISSUE THREAD

**Issue by rhalaly** [microsoft/fluentui#30727]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

Please add React Hooks for styling like in React-JSS or Material-UI libraries, that will allow to access the theme object directly and release the dependencies of 3rd party libraries.

### Additional context

```
const useStyles = makeStyles((theme: ITheme) => ({
    root: {
        color: theme.palette.themeLighterAlt,
        fontSize: theme.fonts.superLarge,
    }
});

const MyButton: React.FC = () => {
    const classes = useStyles();

    return <DefaultButton classNames={classes.root} />
}
```

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by ling1726** [comment]
`makeStyles` that is imported from Fluent is actually a direct re-export of [Griffel](https://griffel.js.org/). This library is also owned by the Fluent UI team.

The reason that `makeStyles` does not support any runtime parameters/arguments is because of [ahead of time compilation](https://griffel.js.org/react/ahead-of-time-compilation/introduction). This means that styles can be compiled at build time to avoid any computation cost at runtime.

The theming of Fluent UI is based on [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) which is completely independency of any third party. You can see an example of styling using Fluent UI

```ts
import { makeStyles, tokens } from '@fluentui/react-components';

const useStyles = makeStyles({
  root: { display: 'flex' },
  rootPrimary: { color: tokens.colorNeutralForeground3 },
});
```

`tokens` are completely independent and there is absolutely no need for it to be used. Can you please provide more details on what 3rd party libraries you would like to remove as a dependency?

**Comment by rhalaly** [comment]
I wasn't aware of the `tokens` object. Thank you so much!
