### ISSUE TITLE
How to custom color theme through ThemeDesigner?

### ISSUE THREAD

**Issue by Moixiao** [microsoft/fluentui#30788]
### Discussed in https://github.com/microsoft/fluentui/discussions/30787

<div type='discussions-op-text'>

<sup>Originally posted by **Moixiao** March 15, 2024</sup>
We have the need to custom theme color based on the customer's needs, but after I type the Hex code that I want to use, why there's no exact value in the "generated palatte"? How does it really work if there's no matching color?
![WechatIMG28563](https://github.com/microsoft/fluentui/assets/28536133/51ba3141-7bca-44e2-8868-76ad1a56ec20)

</div>

**Comment by micahgodbolt** [comment]
The colors generated aren't guaranteed to include your key color because the colors are chosen at equal points across a color spectrum. This guarantees proper contrast between points. If you need a palette that includes your specific key color, you'll need to manually craft that theme, though the above theme will be a great starting point.
