### ISSUE TITLE
[Bug]: InteractiveTag brand appearance needs better contrast

### ISSUE THREAD

**Issue by mfishma** [microsoft/fluentui#30904]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
n/a
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://react.fluentui.dev/?path=/docs/components-tag-interactiontag--default#appearance

## Actual Behavior
1. go to https://react.fluentui.dev/?path=/docs/components-tag-interactiontag--default
2. Change the theme to "Teams Dark"
3. scroll down to _[Appearance](https://react.fluentui.dev/?path=/docs/components-tag-interactiontag--default#appearance)_ section
4. Since button is using Foreground: BrandForeground1 with Background: BrandBackground2, the contrast is 4.04:1
![image](https://github.com/microsoft/fluentui/assets/1066582/49b4937e-c862-4c6a-b10e-cb2a6648ef73)

## Expected Behavior
Contrast of the InteractiveTag should be 4.5:1. Likely, the foreground was meant to be BrandForeground2 instead of 1. This would be consistent with the "Tag" component rest state for brand, as well as with the Outline appearance, all of which use foreground version "2" of the colors. 
Changing this to BrandForeground2 gives it a 6.38 contrast, and improves all theme's contrast for the brand appearance, too, bringing Web Light's version from 4.8:1 to 5.94:1 for example.
![image](https://github.com/microsoft/fluentui/assets/1066582/94bc0064-a65d-48eb-94a1-2ba4643ff77b)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by YuanboXue-Amber** [comment]
Hi, this is by design. The contrast requirement we are targeting is:
>text should have a 4.5:1 contrast ratio against its background. Large text (over 24px) only needs a 3:1 contrast ratio

The current result is a compromise because of the existing issue with color tokens:
InteractionTag should have back background on rest. However the brand token with black background on rest is colorBrandBackground2, but it has the same color on hover/pressed state (#28478). Because of this, we chose colorCompoundBrandForeground1 for hover/press. We use colorBrandForeground1 for default state because colorBrandForeground2 recommended in the issue description has the same color as colorCompoundBrandForeground1Hover in many themes:
<img width="822" alt="image" src="https://github.com/microsoft/fluentui/assets/28751745/9d519720-cac8-4a1a-b4dc-3104d5d8191a">
