### ISSUE TITLE
[Bug]: Keyborg error on Popover close when Dropdown is used inside Popover

### ISSUE THREAD

**Issue by capturetheflags** [microsoft/fluentui#30961]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Latest version of @fluentui/react-components: 9.47.3
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-fgyuuu?file=src%2FApp.tsx

## Actual Behavior
Opening and closing a Popover containing a Dropdown produces console errors from the library's Keyborg dependency

![image](https://github.com/microsoft/fluentui/assets/50559087/514ee49d-fcdb-44a6-b15d-c7adf5631c30)

## Expected Behavior
No errors should be produced

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
Verified the issue repros with a `Dropdown` that contains `Option`s. 

https://stackblitz.com/edit/stackblitz-starters-7rzxtt?file=src%2FApp.tsx

Issue does not repro when `Button` is used in place of `Dropdown` in the example.

Assigning to @microsoft/teams-prg since the issue seems to be in Keyborg even though it manifests in this example with `Popover` + `Dropdown`.  There is no direct usage of Keyborg in `Dropdown` or `Popover`.

**Comment by 15MariamS** [comment]
👋 I also get this on both combobox and dropdown used in my web app
