### ISSUE TITLE
[Bug]: Accessibility issue | Text Spacing not proper in fluent-ui component's DefaultButton, Combobox, CommandBar and SearchBox 

### ISSUE THREAD

**Issue by vijaykumarsaurav** [microsoft/fluentui#31206]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
$ npx envinfo --system --npmPackages '{@fluent/*}' --browsers
npm WARN exec The following package was not found and will be installed: envinfo@7.12.0

  System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 10.71 GB / 31.77 GB
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting Accessibility issue?

no

### Reproduction

![image](https://github.com/microsoft/fluentui/assets/14073515/aa0011f0-8183-4c6f-a28e-059de52d4c96)  

## Actual Behavior
fill this out
Accessibility issue | Text Spacing not proper in fluent-ui component's DefaultButton, Combobox, CommandBar and SearchBox 
![image](https://github.com/microsoft/fluentui/assets/14073515/c19f32d3-3f96-4e31-a11f-ca09f11ad8ad)
![image](https://github.com/microsoft/fluentui/assets/14073515/2c580a36-3249-48fd-b0ae-3117fab217cf)
![image](https://github.com/microsoft/fluentui/assets/14073515/8efc8fbc-5e61-455c-b99d-7862ef19778a)
Reproduce 
![image](https://github.com/microsoft/fluentui/assets/14073515/aa0011f0-8183-4c6f-a28e-059de52d4c96)  

## Expected Behavior
fluent-ui component's DefaultButton, Combobox, CommandBar and SearchBox  should show spacing as like ag-grid shown on screenshot while Accessibility testing.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
Hi, thanks for logging the issue! This actually looks like an accessibility insights bug rather than one on Fluent or on your product.

The [text spacing bookmarklet](https://codepen.io/stevef/pen/YLMqbo/) I use to test that criterion actually works fine on Fluent's buttons and TextField placeholder styles:

<img width="846" alt="screenshot of various buttons in a docs site. All the buttons, as well as the surrounding documentation text have spaced-out letters." src="https://github.com/microsoft/fluentui/assets/3819570/7f929b99-7d90-4422-82f6-a025fa79263e">

To better explain why this is not an author bug, it helps to understand that the [text spacing criterion](https://www.w3.org/WAI/WCAG22/Understanding/text-spacing.html) requires authors to not break content or functionality when text spacing styles are applied. It does _not_ cover respecting any particular tool's text spacing styles. This difference is largely because in contrast (heh) to things like Windows Contrast Themes or screen readers, there is no set specific tool for applying or testing text spacing. Some tools like browser reader mode do it (while also overriding literally all styles), and there are some browser extensions that do it.

As long as we're not doing anything egregious to prevent text spacing styles from working, it is not an authoring responsibility to troubleshoot how a specific tool applies styles, and all the more so when it is not an end-user-facing tool (which a11y insights is not). My guess is that Accessibility Insights simply hasn't ironed out all edge cases in their own text spacing script.
