### ISSUE TITLE
[Bug]: Re-open: Text in dropdown box and dropdown list wraps when overflows

### ISSUE THREAD

**Issue by chenxinyanc** [microsoft/fluentui#31492]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
@fluentui/react-components v9.53.0 (Using StackBlitz)
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/ka9zb6?file=src%2Fexample.tsx

### Bug Description

Re-opened #28659 per soft-close instruction. I'm not sure but it seems the previous issue has been auto-closed without resolution. The issue might be similar to #27824 but this one discusses single item selection instead of multiple selection.

## Actual Behavior

![image](https://github.com/microsoft/fluentui/assets/50703224/149e6b2c-801f-4d87-87c0-9cfb7eaf90b5)

![image](https://github.com/microsoft/fluentui/assets/50703224/9176017b-7983-44a8-8c71-6548777220f0)

## Expected Behavior

I expect something just like plain-old Fluent UI v8.

![image](https://github.com/microsoft/fluentui/assets/50703224/930e7f83-56af-4f88-b897-52fbf2628d5e)
![Recording_20230727T210734](https://github.com/microsoft/fluentui/assets/50703224/fcfe9b5b-e163-4d96-a0ba-65feed34199f)

### Requested priority

Normal

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@chenxinyanc we actually intentionally moved away from truncating text in Fluent v9 for accessibility reasons. Truncating text disproportionately impacts low-vision users who are using zoom, which causes text to truncate more frequently, while conversely making tooltips more difficult to access (assuming someone is using a combination of static zoom and zooming software like ZoomText, which is quite common).

Additionally, showing the full text in a tooltip is pretty inaccessible itself, since tooltips are inherently fairly inaccessible. They are only available to users who use either a pointer with hover or (sometimes) keyboard. That leaves out touch (which also is more common on smaller screens, where truncation is also going to show up more), voice control, eye gaze, switch, etc.

The example showing how to customize styles to have truncation is there for any teams that have a hard design requirement for truncation, but we'd generally recommend allowing text wrapping if at all possible.

Let me know if that all makes sense and explains why we went the way we did with styles!
