### ISSUE TITLE
[Bug]: Rendering issue of Combobox Component in some specific width range.

### ISSUE THREAD

**Issue by qjkobe** [microsoft/fluentui#31761]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
```

### Are you reporting Accessibility issue?

no

### Reproduction

https://stackblitz.com/edit/6gtzhg?file=src%2Fexample.tsx

### Bug Description

Go to the reproduction link.

## Actual Behavior
When the width of the Combobox become larger and over the center of the page and the Combobox is in the half buttom of the page, dropdown popover will render the list overflowing the top. For convenience, I use 100% width to reproduce this problem.
![image](https://github.com/microsoft/fluentui/assets/16449598/3b85d3bf-521d-4d40-a25f-8eb69deef94b)

## Expected Behavior
Set width to a small size, then it run well.
![image](https://github.com/microsoft/fluentui/assets/16449598/ea058e9b-29fd-4122-91bd-22bba6923a28)

### Logs

```shell
NA
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
Hi @qjkobe 👋🏻 

I think it's expected behavior. This is how [flip](https://floating-ui.com/docs/flip) works. 
In order to ignore automatic flipping, try to use `pinned` prop, it disables automatic repositioning of the component, it will always be placed according to the values of `align` and `position` props, regardless of the size of the component, the reference element or the viewport.

```jsx
 <Combobox
      positioning={{
         pinned: true,
         position: 'below',
      }}
      className={styles.root}
      onOptionSelect={onOptionSelect}
      aria-labelledby={comboId}
      placeholder="Select an animal"
      onChange={(ev) => setQuery(ev.target.value)}
      value={query}
    >
      {children}
   </Combobox>
```


<img width="587" alt="Screenshot 2024-06-19 at 17 09 03" src="https://github.com/microsoft/fluentui/assets/14054752/b5aaf8ea-4bc1-444e-9b98-ae2af526643b">

**Comment by qjkobe** [comment]
Hi @mainframev ,
I get your point that it's behavior of "flip" to change the popover dropdown to the top of the control. However, the problem is that when the popover drop down is re-positioned to the top, why isn't the height of the popover calculated agian? That's the root cause of the hidden options. 
If I change the position to pinned and turn it to bottom forever, some a11y issues may happen that there are 2 scroll bar:
![image](https://github.com/microsoft/fluentui/assets/16449598/8fcfe788-08a8-42dd-a10e-f331d301cfb8)

**Comment by mainframev** [comment]
Hi @qjkobe 👋🏻 

Thank you for quick response. Now got it, In order to prevent the content overflowing by viewport you can use combination of `autoSize` prop in `positioning` (fits popping content available space in viewport)

```jsx
<Combobox
      positioning={{
        autoSize: true,
        overflowBoundaryPadding: {
          top: 10,
        },
      }}
      className={styles.root}
      onOptionSelect={onOptionSelect}
      aria-labelledby={comboId}
      placeholder="Select an animal"
      onChange={(ev) => setQuery(ev.target.value)}
      value={query}
    >
      {children}
    </Combobox>
    // </Field>
  );
```

![ScreenRecording2024-06-20at9 49 00-ezgif com-video-to-gif-converter](https://github.com/microsoft/fluentui/assets/14054752/063b70a5-9889-49f6-b80e-4f65a3bc3fdc)

**Comment by qjkobe** [comment]
Hi @mainframev ,
Amazing! it works for me.
I tried overflowBoundaryPadding property before, but I didn't know this property only takes effect when setting autoSize true.
Anyway, I'll close this ticket. Thank you very much
