### ISSUE TITLE
[Bug]: ComboBox and TextField components shared the same autofill data.

### ISSUE THREAD

**Issue by javierzc05** [microsoft/fluentui#31820]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 7.64 GB / 31.71 GB
  Browsers:
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://codepen.io/jzaldivar05/pen/JjqaxXP

## Actual Behavior
When a ComboBox and a TextField component have similar IDs, the browser's autofill functionality unexpectedly fills both inputs with the same data.

<img width="923" alt="image" src="https://github.com/microsoft/fluentui/assets/29607173/85d03e1f-c70b-44ef-bed1-117cc844f5fb">

## Expected Behavior
Only the hovered/selected input is autofilled.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This behavior is handled by the browser, not by Fluent. The issue here is that there are two unlabelled inputs on a page (which is also a major accessibility issue beyond just autocomplete). The browser is doing its best-guess at what autofill information should go in each field based on a combination of heuristics, but it doesn't have enough information to differentiate the two fields, so it's guessing `tel` for both.

If you label each field, this issue goes away. You can also provide an explicit `autoComplete` value for the TextField, though the value of `off` is sometimes not respected.

**Comment by javierzc05** [comment]
So by adding aria-labels would fix the issue? Please provide code examples so the issue can be fully discarded

**Comment by javierzc05** [comment]
I tried adding labels and the autoComplete="off" and the isse is still repro. I wouldn't close this issue just yet.
