### ISSUE TITLE
[Bug]: [Screen reader]: Selected option name is included as part of the label for all the dropdowns 

### ISSUE THREAD

**Issue by rutuja** [microsoft/fluentui#31822]
### Library

React Northstar / v0 (@fluentui/react-northstar)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (20) x64 Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz
    Memory: 92.26 GB / 127.71 GB
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (126.0.2592.61)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/

## Actual Behavior
Text value for dropdown is read out multiple times
Here is the dropdown control
![image](https://github.com/microsoft/fluentui/assets/1624684/11166102-3f63-451a-b88c-f6da9c8b5434)

Here is the screenshot of how narrator is reading
![image](https://github.com/microsoft/fluentui/assets/1624684/7cf6462a-6c7e-4b25-805d-6ea5b0b599a5)

## Expected Behavior
Should not read the text value multiple times

Also Aria-labelledby is generated based on text values from 2 div (label and data). That needs to be changed to aria-describedBy

### Logs

```shell
NA
```

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
This was by design, from when browsers did not calculate a value for elements with `role=combobox`, aside from `<input>` elements. Now that modern browsers reliably calculate the value from the text content, we could drop it from the accessible name. We would actually not want to put it in the description (value is too important to be hidden in a description, hence why it was in the accName).

@rutuja since this was originally tagged on Northstar but the description seems to match v8 and there was no repro, could you confirm if this is about the v8 Dropdown? (https://developer.microsoft.com/en-us/fluentui#/controls/web/dropdown)
