### ISSUE TITLE
[Bug]: Tooltip inside popover doesn't get automatically displayed on focus

### ISSUE THREAD

**Issue by ahmedlhanafy** [microsoft/fluentui#31862]
### Library

React / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 71.73 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Chrome Canary: 128.0.6563.0
    Firefox: 127.0.2
    Safari: 17.5
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/dgt2no?file=src%2Fexample.tsx

### Bug Description

Tooltip inside popover doesn't get automatically displayed on focus

https://github.com/microsoft/fluentui/assets/7052827/d51c090f-78db-433c-87ce-d5ff4477cdfc

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by smhigley** [comment]
@ahmedlhanafy we actually have specifically coded Tooltip to not show when the control receives focus programmatically, for a few reasons:
- Focus moves to the first focusable element regardless of wither the user is using the mouse vs. keyboard.
- We generally don't want an auto-showing tooltip when someone opens or closes a menu, popup, or other similar UI.
- We generally want tooltips to show only when the user has taken an action to make them show (or intentionally interacted with the control they are attached to)

If you have a use case where the button with the tooltip is the only focusable item inside a Popover, making it impossible for the user to tab to the button, I might suggest making the Popover surface itself focusable via `tabindex="-1"`. That will make focus move to the Popover as a whole when opened, instead of to the button, and is what we recommend for cases where the Popover has no focusable items. Our Default example shows this behavior: https://react.fluentui.dev/?path=/docs/components-popover--default

Would that solve your use case?

**Comment by ling1726** [comment]
@behowell are we ok to merge #31887 to fix? This affects Teams
