### ISSUE TITLE
[Feature]: Optimize CSS in JS syntax

### ISSUE THREAD

**Issue by ljianc** [microsoft/fluentui#31979]
### Library

React Components / v9 (@fluentui/react-components)

### Describe the feature that you would like added

use [Griffel](https://griffel.js.org/):   Need to manually define class names and write hooks，There are too many duplicate template codes
```
import { makeStyles } from '@fluentui/react-components';

const useStyles = makeStyles({
  root: { color: 'red' },
});

function Component() {
  const classes = useStyles();

  return <div className={classes.root} />;
}
```
use  [emotion](https://emotion.sh/docs/object-styles): only write properties
```
 <div
    css={{
      color: 'darkorchid',
      backgroundColor: 'lightgray'
    }}
  >
    This is darkorchid.
  </div>
```

hope to imitate the syntax of **emotion**, Or replace **griffel** with **emotion**

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Priority

Normal

**Comment by khmakoto** [comment]
Hi @ljianc, thanks for filing this issue. Unfortunately, we have no plans of switching to `emotion`. The reason why `griffel` has that kind of API is because we need to ensure the CSS in JS is the same independent of runtime because of build time optimizations it has to make the code more performant, and in this case, much more performant than `emotion`.
