### ISSUE TITLE
[Bug]: Combobox/Dropdown listbox doesn't respect classname props

### ISSUE THREAD

**Issue by 15MariamS** [microsoft/fluentui#31972]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (14) arm64 Apple M3 Max
    Memory: 113.97 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.4
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/gp6nrz?file=src%2Fexample.tsx

## Actual Behavior
Listbox no longer respects the classname props, especially for setting the max height on the listbox.

## Expected Behavior
Listbox respects the max-height prop passed in the useStyles

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
The `maxHeight` is automatically applied because of our positioning logic, if you want to specify your own `maxHeight` you have to turn off height auto sizing by passing `positioning={{ autoSize: 'width' }}` if you only want our positioning logic to auto size the width or `positioning={{ autoSize: false }}` if you want to turn off auto sizing completely, after which your `maxWidth` and `maxHeight` props will be correctly applied.

You can see that in action [here](https://stackblitz.com/edit/gp6nrz-cx68ll?file=src%2Fexample.tsx).

Let me know if I can help with anything else!
