### ISSUE TITLE
[Bug]: Tooltip for PivotItem does not display with keyboard focus

### ISSUE THREAD

**Issue by Antonio-Microsoft** [microsoft/fluentui#31980]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 27.09 GB / 47.71 GB
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting Accessibility issue?

yes

### Reproduction

https://codesandbox.io/p/sandbox/festive-haslett-xctv7r?workspaceId=17876e36-3fe3-4734-81c5-5dfee5cb9d75&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyhj0pi300063j6j6ev97cci%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyhj0pi300023j6ju3feisyv%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyhj0pi300033j6jy34m4z42%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyhj0pi300053j6jqii7m6r9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyhj0pi300023j6ju3feisyv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhj0pi300013j6jzizqqxmc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A1%257D%255D%257D%252C%257B%2522id%2522%253A%2522clyhj6msr00023j6jm9pkxmym%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clyhj0pi300023j6ju3feisyv%2522%252C%2522activeTabId%2522%253A%2522clyhj6msr00023j6jm9pkxmym%2522%257D%252C%2522clyhj0pi300053j6jqii7m6r9%2522%253A%257B%2522id%2522%253A%2522clyhj0pi300053j6jqii7m6r9%2522%252C%2522activeTabId%2522%253A%2522clyhk3opq004u3j6j10olca2a%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhj0pi300043j6jol8qcixl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clyhj6n3k00093j6j9bj8lk6y%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clyhk3opq004u3j6j10olca2a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyhj0pi300033j6jy34m4z42%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyhj0pi300033j6jy34m4z42%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

## Actual Behavior
Hovering over a PivotItem button with the mouse cursor displays the tooltip but whenever user tries to focus a PivotItem button with their keyboard, the tooltip does not display.

## Expected Behavior
Hovering over a PivotItem button with the mouse cursor displays the tooltip and focusing the PivotItem button with the keyboard also displays the tooltip.

### Requested priority

Blocking

### Products/sites affected

https://ra.ev2portal.azure.net/

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by khmakoto** [comment]
Hi @Antonio-Microsoft, this happens because the `TooltipHost` is wrapping the internals of the button that you are focusing and not the button itself, therefore not triggering the `onFocus` and `onBlur` methods of the div created by the `TooltipHost`. Unfortunately, the design of `Pivot` doesn't allow you to wrap these buttons via its API. A workaround, however, is to get a ref to the host and imperatively show and dismiss the tooltip `onFocus` and `onBlur` of the `PivotItem's` header button.

You can find that workaround [here](https://codesandbox.io/p/sandbox/tooltips-on-pivotitem-links-kzwhf5?file=%2Fsrc%2FApp.tsx%3A13%2C28). I hope this helps!

**Comment by Antonio-Microsoft** [comment]
Appreciate the help, the workaround you provided works perfectly, thank you!

**Comment by Antonio-Microsoft** [comment]
Hello again, in the workaround you provided, I noticed that a screen reader (Microsoft Edge "Read aloud this page") is unable to read out the tooltip even if an appropriate aria-describedby attribute is added. Is there guidance as to how one could enable screen reader functionality with a tooltip? I provided I fork to your workaround below which contains the code I tried for a screen-reader.
https://codesandbox.io/p/sandbox/tooltips-on-pivotitem-links-forked-92ct5w?file=%2Fsrc%2FApp.tsx%3A52%2C31

**Comment by khmakoto** [comment]
I'm not familiar with the intricacies of Edge "Read aloud". @smhigley do you know what the expected behavior would be here?

**Comment by smhigley** [comment]
@Antonio-Microsoft Edge's read aloud isn't a screen reader, it's a lighter-weight assistive tech for people who want to consume text content through speech. That could be for a number of reasons -- low vision & reducing eye strain, dyslexia or other learning disabilities, migraines, etc. Leaving off descriptions & hint text is an intentional design decision on their part; it's not dissimilar to an audio version of reader mode, and shouldn't be treated like a screen reader or subject to the same expectations for rich non-visual interaction.

That said, tooltips by their very nature are not going to be accessed by a large number of users. That could be because they're using touch even without assistive tech, or a screen reader but at a lower verbosity setting, or voice control, switch access, etc. etc. As long as the tooltip text is mapped to the description in the browser's a11y tree, you've done what you can as a page author. If you put required text into a tooltip, that's a whole separate accessibility issue :D
