### ISSUE TITLE
[Bug]: Overlay DrawerBody scroll bar is hidden when opened to the right

### ISSUE THREAD

**Issue by YufeiMefei** [microsoft/fluentui#32006]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
Macbook Air M2 
Memory: 24GB
OS: Sonoma Version 14.5 (23F79)

Browser: Chrome Version 126.0.6478.127 (Official Build) (arm64)
```

### Are you reporting Accessibility issue?

None

### Reproduction

https://react.fluentui.dev/?path=/docs/components-drawer--default#position

## Repro
* Click on "Open Right"
* Use devtool to change DrawerBody content to overflow height.
* Notice how the scrollbar is hidden, but content is scrollable
* 
<img width="505" alt="Screenshot 2024-07-15 at 3 40 28 PM" src="https://github.com/user-attachments/assets/adc3acd5-006c-43d1-86dc-584cc839affb">

## Actual Behavior
Content in <DrawerBody> is scrollable but scrollbar is hidden

## Expected Behavior
Expect scroll bar to be visible

If parent node <OverlayDrawer>'s `right: 0px` is updated to `right: 10px`, you can see the scrollbar. It seems like the scrollbar is covered because of drawer component positioning.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by sopranopillow** [comment]
Hi @YufeiMefei, I don't think I'm able to repro, I've tried in a stackblitz and the way you explained in your steps. Another thing is that changing things in devtools while is fine, would be a bit harder to say if it's drawer's issue. If this can be also reproed with react, then it definitely is a bug.

tried to repro with react: https://stackblitz.com/edit/2gydwh?file=src%2Fexample.tsx

tried to repro with provided steps:

https://github.com/user-attachments/assets/bdb48955-d715-40c8-be39-b72e60e948be

**Comment by YufeiMefei** [comment]
It was a chromium bug, downloaded older version 126.0.6478.62 and was able to repro. It's fixed in current version 126.0.6478.183. Closing, thanks for looking into this still @sopranopillow

https://github.com/user-attachments/assets/3026309f-8ca1-4726-a350-b14e60d775ee

**Comment by KarlsonxD** [comment]
> Hi [@YufeiMefei](https://github.com/YufeiMefei), I don't think I'm able to repro, I've tried in a stackblitz and the way you explained in your steps. Another thing is that changing things in devtools while is fine, would be a bit harder to say if it's drawer's issue. If this can be also reproed with react, then it definitely is a bug.
> 
> tried to repro with react: https://stackblitz.com/edit/2gydwh?file=src%2Fexample.tsx
> 
> tried to repro with provided steps:
> 
>  Recording.2024-07-25.232103.mp4

I think there is still a bug in the overlay drawer.
I'm using Microsoft Edge for Business Version 131.0.2903.99 and was able to reproduce the bug.
Seems like when the main content has a scrollbar, the overlay drawer suddenly needs a offset, but when the main content doesn't have a scrollbar everything works like expected.
Expected Behaviour: Show Drawer Scrollbar when the overlay drawer is scrollable, no matter if the main content has a scroll bar.
I changed your stackblitz example to reproduce the error: https://stackblitz.com/edit/2gydwh-t95q8t19?file=src%2Fexample.tsx
https://github.com/user-attachments/assets/64e894df-0aea-4282-a709-48379e419276

**Comment by KarlsonxD** [comment]
> Hi [@YufeiMefei](https://github.com/YufeiMefei), I don't think I'm able to repro, I've tried in a stackblitz and the way you explained in your steps. Another thing is that changing things in devtools while is fine, would be a bit harder to say if it's drawer's issue. If this can be also reproed with react, then it definitely is a bug.
> 
> tried to repro with react: https://stackblitz.com/edit/2gydwh?file=src%2Fexample.tsx
> 
> tried to repro with provided steps:
> 
>  Recording.2024-07-25.232103.mp4

I think there is still a bug in the overlay drawer.
I'm using Microsoft Edge for Business Version 131.0.2903.99 and was able to reproduce the bug.
Seems like when the main content has a scrollbar, the overlay drawer suddenly needs a offset, but when the main content doesn't have a scrollbar everything works like expected.
Expected Behaviour: Show Drawer Scrollbar when the overlay drawer is scrollable, no matter if the main content has a scroll bar.
I changed your stackblitz example to reproduce the error: https://stackblitz.com/edit/2gydwh-t95q8t19?file=src%2Fexample.tsx

https://github.com/user-attachments/assets/15a9a689-4ac4-4950-915f-1891b6c0c755

**Comment by KarlsonxD** [comment]
@sopranopillow i think there still is a bug in the overlay drawer, can you reopen the issue or do i have to create a new one?
see my repro in the last comment
