### ISSUE TITLE
Drawer compoent does not show bottom divider when content expands.

### ISSUE THREAD

**Issue by aathavale-microsoft** [microsoft/fluentui#32201]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 112.89 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 127.0.6533.89
    Edge: 127.0.2651.74
    Safari: 17.5
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/ei5w4h?file=src%2Fexample.tsx

## Actual Behavior
We are using Drawer Component in our react app.

The content of the drawer are dynamic. And it has header and footer.

When contents of the drawer expand while we are at the bottom of contents in the drawer, the divider at the top of drawer bottom does not appear.

## Expected Behavior
When contents of the drawer expand while we are at the bottom of contents in the drawer, the divider at the top of drawer bottom should appear.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
@aathavale-microsoft Can you update the repro link please. It's not pointing to a project at the moment.

**Comment by aathavale-microsoft** [comment]
@spmonahan  done!

**Comment by spmonahan** [comment]
Looks like the problem is that [`scrollState` is what controls the relevant styles](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-drawer/library/src/components/DrawerHeader/useDrawerHeaderStyles.styles.ts#L56-L57) and `useDrawerBody()` [only sets the scroll state on mount and when the body scrolls](https://github.com/microsoft/fluentui/blob/master/packages/react-components/react-drawer/library/src/components/DrawerBody/useDrawerBody.ts#L54-L73).

![screen recording demonstrating the issue](https://github.com/user-attachments/assets/a757aef9-cf0d-47dd-bd18-3190f5a938f9)

**Comment by aathavale-microsoft** [comment]
Product Affected: “Microsoft + Nuance: DAX Copilot”
