### ISSUE TITLE
[Bug]: Increment and Decrement Buttons do not set event.target.id

### ISSUE THREAD

**Issue by mr-github-user** [microsoft/fluentui#32204]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 7.30 GB / 31.83 GB
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://codesandbox.io/s/intelligent-jerry-xryjrd?file=/src/App.js

## Actual Behavior
SpinButton increment and decrement buttons do not set the event.target.id.  Clicking into SpinBox modifying the value and then clicking out sets event.target.id with the SpinBox Id

## Expected Behavior
Increment and decrement buttons should set event.target.id.  I need a way to determine which SpinBox is being modified.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
The reason this happens is that both buttons simply pass their `MouseEvent` through to the change handler so `event.target` in those cases is the button, which lacks an `id` attribute (unless it's set via the slots API). The input also forwards its change event but the `id` is set on this element and `event.target` is the input in this case.

I think the above makes sense given that [`event.target` is the element that was interacted with while `event.currentTarget` is the element with the event listener attached](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget). Of course `.currentTarget` is not available in your change handler 😔 Ideally in your case you would inspect `.currentTarget` which would always have the correct ID regardless of interaction method.

While I don't think we can make a change to the listed "expected behavior" as this would be a breaking change, we should find a way to surface the ID because that's obviously useful 🙂.

**Comment by mr-github-user** [comment]
Interesting, I was thinking that was the problem the ID was attached to the input not the button.  When you mentioned setting the id via the slots API is this what you meant:
```
<SpinButton
    id={subscription.subscriptionId}
    value={subscription.quantity}
    onChange={onSpinButtonChange} 
    incrementButton={
        <Button 
            appearance='transparent' 
            icon={<ChevronUp16Regular 
            id={subscription.subscriptionId} />} 
        />
    }
    decrementButton={
        <Button 
            appearance='transparent' 
            icon={<ChevronDown16Regular 
            id={subscription.subscriptionId} />} 
        />
    }
/>
```

I overwrote the increment and the decrement buttons with my own, and added the id attribute.  It almost works, clicking on the button shows the id as long as you click on the center of the button.  If I click on the edges of the button there is no Id.  It seems to be the same problem, my button is nested inside of another button which does not have an Id.  

Do you have any suggestions?

**Comment by spmonahan** [comment]
Assuming you don't otherwise need or want to override the buttons you can do:

```tsx
<SpinButton
   incrementButton={{ id: 'increment' }}
   decrementButton={{ id: 'decrement' }}
  {...otherPropsHere}/>
```

However, you'll have a similar issue to what you reported because you're likely to click on the chevron icon rather than the button itself so `event.target.id` will not be what you expect.

I think the correct thing is to implement `.currentTarget` (or a different API that accomplishes the same thing).

In the meantime, a work around is:

```tsx
const onChangeFactory = (id: string) => (e, data) => {
    // your SpinButton onChange handler here
    // get `id` from the closure
};

<SpinButton
  id={myId}
  onChange={onChangeFactory(myId)}
/>

<SpinButton
  id={myOtherId}
  onChange={onChangeFactory(myOtherId)}
/>
```

**Comment by mr-github-user** [comment]
The workaround with the onChangeFactory works perfectly.  

I don't think I understand enough about .currentTarget to implement that type of solution.

Thank you for your help!

**Comment by tudorpopams** [comment]
@mr-github-user is the solution provided by @spmonahan good enough for your use case, or should we still keep this issue open?

**Comment by spmonahan** [comment]
@tudorpopams My feeling is we should keep this but think of it as more of an enhancement rather than a bug (though I guess I don't really care what we call it -- it is a good feature to add)

**Comment by mr-github-user** [comment]
> @mr-github-user is the solution provided by @spmonahan good enough for your use case, or should we still keep this issue open?

The solution provided by @spmonahan was good enough to get me what I needed.  Thanks
