### ISSUE TITLE
[Bug]: Unable to uncheck the checkbox after checking it in DetailsList in Fluent UI using the keyboard.

### ISSUE THREAD

**Issue by EbramTawfik** [microsoft/fluentui#32367]
### Library

React / v8 (@fluentui/react)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 26.01 GB / 47.71 GB
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
```

### Are you reporting an Accessibility issue?

yes

### Reproduction

https://codepen.io/EbramTawfik/pen/zYVjGLb

### Bug Description

When navigating through a `DetailsList` using the keyboard, the user is able to check the checkbox for an item by pressing the `Space` bar. However, after checking the checkbox, the user is unable to uncheck it using the `Space` bar again. This issue disrupts keyboard accessibility and usability.

### Requested priority

High

### Are you willing to submit a PR to fix?

no

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by TristanWatanabe** [comment]
@EbramTawfik this behavior is by design. Arrowing up/down moves **selection** only. Ctrl + up/down moves **focus** without selection and then pressing space on the focused row selects it. You can find a similar conversation regarding this on an issue that was closed here: https://github.com/microsoft/fluentui/issues/8406#issuecomment-476726046
