### ISSUE TITLE
[Bug]: NavDrawer: Cannot change the value if the initial value is undefined.

### ISSUE THREAD

**Issue by kkamik** [microsoft/fluentui#32875]
### Library

React Components / v9 (@fluentui/react-components)

### System Info

```shell
https://stackblitz.com/edit/f2xpac?file=src%2Fexample.tsx
```

### Are you reporting an Accessibility issue?

None

### Reproduction

https://stackblitz.com/edit/f2xpac?file=src%2Fexample.tsx

### Bug Description

[screen-capture (1).webm](https://github.com/user-attachments/assets/11399452-a87d-4799-a41e-2075ed6ae19a)

## Actual Behavior
Cannot change "selectedValue" and "selectedCategoryValue" if the initial value is undefined.

## Expected Behavior
Can change "selectedValue" and "selectedCategoryValue" if the initial value is undefined.

### Requested priority

Blocking

### Are you willing to submit a PR to fix?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by mainframev** [comment]
hi @kkamik 👋🏻 

It happens because you are changing the value from undefined to defined, the component has a check for controlled/uncontrolled behaviour. If you will open the console you will see the warning: 

`@fluentui/react-utilities [useControllableState]:
A component is changing an uncontrolled value to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen.
Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

So in your case, you will have to set the default state value to some category, or even the empty string will work.
