### ISSUE TITLE
[Feature]: Addition to Tooltip for managing overflow

### ISSUE THREAD

**Issue by gouttierre** [microsoft/fluentui#33073]
### Area

React Components (@fluentui/react-components)

### Describe the feature that you would like added

In the 8th version, there's a utility feature for managing overflow and tooltips, showcased in the [Tooltip](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip) example titled "Tooltip only on overflow." 

However, in version 9, this particular example is absent from the [ToolTip](https://react.fluentui.dev/?path=/docs/components-tooltip--docs) code samples, leading to some confusion among partners who are updating their products to v9. 

To bridge this transition smoothly for migration, it would be beneficial to include a "Tooltip only on overflow" example in version 9's [React Storybook](https://react.fluentui.dev/).

### Additional context

Reported by Azure Portal [Nicole Thuna]

### Have you discussed this feature with our team

Gouttierre Gomes, Paul Gildea 

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

High

**Comment by tudorpopams** [comment]
@mainframev can you please check if this can be achieved with the current implementation of Tooltip / Overflow?

**Comment by mainframev** [comment]
@tudorpopams @gouttierre 

Hello folks 👋🏻 

I've checked this, v8 Tooltip had a specific property and overflow logic. It's selecting for overflow check either self or parent based on `overflowMode` property passed to `TooltipHost`. The current v9 implementation does not have this and I do not think it should. The visibility of Tooltip based on overflow content can be added additionally by the user. 

[I quickly made a a couple examples](https://stackblitz.com/edit/fu8vhs?file=src%2FApp.tsx) demonstrating this. 

I suggest, that maybe instead of creating a story example of this scenario, provide this issue and our migration doc, that says: 
> _**"overflowMode` => Not supported. If this behavior is needed, the tooltip's visibility can be controlled using the `visible` prop and `onVisibleChange` event."**_  

It's already covered with `controlled` example and adding a simple check for overflowing content via ref should not be a problem for user.

**Comment by dmytrokirpa** [comment]
I suggest we could add the `useIsOverflowing` hook to the core library to streamline both examples. This approach could enhance simplicity and efficiency. Here's the link with your examples slightly updated: 

https://stackblitz.com/edit/fu8vhs-iz3vyv?file=src%2FuseIsOverflowing.ts,src%2FSelfOverflow.tsx

wdyt?

**Comment by mainframev** [comment]
@dmytrokirpa

Good question. I feel like it might not be used often and such things can be abstracted to utility hook on the user side without a problem. We can add it to `react-utilities`, but currently it holds hooks and other utilities that a re being first used in our development.
