### ISSUE TITLE
[Feature]: Input outlineStyle when focused should be more specific

### ISSUE THREAD

**Issue by mathis-m** [microsoft/fluentui#33367]
### Area

React Components (@fluentui/react-components)

### Describe the feature that you would like added

The `outlineStyle: none` on `<Input />` has specificity 1.
Eg. D365 has global styling on `.showOutline *:focus` with dotted outline.
When using [PCFs](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/overview) with Fluent UI the expected `outlineStyle: none` from:

https://github.com/microsoft/fluentui/blob/883151bfb7aa84ea8f950d2c27a806922d438122/packages/react-components/react-input/library/src/components/Input/useInputStyles.styles.ts#L236-L260

Is overridden by `.showOutline *:focus` selector due to specificity 2.
**Context:** `showOutline` is added to body element when keyboard navigation is used

I am opening this feature request as I noticed that eg. for the input of combobox this is explicitly set:
https://github.com/microsoft/fluentui/blob/883151bfb7aa84ea8f950d2c27a806922d438122/packages/react-components/react-combobox/library/src/components/Combobox/useComboboxStyles.styles.ts#L168-L178

**Workaround**  
By adding the following style to your application root:
```ts
const MyRoot = styled.div`
    & .${inputClassNames.input} {
        outline-style: none;
    }
`;
```

Or by using Shadow DOM API but this introduces more complexity.

### Additional context

Combobox:
![Image](https://github.com/user-attachments/assets/f6c4d39b-cdf9-48ec-abba-e568dee007ce)

Input:
![Image](https://github.com/user-attachments/assets/9a9abbc7-aa83-49e4-ac9c-ad0f531fcade)

### Validations

- [x] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

### Priority

Low

**Comment by spmonahan** [comment]
I don't think we'll make this change.

As a general principle for component libraries like Fluent, styles should have as low a specificity as possible, so they are easily overridden by host applications. Sometimes this results in unintentional overrides as you are aware but overall, the current situation is still preferrable 🙂

As a matter of practicality, CSS changes are fraught when trying to respect [semver](https://semver.org/) and this change may result in other folks having their styles break due to the specificity change. Since this issue isn't a bug or accessibility problem the change isn't worth the potential breakage.

I'm going to close, but feel free to re-open if you want to follow up more.
