### ISSUE TITLE
[Bug]: Button dropdown intermittently opens behind a dialog

### ISSUE THREAD

**Issue by Santirax** [microsoft/fluentui#33400]
### Component

Dialog

### Package version

9.56.3

### React version

18.3.1

### Environment

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
npmPackages:
    @fluentui/react: ^8.121.13 => 8.121.13 
    @fluentui/react-components: ^9.0.0 => 9.56.3 
    @types/react: >=16.8.0 <19.0.0 >=16.14.0 <19.0.0 => 17.0.83 
    @types/react-dom: >=16.8.0 <19.0.0 >=16.9.0 <19.0.0 => 17.0.25 
    react: ^18 => 18.3.1 
    react-dom: ^18 => 18.3.1
```

### Current Behavior

When a dropdown menu (default button component) is inside a dialog, the menu to select the items renders behind the dialog when the dialog is dismissed and opened again.

### Expected Behavior

Every single time the dialog is opened, the dropdown menu shows inside the dialog, not behind it.

### Reproduction

https://stackblitz.com/edit/jstnrn-4xkv9u

### Steps to reproduce

1. Open the dialog.
2. Open the dropdown menu.
3. Close the dialog.
4. Open the dialog again.
5. Open the dropdown menu again.
6. The dropdown menu is rendered behind the dialog.
7. If the page is reloaded and steps 1-3 are repeated, the dropdown menu should be rendered correctly.
8. But if steps 4-6 are repeated, the issue persists.

### Are you reporting an Accessibility issue?

no

### Suggested severity

High - No workaround

### Products/sites affected

Outlook Monarch

### Are you willing to submit a PR to fix?

no

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a minimal reproducible example of the bug.

**Comment by spmonahan** [comment]
This happens because the `Button` in your example is Fluent v8 and the `Dialog` is Fluent v9 and both are [portaled elements](https://react.dev/reference/react-dom/createPortal). Fluent v8 and v9 handle portals slightly differently resulting in the behavior you see.

What is happening is:

1. Open the `Dialog` --> FUI9 creates a div as the last element of the DOM and puts the portaled content here
2. Open the `Button` dropdown --> FUI8 creates a div as the last element of the DOM and puts the portalted content here
3. Close the `Dialog` --> FUI9 tears down the div it created but FUI8 does not. This is where the problem starts.
4. Open the `Dialog` --> FUI9 creates a new div as the last element of the DOM again. It now sits above the FUI8 portal div
5. Open the `Button` dropdown --> FUI8 puts the dropdown in the previously created portal div. This is behind the FUI9 dialog div.
6. FUI8 content is behind the FUI9 content.

There are two ways to fix this:
1. Switch the dropdown to also be Fluent v9. This is my recommendation as styling will be consistent and the problem goes away.
2. Use manually create a `div` to host your Fluent v9 portal content such that it is always in the correct DOM order relative to your FUI8 content. This can be done by setting the `mountNode` prop on `DialogSurface` or using `PortalMountNodeProvider` ([example](https://stackblitz.com/edit/jstnrn-tnapzn?file=src%2Fexample.tsx,src%2FApp.tsx)). This approach requires more coordination in your code and in the larger application as well. I would not take this approach unless you 100% need to keep the Fluent v8 content inside the Fluent v9 Dialog.

**Comment by Santirax** [comment]
Thank you for the detailed explanation! Using the `MenuButton` component worked perfectly.
