### ISSUE TITLE
allow mergeStyles to inject into a specific target element, allows ease of use with React.createPortal

### ISSUE THREAD

**Issue by aappddeevv** [microsoft/fluentui#3724]
With React.createPortal, we can push our react tree into different parts of the dom including other iframes. iframes are used heavily in some MS business applications like Dynamics. In order to allow the fabric elements to be styled, we need to be able to push styles into the parent iframe. Hence, we need the class `Stylesheet` to allow us to set a specific target element to add the style element to. It should of course still default to `document.head`. This functionality would be used when the InjectionMode is `insertMode`. 

This also means that we need to put the user in control of setting the singleton initialization of the stylesheet which occurs in the `Stylesheet.getInstance` method or allow us to override this in `Stylesheet.reset`.

To some degree you can turn off injection then use `Stylesheet.getRules` then add the rules yourself to the parent iframe.

**Comment by aappddeevv** [comment]
Just as a quick note, webpack style-loader has a insertInto option that allows you to do this for webpack bundled CSS files.

**Comment by dzearing** [comment]
Interesting, just to cover the bases:

It is easy to add the ability to configure the style element to inject into. However, just want to run through your case to make sure I totally understand:

Your app is running. Styles have been injected.
You open an iframe and render a portal. You want the styles from the parent frame to become available in the child frame.

And... if in the parent frame new styles become available, you'd probably want them added to BOTH style elements. Is this correct? In other words:

1. You want the ability to add and remove style elements as targets for the styling, so that you can have multiple frames.
2. When a new style element is added, you want the existing rules to be registered within.

Is this right? Let me know if I'm misunderstanding.

**Comment by aappddeevv** [comment]
I think we only need one target style element that is controllable through some initialization process. That target style element may or may not be in the same window as the where the assets are being loaded. I think your text suggested that there could be more than one.

We need this for font loading as well via `iconsInitialize` but that's another story.

Here's the DOM scenario:
* Parent IFrame - I need styles inserted here so when I use ReactDOM.createPortal, the styles are in the right place.
  * Child IFrame - the <script> tags are here where react components are loaded and where createPortal is called.

I wrote a style copier that importNodes into the parent (import then append) but it's not quite working well and I'm not sure that is a reliable way vs directing the load via code.

**Comment by michaelangotti** [comment]
@dzearing Do we think this is something we still want to do?

**Comment by dzearing** [comment]
I think the issue here is that you need to insert a totally reset stylesheet in that domain. E.g.

If you render a button, the document page gets button styles injected.
If you render the button again, the styles won't be injected the second time.
If you render the button in an iframe using a portal, you would want a reset stylesheet inside of that context.

**Comment by dzearing** [comment]
This is pretty complicated. I'm not 100% sure we can do this easily.

I will assign to @cliffkoh and we'll discuss what can be done.

**Comment by FixRM** [comment]
+1 here. The same issue with MS Dynamics / Power App. My code is running inside iframe, but I need to inject styles to parent document to use Dialog component and it's possible children. I believe we don't actually need handling or resetting styles in two windows. We only need to be able to React.render or React.createPortal with appropriate styles in parent window only, as we are probably going to unmount that dialog after usage.
