### ISSUE TITLE
Provide a way to register font base url programatically without global FabricConfig

### ISSUE THREAD

**Issue by jekaspekas** [microsoft/fluentui#3881]
### Bug Report

- __Package version(s)__: 5.45.3
- __Browser and OS versions__: Google Chrome 64.0.3282.119, Windows 10 Pro

#### Describe the issue:

Hello, I need to use fonts from my host.
To do this, I use this code:
```js
import { registerDefaultFontFaces } from '@uifabric/styling';
// localhost - for example
registerDefaultFontFaces('http://localhost/static/css/files/fabric/assets');
```

#### Actual behavior:

The browser download fonts from static2.sharepointonline.com

#### Expected behavior:

The browser download fonts from localhost (in this case)

### Problem:

import registerDefaultFontFaces function does not make sense.
registerDefaultFontFaces calls at file @uifabric\styling\lib\styles\DefaultFontStyles.js with:
```js
var DefaultBaseUrl = 'https://static2.sharepointonline.com/files/fabric/assets';
```
if no property is specified:
```js
window.FabricConfig = {
  fontBaseUrl: 'http://localhost/static/css/files/fabric/assets'
};
```
But typescript  compiler returns an error: 

> Property 'FabricConfig' does not exist on type 'Window'.

I believe this is an idiomatically wrong way: window.FabricConfig

### Solution:

I removed this code from @uifabric\styling\lib\styles\DefaultFontStyles.js and it worked:
```js
/**
 * Reads the fontBaseUrl from window.FabricConfig.fontBaseUrl or falls back to a default.
 */
function _getFontBaseUrl() {
    var win = typeof window !== 'undefined' ? window : undefined;
    // tslint:disable-next-line:no-string-literal no-any
    var fabricConfig = win ? win['FabricConfig'] : undefined;
    return (fabricConfig && fabricConfig.fontBaseUrl !== undefined) ? fabricConfig.fontBaseUrl : DefaultBaseUrl;
}
/**
 * Register the font faces.
 */
registerDefaultFontFaces(_getFontBaseUrl());
```

P.S. Sorry for my English

**Comment by jekaspekas** [comment]
Now latest Fabric release 5.90.0. The problem is not solved.

**Comment by aditima** [comment]
@dzearing - seems like registerDefaultFontFaces should also update window.FabricConfig? Is that the right thing to do?

**Comment by dzearing** [comment]
@aditima no.

I think what we want to do is to avoid registering the font faces in file scope and allow the user to initialize the fonts, similar to how we do icons.

We did the global fabric config as a workaround.

**Comment by micahgodbolt** [comment]
Proposal: Allow font faces to be registered in the theme.

Update ITheme and add this to docs.

**Comment by micahgodbolt** [comment]
@natalieethell can you place this into a month iteration when you get a sense of where this will fall?

**Comment by dzearing** [comment]
This is really a timing issue because of the file-scoped side effect registration code. This caused us to invent the `FabricConfig` method, to avoid registering fontFace definitions that pointed to the wrong location.

I *suspect* that if even if we do register "Segoe UI" to map to "SharePoint cdn", and you call `registerDefaultFontFaces` to register font faces to a new base url before rendering things, things should work and NOT resolve to the SharePoint cdn, so long as your new url resolves correctly. I think it will still fall back to old url. This needs to be tested however, as I think some browsers (Edge) may want to prematurely download font faces even before render.

A better approach could be that the theme contains the font faces and is only registered on first access of the font styles. This means that you could simply use a different default theme to override fontface definitions.

**Comment by omarsourour** [comment]
If I want to use my custom CDN, I must have the font files uploaded there via a build step. How do I get the listing of fonts available to copy?

For font icons, the its simple. The woff files exist under `@uifabric/icons/fonts`. What about typography fonts? There are many variants of the Segoe UI font that need to be uploaded to a custom CDN.

Where do I get a listing of these fonts?
