### ISSUE TITLE
Nav component performing slowly (bad implementation)

### ISSUE THREAD

**Issue by oengusmacinog** [microsoft/fluentui#4575]
### Bug Report

- __Package version(s)__: v5.82.1
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Not now

Requested priority: Normal

#### Describe the issue:

Nav component performing slowly.

#### Actual behavior:

The mergeStyles function `getClassNames` being called multiple times in private methods.  This was originally done because of the nested structure (Nav, Group/Accordion, Links).

#### Expected behavior:

Optimally this component needs a refactor that will break it up into subcomponents like NavLinks, Nav, and the styles can be broken up and applied properly.  There may be a quicker solution, but I don't see one right away.

**Comment by dzearing** [comment]
1. The Nav is one component, makes no pure component optimizations. Therefore, it renders ever individual link EVERYTIME anything changes in it.

2. When it was converted to use js styling, one single function (getStyles) was created to create all of these styles, and it was called in 5 different places in the function render path, including the map (getStyles evaluates on every individual item.)

If we fix #1, so that we have individual links which can be pure components, we avoid #2 and have better component design.

**Comment by aditima** [comment]
@jordandrako @oengusmacinog @mikewheaton - trying to avoid multiple assignees for better book-keeping. Please update if you need to...

**Comment by ecraig12345** [comment]
Closing since we are not likely going to invest in the current implementation of Nav going forward, due to focusing on converged components. (Though if anyone else would like to submit a PR with Nav perf improvements, I'd be happy to review it.)
