### ISSUE TITLE
Customization: Update the theming documentation to have basic/medium/advanced customization.

### ISSUE THREAD

**Issue by dzearing** [microsoft/fluentui#5610]
On the public website, we should have very clear documentation on customizability, now that we've converted most of the css to customizable css in js.

I'd like the documentation to outline the following:

Basic site customization:
* palette colors vs semantic colors
* typography
* sizing

Per component customization:
* button borders
* dialog paddings
* per component coloring
 
Advanced customization:
* styling overrides
* prop overrides

**Comment by keydoubleu** [comment]
That would be awesome! I constantly struggle with finding clear instructions about styling and customization. For example, I am trying to set a custom font (instead of Segoe UI) and the public website has no guides on that. It would be so nice to have clear documentation on things like this.

**Comment by mltejera** [comment]
Here's a write up I did for our M365 Themeing system. Certainly open to feedback...

## Creating and extending custom themes with Fabric

Fabric's theme system is great. It provides  all sorts of goodies to pump colors, fonts and styles throughout an app built with Fabric. Let's look at the color system and how we can fiddle with colors, remap things tackle some problems and even extend it to meet a broader range of needs.

For starters, there's Fabric's [theme designer](https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/9318/merge/theming-designer/index.html). If all you want to do was change your theme's foreground, background and accent colors, this is the best way to go. Plug in 3 new values, hit the big blue export button and it might generate a whole new palette like this one:
```
import { loadTheme } from 'office-ui-fabric-react';

loadTheme({
  palette: {
    themePrimary: '#0078D4',
    themeLighterAlt: '#0C2031',
    themeLighter: '#D0E7F8',
    themeLight: '#043862',
    themeTertiary: '#004C87',
    themeSecondary: '#1A86D9',
    themeDarkAlt: '#1890F1',
    themeDark: '#3AA0F3',
    themeDarker: '#6CB8F6',
    neutralLighterAlt: '#202020',
    neutralLighter: '#252525',
    neutralLight: '#292929',
    neutralQuaternaryAlt: '#323232',
    neutralQuaternary: '#3B3B3B',
    neutralTertiaryAlt: '#484848',
    neutralTertiary: '#797979',
    neutralSecondary: '#B3B3B3',
    neutralPrimaryAlt: '#E1E1E1',
    neutralPrimary: '#EDEDED',
    neutralDark: '#F3F3F3',
    black: '#FFFFFF',
    white: '#141414',
  }
});
```

But what if you want to change the mapping from the base palette colors to the semantic slots? 

For instance, let's look at the link on body background combination:

link-> themePrimary -> #0078D4
bodyBackground -> white -> #141414

This leaves us with a contrast ratio of 4.02:1, short of our required 4.52:1 for text. However, in this new theme, themeDarkAlt color happens to be #1890F1.

link-> **themeDarkAlt** -> #1890F1
bodyBackground -> white -> #141414

5.52:1. Brilliant. Now for the code:

```
// YourDarkTheme.ts

// Define some constants for re-usability later in the file
namespace  YourDarkColorPalette {
export  const  themePrimary = '#0078D4';
export  const  themeLighterAlt = '#0C2031';
export  const  themeLighter = '#D0E7F8';
export  const  themeLight = '#043862';
// ... and so on until all the palette colors are set
}

const p = YourDarkColorPalette ;

const YourDarkSemanticColors: Partial<ISemanticColors> {
	link: p.themeDarkAlt
	// re-assign others as needed
}

// Export our consumable theme:
export const YourDarkCustomization: ICustomization = {
  settings: {
    theme:  
      createTheme({
	palette: {
	  themePrimary:  p.themePrimary,
	    themeLighterAlt:  p.themeLighterAlt,
	    // ...
	    neutralDark:  p.neutralDark,
	    black:  p.black,
	    white:  p.white
	},
	effects: {}, // to complete the interface
	semanticColors:  YourDarkColorSemanticColors
      })
  },
  scopedSettings: {} // to complete the interface
 };
}
```
And finally
```
// App.tsx
<Customizer settings={{theme: YourDarkCustomization.settings.theme}}>
 // ... more app code here
<Customizer/>
```


Here we've created our new theme with that new palette. `createTheme` is super handy because it will apply the default mapping for semantic colors, but change any we've specified. We've `omitted` effects and `scopedSettings` for demonstration's sake, so  this theme object won't have shadows or custom styles.

## Extending the theme

Many apps will have color needs beyond the base palette and semantic colors. For example, let's say we want to have some data visualization colors that we know are accessible against each other.

Let's start by defining a new theme type:

```
// YourAppTheme.ts
import { ITheme } from  'office-ui-fabric-react';

export  interface  IYourTheme extends  ITheme {
  semanticColors: IM365ExtendedSemanticColors;
}
```

```
// YourExtendedSemanticColors.types.ts  
import { ISemanticColors } from  'office-ui-fabric-react';

export  interface  IYourExtendedSemanticColors extends  ISemanticColors {
  // Data Viz
  dataVis1: string;
  dataVis2: string;
  dataVis3: string;
  dataVis4: string;
  dataVis5: string;
  dataVis6: string;
  dataVis7: string;
  dataVis8: string;
  dataVis9: string;
  dataVis10: string;
  // ... more as needed
}
```
Now our theme file is pretty similair, we just need to be sure to treat our semantic colors as an IYourTheme.
```
// YourAppDarkTheme.ts
import { IYourExtendedSemanticColors } from  './YourExtendedSemanticColors.types';

namespace  YourDarkPalette {
  export  const  themePrimary = '#0078D4';
  export  const  themeLighterAlt = '#0C2031';
  // ... more base palette definitions
  // Extended colors
  export  const  dataVis1 = themePrimary;
  export  const  dataVis2 = '#BEDFFF';
  export  const  dataVis3 = '#038387';
  export  const  dataVis4 = '#F6C0FF';
  export  const  dataVis5 = '#6E5DB7';
  export  const  dataVis6 = '#C7D3FF';
  export  const  dataVis7 = '#D90086';
  export  const  dataVis8 = '#A4E1D2';
  export  const  dataVis9 = '#CB4936';
  export  const  dataVis10 = '#FFCA8A';
}

const p = YourDarkPalette ;
const  extendedSemanticColors: Partial<IYourExtendedSemanticColors > = {
  link: p.themeDarkAlt,
  // re-assign others as needed
	
  // Data Vis:
  dataVis1:  p.dataVis1,
  dataVis2:  p.dataVis2,
  dataVis3:  p.dataVis3,
  dataVis4:  p.dataVis4,
  dataVis5:  p.dataVis5,
  dataVis6:  p.dataVis6,
  dataVis7:  p.dataVis7,
  dataVis8:  p.dataVis8,
  dataVis9:  p.dataVis9,
  dataVis10:  p.dataVis10,
}

export const YourDarkCustomization: ICustomization = {
  settings: {
    theme:  
      createTheme({
	palette: {
	    // ... same as the above example
	},
	effects: {}, // to complete the interface
	semanticColors:  extendedSemanticColors
      })
  },
  scopedSettings: {} // to complete the interface
 };
}
```

Since this all compiles down to javascript anyways, our extended colors get maintained throughout our app when we load it:

```
// App.tsx
<Customizer settings={{theme: YourDarkCustomization.settings.theme}}>
 // ... more app code here
<Customizer/>
```

And then treat your theme as an IYourTheme anywhere you want to use those slots. You'll still have that sweet sweet type saftey.
 
 ```
 // YourStyledComponent.types.ts

export interface YourStyledComponentProps {
  // ...
  theme?: IYourTheme 
}

export interface YourStyledComponentStyleProps {
  // ...
  theme: IYourTheme 
}
```

```
// YourComponentStyles.ts
export getYourComponentStyles(props: YourStyledComponentStyleProps): IYourStyledComponentStyles => {
  const { theme } = props;
  // ...
  backgroundColor: theme.semanticColors.dataVis1
  // ...
}
```
A few words of wisdom, some learned the hard way:
- If you ever pass in a theme object that **doesn't** have one of our new slots and you try to reference them, it'll fail silently and end up rendering undefined, or transparent.
- Be judicious when adding new slots. Removing one is a breaking change. Add too many, and your list gets harder to search, discouraging it's use or increasing the chance of picking the wrong one.
- Do your best to think of descriptive names that opens your colors up to a broad range of uses, but gives it semantic meaning and intent. 'scaryRed' -> 'severeWarningBackground'

Happy themeing!

**Comment by mltejera** [comment]
Here's a write up I did on styling fonts...

## Font styling best practices with Fabric


Let's say I have a component with some text, and I want to apply some styling to meet the design spec. The getComponentStyle function might look something like:

```
  export  const  getComponentStyles = (props:  IComponentStyleProps):  IComponentStyles => {
    const { theme } =  props;
    return {
      title: {
        fontWeight:  'bold',
        margin:  '0',
        padding: '14px',
        fontSize:  '18px',
        fontFamily: 'Segoe-UI',
        lineHeight:  20,
        color:  theme.semanticColors.bodyText,
        // ...more properties
      },
      description: {
        fontSize:  '14px',
        fontFamily: 'Segoe-UI',
        color:  theme.semanticColors.bodyText,
        lineHeight:  20,
        paddingTop:  8,
        marginBottom:  8,
        overflow:  'hidden',
        // ... more properties
      }
    };
  };
```

That's a great start. But it's pretty hard-cody. If the design team wanted to tweak the font across the app, every developer would have to go in and update their code. That sounds time consuming, error prone, and we all have bigger problems to tackle. Let's look at a few approaches for how we can make this kind of styling more dynamic and easier to change.

We have a few tools at our disposal:

- [Fabric's font weight constants.](https://github.com/OfficeDev/office-ui-fabric-react/blob/ed8a416b4628ea7c2ec8b53ef878422183d80f9d/packages/styling/src/styles/fonts.ts#L94)
- Fabric's array syntax for styles.
- Fonts that live in theme object.

First, let's apply the font weight constant:

```
    import { FontWeights } from 'office-ui-fabric-react';
    ...
    fontWeight:  FontWeights.bold
```

Sweet - that was pretty easy, and now we're referencing something we could easily change later. Next, let's look at how we can combine the fonts that live in theme with array syntax for merging styles.

Fabric's mergeStyles is pretty handy for boiling our javascript styles into css. Doing this with a single object is pretty simple to follow:

```
  myClassName: {
    styleProp1: someValue,
    styleProp2: someValue,
    //... and so on
  }
```

If we want to combine multiple style objects, we can use an array of style objects like this:

```
  myClassName: [
    someBaseStyleObject,
    anotherVariantStyleObject,
    {
      margin: 16,
      padding: 32,
      //... and so on
    }
]
```

MergeStyles will combine all the properties in someBaseStyleObject and anotherVariantStyleObject with the margin and padding into myClassName.

So let's combine this idea with the font styles that live in our theme object. These are organized by fontSize, so it should be easy to find the one that matches your scenario. The important bit here is that fontSize and fontFamily are already set for you.

```
export  const  getComponentStyles = (props:  IComponentStyleProps):  IComponentStyles => {
  const { theme } =  props;
  return {
    title: [
      theme.fonts.large
      {
        fontWeight:  fontWeights.Bold,
        lineHeight:  20,
        margin:  '0',
        padding: '14px',
        color:  theme.semanticColors.bodyText,
        // ...more properties

        }
    ],
    description: [
    theme.fonts.medium
    {
      color:  theme.semanticColors.bodyText,
      lineHeight:  20,
      paddingTop:  8,
      marginBottom:  8,
      overflow:  'hidden',
      // ... more properties
    }
    ]
  };
};
```

With this pattern in place, if the design team wanted to make a font change - all they'd need to touch is the one place where the fonts are loaded into the theme object. Way less work for developers.

Regrettably, lineHeight and fontWeights still aren't part of into our theme fonts. We'll have to code those inline for the time being.
