### ISSUE TITLE
Teaching bubble - display issues on mobiles

### ISSUE THREAD

**Issue by AgnieszkaBajek** [microsoft/fluentui#5732]
### Bug Report 
 
- __Package version(s)__: 6.41.1
- __Browser and OS versions__: mobiles (tested on Chrome on Android and Safari on iPhone)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Teaching bubble is not displayed correctly on mobiles.
 
#### Actual behavior:
 
 In some cases part of teching bubble container is not visible on screen.

#### Expected behavior:
 
Teaching bubble should adjust to screen size.
 
### If applicable, please provide a codepen repro:
 

![img_0082](https://user-images.githubusercontent.com/40884253/43452301-686d6b38-94b7-11e8-8e76-212bd6818616.PNG)
![img_0083](https://user-images.githubusercontent.com/40884253/43452303-68944578-94b7-11e8-959b-ec77a14afd6e.PNG)

**Comment by betrue-final-final** [comment]
I would talk to @Reema<mailto:rebhagat@microsoft.com> or @Angela<mailto:angeal@microsoft.com>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by natalieethell** [comment]
Just spoke with Reema about what the expected behavior is for TeachingBubble. She said that the design intent is that the bubble adjusts size as needed. So, it'd always be on screen fully (not cut off) and then the text would wrap as needed to accommodate content, likely causing the bubble to grow a bit.

**Comment by natalieethell** [comment]
Just spoke to @joschect offline about this issue. So the `Callout` logic, which `TeachingBubble` uses, should already reposition/resize the element depending on screen size. The issue seen in the screenshots above might be due to animations. I'll investigate further and report back.

**Comment by natalieethell** [comment]
Just looked into this a little more and it looks like animations may be the culprit here. Here are some screenshots I got of the TeachingBubble with animation styles and without.

With animation:

![image](https://user-images.githubusercontent.com/14134000/44483537-35587300-a600-11e8-9a44-bf38622d810e.png) 


Without:

![image](https://user-images.githubusercontent.com/14134000/44483542-37bacd00-a600-11e8-8b89-ea22fdd72d15.png)


With animation:

![image](https://user-images.githubusercontent.com/14134000/44483596-6173f400-a600-11e8-8d95-7e1019d342f2.png)


Without:

![image](https://user-images.githubusercontent.com/14134000/44483599-63d64e00-a600-11e8-82e8-044a34eaddf8.png)

**Comment by micahgodbolt** [comment]
Can we turn off animation under a given screen size?

**Comment by micahgodbolt** [comment]
The problem is right here:

![image](https://user-images.githubusercontent.com/1434956/44864584-e11f4580-ac34-11e8-9908-52f42d4f9de3.png)

The bubble's max width is set to 100% +1px. That 100% is derived from it's parent, which is 100% of the screen width.

But the teaching bubble is being given a left value, in this case 54px. The positioning logic must think that the bubble is smaller than it is, and thinks it needs to be moved over to fit the screen.

So again, it appears that positioning logic is getting confused by the animation. So we can either fix the logic (which might be difficult considering it's not broken, just confused by animation), or we can simply remove/change the animation under a given screen size. Maybe we change to a simple fade...or something that doesn't modify the dimensions of the teaching bubble.

**Comment by micahgodbolt** [comment]
@betrue-final-final i'll leave this solution up to you and design. Remove/change animation on mobile, or wait for a engineering fix....that might not be possible in the end.

**Comment by micahgodbolt** [comment]
There is already discussion about changing teaching bubble animation here #5874
