### ISSUE TITLE
Convert Fabric to REM 

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/fluentui#6014]
Placeholder for conversation
This would involve allowing users to set their default body px size in the theme (or something similar).

**Comment by swese44** [comment]
awesome. YamUI sets `html` font-size to 62.5% which equates to 10px, then scales our fonts with rems. after this gets implemented in Fabric and we conform to Fluent we can probably remove our custom font strategy.

from the design side, i wonder if there are Fabric component gutters, widths or other dimensions which should also scale with rems? Yammer tries to maintain a 4px vertical rhythm for typography so we also scale most of our vertical gutters with rems.

AppContainer component sets style on html element:
https://github.com/Microsoft/YamUI/blob/master/src/components/AppContainer/AppContainer.styles.ts#L24

Fabric theme fonts use rems:
https://github.com/Microsoft/YamUI/blob/master/src/util/theme.ts#L18

And components use a utility function to get a gutter value based on the number of 4px gutter units. They can specify whether the gutter dimension should grow with base font size (use multiples of .4rem instead of a fixed 4px value):
https://github.com/Microsoft/YamUI/blob/master/src/util/styles/gutters.ts#L26

**Comment by micahgodbolt** [comment]
better solution will probably be to drive all of our size values off of theme 'sizing' and 'font' values. This would make it easy to swap px values out for REM values.

**Comment by vitthalr** [comment]
Is there any ETA for this?

**Comment by Jessica-Koch** [comment]
I personally would LOVE this feature, it would make working with FLuent + mobile web so much easier!

**Comment by dran5447** [comment]
It looks like the [Fluent Typography page](https://developer.microsoft.com/en-us/fluentui#/styles/web/typography) ms-fontSize-X variables all use px. Is there a plan to create rem versions or convert them? Right now using those and many Fluent controls don't adjust when users customize their font size in browser (e.g. in Chrome Settings > Appearance > font size).
