### ISSUE TITLE
[DevExp] Reduce NPM package size

### ISSUE THREAD

**Issue by kenotron** [microsoft/fluentui#7255]
**Describe the feature that you would like added**
Currently OUFR package is at 7mb and contains a lot of cruft like api.json. We should add things like that in .npmignore within OUFR package to make sure the npm install time of OUFR isn't that bad.

**What component or utility would this be added to**

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by KevinTCoughlin** [comment]
@kenotron what should we consider our completion criteria for this?

One thought is we can recursively list the installed package's contents sorted by file size and propose a list of files to omit via `.npmignore`.

**Comment by micahgodbolt** [comment]
@KevinTCoughlin did #7322 resolve this?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin did #7322 resolve this?

@micahgodbolt, I'm deferring to @kenotron to decide on completion criteria here. I have a branch which adds the image media file rules to _all_ `.npmignore` files including our `create-package` `.npmignore`. template. I'll raise that in a bit, see: https://github.com/OfficeDev/office-ui-fabric-react/compare/master...KevinTCoughlin:keco/npmignore-media-types-all

@kenotron, would it be worthwhile to write a script to see if there are any other unnecessary file types within our packages to exclude?

@aftab-hassan, tracking the size of built packages via `npm pack` over time via the size-auditor bot may be an interesting feature to add down the road.

To my knowledge, we don't currently have a method of guarding against this problem via CI.

**Comment by kenotron** [comment]
@KevinTCoughlin - sorry dropped the ball in answer to your questions. Do you still want to create a PR with that your branch?

**Comment by ecraig12345** [comment]
I think we can consider this fixed now due to various changes that have been made over time:
- Looks like all the ignores previously discussed in this thread have been added
- Examples and docs have been moved to a separate package (including in v7)
- I'm about to merge another PR #15414 which completely gets rid of demo app-related files from the published packages (oops). That one is master-only for now but could be ported back to 7 if desired, though I won't have time right away.
