### ISSUE TITLE
Dropdown: Add public interface to get selected value

### ISSUE THREAD

**Issue by peterremote1980** [microsoft/fluentui#7692]
Hi
   i can:
```
let gender: Dropdown = this.refs['gender'] as Dropdown
```
But the object gender has no property for the selected value, please help
thanks
Peter

**Comment by mikewheaton** [comment]
Here's a CodePen that logs the reference each time the dropdown is changed: https://codepen.io/mikewheaton/pen/pqmLeK?editors=0010

I don't see a way to get the selected value directly from the reference object. Could you provide some more details on what you're building? You'll likely want to use the `onChange` prop to provide a function that updates the parent component's state, so that you can access the selected value.

**Comment by micahgodbolt** [comment]
@mikewheaton this is a pretty low hanging fruit addition to dropdown's public interface. For any control that can be used uncontrolled, we should have have a public getter for the current value.

**Comment by joschect** [comment]
Even though this isn't a huge change I think that we could batch it into #6030
