### ISSUE TITLE
Post OUFR bundles from PR builds

### ISSUE THREAD

**Issue by JasonGore** [microsoft/fluentui#8217]
**Describe the feature that you would like added**\

#8216 has a bunch of CodePens using ngrok and made me realize it'd be nice to have a hosted bundle built off of PRs that could be used in CodePens.

**What component or utility would this be added to**

CI Deploy I guess.

**Have you discussed this feature with our team, and if so, who**

Briefly verbally mentioned to @kenotron 

**Additional context/screenshots**

#8216

**Comment by aftab-hassan** [comment]
@JasonGore I modified the build definition on `Azure Dev Ops` to push the `dist/office-ui-fabric-react.js` file which we would like to use instead of `ngrok`'ing it. This generates a file like below on every `PR` (`container id is the variable`)

https://uifabric.visualstudio.com/_apis/resources/Containers/3192849?itemPath=oufrdrop%2Foffice-ui-fabric-react.js

But looks like `Azure Dev Ops` has mechanism in place and adds additional headers to avoid exactly this, which is use it as a `CDN`, and potentially `DDOS` it.

We'll have to push the files to another `CDN` to be able to get a shareable link that has the bundle.

**Comment by aftab-hassan** [comment]
@micahgodbolt , this is something we would like to add as part of the `CI` workflow.

`sp-client` for example, has a `dev-deploy` process, where every `build` copies the `dist` folder to an `Azure blob store`, and appends the `PR` `id`. Here is an example
https://resourceseng.blob.core.windows.net/files/refs_pull_242337_merge/manifests.js

We could do the same for `fabric` but being open source, we would want to discuss the implications, since cost is billed by traffic.

Can I unassign myself from this `feature` ?

**Comment by micahgodbolt** [comment]
I 100% agree with Jason. It'd be great if each PR, in addition to creating a deploy site, also creates a bundle that you could drop into a codepen. I've had similar situations where I needed to demonstrate how the new code would work via a codepen. 

Assigning to Ken and flywheel

**Comment by JustSlone** [comment]
This is covered by the recent addition of the CodeSandbox on PRs, closing this out
