### ISSUE TITLE
A DetailsList or ShimmeredDetailsList inside a ScrollablePane has unnecessary horizontal scrolling bar

### ISSUE THREAD

**Issue by sealightPT** [microsoft/fluentui#8589]
### Bug Report

- Office-ui-fabric-react 6.162.1
- Google Chrome Version 73.0.3683.86 
- Windows 10 version 1809

#### Priorities and help requested

Are you willing to submit a PR to fix? No
Requested priority: High
Products/sites affected: 

#### Describe the issue:

A DetailsList or ShimmeredDetailsList inside a ScrollablePane has unnecessary horizontal scrolling bar.

#### Actual behavior:

The horizontal scrollbar is always present, even in unnecessary.
![image](https://user-images.githubusercontent.com/10246381/55487878-db546d00-5626-11e9-9bd1-a3b0ff55df9d.png)

#### Expected behavior:

The horizonal scrollbar should only be visibile if there is content to scroll.

### Repro:

The official example can be used to reproduce the issue:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ScrollablePane/examples/ScrollablePane.DetailsList.Example.tsx

Reduce the number of columns (e.g. to 3) to have no reason to scroll.
```
this._columns = [];
for (let i = 1; i < 4; i++) {
    this._columns.push({
    ...

```

**Comment by sealightPT** [comment]
PS: In some conditions this scss hack works: 
.ms-DetailsList {
	> div[role=grid] {
		max-width: 100px;
	}
}

**Comment by kkjeer** [comment]
@KevinTCoughlin @aditima as the code owner and author of DetailsList, could you take a look at this? Thanks!

**Comment by KevinTCoughlin** [comment]
Regarding the original issue report, I don't see it _quite as pronounced_ in Chrome Version 73.0.3683.86

![image](https://user-images.githubusercontent.com/706967/55592071-33a17280-56ec-11e9-862d-39c2c277fcc2.png)

I _do see_ the unnecessary flash of horizontal scrollbar as reported in #7772.

@sealightPT, can you offer any assistance on how to get it to repro as you captured above? Meanwhile, I'll take another pass at resolving the flash of horizontal scroll I am able to repro.

**Comment by KevinTCoughlin** [comment]
> PS: In some conditions this scss hack works:
> .ms-DetailsList {
> > div[role=grid] {
> max-width: 100px;
> }
> }

Note that this style _only_ works if you do not need to support horizontal scrolling to view additional columns.

**Comment by sealightPT** [comment]
@KevinTCoughlin, from a blank CRA app we can reproduce the behaviour you mentioned on Chrome: The horizontal scrollbar is visible for a second and then it is hidden
However on Edge (Microsoft Edge 44.17763.1.0; Microsoft EdgeHTML 18.17763) the scrollbar is never hidden.

Steps:
```
npx create-react-app my-app
cd my-app
npm install office-ui-fabric-react
npm install --save typescript @types/node @types/react @types/react-dom @types/jest
```
Add ScrollablePane.DetailsList.Example.tsx to the project

I then had to comment the following lines for it to compile:
```
{/* <TextField className={classNames.filter} label="Filter by name:" onChange={this._onFilterChange} /> */}

//   onRenderDetailsHeader={onRenderDetailsHeader}
//   onRenderDetailsFooter={onRenderDetailsFooter}

/*
function onRenderDetailsHeader (...)
function onRenderDetailsFooter (...)
*/

```

Reduce the number of columns to less than 4:
```
this._columns = [];
for (let i = 1; i < 4; i++) {
```

Then this happens:
![image](https://user-images.githubusercontent.com/10246381/55636160-310d4e80-57ba-11e9-9545-8e465d1d4c5a.png)

**Comment by KevinTCoughlin** [comment]
@sealightPT, yea I agree that it happens in the default case. From my prior debug sessions it looks to be a stale width measurement as part of the component's lifecycle. I'm still in search of a fix.

**Comment by rachitpuri95** [comment]
I am seeing the horizontal scroll bar flash still. Is there a good workaround for this?

**Comment by bharath3719** [comment]
Any fix/ workaround for this ?

**Comment by GeoffCoxMSFT** [comment]
Update:  Investigated and think a small change in viewport will fix the issue, prepping a PR.

- The DetailsList uses getDerivedStateFromProps which calculates the column widths based on the viewport props. getDerivedStateFromProps runs just before each render.
- The Viewport calculation is based on the scroll rectangle so is calculated based on the contained control (the DetailsList) rendered size.
- The Viewport calculates initially from componentDidMount. 
- The Viewport resizeObserver is debounced (500ms) both to avoid too many render calls as the user resizes the browser window, but also so the calculation will be based on the contained controls actual size.

Because the DetailsList calculates before rendering and the Viewport depends on the DetailsList rendering, everyone is one step behind.  The viewport gets the initial calculation wrong, causing DetailsList to calculate wrong and then render too wide.  The viewport then recalculates based on the rendered DetailsList and gets the correct calculation.  The DetailsList then recalculates and gets the right column widths and re-renders.  Yikes!

The likely fix is to introduce a delay of the initial viewport calculation of the same amount as the delay in the debounced resize observer. From what I see, this causes the viewport to get the initial calculation correct and the DetailsList to not have to recalculate.
