### ISSUE TITLE
DetailsList initialFocusedIndex doesn't work past first virtualized page

### ISSUE THREAD

**Issue by mattjohnsonpint** [microsoft/fluentui#8722]
### Environment Information 
 
- __Package version(s)__: office-ui-fabric-react 6.166.0
- __Browser and OS versions__: Chrome 73 / Windows 10

### Please provide a reproduction of the bug in a codepen:

Starting with the existing example at
https://developer.microsoft.com/en-us/fabric/#/components/detailslist/basic

I added one prop to the `DetailsList` component: `initialFocusedIndex={100}`
[Repo pen here](https://codepen.io/anon/pen/WWEoVo).
 
#### Actual behavior:
 
It does not bring item 100 into focus, presumably because it is not on the first page of results that have been virtualized.
 
#### Expected behavior:
 
I expect it to scroll to item 100.   Indeed, if I change it to something smaller like 20 then it works fine.  [Working pen here](https://codepen.io/anon/pen/dLzOBr).

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
Requested priority: High
Products/sites affected: (internal MS)

Note: I also found the same problem if I use the `focusIndex` function.  It only works if the index provided is within the virtualized page currently loaded.  It should work with any index within the list of items.

**Comment by ecraig12345** [comment]
Thanks for reporting this! @KevinTCoughlin Can you help make a recommendation for the fix here?

**Comment by KevinTCoughlin** [comment]
The virtualization logic was supposed to accommodate this scenario, but perhaps it isn't.

If we were to solve, we'd need to materialize the page containing the specified index if either of these props are used. It will be expensive w.r.t performance since it invokes the costly virtualization call flow that in turn invokes [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

I wonder if List's `scrollToIndex` is being invoked or not.. it seems like it should handle this: https://github.com/OfficeDev/office-ui-fabric-react/blob/48ef2097fcaf941b71e9f2173751d1f6971f4f02/packages/office-ui-fabric-react/src/components/List/List.tsx#L180.

**Comment by ecraig12345** [comment]
I think even if materializing the relevant page is expensive, it's the right thing to do.

Would calling `scrollToIndex` automatically materialize the relevant page?

**Comment by KevinTCoughlin** [comment]
> I think even if materializing the relevant page is expensive, it's the right thing to do.
> 
> Would calling `scrollToIndex` automatically materialize the relevant page?

Unsure without testing and I'm a bit behind my queue right now. I would hope that it does.

**Comment by anti-aguilarr** [comment]
Hello! Reached the same issue as the OC. I'm using DetailList with a large number of items (500+). InitialFocusIndex appears to stop working once I try to enter indexes above 70. 

Poked around and was not able to see if this solution had been solved. Is this still a bug ?

**Comment by joschect** [comment]
@anti-aguilarr This has not been fixed. @KevinTCoughlin I don't think that we ever figured out a good way to handle this particular bug.

**Comment by maheshkumawat24** [comment]
Looking for a solution to this problem.
