### ISSUE TITLE
[Nav] Expand icon overlaps item icon

### ISSUE THREAD

**Issue by frevds** [microsoft/fluentui#8830]
It appears a Nav item cannot both have child links and an icon: 

![image](https://user-images.githubusercontent.com/5341447/56624058-5f52b100-6637-11e9-880e-fa52ecde24ae.png)

This might be a consequence of fixing https://github.com/OfficeDev/office-ui-fabric-react/issues/3945

**Comment by frevds** [comment]
The current construct is a <div> with a <button> in it (absolutely positioned) and an <a> (which is thus overlapped) which contains the icon and label. 

Child elements seems to be offset from the start using a calculated padding-left. 
The icon is regular content of the node, so this calculation must take icon of the parent into account, which it currently doesn't! 

Giving the child elements the correct padding makes it looks correct: 

![image](https://user-images.githubusercontent.com/5341447/56624908-20265f00-663b-11e9-81c7-38bde59a4e61.png)

**Comment by frevds** [comment]
There is another (unrelated) bug in the Nav (which apparently nobody uses): 

If a sub item has sub items and is selected (e.g. by passing Nav.selectedKey or by not defining it), there is a second highlight, because of a .chevronButton::after definition that conflicts with the general .link::after. 

![image](https://user-images.githubusercontent.com/5341447/56689659-da6da300-66db-11e9-9e6f-6822bbd14fe6.png)

![image](https://user-images.githubusercontent.com/5341447/56689740-130d7c80-66dc-11e9-8c06-6b31df133292.png)

**Comment by apneer** [comment]
Thank for the update. I am working with our design to verify the fixes could be integrated.

**Comment by savkelita** [comment]
Is there any temporary solution to change default `Chevron Icon` without overlapping? Thanks.

**Comment by frevds** [comment]
Yes, my hack should do that: 
https://github.com/OfficeDev/office-ui-fabric-react/issues/8830#issuecomment-486025019

**Comment by savkelita** [comment]
@frevds i mean to replace current icon with new one

**Comment by frevds** [comment]
@savkelita Not sure what you mean with current icon. If you don't assign the icon property for a INavLink item then it shows no icon unless it has child items in which case it shows a chevron. If you assign an icon it shows both, the chevron and the icon, but on-top of each others (that's the bug). My workaround is a CSS hack to put additional margin to separate the two icons, but it is limited (e.g. every item should have an icon per level). There is also another bug mentioned here with double highlighting which can be fixed with another CSS hack.

**Comment by robert1826** [comment]
> Is there any temporary solution to change default `Chevron Icon` without overlapping? Thanks.

I guess you can use this: https://stackoverflow.com/questions/49542450/override-officeui-nav-chevron-icon?rq=1

**Comment by attiqe** [comment]
any update on this?

**Comment by yalian-icom** [comment]
here my hack:
```
.ms-Nav-chevronButton {
  right: 10px;
  left: unset;
}
```

**Comment by ColinGardner** [comment]
@yalian-icom's solution (hack) is the simplest but has the side effect of relocating the chevron to the right - which is I guess the point as it gets the chevron out of the way so that there is no overlap.  It does make for an inconsistent UI if you use groups as the chevron for them remains on the left.  However, I quite like it as it make it very clear as to what is a group and what is a nav link.

![image](https://user-images.githubusercontent.com/3699922/80847460-e8d78e80-8c4e-11ea-992a-53e314a928b7.png)

A few other points to note:

- For anyone doing this in a SharePoint Framework (SPFx) solution, I had to mark the CSS as global in the module.scss file for this to take.  But it's only global within the parent CSS class and so the Nav control will need to be wrapped in a container that uses the primary CSS class.
- Setting the right attribute to 10px resulted in the group chevrons being cut off on the left and I found that a value of 4px works better.
- As can be seen from the screenshot, we are still suffering from the other issue identified by @frevds, the second highlight bar

So I was able to sort these issues out with the following:
```
.linkBar {
  
   :global .ms-Nav-chevronButton {
     right: 4px;
    left: unset;
  }

  :global .ms-Nav-chevronButton::after { content: none; }
  :global .ms-Nav-chevronButton { background-color: transparent; }

...
```
After that all is well.

However, I would like to point out that is over a year since @frevds identified these bugs and I think we could have expected a proper fix by now.  I suspect it would only take someone 10 minutes to sort this out on the control itself rather than forcing us to use ugly hacks!
