### ISSUE TITLE
DetailsList onItemInvoked responsive

### ISSUE THREAD

**Issue by rafakil** [microsoft/fluentui#8858]
onItemInvoked can't be triggered from a different responsive screen(Tablet, Smartphone....).
Any suggestions please?

**Comment by apneer** [comment]
Thank you for bringing this to our attention. I can repro this. Looking quickly through the code I don't see any touch event hooks used in DetailsList. I believe solution could be to attach touch events to doubleClick callback. @KevinTCoughlin, can you double check my reasoning?

**Comment by KevinTCoughlin** [comment]
> Thank you for bringing this to our attention. I can repro this. Looking quickly through the code I don't see any touch event hooks used in DetailsList. I believe solution could be to attach touch events to doubleClick callback. @KevinTCoughlin, can you double check my reasoning?

@apneer, your reasoning seems correct. Prior to implementation we'd probably have to double check with @betrue-final-final / @Vitalius1 on expected behavior here.

Mainly, should the following occur:

1) Single-touch un/select rows which is analogous to single 'click' via mouse / `SPACE` via keyboard.
2) Double-touch invoke `onItemInvoked` which is analogous to pressing `ENTER` via keyboard.

cc: @ThomasMichon

**Comment by KevinTCoughlin** [comment]
Actually, are we sure that this doesn't currently work? See this Codepen where `onItemInvoked` fires on double "touch" of a row -- https://codepen.io/kevintcoughlin/pen/mgvwdL?editors=0011

**Comment by FullStackRafik** [comment]
@KevinTCoughlin 
Exactly, the issue occurs on simulators, I'll try this on an IPad and then let you know.

Thanks

**Comment by apneer** [comment]
I confirm this does not work on ipad either.

**Comment by KevinTCoughlin** [comment]
Some additional data points as we investigate:

- https://stackoverflow.com/questions/55916190/officeui-fabric-iteminvoked-in-detailslist-not-working-in-iphone-spfx
- https://github.com/SharePoint/sp-dev-fx-webparts/issues/855

**Comment by Leif-Frederiksen** [comment]
I see the problem as well. The CodePen provided by @KevinTCoughlin shows the problem on both simulator and actual iPad. 

However, it works on my Samsung S8 in both Chrome and the native Samsung browser.

My project is based on newest SPFx version as per today - version 1.8.2
React version is 16.7.0 and office-ui-fabric-react is 6.143.0

**Comment by xugao** [comment]
@Leif-Frederiksen - could you confirm on your repro device using [this codepen](https://codepen.io/xugao/pen/rNVmoZg) repros the issue? 

in the code, it is relaying on `onDoubleClick` (ondblclick) event listener, which looks like it is not well supported - https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondblclick
I am suspecting that is the root cause
