### ISSUE TITLE
Calendar component doesn't highlight workweek correctly

### ISSUE THREAD

**Issue by mayankaggarwal092** [microsoft/fluentui#8995]
### Environment Information 
 
- __Package version(s)__: 6.176.3
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/anon/pen/RmNvqQ

1. Render a Calendar component with dateRangeType={DateRangeType.WorkWeek}
2. Select or hover over a date.

 
#### Actual behavior:
Entire week gets highlighted 

 
#### Expected behavior:
 Only the work week should get highlighted

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
High
 
Products/sites affected: (if applicable)
MS Teams

**Comment by jdhuntington** [comment]
@lorejoh12 Are you able to comment on this behavior in the Calendar control?

**Comment by lorejoh12** [comment]
This was an intentional decision by our designer. Commit that made this change was here: https://github.com/OfficeDev/office-ui-fabric-react/commit/829a5263d7ed4e4decb759cfad9cdf32aad5f86e

basically, it looked really weird to only highlight the work week. It's not that bad with the "normal" workweek of mon-fri, but with disjoint working days, like the example [Tuesday, Wednesday, Friday, Saturday] here https://fabricweb.z5.web.core.windows.net/oufr/6.178.0/#/examples/calendar, it looks really weird. This is especially the case on hover, because if you hover over any of the non-working days in a week, do you expect the week to highlight or not? Given these, we opted to just highlight the whole week instead, since a work week is a strict subset of a week it seemed the cleanest.

If you have suggestions about how you'd prefer this to look, we're open to the discussion. You could potentially add a new prop that allows for the desired highlighting that defaults to false, but no promises about how that would work with hover behavior.

**Comment by micahgodbolt** [comment]
Reopening issue. OP would still like to pursue an possible solution here.

**Comment by mayankaggarwal092** [comment]
@micahgodbolt @lorejoh12 
I agree that it would look really weird to highlight a disjoint workweek. However, it is also weird that we highlight the entire week if we select a work week but it works perfectly fine if you select day, week or month view. I believe that disjoint workweek wouldn't be a very common scenario. My opinion here would be

- Highlight the workweek if it's proper continuous range in the user's week
- 	Highlight the entire week if the work week is disjoint i.e. retain the current behavior

**Comment by dzearing** [comment]
@lorejoh12 gentle ping on responding to @mayankaggarwal092 feedback. If this is not the plan we should close, or, if we think this makes sense, we should have a plan to address

**Comment by nikhilpuria** [comment]
@dzearing @micahgodbolt @lorejoh12 Is there a plan to fix this on fabric side ?
