### ISSUE TITLE
DetailsList: css for a column is being overwritten by cell css

### ISSUE THREAD

**Issue by vasticles** [microsoft/fluentui#9111]
### Please provide a reproduction of the bug in a codepen:
This is a fork of the DetailsList documentation page example.
https://codepen.io/vasticles/pen/VOpPjB
 
#### Actual behavior:
In my attempts of trying to change the anchoring of the last column in a DetailsList, I came across some strange behaviour. My custom style for the column is being overwritten by some cell css. I tried looking around where I can customize cell styles, but I haven't found anything in the documentation or the exposed interfaces.
![image](https://user-images.githubusercontent.com/5666413/57813423-09f15780-773e-11e9-8a8b-d00c91722219.png)

 
#### Expected behavior:
The column is expected to honour the custom style. Or otherwise, there should be a better (more obvious) place where this style can be applied.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No. Not sure where the culprit is.
 
Requested priority: (Blocking, High, Normal, Low) 
Normal

Disclaimer: I am fairly new to web dev, Fabric, and React, so if this is the intended behaviour...then my apologies, and I would greatly appreciate some clarity. Thanks!

**Comment by JasonGore** [comment]
It should be possible, but looking at your CodePen I can't identify exactly which styling you're applying or where. Could you point it out? Thanks!

**Comment by vasticles** [comment]
This is the bit:

`    const colorColumnStyle = mergeStyles({
        position: "absolute",
        right: 0,
    });
    
    this._columns = [
      {
        key: 'name',
        name: 'Name',
        fieldName: 'name',
        minWidth: 100,
        maxWidth: 200,
        isResizable: true
      },
      { key: 'color', 
       name: 'Color', 
       fieldName: 'color', 
       minWidth: 100, 
       maxWidth: 200,
       className: colorColumnStyle
      }
    ];
  }`

**Comment by JasonGore** [comment]
I see the behavior you describe. It looks like [the implementation is in DetailRowsFields](https://github.com/OfficeDev/office-ui-fabric-react/blob/9af0e13acba5f14a9d8c566d435db06159e40629/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRowFields.tsx#L61). Since this is just concatenating class names I don't see any easy way to fix other than actually merging styles while giving `column.className` priority.

I also see a [comment in `DetailsRow.base`](https://github.com/OfficeDev/office-ui-fabric-react/blob/9af0e13acba5f14a9d8c566d435db06159e40629/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx#L225) about having DetailsRowFields generate its own styles. Maybe that would also fix this issue?

@KevinTCoughlin What do you think?

**Comment by vasticles** [comment]
Workaround for anyone facing the same issue:

Component:
```
const columnStyle = mergeStyles({ displayName: "CustomColumn" });
const column: IColumn = { className: columnStyle };

return (
    <DetailsList columns={[column]} />
);
```

Your loaded CSS:
```
[class^="CustomColumn-"] {
    position: absolute;
    right: 0;
}
```

**Comment by calvinf** [comment]
Overriding cell styles still requires setting your own classes on a cell via `className` and cannot be achieved by passing in a `styles` property. The style specificity results in passed in styles being overridden unless you provide your own class name on the column.

**Comment by badsyntax** [comment]
Having the same problem. `column.className` should take priority over default styles.
