### ISSUE TITLE
Left Aligned Callout Not Positioned Correctly When Content Changes

### ISSUE THREAD

**Issue by SpencerLynn** [microsoft/fluentui#9249]
### Environment Information 
 
- __Package version(s)__: 6.184.0
- __Browser and OS versions__: All Tested (Chrome, Safari)

### Please provide a reproduction of the bug in a codepen:

\* reduce window height until callout renders on the left of the button
https://codepen.io/anon/pen/dEqyWR?editors=1010

When typing in the SearchBox in the callout, it causes the content to filter/change. The height of the content changes. The `Callout` does not recalculate it's position when the content changes.

I see that there is a `finalHeight` prop, and perhaps that is the solution for this problem. However, I don't think having to calculate the final height to give to the callout a height is a great solution. Perhaps a mutation observer of sorts would work for the callout?

I'm filing this bug in case there are any ideas on easier out-of-the-box solutions.

**Note**: You will have to size the code-pen viewer window small enough such that the callout opens to the left rather than the 'directional hint' down.

**Another note**: I have a commented out `setState` that will fix the issue by forcing a re-render of the `Callout`
 
#### Actual behavior:
 
When list in callout is filtered with search box, the callout can be positioned far from the target.
 
#### Expected behavior:
 
The callout is always positioned near the target.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: PowerApps

**Comment by leddie24** [comment]
Hey @SpencerLynn, thanks for submitting this issue.  I agree that this looks like a bug, but I'm not sure it's something we want to fix in Callout at the moment.  Having the Callout watch for content changes is a big perf hit that not all users may want.  A proper solution for this may be to have a composite component for Callout that watches out for all the sizing changes.  You're welcome to submit a PR for this; in the interim I will add this to our backlog.

**Comment by Mhbuur** [comment]
I'm facing the same issue. The CallOut content takes a moment to load (async) and meanwhile the callout has been positioned (in my case initially ok, near the bottom edge). When content comes in, the callout expands outside the viewport. I have tried a fixed finalHeight, but that doesn't seem to do any difference.

**Comment by jacksonv1lle** [comment]
I agree that the callout should not watch for changes to the content. It would be good to have a `forceUpdate` feature similar to the DetailsList so that the position could be recalculated programmatically.

**Comment by jacksonv1lle** [comment]
@SpencerLynn I had a similar issue where the callout was not updating when the page content changes. I was able to resolve it by specifiying the `hostId` in the layerProps to the id of the callout's parent element. That will allow you to render the callout within the parent element instead of rendering it at the end of the body.

**Comment by micahgodbolt** [comment]
There aren't any screencaps of the issue, but it looks like the issue has been fixed? When content changes the dropdown is always positioned in the right spot. 

![dropdown](https://user-images.githubusercontent.com/1434956/71699741-e71bbe00-2d75-11ea-9c10-19c4dae0f884.gif)

**Comment by SpencerLynn** [comment]
Here is a screen shot of the repro with my original codepen link. The key to getting a repro is to have the window small enough so that the menu opens to the left, rather than down. 

![image](https://user-images.githubusercontent.com/5921571/71702280-54821b80-2d83-11ea-8793-b0bc20af8c1a.png)

**Comment by micahgodbolt** [comment]
Yeah, this a tough scenario. What is the expected behavior? Should the callout start level with the button and never move? (Wasted space above). Should it start filling the screen and then continue to center itself as the menu shrinks? (Seems a bit jarring, and moving click targets). 

This behavior certainly isn't desired:

![dropdown](https://user-images.githubusercontent.com/1434956/71739979-ca33c900-2e0f-11ea-9b32-8fb1f98bcd79.gif)

**Comment by SpencerLynn** [comment]
I do agree it's tricky and also agree that the top of the callout moving a bunch is jarring.

You could probably make the argument that once the Callout is opened, the top position should not change. You could probably also make an argument that the content (and thus Callout itself) shrinking/growing a bunch is jarring also. But perhaps that detail is more of a consumption issue than a library/component issue.

**Comment by micahgodbolt** [comment]
Maybe a prop that says to maintain height after initial render, or something. Or a callback with the height, and you set the height to that value onRender.

**Comment by joschect** [comment]
@SpencerLynn and @micahgodbolt Currently the callout is optimized to position itself such that it can correctly grow into a space rather than shrink. It attempts to choose the correct anchor point (like top, left) so that its contents can expand out. 

Shrinking on the sides is much harder as both of you noted. It would certainly be nice if there was some kind of idiomatic way to tell the callout to resize rather than calling force update, which can be pretty ugly. This is one of the times where I think having another callout flavor, something like "resizing" callout, might be a good idea.
