### ISSUE TITLE
Dropdown label still shows when component is hidden

### ISSUE THREAD

**Issue by nishikaza** [microsoft/fluentui#9286]
### Environment Information 
 
- __Package version(s)__: 6.165.0 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/anon/pen/rgqLyX?editors=0010

 
#### Actual behavior:
 
Label assigned to Dropdown is still showing even when component itself is marked as hidden.

_When hidden is set to false:_
![DropdownNotHidden](https://user-images.githubusercontent.com/20346461/58649947-569e6c00-82c2-11e9-9ad8-8bba16e8afc1.PNG)

_When hidden is then set to true:_
![DropdownHidden](https://user-images.githubusercontent.com/20346461/58649964-5ef6a700-82c2-11e9-90d0-b2e8e93d4711.PNG)

 
#### Expected behavior:
 
All properties of the Dropdown component should be hidden, including the label, if the component is marked as hidden.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (**Yes**, No)
 
Requested priority: (Blocking, High, **Normal**, Low) 
 
Products/sites affected: (if applicable)

**Comment by nishikaza** [comment]
@ecraig12345 @joschect

**Comment by ecraig12345** [comment]
This is happening because the native props are being applied to the `div` for the dropdown itself, not the root `div` for the control. I think it would make sense to filter out the `hidden` prop and apply it to the root, but I'm curious what @joschect thinks. 

I'm also curious what the behavior is on other input controls like ComboBox, Toggle, SpinButton, and TextField, since ideally the behavior of `hidden` across all input-type controls should be consistent. @nishikaza Would you mind adding some of those other controls to your codepen? (you can see a list of our input controls [here](https://developer.microsoft.com/en-us/fabric#/controls/web))

**Comment by leddie24** [comment]
Hey @ecraig12345 , I went ahead and added the rest of the input controls to a codepen here, let me know if this is what you had in mind.

https://codepen.io/leddie24/pen/BeEyeY

**Comment by shruthisimha** [comment]
Hi, I have hit the same issue of label not hidden when the dropdown is hidden. Wanted to check if we have an ETA for the bug.
