### ISSUE TITLE
Examples site code viewer is buggy

### ISSUE THREAD

**Issue by amirburbea** [microsoft/fluentui#9309]
It's not the biggest issue but when using Chrome 74 and browsing the examples, a number of them run into an issue where the code editor thinks most of the example code is comments and makes everything green.  (see for example the "Show Code" for teaching bubble https://developer.microsoft.com/en-us/fabric#/controls/web/teachingbubble)

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/58819820-e3f4ff80-85e5-11e9-9f65-f397935e5585.png)

**Comment by cliffkoh** [comment]
Timely :) There is actually work that has started to improve this.

**Comment by ecraig12345** [comment]
The syntax highlighting issues are because we currently use highlight.js, which doesn't support TSX. I wasn't around when the website was originally made ~3 years ago, but I'm guessing at that time there wasn't a standalone syntax highlighter with TSX support readily available, and something as heavy-weight as Monaco isn't a great option for displaying read-only code.

Last month I briefly looked into switching to prism.js for syntax highlighting, but the main sticking point I didn't have enough time to fix right then was the color theme--getting it to look similar to the one we're currently using and ensuring all the text/background color pairs meet accessibility standards (this turns out to be pretty difficult with light themes).

We're currently working on making the examples editable inline, which will hopefully be live by the end of the summer. But we can probably fix the syntax highlighting even before then.

**Comment by ecraig12345** [comment]
This is fixed now for the main examples, but not for smaller code snippets. The remaining fix involves switching read-only code snippets to use prism.js (I just checked on highlight.js again and it still doesn't have proper TS+React support).
