### ISSUE TITLE
Calendar Restricted Months

### ISSUE THREAD

**Issue by nserr** [microsoft/fluentui#9391]
**Describe the feature that you would like added**
I am using a Calendar for a project with just the month picker. I would like to be able to disable a full month if each day of the month is passed in to the restrictedDates parameter.

**What component or utility would this be added to**
Calendar.

**Have you discussed this feature with our team, and if so, who**
I have not.

**Additional context/screenshots**
Would be very similar to how a month is disabled if it is outside the minDate and maxDate range.

**Comment by lorejoh12** [comment]
We haven't discussed this idea before, but it would make sense, specifically in the case of having just the month picker.

This gets a little weirder when you consider similar behavior with the day and month picker both enabled. We can't disable the navigation arrows in the day picker just because all the days in the next month are disabled, because that would prevent you from getting to the month past it. So we could disable that particular month in the month picker, but still allow the user to get to it using navigation arrows, which could be confusing.

This also gets into a confusing state when we consider the "current month" highlight. If the current month has no valid days in it, what sort of disabled style does it get?

For the simplest use case, we could just make it so that if you have only month picker, we can by-default disable selection of months that have no valid days inside them. If currentMonth highlight is turned on but no valid days, just show normal disable styling.

Are you willing to submit a PR for this, by the way? If not, I can bring this up at our next team meeting to triage it, but it might be a while before we get around to it.
