### ISSUE TITLE
Issue with sticky element in scrollable pane that has animations

### ISSUE THREAD

**Issue by schemburkar** [microsoft/fluentui#9486]
### Environment Information 
 
- __Package version(s)__: 6.189.x - 7.0.0
- __Browser and OS versions__: Seen on Chrome

### Please provide a reproduction of the bug in a codepen:
 
Have a Scrollable pane with Sticky element. The sticky element ( e.g. in this case a button) has animations.
On scrolling the scrollable pane, the animation occurs mutiple times. 

Confirmed that render is not called multiple times, content can be replaced with ticks and do not update, but animations do.

Code Pen
https://codepen.io/shubhan/full/ydNORg
 
#### Actual behavior:
On scroll, the sticky element repeats animations.
 
#### Expected behavior:
 
The element should not cause re-animations

 
Requested priority: Low

**Comment by aftab-hassan** [comment]
@schemburkar Thanks for opening the issue. 

The codepen you provided does not display anything. Could you please confirm if the link works for you?

**Comment by schemburkar** [comment]
@aftab-hassan I can see the codepen (its full screen view link). Here is another link for the same
https://codepen.io/shubhan/pen/ydNORg

Code details

***References***
office-ui-fabric-react.js
fabric.min.css

***UI*** 
```
 <ScrollablePane>
      <Sticky>
        <div style={{minHeight:'50px', backgroundColor: 'white', padding:10}}>
          <DefaultButton className=" ms-motion-fadeIn ms-fadeIn500" >Sticky Button</DefaultButton>
        </div>
      </Sticky>
      <div style={{minHeight:'1400px', backgroundColor: 'lightgrey', margin:10, padding:10}}>
        <PrimaryButton >Click me</PrimaryButton>
      </div>
    </ScrollablePane>
```
**See Attached gif**
On scroll, the sticky button blinks.

![OfficeFabricIssue](https://user-images.githubusercontent.com/3159347/59696517-c50f8380-9209-11e9-95b9-f4b8e65bae3c.gif)

Does this information help?

**Comment by aftab-hassan** [comment]
@schemburkar, thank you for providing the codepen and the gif, I see it now. I'll take a look and respond back here.

**Comment by Vitalius1** [comment]
@tharshada , you've done some extensive work in `ScrollablePane` and `Sticky`... could you please take a look at this issue as you probably have more context with it. Thanks.

**Comment by leddie24** [comment]
Hey @aftab-hassan, did some digging around here.  This is a little bit of a tricky issue, not entirely sure what the best solution would be.  This is happening because ScrollablePane/Sticky moves the element from stickyAbove container to the scrollableContent region (and vice versa) upon being sticky/unsticky'd. Whenever this happens, any css animations will trigger again.

One solution comes to mind, although I'm not sure how optimal it is.
- Duplicate the Sticky `props.children` in the scrollableContent region to the `stickyAbove` and `stickyBelow` region instead of using a placeholder div.  This way we can toggle the css `visibility` of the children instead of moving them from region to region.  A downside of this is a messier DOM since we have to possibly triplicate the HTML for each Sticky component.

**Comment by aftab-hassan** [comment]
@leddie24 thanks for taking a look. We don't seem to have a codeowner for either of these components. @tharshada @dzearing, would you have any thoughts on @leddie24's proposed solution ?
