### ISSUE TITLE
Overlay component add bodyScroll props

### ISSUE THREAD

**Issue by x73x63** [microsoft/fluentui#9784]
**Describe the feature that you would like added**
I need to allow the parent component to set whether to display the body scrollbar

**What component or utility would this be added to**
Panel
Modal
Dialog

**Comment by Vitalius1** [comment]
@x73x63, seems like you already have an issue open regarding this and there is a PR that investigates the possibility to address it (both linked by you in the issue description). Could you please continue the discussion on that thread and work along with 2 developers that invested time in trying to help you. Opening a duplicate issue will not expedite a solution. Thanks.

Will soft close the issue due to it being a duplicate and the other issue having more info along with a PR trying to solve it.

**Comment by Vitalius1** [comment]
@khmakoto @KevinTCoughlin FYI

**Comment by x73x63** [comment]
@JasonGore I need your help
Add bodyScroll props allow the parent component(Panel Modal Dialog)  to set whether to display the body scrollbar

IOverlayProps add 
`
  bodyScroll?: boolean;
`

change Overlay.base.tsx
`
export class OverlayBase extends BaseComponent<IOverlayProps, {}> {
    public static defaultProps: IOverlayProps = {
        bodyScroll: true,
    };

  public componentDidMount(): void {
    if(this.props.bodyScroll){
        disableBodyScroll();
    }
  }

  ...
}
`

**Comment by JasonGore** [comment]
@x73x63 We have this currently labeled as a feature request. Do you want to take a stab at a PR?
