### ISSUE TITLE
Rating: Add method to set value to 0

### ISSUE THREAD

**Issue by j-te** [microsoft/fluentui#9807]
**Describe the feature that you would like added**
relates to #9799 

Currently, there is no way to set the value to `0` (however #9805 may now fix this). 

It seems sensible for the component to set the value to `0` `if (previousValue === nextValue)`, when `allowZeroStars={true}`. 

So say 3 stars is the current value, value will become 0 if 3 stars is selected again. 

I don't think there's a case when a user would not want this feature when `allowZeroStars={true}`

**What component or utility would this be added to**
Rating

**Have you discussed this feature with our team, and if so, who**
@Vitalius1

**Comment by joschect** [comment]
@j-te Thanks for adding this here for tracking! And for including all the linked issues and pr's. I'll keep track of the fix and make sure this gets resolved.

**Comment by joschect** [comment]
Per Vitalie #9805 does not fix this. A different feature will need to be added.

**Comment by andykurz** [comment]
One year later and the bug is still not fixed???

**Comment by drivardxrm** [comment]
@andykurz 
I may have found a way to make this work.
if you look at this codepen it works well : [https://codepen.io/drivardxrm/pen/jObYBWm](https://codepen.io/drivardxrm/pen/jObYBWm)

instead of using the onChange method, I use a custom onClick in conjunction with the componentRef attribute exposed by the control. 
![image](https://user-images.githubusercontent.com/38399134/81032785-1e52c680-8e5f-11ea-9daa-b5f5c50eca3a.png)
