### ISSUE TITLE
DetailsList rowWidth added on detailsHeaderProps broke fullwidth list layout

### ISSUE THREAD

**Issue by kennyoctopus** [microsoft/fluentui#9842]
### Environment Information 
 
- __Package version(s)__: 7.11.0
- __Browser and OS versions__: Chrome
- __Revision__: 5b8005c7dd8dcff9bc4c3d46550a0e02a7885199

DetailsList rowWidth added on detailsHeaderProps broke fullwidth list layout:

This line was added: `rowWidth: this._sumColumnWidths(this.state.adjustedColumns)` and since, the component with the class name `ms-DetailsRow` have a dynamically added `min-width` attribute which is not equal 100% of the parent container (which is 100% of its parent, as expected) since its based on the sum of all columns width. This break the layout because the border-bottom line is not 100%

![image](https://user-images.githubusercontent.com/51915343/61409085-79570500-a8af-11e9-9723-ca873e48e7b8.png)

![image](https://user-images.githubusercontent.com/51915343/61409314-fa160100-a8af-11e9-94ec-b1746676ce03.png)

__ACTUAL__

![image](https://user-images.githubusercontent.com/51915343/61409455-47926e00-a8b0-11e9-950a-f2ff0592e7ae.png)

__EXPECTED__

![image](https://user-images.githubusercontent.com/51915343/61409491-5bd66b00-a8b0-11e9-8224-f2fe5ab709de.png)

__Hackish fix__: 

```
const StickyHeader = (detailsHeaderProps, defaultRender) => {
  detailsHeaderProps.rowWidth = '100%'; // <--- THIS FIX the issue

  return (
    <Sticky stickyPosition={StickyPositionType.Header}>
      {defaultRender(detailsHeaderProps)}
    </Sticky>
  );
};
```

**Comment by KevinTCoughlin** [comment]
@kennyoctopus, apologies for the friction. My understanding after having worked on this is that `DetailsListLayoutMode.fixedColumns` was intended to render columns with a "fixed" width, not to fill the `DetailsList` contents. However, it was filling its contents by chance due to bugs in the render path of `DetailsList`. Related PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/9343.

`DetailsListLayoutMode.justified` on the other hand is intended to render rows which fill their parent. Can you try using that as your `layoutMode`? Does it fix the UI regression you're seeing?

I mention the above in https://github.com/OfficeDev/office-ui-fabric-react/pull/9565#issuecomment-506924728.

**Comment by kennyoctopus** [comment]
It does fix the layout problem, but using the `justified ` mode cancel the overflow-x. So when there are lots of columns instead of rendering an overflow with a scroll bar, it ajusts the width of each column to fix the viewport, which is a problem for us as we can have 15+ columns.

![image](https://user-images.githubusercontent.com/51915343/61409767-eb7c1980-a8b0-11e9-89d9-3a71a5a94057.png)
